### ISSUE TITLE
How can I stop the gif playing from first load?

### ISSUE THREAD

**Issue by shawnthye** [coil-kt/coil#1007]
# How can I stop the gif playing from first load?
As my requirement didn't want the Gif auto play itself,

I set repeatCount(0) but it still playing at least once, I think still make sense on this setting.

I am using the ImageView extension to load the Gif from network with Crossfade effect.

Is there a way I can get ScaleDrawable or AnimatedImageDrawable from CrossfadeDrawable?

I tried just make a CustomImageView, and override the setImageDrawable(), and manually calling CrossfadeDrawble#stop(), but its doesn't work, and the Crossfade effect is gone too 😭

**Comment by colinrtwhite** [comment]
Please ask keep usage questions in Github Discussions. I saw you already created: https://github.com/coil-kt/coil/discussions/1000
