### ISSUE TITLE
Strange condition in AsyncImage

### ISSUE THREAD

**Issue by Anton111111** [coil-kt/coil#1025]
@colinrtwhite , I confused by condition on this line:
https://github.com/coil-kt/coil/blob/0459229a69609bcf0f38967151b0eb96830b0556/coil-compose-base/src/main/java/coil/compose/AsyncImage.kt#L223

Looks like it must be:
`
if (loading = null && success = null && error = null)
`
Otherwise if we add to AsyncImage all 3 callbacks it will call DefaultContent.

**Comment by colinrtwhite** [comment]
Good catch! Fixed here: https://github.com/coil-kt/coil/pull/1026
