### ISSUE TITLE
[coil-compose] fill-bounds doesn't work when I set the crossfade attribute 

### ISSUE THREAD

**Issue by dearXiaoCheng** [coil-kt/coil#1032]
fill-bounds doesn't work when I set the crossfade attribute 

for example:

Image(
                    painter = rememberImagePainter(
                        builder = {
                            crossfade(500)
                        },
                        data = "///////"),
                    contentDescription = null,
                    modifier = Modifier
                        .fillMaxWidth()
                        .aspectRatio(1f),
                    contentScale = ContentScale.FillBounds
                )

**Comment by colinrtwhite** [comment]
You have to set `scale(Scale.FILL)` as well. Unfortunately, it's not possible for the `ImagePainter` crossfade animation to autodetect the content scale.
