### ISSUE TITLE
Hoist AsyncImagePainter

### ISSUE THREAD

**Issue by OliverRhyme** [coil-kt/coil#1035]
**Is your feature request related to a problem? Please describe.**
`AsyncImagePainter` is currently created internally.

**Describe the solution you'd like**
Allow `AsyncImage` to accept `AsyncImagePainter`

**Additional context**
This will allow hoisting of state without going full low-level with `Image` and stuff

**Comment by colinrtwhite** [comment]
Can you give an example (ideally with code) of how this would be useful? It's already possible to configure all the attributes (`model` and `filterQuality`) used to create the `AsyncImagePainter` when you create an `AsyncImage`.

Also it's already possible to create your own `AsyncImagePainter` with `rememberAsyncImagePainter`.

**Comment by OliverRhyme** [comment]
for example when I want to trigger a side effect based on the current state of the painter. I mean it can be done using the composable callbacks, but it seems wrong doing that when I'm only interested in the state rather than displaying content.

**Comment by colinrtwhite** [comment]
Ah gotcha - unfortunately I don't think we can hoist the internal `AsyncImagePainter` this way. If we accept an `AsyncImagePainter` as input to `AsyncImage` then we can't set `ConstraintsSizeResolver` and `ImageRequest.scale` before the `ImageRequest` is launched. This loses a lot of the benefits of `AsyncImage` and you're probably better off using `rememberAsyncImagePainter` directly:

```kotlin
val imagePainter = rememberAsyncImagePainter(request)

if (imagePainter.state is State.Success) {
    SideEffect { TODO() }
}

Image(imagePainter, null)
```

I think your best bet to emit side effects based on the state is use `content`/`loading`/`success`/`error` as you mentioned. Personally I'd use `content`:

```kotlin
AsyncImage(
    model = request,
    contentDescription = null
) { state ->
    if (state is AsyncImagePainter.State.Success) {
        SideEffect { TODO() }
    }

    AsyncImageContent()
}
```

You could also potentially use `ImageRequest.listener`, though that doesn't support @Composable invocations.
