### ISSUE TITLE
Placeholder image gets shown delayed or loaded asynchronously

### ISSUE THREAD

**Issue by day950** [coil-kt/coil#1037]
**Describe the bug**
I have a Compose screen where I show multiple images and text, the images are loaded with coil and I use the placeholder functionality to show content while they're being loaded.
Now if frequently happens that the text and the placeholders are not being shown exactly at the same time, the placeholders are only shown a couple of frames later. So it looks like they are loaded asynchronously, despite coming from a bundled resource.

This is not a major bug, but causes some flickering and it would look better if the whole content of the screen is shown together.

If I don't use coil, and just display the placeholder images (via `painter = painterResource(id = R.drawable.placeholder1)`) the images are always shown immediately (together with the rest of the content on the screen)

**To Reproduce**
Reproduced with this Compose snippet:
```
    Column {
        val imageList = remember { mutableStateOf(listOf<String>()) }
        Row {
            TextButton(
                onClick = {
                    imageList.value = mutableListOf<String>().apply {
                        for (i in 1..30) {
                            add("https://picsum.photos/400?q=${Random.nextInt()}")
                        }
                    }
                }
            ) {
                Text(text = "Show images")
            }
            TextButton(
                onClick = {
                    imageList.value = listOf()
                }
            ) {
                Text(text = "Hide images")
            }
        }
        Spacer(modifier = Modifier.height(12.dp))
        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(vertical = 8.dp)
        ) {
            items(imageList.value) { imageUrl ->
                Row(modifier = Modifier.height(56.dp)) {
                    Spacer(modifier = Modifier.width(16.dp))
                    Image(
                        painter = rememberImagePainter(
                            data = imageUrl,
                            builder = {
                                placeholder(R.drawable.placeholder1)
                            }
                        ),
                        contentDescription = null,
                        modifier = Modifier
                            .size(52.dp)
                            .align(Alignment.CenterVertically)
                    )
                    Spacer(modifier = Modifier.width(16.dp))
                    Text(
                        text = imageUrl,
                        modifier = Modifier.align(Alignment.CenterVertically)
                    )
                }
            }
        }
    }
```

**Logs/Screenshots**
Once the button is pressed, at first only the text is shown:
![text_shown_before_the_placeholders](https://user-images.githubusercontent.com/9554672/146176410-4acd1cb3-4fb0-435e-aa3a-95dac1f2cca8.png)

Then (1 or more frames later) only the first placeholder is shown:
![not_all_placeholders_shown_together](https://user-images.githubusercontent.com/9554672/146176559-65f6995f-37ca-42e7-9d55-f6daf49b1586.png)

Then (1 or more frames later) all placeholders are shown. This is the expected state, the state from the first 2 screenshots should never happen:
![expected_state_all_placeholders_shown](https://user-images.githubusercontent.com/9554672/146176654-d598044b-be13-4cf2-a0d1-cf2d338c809f.png)

**Version**
Version used: `io.coil-kt:coil-compose:1.3.2`

**Comment by colinrtwhite** [comment]
This is solved in the 2.x releases.

**Comment by colinrtwhite** [comment]
`2.0.0` stable is now released with the fix.
