### ISSUE TITLE
[Bug]: AsyncImage contentOf(loading, success, error) is returning wrong value

### ISSUE THREAD

**Issue by rustamsmax** [coil-kt/coil#1043]
expected 
![image](https://user-images.githubusercontent.com/36570577/146459625-23a62873-0388-45bb-a8c5-e79a0c90eed7.png)

actual
![image](https://user-images.githubusercontent.com/36570577/146459687-dc1152fd-67bb-4a70-ab7f-5da98ddadf17.png)

**Comment by colinrtwhite** [comment]
Yep, this will be fixed in the next release. Duplicate: https://github.com/coil-kt/coil/issues/1025
