### ISSUE TITLE
Avoid copying when using a URI to decode a video frame

### ISSUE THREAD

**Issue by Khang-NT** [coil-kt/coil#1049]
**Is your feature request related to a problem? Please describe.**
When loading video frame from a `content://` URI, `VideoFrameDecoder` has to create a copy of this content uri as a temporary file, it's inefficient and unnecessary (imagine copy a 2GB video file just to load a thumbnail). `coil` need a way to let decoder use the content URI directly,

**Comment by colinrtwhite** [comment]
This is implemented in 2.0.0-alpha01 and above.

**Comment by colinrtwhite** [comment]
Hmm I'm pretty apprehensive to make this change. Coil's image loading pipeline is built to separate fetching responsibilities from decoding responsibilities. Passing the URI to a decoder couples the fetching behaviour with the decoding behaviour, which can cause issues. For instance, `MediaMetadataRetriever` might use non-standard APIs to open a content URI, which behave differently from our standard [`ContentUriFetcher`](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/fetch/ContentUriFetcher.kt). How do you suggest we solve this?

**Comment by colinrtwhite** [comment]
After thinking about this a bit more this may be OK, but we want to heavily discourage using the URI if it can be avoided. I added an experimental API here: https://github.com/coil-kt/coil/pull/1050

**Comment by Khang-NT** [comment]
The URI we're talking about here has to be supported by `ContentResolver#openInputStream`, so its schema must be one of "file", "content", or "android.resource". My idea is you can consider `@Deprecated FileImageSource` and add a class `ContentResolverImageSource` which is more flexible, it takes an `Uri`, and for `File` you can convert it to URI by using `Uri.fromFile`. 
```kotlin
internal class ContentResolverImageSource(
    private val contentResolver: ContentResolver,
    internal val uri: Uri,
    internal val diskCacheKey: String?,
    private val closeable: Closeable?
) : ImageSource() {
    private var isClosed = false
    private var source: BufferedSource? = null

    init {
        check(isSupportedScheme(uri)) { "Invalid uri scheme: $uri" }
    }

    @Synchronized
    override fun source(): BufferedSource {
        assertNotClosed()
        source?.let { return it }
        val inputStream = checkNotNull(contentResolver.openInputStream(uri)) {
            "Can't open $uri"
        }
        return inputStream.source().buffer().also { source = it }
    }

    @Synchronized
    override fun sourceOrNull(): BufferedSource? {
        assertNotClosed()
        return source
    }

    // should @Deprecated ?? 
    @Synchronized
    override fun file(): File {
        fileOrNull()?.let { return it }
        TODO("Throw error or copy file?")
    }

    // should @Deprecated ?? 
    override fun fileOrNull(): File? {
        assertNotClosed()
        if (uri.scheme == ContentResolver.SCHEME_FILE) {
            return File(checkNotNull(uri.path))
        }
        return null
    }

    @Synchronized
    override fun close() {
        isClosed = true
        source?.closeQuietly()
        closeable?.closeQuietly()
    }
    
    override fun uri() = uri
    override fun uriOrNull() = uri

    private fun assertNotClosed() {
        check(!isClosed) { "closed" }
    }
    
    companion object {
        private fun isSupportedScheme(uri: Uri): Boolean {
            if (uri.scheme == ContentResolver.SCHEME_FILE
                || uri.scheme == ContentResolver.SCHEME_CONTENT
                || uri.scheme == ContentResolver.SCHEME_ANDROID_RESOURCE) {
                return true
            }
            return false
        }
    }
}
```

**Comment by colinrtwhite** [comment]
@Khang-NT `contentResolver.openInputStream` doesn't work for all cases; notably, it doesn't work for assets, `ContentResolver.SCHEME_ANDROID_RESOURCE`, and [specific contacts and music thumbnail URIs](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/fetch/ContentUriFetcher.kt). By adding `uri` as an optional param we can ensure the buffered source is always opened correctly or the file is always correct, however the uri is there as a fallback.

**Comment by colinrtwhite** [comment]
Going to merge https://github.com/coil-kt/coil/pull/1050 as it fixes the issue in the interim and avoids pulling the fetching logic into `ImageSource`.

**Comment by Khang-NT** [comment]
> Going to merge #1050 as it fixes the issue in the interim and avoids pulling the fetching logic into `ImageSource`.

Thanks for the quick fix.
