### ISSUE TITLE
how to load video thumb

### ISSUE THREAD

**Issue by mt131** [coil-kt/coil#106]
i want to load video thumb like glide:

 var interval = 1 * 1000
            var options = RequestOptions().centerCrop()
                .frame(interval.toLong())
            Glide.with(activity!!.applicationContext)
                .asBitmap()
                .load(R.raw.a1)
                .apply(options)
                .into(imageView)

**Comment by colinrtwhite** [comment]
Unfortunately, this isn't currently supported. Tracking support for it here: https://github.com/coil-kt/coil/issues/25
