### ISSUE TITLE
How add tag to http request.

### ISSUE THREAD

**Issue by xiazunyang** [coil-kt/coil#1061]
My OkHttpClient can listen download progress by adding a DownloadProgressCallback as Tag to the Request.Builder. 
In Coil, I also need to add a Tag, but there is no such Api.

Here is my code for using OkHttpClient :
```
val request = Request.Builder()
    .tag(DlProgressCallback::class.java, DlProgressCallback { progress: Float ->
        //processing download progress
    })
    .tag(File::Class.java, file)
    ...
    .build()
val response = okHttpClient.newCall(request).execute()
```

I expect the Coil code:
```
    imageView.load(url) {
        error(error)
        placeholder(placeholder)
        //like add header
        addTag(DlProgressCallback { progress: Float ->  
             //processing download progress
        })
    }
```

**Comment by colinrtwhite** [comment]
Coil 2.0 passes its `Parameters` as a tag. You can use this code to attach a tag:

```kotlin
imageView.load(url) {
    error(error)
    placeholder(placeholder)
    //like add header
    addParameter("progress_callback", DlProgressCallback { progress: Float ->  
         //processing download progress
    })
}

// Inside your interceptor:
val progressCallback = request.tag(Parameters::class.java)["progress_callback"] as DlProgressCallback
```

If we add a separate API for setting tags we'll have two APIs for attaching custom info to a request, which is confusing.

**Comment by xiazunyang** [comment]
While looking at the latest source code, I also found Parameters, but they are part of the Coil, and I use DlProgressCallback in the okHttp3.Interceptor, just like DlProgressCallback.   It is another Java library that cannot dependence on Coil in the reverse direction, because Coil is an Android library.

Here is part of their code:
```
class ProgressInterceptor : Interceptor {

    override fun intercept(chain: Interceptor.Chain): Response {
        var request = chain.request()
        val upProgressCallback = request.getTag<UpProgressCallback>()
        val dlProgressCallback = request.getTag<DlProgressCallback>()
        if (upProgressCallback != null && request.body != null) {
            val progressRequestBody = ProgressRequestBody(request.body!!, upProgressCallback)
            request = request.newBuilder()
                .method(request.method, progressRequestBody)
                .build()
        }
        val response = chain.proceed(request)
        if (dlProgressCallback != null && response.body != null) {
            val progressResponseBody = ProgressResponseBody(response.body!!, dlProgressCallback)
            response = response.newBuilder()
                .body(progressResponseBody)
                .build()
        }
        return response
    }

}
```
It's already added to my OkHttpClient, so I just need to add the Tag to the request to make it work. 
I hope you understand my idea.

**Comment by colinrtwhite** [comment]
I see - can you link me to the Java library so I can understand more about your use case?

**Comment by colinrtwhite** [comment]
You can also wrap `ProgressInterceptor` in a custom interceptor that passes the correct tags from the `Parameters` object.

**Comment by xiazunyang** [comment]
Thanks for helps.
Can this be added in the next 1.4 update?
We may not wait for 2.0

**Comment by xiazunyang** [comment]
This is a demo of listen progress of images downloading.
[https://github.com/xiazunyang/CoilTest.git](https://github.com/xiazunyang/CoilTest.git)
I modified the code on the 1.x branch.
Can I submit a PR?

**Comment by colinrtwhite** [comment]
@xiazunyang Unfortunately this feature isn't likely to get added to the 1.x branch. I'm focused on releasing a 2.x release candidate and am not planning another 1.x release (aside from important bug fixes) at the moment.

**Comment by colinrtwhite** [comment]
Going to close this out since it's possible access the `Parameters` in an OkHttp interceptor in 2.x.

**Comment by vitorpamplona** [comment]
@colinrtwhite is this still true? Are Extras passed to the OkHttp interceptor on Coil 3? I can't find it.

**Comment by colinrtwhite** [comment]
@vitorpamplona Unfortunately this was removed when Ktor/multiplatform support was added to Coil in 3.0. I don't think there's an easy way to add an OkHttp tag in 3.x at the moment. Your best bet for now is to use a custom OkHttp `Interceptor` or use a custom `Header` instead.
