### ISSUE TITLE
crossfade  lead to  the activity lifecycle's destroy  delay

### ISSUE THREAD

**Issue by xh307** [coil-kt/coil#1071]
**Describe the bug**
hi, i use the crossfade , it can lead to delay  the activity's lifecycle

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.

**Version**
1.4.0

**Comment by colinrtwhite** [comment]
There isn't enough information in this report to investigate.

**Comment by xh307** [comment]
I used crossfade load image in the first Activity,   after close the other activity   lead to  these activitites lifecycle's destory delay (duation 5 seconds callback the destroy way)

**Comment by xh307** [comment]
This is simple project, I test Activity's lifecycle with coil,    this project contais two Activity;
1:  load image in first activity with crossfade property
2: turn to the second Activity 
3: finish second Activity
 
logcat print logs  (callback second Activity destroy wait  5seconds )
