### ISSUE TITLE
Support disabling EXIF rotation

### ISSUE THREAD

**Issue by K1rakishou** [coil-kt/coil#1074]
Right now [BitmapFactoryDecoder](https://github.com/coil-kt/coil/blob/0459229a69609bcf0f38967151b0eb96830b0556/coil-base/src/main/java/coil/decode/BitmapFactoryDecoder.kt#L54) always tries to read the exif data and if it finds it and there is the rotation parameter the bitmap will be corrected with that rotation. Sometimes this behavior is not desirable. 

In my app, I want to show the image as it is because there are some image re-encoding features (like an ability to correct image rotation based on the exif) so if the image appears rotated in the preview the user will see that it needs to be corrected so the user will go to the appropriate settings to do so. Right now the image appears with the correct rotation so to the users it's confusing that the image then appears rotated in other places when it appears to be fine in the preview.

BitmapFactoryDecoder.decode() already accepts Options class which contains Parameters which can be used to store the flag that will decide whether this bitmap should use exif or not (also allows it to be configured per-request separately).

**Comment by fsgjlp** [comment]
I am also waiting for this!

**Comment by fsgjlp** [comment]
@pubiqq, when will your fix be released?

**Comment by pubiqq** [comment]
> @pubiqq, when will your fix be released?

I'm afraid it's not up to me.
If @colinrtwhite is satisfied with the [proposed](https://github.com/pubiqq/coil/pull/1#issue-1204788884) API, I will finalize the pull request and submit it for review as soon as possible.

**Comment by colinrtwhite** [comment]
Ah just seeing this now. @pubiqq I'll take a look in a bit - thanks for the PR.

**Comment by pubiqq** [comment]
Great! In case of something, feel free to leave comments in my draft PR.
