### ISSUE TITLE
Include size and dimensions for ImageResult.Metadata

### ISSUE THREAD

**Issue by nd-jchu** [coil-kt/coil#1078]
**Is your feature request related to a problem? Please describe.**
`EventListener` is useful for collecting metrics, but the current implementation isn't able to access some important metadata. Size in bytes and image dimensions could be important as it can help provide additional insight for image loading performance. We want to try and access these properties from `onSuccess`.

**Describe the solution you'd like**
Include additional properties for `ImageResult.Metadata`
- Size (in bytes?)
- Dimensions (width and height)

**Comment by colinrtwhite** [comment]
Unfortunately I don't think it's possible to provide this as part of `ImageResult.Metadata` as it can't be determined for most drawable types. For example, it's not possible to determine the in-memory size for GIFs and SVGs as `AnimatedImageDrawable` and `MovieDrawable` doesn't support determining the size.

That said, you can access this for Bitmap drawables by using `Bitmap.allocationByteCount` and `Bitmap.width`/`Bitmap.height`. In Coil 2.x the `ImageResult.Metadata` is folded into `ImageResult` so you can access the drawable in `onSuccess`: `result.drawable.toBitmap().allocationByteCount`.

If you need the file size on disk, Coil's disk cache is public in 2.x so you can read the file size using that API.

**Comment by nd-jchu** [comment]
@colinrtwhite 
That help, thanks for the advice!
