### ISSUE TITLE
ViewSizeResolver does not report the actual size of view

### ISSUE THREAD

**Issue by gergely-sallai** [coil-kt/coil#108]
**Describe the bug**
`ViewSizeResolver`'s `getDimension` function deducts the View's paddings when calculating the size of a dimension. 

This might be the intended behaviour when using the library with an `ImageView`, but does not function properly if the image is loaded to a `View`'s background, as it is rarely a goal in such case to respect the padding.

**To Reproduce**
Use `ViewSizeResolver`'s `size()` function to get a view's size that has paddings set up; the result values will not contain the paddings.
The resulting image will be loaded using incorrect size.

**Expected behavior**
I can imagine multiple solutions for this:
1) Make `ViewSizeResolver` accept a parameter whether to subtract paddings or not.
2) Make the resulting `PixelSize` class contain both the size and padding data. Therefore other components could decide whether to respect padding or not. (I can see this being a bit more problematic as the image loader needs to know in advance where and how the image will be used.)
3) Make a separate `ViewSizeResolver` e.g: `ViewInsetSizeResolver` and `ViewSizeResolver` the former deducts the padding, the latter incorporates.

**Library version**
0.7.0

**Comment by colinrtwhite** [comment]
Makes sense; I'll likely expose the padding calculation methods so they can be hardcoded to 0.
