### ISSUE TITLE
Android Vector Drawable scaling issues

### ISSUE THREAD

**Issue by mightea** [coil-kt/coil#1081]
**Describe the bug**
Starting with `alpha05` there seem to be an issue when scaling Android Vector Drawables

**To Reproduce**
A sample project can be found here: (https://github.com/mightea/coil-alpha06-issue-demo) or here: 
[coil-alpha06-issue-demo-main.zip](https://github.com/coil-kt/coil/files/7854370/coil-alpha06-issue-demo-main.zip)

**Logs/Screenshots**
coil:2.0.0-alpha04  (Working)          |  coil:2.0.0-alpha06 (Scaling issue)
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/3684954/149136890-7f0f9d70-b198-4e98-ba73-987b8b2c8218.png" height="400"> | <img src="https://user-images.githubusercontent.com/3684954/149136893-cde56823-97c5-453e-b20c-679a1e104b0c.png" height="400">

**Version**
I'm using `coil:2.0.0-alpha06` the issue also occurs with `coil:2.0.0-alpha05`

**Comment by colinrtwhite** [comment]
Thanks for the repro project! Fixed here: https://github.com/coil-kt/coil/pull/1084
