### ISSUE TITLE
Support building lib via JitPack (Jitpack configuration file with jdk11 has to be added)

### ISSUE THREAD

**Issue by carstenhag** [coil-kt/coil#1082]
**Is your feature request related to a problem? Please describe.**
I would like to use jitpack to build coil. Specifically, because https://github.com/coil-kt/coil/pull/1072 is not merged/released yet :). Other people might want to use it to get snapshots/use master/etc.

Currently, jitpack can't build coil as jitpack's default is jdk8 and coil requires jdk11.

Jitpack build logs: https://jitpack.io/com/github/coil-kt/coil/PR1072-5a30dd96a1-1/build.log

**Describe the solution you'd like**
Add a jitpack.yml config file

**Additional context**
* https://jitpack.io/docs/BUILDING/#java-version
* https://github.com/javlock/ostools/blob/dfb8a9d0d53dd5733019ca1141953c9bdcc5f881/jitpack.yml

I think a `jitpack.yml` file with these contents should do the job:
```
jdk:
  - openjdk11
```

**Comment by carstenhag** [comment]
I have tried it out myself and it works with that config. 

https://jitpack.io/com/github/carstenhag/coil/fixresourcescale-24ece8bf93-1/build.log

Also see this branch https://github.com/carstenhag/coil/commits/fixresourcescale & commit: https://github.com/carstenhag/coil/commit/e14ee3e889777be71c691bd74153c1ab6e070b63

**Comment by colinrtwhite** [comment]
Sounds reasonable! I'd rather not officially support Jitpack since Maven (and maven snapshots) are still the preferred way to get the Coil artifact, but it makes sense to unblock Jitpack in this case since it's an easy fix.
