### ISSUE TITLE
Access tokens in request headers

### ISSUE THREAD

**Issue by premacck** [coil-kt/coil#11]
**Is your feature request related to a problem? Please describe.**
Thanks for this awesome library! I am trying it out in a project currently.
However, I am sending access tokens when loading the images.

```
Glide.with(context)
    .load(GlideUrl(imageUrl, LazyHeaders.Builder().addHeader(AUTHORIZATION, accessToken).build()))
    .into(imageView)
```

I looked around in the docs but couldn't find anything related to sending tokens in request headers.

**Describe the solution you'd like**
It would be great to have something like this:
`imageView.load(imageUrl).header(AUTHORIZATION, accessToken)`

**Comment by colinrtwhite** [comment]
The current recommended way to add headers to your requests is to add an [OkHttp Interceptor](https://square.github.io/okhttp/interceptors/) when building your [ImageLoader](https://coil-kt.github.io/coil/api/coil-base/coil/-image-loader-builder/).

I agree this doesn't work best for defining headers for one request only. Going to think on the design a little bit, but something like this sounds reasonable:

```kotlin
imageView.load(url) {
    header(key, value)
}
```

**Comment by colinrtwhite** [comment]
This is now supported in the [0.8.0-SNAPSHOT](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots).
