### ISSUE TITLE
ImageDecoderDecoder does't work if app comes to foreground from background 

### ISSUE THREAD

**Issue by kibria91** [coil-kt/coil#1102]
**Bug Details**
I am using ImageDecoderDecoder to show a GIF animation. GIF animation shows properly first time, but if the app goes to the background and then comes to the foreground again, then GIF animation is stuck.

Additionally, If I use GifDecoder instead of ImageDecoderDecoder then animation works fine ever after coming from the background. 

I am using, "io.coil-kt:coil-compose:1.4.0" and  "io.coil-kt:coil-gif:1.4.0"

**Comment by colinrtwhite** [comment]
I'm unable to reproduce this in the [`coil-sample` app](https://github.com/coil-kt/coil/tree/1.x/coil-sample). Do you have a reproduction project that reproduces this?
