### ISSUE TITLE
 -Xjvm-default=all requirement for 2.0.0 alphas causes havoc with KAPT / Room 

### ISSUE THREAD

**Issue by matejdro** [coil-kt/coil#1104]
**Describe the bug**
This library forces us to add `-Xjvm-default=all` to the compiler properties, which causes issues with Kapt.

**To Reproduce**

1. Enable Coil and Room in the same project
2. Implement a coil interface that uses `@JvmDefault` underneath (for example `coil.transform.Transformation`) - this forces us to add `-Xjvm-default=all` to the compiler properties,
3. Room build will fail with some cryptic errors, like `error: not an enclosing class: MyDao`

**Version**
Coil 2.0.0 alpha-06, room 2.4.1, kotlin 1.6.10

This has happened before with 1.x (#507), so it is a returning regression. 

I don't think a library should force developers to add any compiler flags, especially when those flags break things.

**Comment by colinrtwhite** [comment]
@matejdro I'm unable to reproduce this in my personal project that uses the same Coil + Room versions. What's the best way for me to reproduce this?

Coil uses `-Xjvm-default=all` for the following reasons:

- It's a binary incompatible change. If we don't declare it in 2.x, we'll have to wait until 3.x which there are no plans for.
- Coil depends on Okio and [Okio declares the compiler flag](https://github.com/square/okio/blob/8fc7d691bd14d8fb4a335f3ece67d58feaa6f686/build.gradle.kts#L135). If we ever want to implement an Okio interface in 2.x, we must declare it now.
- It generates faster, more efficient bytecode if your min SDK is API 24 or above.
- It's better for Java interoperability.
- Kotlin's old mechanism of default method generation will eventually be deprecated (like Java 6 support).

You can also try using `-Xjvm-default=all-compatibility` or use Room's KSP support.

**Comment by matejdro** [comment]
Issue seems to be `@Transaction` methods.

Google is supposed to have fixed that in November, but it is still happening: https://issuetracker.google.com/issues/199546642. I have attached repro zip as a comment to that ticket.

Thanks for the detailed explanation, I see now that it is generally a good idea to enable this and it is the Room that is the problem here, not Coil.

**Comment by colinrtwhite** [comment]
Interesting I was able to add a transaction to my DAO using Room `2.4.1`; maybe the compiler's resolving to an older version? If other folks encounter this issue, converting your DAO to an abstract class may help as well.

**Comment by PhilGlass** [comment]
`-Xjvm-default=all` also breaks the KSP implementation of Room - but you can work around it by using `-Xjvm-default=all-compatibility`.

Details @ https://issuetracker.google.com/issues/199558066#comment3

**Comment by matejdro** [comment]
Heads up: Room has released a fix https://developer.android.com/jetpack/androidx/releases/room#2.4.2
