### ISSUE TITLE
crossfade lead to the activity lifecycle's destroy delay

### ISSUE THREAD

**Issue by anthony3637** [coil-kt/coil#1106]
version:1.4.0

This is simple project, I test Activity's lifecycle with coil, this project contais two Activity;
1: load image in first activity with crossfade property
2: turn to the second Activity
3: finish second Activity

logcat print logs (callback second Activity destroy wait 5seconds )

**Comment by colinrtwhite** [comment]
Duplicate: https://github.com/coil-kt/coil/issues/1071

I tested this out in the `coil-sample` app in this repo and didn't see this issue. Please include a project that reproduces this issue. Coil doesn't control an Activity's lifecycle and a request is cancelled as soon as an `onDestroy` is called.
