### ISSUE TITLE
It is not possible to make a request when network capabilities are change

### ISSUE THREAD

**Issue by jizoquval** [coil-kt/coil#1127]
**Describe the bug**
In our application we use ConnectivityManager requestNetworks() API for connect to network of hardware device and setup Internet access on it. After that process the app check internet access on connected network and make some other network requests (so I'm on 100% sure what internet is available). At the same time, we are trying to download image using coil and get `coil.network.HttpException: HTTP 504: Unsatisfiable Request (only-if-cached)`. As far as I understand, coil uses optimization and doesn't make a network request when it considers that the application is offline. In our case we always get the exception because we don't have what image in cache.

In my opinion the main problem is that coil handle network assess only when network become available (inside `NetworkObserverApi21.kt`), but not when network capabilities changes (`onCapabilitiesChanged() `callback). In our case network capabilities changes, after we setup internet access on bounded network.

Maybe will be good give to user possibility to control this optimisation? 

**To Reproduce**
It is not easy to reproduce but main thing is initialize coil, do connect to network which doesn't have capability Internet Access, change that network to have capability internet access and after make coil request. 

As I said we use `requestNetwork()` but I believe what this can be reproduced without this api call. 
```
       val netSpecifier = WifiNetworkSpecifier.Builder()
            .setSsid(ssid)
            .setWpa2Passphrase(password)
            .build()
        val netRequest = NetworkRequest.Builder()
            .addTransportType(NetworkCapabilities.TRANSPORT_WIFI)
            .setNetworkSpecifier(netSpecifier)
            .build()
        connectivityManager.requestNetwork(netRequest, networkCallback)
```
**Logs**
```
coil.network.HttpException: HTTP 504: Unsatisfiable Request (only-if-cached)
at coil.fetch.HttpFetcher.fetch$suspendImpl(HttpFetcher.kt:90)
at coil.fetch.HttpFetcher$fetch$1.invokeSuspend(Unknown Source:16)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Version**
Tested on Coil version **1.1.1** and version **1.4.0**, Android api >= 29

**Comment by colinrtwhite** [comment]
It's possible to disable the network observer in Coil 2.x using `ImageLoader.Builder.networkObserverEnabled` so network requests will always be attempted. You could also write a custom `Interceptor` that suspends all requests until you're ready. Does that fit your use case?

**Comment by jizoquval** [comment]
Ok, thanks that is exactly what we need. Thanks for your job, Coil is the great library
