### ISSUE TITLE
Precision.EXACT and Size is not being respected when loading a bitmap without target view

### ISSUE THREAD

**Issue by halizton** [coil-kt/coil#1128]
**Describe the bug**
The requested size with exact precision is not being respected by the bitmap image loader. I am using Coil to load a bitmap directly. Using the `Precision.EXACT` in order to get back the bitmap which has the exact resolution, however the resolution of the bitmap that I get from the image loader is not expected.

For example, when I set size(252, 338) for an image, what I get as a result is either (252, 378) or (255, 338).

**To Reproduce**
```
val builder = ImageRequest.Builder(context)
builder.data(url)
builder.size(desiredWidth, desiredHeight)
builder.precision(Precision.EXACT)
val request = builder.build()
runBlocking {
       val result = context.imageLoader.execute(request)
       (result.drawable as? BitmapDrawable)?.bitmap
}
```

**Logs/Screenshots**
I can grab logs if needed

**Version**
1.4.0

**Comment by colinrtwhite** [comment]
What are the original dimensions of the image and what are the expected output dimensions? `Precision.EXACT` preserves aspect ratio and doesn't stretch the image so it sounds like this might be expected behaviour.

**Comment by halizton** [comment]
The original resolution for this image is "226x300", the ask is (252, 338). It doesn't look like the original aspect ratio is preserved.

    /**
     * Require that the loaded image's dimensions match the request's size and scale exactly.
     */
    EXACT,

**Comment by colinrtwhite** [comment]
Hmm that's slightly off - though a small amount of variance is expected as Android's image scaling algorithm varies by device manufacturer and API level. Can you post an image that reproduces the image?

**Comment by halizton** [comment]
Yeah, here's the image
![sample_image_coil](https://user-images.githubusercontent.com/12901839/153272266-067a701e-799f-4547-8a56-6772584046bc.jpg)

**Comment by colinrtwhite** [comment]
@halizton Thanks - it does look like there's more variance in the aspect ratio when loaded with 1.x. I tried loading the image on my Pixel 3 using `2.0.0-alpha08` with `ImageRequest.Builder.size(252, 338)` and got a 252x355 bitmap, which is scaled correctly preserving aspect ratio.

Coil `2.0.0-rc01` should be out ASAP so I'd recommend waiting for that release or upgrading to `2.0.0-alpha08` if you're willing. `2.0.0-alpha08` is expected to be the last alpha release.

**Comment by halizton** [comment]
Cool, thanks! Let me grab it and try!

**Comment by halizton** [comment]
But wait, if we ask for "252x338" and the return is "252x355", it is still not as same as the exact ask although the aspect ratio is preserved. Is there an API to support returning an bitmap scaled to the exact request resolution?

**Comment by colinrtwhite** [comment]
There's no API that will stretch the image and not preserve the aspect ratio - though you could accomplish this with a `Transformation`. If you want to fill to the larger dimension, use `Scale.FILL`.

**Comment by halizton** [comment]
Got it, yeah, usually it's a good practice to preserve the aspect ratio as well. Thanks, I think we can close this ticket.
