### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcoil/compose/LocalImageLoaderKt;

### ISSUE THREAD

**Issue by viratshukla** [coil-kt/coil#1138]
Currently I am using this dependency in Jetpack Compose.

def coil_version = "1.4.0"
implementation("io.coil-kt:coil-compose:$coil_version")
  
 After generating the aar file of my library, when I am trying to load image,
 I am getting this error

java.lang.NoClassDefFoundError: Failed resolution of: Lcoil/compose/LocalImageLoaderKt

**Comment by viratshukla** [comment]
I even tried adding these lines as well in proguard file

https://github.com/coil-kt/coil#r8--proguard

**Comment by colinrtwhite** [comment]
Sorry I can't provide 1 on 1 support without a way to reproduce the issue. The class is present in both [1.x](https://github.com/coil-kt/coil/blob/1.x/coil-compose-singleton/api/coil-compose-singleton.api#L17) and [2.x](https://github.com/coil-kt/coil/blob/main/coil-compose-singleton/api/coil-compose-singleton.api#L16) so this is likely a local build or R8 issue.

**Comment by viratshukla** [comment]
@colinrtwhite  
Please follow below steps - 

- Just create a compose project. 
- Add a library module.
- Write one method to load image through coil
- Export library as aar
- from your main project, call that library method by using that aar (don't use module directly)
- You will see this error

**Comment by viratshukla** [comment]
@colinrtwhite  I found the solution. Just posting here, might help others.

Scenario - App uses a aar. Aar is having code to load the image using coil library.

Now this coil library integration is required in both - app & aar (lib) build.gradle file.

Its works fine then.
