### ISSUE TITLE
Some special gifs cannot be loaded correctly

### ISSUE THREAD

**Issue by zhushenwudi** [coil-kt/coil#1151]
**Describe the bug**
hello, i use this gif.
![gif_loading](https://user-images.githubusercontent.com/30340027/154233161-299ef6db-e6a9-4524-bb5c-0529765ae783.gif)
It can load, but it can't animate

**To Reproduce**
val imgLoader = ImageLoader.Builder(context)
                .componentRegistry {
                    add(GifDecoder())
                }
                .build()
gif.load(R.drawable.gif_loading, imgLoader)

**Version**
rk3288 android7.1.1

**Comment by colinrtwhite** [comment]
If you're using 1.x you need to use `GifDecoder(enforceMinimumFrameDelay = true)`. It's enabled by default in 2.x.

**Comment by zhushenwudi** [comment]
3q, it worked
