### ISSUE TITLE
Enhance SvgDecoder Factory & DecodeUtils.isSvg

### ISSUE THREAD

**Issue by dummyco** [coil-kt/coil#1154]
**Describe the bug**
Some SVGs are formatted/generated in a way where there is no space after `svg` word in `<svg` tag:

```
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   ...
```

However, `DecodeUtils.isSvg` explicitly defines `SVG_TAG = "<svg ".encodeUtf8()` with a space, resulting in aforementioned SVGs being dropped from decoder handling.

**Version**
`io.coil-kt:coil-svg:2.0.0-alpha09`

**Comment by colinrtwhite** [comment]
Good point! Fixed here: https://github.com/coil-kt/coil/pull/1156
