### ISSUE TITLE
Could not initialize `SvgDecoder` in Compose Preview

### ISSUE THREAD

**Issue by ashughes** [coil-kt/coil#1155]
**Describe the bug**
When using the `SvgDecoder`, Compose Previews fail with the following error:
```
java.lang.NoClassDefFoundError: Could not initialize class coil.decode.SvgDecoder
```
I'm not sure if this is a known issue or limitation (I couldn't find anything) and during my brief investigation I couldn't determine why `SvgDecoder` wouldn't be able to load. :confused: 

**To Reproduce**
```kotlin
@Preview
@Composable
fun SvgDecoderIssuePreview() {
    val context = LocalContext.current
    val imageLoader = ImageLoader.Builder(context)
        .componentRegistry {
            add(SvgDecoder(context))
        }
        .build()
    CompositionLocalProvider(LocalImageLoader provides imageLoader) {
        Image(
            painter = rememberImagePainter(data = "file:///android_asset/example.svg"),
            contentDescription = null,
        )
    }
}
```
Add the above code and observe that the Compose Preview has the above error.

**Version**
1.4.0

**Comment by colinrtwhite** [comment]
@ashughes Setting the `ImageLoader` by implementing `ImageLoaderFactory` on your `Application` should solve the issue.
