### ISSUE TITLE
[coil-compose] set two image in the same page with the sam image url, will load failed

### ISSUE THREAD

**Issue by mancity2016** [coil-kt/coil#1161]
code example like this:

val imageUrl = "
https://szcty.bgzs.site:8999/app-manager/cpAppManager/QQmail/QQmail.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=L7Q7YVTDR8X0R71JVUP2%2F20220221%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220221T030054Z&X-Amz-Expires=518400&X-Amz-SignedHeaders=host&X-Amz-Signature=9cf347233a1ef45aac2a5d9101cc6757922eb860f59ad5aec691f254a6960b6a
"

Row {
      Image( rememberImagePainter(data =imageUrl)
      Image( rememberImagePainter(data =imageUrl)
}
two image load the same imageUrl, one of image will load failed
the failed exception is :
BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format

**Comment by colinrtwhite** [comment]
@mancity2016 That URL times out for me. I tried with `https://images.unsplash.com/photo-1550973886-796d048c599f?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjU4MjM5fQ`, but wasn't able to reproduce the issue.

**Comment by mancity2016** [comment]
> @mancity2016 That URL times out for me. I tried with `https://images.unsplash.com/photo-1550973886-796d048c599f?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjU4MjM5fQ`, but wasn't able to reproduce the issue.

try more times, restart you app and try
<img width="694" alt="9C0D2FE8-B959-4165-81B8-30E62DB847CC" src="https://user-images.githubusercontent.com/22315968/155642853-8090a94e-c5aa-4c31-9598-d7fa32b29c78.png">

**Comment by colinrtwhite** [comment]
Sorry, but there's not much to go on here. The issue could be related something specific with how your app is using Coil. Without more info or a way to reproduce the issue, it's not possible to debug. You could also try using version `2.0.0-alpha09` and see if that resolves the issue.

**Comment by colinrtwhite** [comment]
@mancity2016 I think [this](https://github.com/coil-kt/coil/pull/1173) should fix the issue you were seeing (assuming you're using Coil 2.x). You can also set `ImageLoader.Builder.respectCacheHeaders(false)`, which might be preferable if you don't want to obey the cache headers set by your server.
