### ISSUE TITLE
rembemberImagePainter should take an optional `key` for invalidation

### ISSUE THREAD

**Issue by tunjid** [coil-kt/coil#1169]
**Describe the bug**
Assume I have a composable that loads an image from a var.

```kotlin
@Composable
fun ImageComposable() {
    var imageToLoad by remember { mutableStateOf("url") }
    val options by remember { listOf("url1", "url2", ...) }
    
    Row {
        options.forEach { 
            Button(
               onClick = { imageToLoad = it },
               content = { Text(it) }
            )
        }
    }
        val painter = rememberImagePainter(urlToLoad)

        Image(
            painter = painter,
            contentScale = ContentScale.Crop,
            contentDescription = null,
        )

}
```
Without being able to pas a `key` to `rememberImagePainter`, I cannot invalidate the painter and make it start loading a new image when the url changes. An example of the `key` parameter can be seen in the overloads of the [remember](https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary#remember(kotlin.Any,kotlin.Function0)) method.

**Comment by colinrtwhite** [comment]
If the URL change, the image painter should start a new request with that URL since the `ImageRequest`'s `hashCode` changes. Are you seeing the new URL not be loaded if the URL changes?

**Comment by tunjid** [comment]
Hmm maybe I'm doing something wrong. I start with a null url, and when the url is updated to a non null version it still doesn't load. This is why I thought a key was needed.

**Comment by tunjid** [comment]
Egg on my face here, I forgot to specify the dimensions of the image. This was not a problem on the compose desktop app where I just loaded the image directly in, so I completely missed out on it while debugging.
