### ISSUE TITLE
AsyncImage: "colorFilter" is not applied to "placeholder" painter

### ISSUE THREAD

**Issue by nzakharchenko** [coil-kt/coil#1180]
**Is your feature request related to a problem? Please describe.**
While `AsyncImage` gives a possibility to define `colorFilter` and `placeholder` painter, when I run the app, placeholder is not using the color filter specified for the `AsyncImage`

**Describe the solution you'd like**
If `colorFilter` is defined for the `AsyncImage` then it should be applied to `placeholder` and `error` painters.

Tested with version `2.0.0-rc01`

**Comment by colinrtwhite** [comment]
Do you have a sample code snippit that reproduces this? I tested locally and this code applies the color filter to the placeholder correctly:

```kotlin
AsyncImage(
    model = server.url("/image"),
    contentDescription = null,
    colorFilter = ColorFilter.tint(Color.Cyan),
    placeholder = painterResource(R.drawable.sample),
    imageLoader = imageLoader,
    modifier = Modifier.testTag(Image),
    contentScale = ContentScale.Crop
)
```

**Comment by colinrtwhite** [comment]
Going to close this out as `colorFilter` appears to be working correctly in my testing.

**Comment by nzakharchenko** [comment]
@colinrtwhite you are absolutely right, everything works as expected. Sorry, that was my fault.

**Comment by nzakharchenko** [comment]
@colinrtwhite but now I have a bit of different issue. 
```
AsyncImage(
        model = ImageRequest.Builder(LocalContext.current).data(url).build(),
        contentDescription = null,
        colorFilter = ColorFilter.tint(Color.Cyan),
        placeholder = painterResource(id = ....),
        error = painterResource(id = ...)
    )
```

This code snippet would apply `colorFilter` to the loaded image as well. So basically any image (loaded, error, placeholder) would be using specified `colorFilter`.

Is there any way to apply `colorFilter` only to `placeholder` and `error` and not to the loaded image?

**Comment by colinrtwhite** [comment]
@nzakharchenko You'll have to wrap the painter to accomplish this. I wrote up a recipe [here](https://coil-kt.github.io/coil/recipes/#transforming-painters) that outlines how to do this. If you copy [this gist locally](https://gist.github.com/colinrtwhite/c2966e0b8584b4cdf0a5b05786b20ae1) you can then do:

```kotlin
AsyncImage(
    model = ImageRequest.Builder(LocalContext.current).data(url).build(),
    contentDescription = null,
    placeholder = forwardingPainter(painterResource(id = ....), ColorFilter.tint(Color.Cyan)),
    error = forwardingPainter(painterResource(id = ....), ColorFilter.tint(Color.Cyan))
)
```
