### ISSUE TITLE
Can not load Image

### ISSUE THREAD

**Issue by ssSFrankSss** [coil-kt/coil#1183]
I am trying to load an image on Jetpack Compose like so:

```
        AsyncImage(
            model = ImageRequest.Builder(LocalContext.current)
                .data("http://api.labelary.com/v1/printers/8dpmm/labels/4x6/0/^xa^cfa,50^fo100,100^fdHello World^fs^xz")
                .crossfade(true)
                .build(),
            contentDescription = "stringResource(R.string.description)",
            contentScale = ContentScale.Crop,
            modifier = Modifier
        )
```
But I get nothing. 
More info on URI I am calling could be found on [Labelary](http://labelary.com/service.html)

**Comment by colinrtwhite** [comment]
It looks like you're using a non-HTTPS URL. Android prevents clear text traffic by default. Changing the URL to `http://api.labelary.com/v1/printers/8dpmm/labels/4x6/0/^xa^cfa,50^fo100,100^fdHello World^fs^xz` might fix the issue.
