### ISSUE TITLE
Image not showing with coil-compose 2.0.0rc1

### ISSUE THREAD

**Issue by GabrielLasso** [coil-kt/coil#1188]
**Describe the bug**
I am trying to load an icon from a URL using coil-compose 2.0.0rc1, but it won't load

**To Reproduce**
A code example is:
```kt
@Composable
fun Test() {
    val painter = rememberAsyncImagePainter("https://s3-sa-east-1.amazonaws.com/delivery-direto-test/img/card-brands/visa.png")
    Icon(
        painter = painter,
        contentDescription = null,
        modifier = Modifier
            .padding(0.dp, 0.dp, 16.dp, 0.dp)
            .size(32.dp, 20.dp)
    )
}
```

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?
`    implementation "io.coil-kt:coil-compose:2.0.0-rc01"`

**Comment by colinrtwhite** [comment]
Duplicate: https://github.com/coil-kt/coil/issues/901

**Comment by GabrielLasso** [comment]
@colinrtwhite I changed to Image and it still now works... I think you can reopen the issue

**Comment by colinrtwhite** [comment]
@GabrielLasso I tested in the sample app and that URL loads as expected. It might be a local issue in your app.

**Comment by GabrielLasso** [comment]
@colinrtwhite oh... Ok... I will investigate what is happening here... Thanks
