### ISSUE TITLE
On Download Progress 

### ISSUE THREAD

**Issue by ghasemdev** [coil-kt/coil#1232]
I think there should be a simpler solution to display the amount of bytes downloaded so that it can be accessed in `onLoading` instead of the user customizing the okhttp interrupt.

[okhttp3-recipes](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java)

**Comment by colinrtwhite** [comment]
It's not possible to add simple APIs for every use case. I think OkHttp's existing solution addresses download progress with the right amount of verbosity/flexibility. There are also [3rd party libraries](https://github.com/jobinlawrance/okhttp3-downloadprogress-interceptor) for this use case.
