### ISSUE TITLE
Video frame ended with Exception

### ISSUE THREAD

**Issue by mirjalal** [coil-kt/coil#1236]
### Discussed in https://github.com/coil-kt/coil/discussions/1224

<div type='discussions-op-text'>

<sup>Originally posted by **mirjalal** April  4, 2022</sup>
Hi there.

I've tried to show thumnail of [this video](https://ak.picdn.net/shutterstock/videos/1015821427/preview/stock-footage--s-car-slams-into-barricade-on-vehicle-test-track-crash-test-dummies-lie-in-crashed-car-man.mp4). However, it was end with exception.

### Case 1

My global `ImageLoader`:
```
ImageLoader.Builder(LocalContext.current)
    .components {
        add(SvgDecoder.Factory())
        add(VideoFrameDecoder.Factory())
    }
    .logger(DebugLogger(Log.VERBOSE))
    .build()

```

My UI code:
```
AsyncImage(
    onError = {
        it.result.throwable.printStackTrace()
    },
    onSuccess = {
        println("success")
    },
    onLoading = {
        println("loading")
    },
    model = "https://ak.picdn.net/shutterstock/videos/1015821427/preview/stock-footage--s-car-slams-into-barricade-on-vehicle-test-track-crash-test-dummies-lie-in-crashed-car-man.mp4",
    contentDescription = null,
    modifier = Modifier.fillMaxSize()
)
```

Stacktrace:
> 2022-04-04 22:11:21.816 26095-26095 I/System.out: loading
> 2022-04-04 22:11:21.844 26095-26174 D/skia: --- Failed to create image decoder with message 'unimplemented'
> 2022-04-04 22:11:21.844 26095-26174 D/skia: --- Failed to create image decoder with message 'unimplemented'
> 2022-04-04 22:11:21.845 26095-26095 W/System.err: java.lang.IllegalStateException: BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format.
> 2022-04-04 22:11:21.845 26095-26095 W/System.err:     at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:64)
> 2022-04-04 22:11:21.845 26095-26095 W/System.err:     at coil.decode.BitmapFactoryDecoder.access$decode(BitmapFactoryDecoder.kt:24)
> 2022-04-04 22:11:21.845 26095-26095 W/System.err:     at coil.decode.BitmapFactoryDecoder$decode$2$1.invoke(BitmapFactoryDecoder.kt:31)
> 2022-04-04 22:11:21.845 26095-26095 W/System.err:     at coil.decode.BitmapFactoryDecoder$decode$2$1.invoke(BitmapFactoryDecoder.kt:31)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:8)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:4)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:157)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:37)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:34)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:31)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.intercept.EngineInterceptor.decode(EngineInterceptor.kt:199)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:41)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:127)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:8)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:4)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:126)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
> 2022-04-04 22:11:21.846 26095-26095 W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 2022-04-04 22:11:21.847 26095-26095 W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 2022-04-04 22:11:21.847 26095-26095 W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 2022-04-04 22:11:21.847 26095-26095 W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

However, when I explicitly passed the `imageLoader` and set a new instance of `ImageRequest` to `model` prop of `AsyncImage`, then it succeeds:

UI code:
```
AsyncImage(
    imageLoader =
        ImageLoader.Builder(LocalContext.current)
            .components {
                add(VideoFrameDecoder.Factory())
            }
            .logger(DebugLogger(Log.VERBOSE))
            .build(),
    onError = {
        it.result.throwable.printStackTrace()
        println(it.result.throwable.message)
    },
    onSuccess = {
        println("success")
    },
    onLoading = {
        println("loading")
    },
    model =
        ImageRequest.Builder(c)
            .data("https://ak.picdn.net/shutterstock/videos/1015821427/preview/stock-footage--s-car-slams-into-barricade-on-vehicle-test-track-crash-test-dummies-lie-in-crashed-car-man.mp4")
            .videoFrameOption(MediaMetadataRetriever.OPTION_NEXT_SYNC)
            .videoFrameMillis(1000)
            .build(),
    contentDescription = null,
    modifier = Modifier.fillMaxSize()
)
```

**Question**: what is the wrong with the code in _Case 1_ ?

Thanks.
</div>

**Comment by colinrtwhite** [comment]
It looks like the URL isn't being autodetected as a video; it's likely the content type is not set correctly by the server. Setting `decoderFactory(VideoFrameDecoder.Factory())` on your image request should solve the issue.
