### ISSUE TITLE
Jetpack compose causing Unit tests to fail in 2.0.0-xx

### ISSUE THREAD

**Issue by techartist** [coil-kt/coil#1242]
**Describe the bug**
Basically, we have a project that we want to migrate over to jetpack compose, so I wanted to use coil.  

Including 1.4.0 works just fine, but in all versions of 2.0.0-xx, I believe that you updated the version of coroutines and therefore our existing unit tests fail when including the latest version of coil.  Which I believe is 2.0.0-rc03.

Anyway in testing, advanceUntilIdle() is "no reference found" and runBlockingTests (which I realize is deprecated) does not allow for multiple dispatchers.  So we had over 100 tests fail.  

At the very least you could put out a warning on this.

**Comment by colinrtwhite** [comment]
The release notes for `2.0.0-rc03` already mention [updating Coroutines to 1.6.1](https://github.com/coil-kt/coil/blob/main/CHANGELOG.md#200-rc03---april-11-2022). For context, Coil needed to [update Coroutines to `1.6.0`](https://kotlinlang.org/docs/releases.html#release-details) to use Kotlin `1.6.10`, which is required by the latest version of Jetpack Compose. Coroutines `1.6.1` should be binary compatible with previous versions of Coroutines including [`advanceUntilIdle`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-delay-controller/advance-until-idle.html), which should still be present.
