### ISSUE TITLE
GIFs never stored in memory cache

### ISSUE THREAD

**Issue by natanfudge** [coil-kt/coil#1259]
**Describe the bug**
Using coil-gif to display gifs, I've noticed the gif is always retrieved from disk or network, see DebugLogger output:
```
I/RealImageLoader: 💾 Successful (DISK) - https://site.com/my_gif.gif
```

While other images will be loaded from memory when appropriate:
```
I/RealImageLoader: 🧠 Successful (MEMORY_CACHE) - https://site.com/my_img.png
```
Is this intentional? If so I would like to hear the developer insights regarding this decision. 

**Version**
2.0.0-rc3

**Comment by colinrtwhite** [comment]
This is currently intended behaviour. Context: https://github.com/coil-kt/coil/issues/1197

**Comment by hm-tamim** [comment]
Any update? Glide has memory cache support for gif
