### ISSUE TITLE
Some webp images not work in vm

### ISSUE THREAD

**Issue by devzwy** [coil-kt/coil#1263]
**Describe the bug**
It's ok of phone,but emulator is not work~ 

eg: http://qncdn.pupu.chat/system/gifts/giftzhenzhu.webp
![vm0](https://user-images.githubusercontent.com/24636051/167236756-c2b8a58a-4c0c-490f-a0ac-fb1fe427f41e.jpg)
![DINGTALK_IM_2429279555 JPG](https://user-images.githubusercontent.com/24636051/167236758-9dffa07c-0d94-439e-94ab-ae16ffb86bb4.JPG)

`
            this.load(
                u, ImageLoader.Builder(this.context)
                    .components {
                        if (Build.VERSION.SDK_INT >= 28) {
                            add(ImageDecoderDecoder.Factory())
                        } else {
                            add(GifDecoder.Factory())
                        }
                    add(SvgDecoder.Factory())
//                    add(VideoFrameDecoder.Factory())
                    }
                    .crossfade(true)
//                    .diskCache(
//                        DiskCache.Builder()
//                            .directory(appContext.cacheDir)
//                            .build()
//                    )
                    .build()
            )
            {
                if (isUseTranDefaultImg == true) {
                    placeholder(view.drawable)
                } else {
                    placeholder(R.mipmap.defulat_4x4)
                }

            }
`

**Comment by colinrtwhite** [comment]
This is likely an emulator config-specific issue as it works in my emulator. It may also have to do with your URL being non-HTTPS.
