### ISSUE TITLE
Set Loop Count on GIF

### ISSUE THREAD

**Issue by mattinger** [coil-kt/coil#127]
I don't currently see any way to set the loop count on a .gif file.  There are times when we get gif files that have an indefinite loop coded in, but would like to play it only once.  It would be great if we could maybe be another ImageView extension function which takes a loop count parameter, which can be passed off to MovieDrawable to determine how many times to loop the movie.

In addition, it would also be nice to know when a particular gif loops via some sort of callback interface/lambda.

It's possible this might required using AnimatedImageDrawable, but that's only API 28 or higher.

**Comment by colinrtwhite** [comment]
Great idea! Definitely open to a PR that adds this to `MovieDrawable`. This is already supported in `AnimatedImageDrawable` via `setRepeatCount`.

**Comment by mattinger** [comment]
I'd be more than willing to try to help out on this (i'd have to get contributions approved, but we have an established process for that).  However, MovieDrawable contains a Movie object, and i'm not seeing any particular way to ask that Movie object where it is in it's looping.  If i could determine how many frames were in the gif, and what frame it was on, then perhaps, but i don't see anything helpful in there.

**Comment by mattinger** [comment]
The issue is libraries like glide (what we're migrating from) have a magic loop count available LOOP_INTRINSIC.  I think it would be easy enough to do a fixed loop count, and an infinite loop (which is what coil does right now).  The problem is figuring out the intrinsic (built in) loop count for the animated gif.  Movie does not support anything like this.

**Comment by mattinger** [comment]
Also, as a side note, my app crashes every time if i try to use ImageDecoderDecoder.  I haven't been able to get a useful stack track yet though.

**Comment by colinrtwhite** [comment]
@mattinger The `ImageDecoderDecoder` crash is due to [this framework issue](https://issuetracker.google.com/issues/139371066). I've worked around it in 0.8.0-SNAPSHOT, though it might still be worth using `GifDecoder` exclusively.

**Comment by mattinger** [comment]
@colinrtwhite I see the change to MovieDrawable.  Is there going to be a corresponding change to the load function to allow us to actually set the repeat count when the movie is inflated?  That still seems to be missing.  I imagine something in the Decoder.Options would be appropriate.

**Comment by mattinger** [comment]
I can submit a PR, but it should be a simple change (limited to Options, GifDecoder and ImageDecoderDecoder), and I'd have tot go through some approvals at  work since i've never submitted to this project before.

**Comment by colinrtwhite** [comment]
@mattinger I added an extension to set the repeat count as part of the request [here](https://github.com/coil-kt/coil/pull/134).

**Comment by mattinger** [comment]
@colinrtwhite Any idea when you plan on a non snapshot release?

**Comment by colinrtwhite** [comment]
@mattinger Likely within the next 1-2 weeks.
