### ISSUE TITLE
File URIs that contain a \ no longer work in 2.0.0

### ISSUE THREAD

**Issue by edwoollard** [coil-kt/coil#1274]
**Describe the bug**
When I load a file URI into an ImageView using an example like the following: imageView.load(Uri.parse("file:/data/user/0/app.example/images/image\image01.jpg")). This used to work completely fine in 1.4.0 but after updating to 2.0.0-rc03, this now just results in a black image. Not sure whether this helps also but when I find it doesn't work, if I find that image using the Android Studio device explorer, it's unable to open the image or save it to my computer (however despite this 1.4.0 still used to render it fine, so not sure if this is a red herring). Do you have any ideas why this would no longer be working in the latest version of the library?

I've tried refactoring my file to not include a backslash and Coil then seems to be able to render it completely fine.

**To Reproduce**
Rename the name of a file to include a \ and check to see if Coil can continue to render that image.

**Version**
2.0.0-rc03

**Comment by colinrtwhite** [comment]
Looks like this is an issue with `String.toPath` in Okio. Going to close this out and track the issue [here](https://github.com/square/okio/issues/1116).

**Comment by swankjesse** [comment]
How did you get a file with a slash in its name? That seems... Bad
