### ISSUE TITLE
rememberAsyncImagePainter with crossfade setup

### ISSUE THREAD

**Issue by hrach** [coil-kt/coil#1277]
**Is your feature request related to a problem? Please describe.**
In Coil 1.X we were using 

```kotlin
Image(rememberImagePainter(avatarUrl) { crossfade(true) })
```

**Describe the solution you'd like**

In Coil 2.0, I see no easy way to use this async painter with crossfade, only using ImageRequest.Builder. This make the API a lot more complex.

```kotlin
Image(rememberAsyncImagePainter(avatarUrl, crossfade = true)
```

or something similar would be nice.

**Comment by colinrtwhite** [comment]
If you'd like to crossfade by default you can set `ImageLoader.Builder.crossfade(true)` otherwise I'd create a custom extension function in your local build that can apply an `ImageRequest` DSL builder similar to `rememberImagePainter`:

```kotlin
@Composable
inline fun rememberAsyncImagePainter(data: Any?, builder: ImageRequest.Builder.() -> Unit) = rememberAsyncImagePainter(ImageRequest.Builder(LocalContext.current).data(data).apply(builder).build())
```
