### ISSUE TITLE
Incorrect svg rendering.

### ISSUE THREAD

**Issue by thejask** [coil-kt/coil#1291]
**Describe the bug**
It is noticed that some svg files are not rendered correctly on android device by COIL library. We tried with both v2.0.0 and v2.1.0. And same svg file renders fine on browser (Chrome and Mozilla).

**To Reproduce**
Here is the sample svg file
![share](https://user-images.githubusercontent.com/5175970/170363786-5ef603e0-0ad0-4db4-bf67-53ffd66d0951.svg)

**Logs/Screenshots**
![android_screenshot](https://user-images.githubusercontent.com/5175970/170364192-40060c32-b46a-4e59-b92c-89a02ff2b0cb.png)

**Version**
v2.1.0, v2.0.0

**Comment by colinrtwhite** [comment]
Please file an issue with [AndroidSVG](https://github.com/BigBadaboom/androidsvg) as Coil delegates to that library for SVG rendering.
