### ISSUE TITLE
E/HeifDecoderImpl: getSize: not supported! on some AVIF images

### ISSUE THREAD

**Issue by FluffyDiscord** [coil-kt/coil#1295]
**Describe the bug**
Some AVIF images are not loading in my Jetpack Compose app from supplied url. The Coil logger says something about `BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format.`, but all my images are encoded the same way (batch encode) and show fine for example when opening them in the browser or any windows image viewer that supports avif

**To Reproduce**
Add anywhere in JC app `AsyncImage `with url pointing to the attached sample image which throws error.
```kotlin
AsyncImage(
    model = gallery.coverUrl, // url to the cover.avif
    contentDescription = "image cover"
    contentScale = ContentScale.Crop,
    filterQuality = FilterQuality.Low,
    modifier = Modifier.fillMaxSize()
)
```

**Logs/Screenshots**
[cover.zip](https://github.com/coil-kt/coil/files/8789588/cover.zip) - the image in question
[snipped.txt](https://github.com/coil-kt/coil/files/8789575/snipped.txt) - debug log with coil

**Version**
Android 12 (API 31)
```gradle
// Images
implementation 'io.coil-kt:coil:2.1.0'
implementation 'io.coil-kt:coil-compose:2.1.0'
```

**Comment by colinrtwhite** [comment]
Thanks - I tested locally and I'm able to reproduce the issue without Coil using `BitmapFactory.decodeStream(context.assets.open("cover.avif"))` with the image in the assets directory. This looks like an issue with the Android framework. I'd [file a bug with the Android graphics team](https://issuetracker.google.com/issues/new?component=192644&template=1438858) as unfortunately it's not possible to fix it in Coil.
