### ISSUE TITLE
Allow specifying a relative frame location for VideoFrameDecoder

### ISSUE THREAD

**Issue by zhanghai** [coil-kt/coil#1296]
**Is your feature request related to a problem? Please describe.**

The current `videoFrameMicros()` option allows specifying an absolute frame location for retrieving the video frame. However, I assume that might be rarely useful for generic video files because a video file can always have a shorter duration than the one specified, unless it stays the default `0`.

In contrast, GNOME Nautilus uses totem-video-thumbnailer by default which tries multiple relative frame locations (`1/3`, `2/3`, `0.1`, `0.9`, `0.5`) - see also https://gitlab.gnome.org/GNOME/totem/-/blob/master/src/totem-video-thumbnailer.c#L543 . Meanwhile, ffmpegthumbnailer using `0.1` which can be found at https://github.com/dirkvdb/ffmpegthumbnailer/blob/2858726b318ec1c95e9edd3f0863f7d843dd63d2/libffmpegthumbnailer/videothumbnailer.cpp#L49 .

So it would be nicer if `coil-video` also allows specifying a relative frame location.

**Describe the solution you'd like**

```
fun ImageRequest.Builder.videoFrameFraction(frameFraction: Double): ImageRequest.Builder {
    require(frameFraction in 0.0..1.0) { "frameFraction must be >= 0 and <= 1." }
    return setParameter(VideoFrameDecoder.VIDEO_FRAME_FRACTION_KEY, frameFraction)
}

fun Parameters.videoFrameFraction(): Double? =
    value(VideoFrameDecoder.VIDEO_FRAME_FRACTION_KEY) as Double?
...
class VideoFrameDecoder(
...
    override suspend fun decode() = MediaMetadataRetriever().use { retriever ->
...
            val durationMillis =
                retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)
                    ?.toLongOrNull() ?: 0L
            val frameFraction = options.parameters.videoFrameFraction() ?: 0.0
            val frameMicros = TimeUnit.MICROSECONDS.convert(
                (frameFraction * durationMillis).roundToLong(), TimeUnit.MILLISECONDS
            )
...
    companion object {
...
        const val VIDEO_FRAME_FRACTION_KEY = "coil#video_frame_fraction"
...
    }
...
```

**Additional context**

The code above is take from my modified copy of `VideoFrameDecoder` and I removed the absolute frame location support there. If we need to support both, maybe make the relative one override the absolute one?

**Comment by colinrtwhite** [comment]
Interesting idea! Can you elaborate more on the use case for this API? Is this something you need for your app?

**Comment by zhanghai** [comment]
Sure. In a file manager app which shows thumbnails for generic video files, it's normal for a video to fade in from pitch dark at the beginning of the video, so that if we simply take the first frame it will just be a black thumbnail and that's not very helpful. See also https://github.com/zhanghai/MaterialFiles/issues/557 .

**Comment by colinrtwhite** [comment]
Sounds good! Want to send a PR? The only thing I would change about your implementation is to use `videoFramePercent` to be [consistent](https://github.com/coil-kt/coil/blob/379f614e23de40d0f0d4d8613dc24e35f01a1cd5/coil-base/src/main/java/coil/disk/DiskCache.kt#L154) with Coil's other APIs.

**Comment by zhanghai** [comment]
How would you prefer the new `videoFramePercent` option to interact with the existing `videoFrameMicros` parameter? i.e. If they both have a non-null value, which one should take precedence, or should we throw an exception?

**Comment by colinrtwhite** [comment]
`videoFrameMicros` should take precedence. If both are undefined then it should default to the first frame of the video.
