### ISSUE TITLE
Graphical corruption warning on android M

### ISSUE THREAD

**Issue by Raj-Varun** [coil-kt/coil#131]
**I'm getting this warning**
`W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!`

**To Reproduce**
I'm using this `BindingAdapter` to load image in the imageView inside a RecyclerView. App is working with no issues but I'm worried about this warning.
`
@BindingAdapter("roundedUrl")
fun bindUrlRounded(imageView: ImageView, url: String) {
    imageView.load(url) {
        transformations(arrayListOf(RoundedCornersTransformation(16f)))
        crossfade(true)
    }
}
`

**Screenshot**
![image](https://user-images.githubusercontent.com/26856605/65816883-d6135c00-e21e-11e9-827a-5ea30c97a91b.png)

**Library version**
0.7.0

**Comment by colinrtwhite** [comment]
@Raj-Varun This should be safe to ignore. [Here's a similar bug report for Glide](https://github.com/bumptech/glide/issues/743#issuecomment-157752057).

I think this warning should be gone in later versions of Android. However, if you do see any graphical corruption, please let me know.
