### ISSUE TITLE
Support load APK files icons

### ISSUE THREAD

**Issue by Goooler** [coil-kt/coil#1329]
**Is your feature request related to a problem? Please describe.**

If we can add an ability to load the APK files' icon?

**Describe the solution you'd like**
```
android.content.pm.PackageItemInfo#loadIcon
```

**Additional context**

**Comment by colinrtwhite** [comment]
What would the api to load an icon look like?

**Comment by Goooler** [comment]
Add an `ApkDecoder`?

**Comment by colinrtwhite** [comment]
What would the `data` argument look like to load an app’s icon? How do we handle adaptive icons?

**Comment by ShowMeThe** [comment]
Why do you load the apk file icon using Coil? 
android.content.pm.PackageItemInfo#loadIcon this method can return a drawable. 
You can create so much style just simply covert it to bitmap and draw on the canvas.

**Comment by colinrtwhite** [comment]
I don’t think there’s a strong reason to add this by default to the main artifact. If users need this functionality they can add a custom fetcher to their component registry.
