### ISSUE TITLE
transformations influence display

### ISSUE THREAD

**Issue by fanzhouyou** [coil-kt/coil#1341]
I set imageview android:scaleType="fitXY",when I load image using coil here is my code
frontImage?.load(picPath) {
transformations(RoundedCornersTransformation(20f))
}
it displays 
<img width="649" alt="截屏2022-06-29 19 19 09" src="https://user-images.githubusercontent.com/9190108/176424554-0f4baefb-151c-479a-be8b-65aa7ee83682.png">

but when I delete transformations(RoundedCornersTransformation(20f))
it displays 
<img width="770" alt="截屏2022-06-29 19 21 42" src="https://user-images.githubusercontent.com/9190108/176424999-c483833f-a6ca-48d1-ad0f-5ed17ce25d06.png">

I find add transformations() influence display,the first image display wrong
I want RoundedCorners and display right ,How can I write the code?
PS: the path of image is from USB flash but I think it does not matter

coil_version = '2.1.0'

**Comment by colinrtwhite** [comment]
scaleType=fitXY runs after the bitmap is transformed to add rounded corners.

I’d recommend using the ShapeImageView from the material components to create the rounded corners. You could also create a custom version of RoundedCornersTransformation that applied the fitXY scaling directly on the bitmap.

**Comment by fanzhouyou** [comment]
@colinrtwhite I am confused why transformations() function has effect on display a completed bitmap
