### ISSUE TITLE
How to download image and get local path with Coil

### ISSUE THREAD

**Issue by wumeixinjiazu** [coil-kt/coil#1353]

**Comment by colinrtwhite** [comment]
You can execute/enqueue an `ImageRequest`, get the `ImageResult` then use `imageLoader?.diskCache` to get a snapshot of the disk cache entry with its path.

**Comment by HehuanAndroid** [comment]
> 您可以执行/排队一个`ImageRequest`，`ImageResult`然后使用它`imageLoader?.diskCache`来获取磁盘缓存条目及其路径的快照。

when i do "imageLoader.diskCache?.clear()"    

fun String?.getCoilCacheFile(): File? {
        return context.imageLoader.diskCache?.get(this.orEmpty())?.data?.toFile()
   }
this is null  but first load  this is have
