### ISSUE TITLE
D/skia: --- Failed to create image decoder with message 'unimplemented'

### ISSUE THREAD

**Issue by lUjek-Sh** [coil-kt/coil#1368]
**Describe the bug**
Not load bitmap. I have error: E/RealImageLoader: coil.request.NullRequestDataException: The request's data is null.
**To Reproduce**
```
                val decodedString = Base64.decode(data.logo, Base64.NO_WRAP)
                val bitmap = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.size)
                circleImageViewLogo.load(bitmap)
```

I try  `circleImageViewLogo.load(Base64.decode(data.logo, Base64.NO_WRAP))`.
but have error E/RealImageLoader: java.lang.IllegalStateException: BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format.

**Version**
Android 12
Version coil 2.1.0

P.S.
This code works. But I would like to use the library
```
                val decodedString = Base64.decode(data.logo, Base64.NO_WRAP)
                val bitmap = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.size)
                circleImageViewLogo.setImageBitmap(bitmap)
```

**Comment by colinrtwhite** [comment]
What's `data.logo`? Do you have an example image that causes the issue?

**Comment by lUjek-Sh** [comment]
> What's `data.logo`? Do you have an example image that causes the issue?

data.logo it bitmap in Base64 String

**Comment by colinrtwhite** [comment]
Can you post an example image that causes the issue?

**Comment by lUjek-Sh** [comment]
> Can you post an example image that reproduces the issue?

This https://gist.github.com/lUjek-Sh/b94d77c5c772057df70c94665f49bff9

**Comment by lUjek-Sh** [comment]
Sorry the problem is on my side. I forgot about land markup.

**Comment by colinrtwhite** [comment]
What's land markup?

**Comment by lUjek-Sh** [comment]
> What's land markup?

Sorry my English bad. I not edit my Horizontal orientation layout file.
