### ISSUE TITLE
stream was reset: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by skyofsky** [coil-kt/coil#1376]
**Describe the bug**
A clear and concise description of what the bug is. **Please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.** Bug reports without reproduction steps are likely to be closed.

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?
library version is 2.1.0 
Load picture address：image.load("https://lmg.jj20.com/up/allimg/1115/092221102018/210922102018-8-1200.jpg") 报错：stream was reset: PROTOCOL_ERROR

**Comment by colinrtwhite** [comment]
That URL 404s for me. This is likely a network error not related to Coil.
