### ISSUE TITLE
Unable to view images loaded in RecyclerView

### ISSUE THREAD

**Issue by Taresin** [coil-kt/coil#14]
**Describe the bug**
When images are loaded with URLs in a RecyclerView, the RecyclerView is still blank. I believe this could be because after the image is retrieved, there is no call to remeasure/invalidate/notify the view.

**To Reproduce**
Create a Single page application with a RecyclerView and a ViewHolder containing an ImageView.
Load up an image into the ImageView
Code snippet below:
```
   class Adapter(private val urlList: List<String>) : RecyclerView.Adapter<VH>() {

        override fun getItemCount(): Int = urlList.size
        override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): VH = VH(ImageView(parent.context))
        override fun onBindViewHolder(holder: VH, position: Int) {
            holder.imageView.load(urlList[position])
        }
    }

    class VH(val imageView: ImageView) : RecyclerView.ViewHolder(imageView)
```

**Expected behavior**
I expect the Image to load up like in Glide and Picasso.
The only way i can get it to show up in a RecyclerView at the moment is if I set the height of the view to a non-zero value.

**Logs/Screenshots**
If applicable, add logs or screenshots to help explain your problem.
![Screenshot_1565680640](https://user-images.githubusercontent.com/2931407/62923445-1050a780-bdf1-11e9-8254-2a52d6158832.png)

**Library version**
0.6.0

**Comment by Taresin** [comment]
Sorry, I created the first accidentally while logged in to my college account. Scared it might not be taken seriously since it doesn't really have a proper account.

**Comment by colinrtwhite** [comment]
Do you have `adjustViewBounds` set on your `ImageView`? Is one of your dimensions set to `wrap_content`? Sounds like the same issue as https://github.com/coil-kt/coil/issues/20.

**Comment by Taresin** [comment]
@colinrtwhite Thanks for the quick response. In my demo it was a programmatically generated `ImageView`.
`adjustViewBounds` was not set. Yep. The bug happens when any of the dimensions are set to `wrap_content`. I believe it could be the same issue as #20

**Comment by colinrtwhite** [comment]
:+1: Going to close this as I've merged the fix. `0.6.1`, which contains the fix, should be out soon.
