### ISSUE TITLE
Crossfade and placeHolder will display wrong image size

### ISSUE THREAD

**Issue by Colaman0** [coil-kt/coil#1411]
I load the image in RecyclerView , when i use crossfade and placeholder, the result image will display with wrong size,
I test different placeholder drawable, when the placeholder is bigger than result image it will be wrong display, and when i scroll back to the RecyclerView item, ImageView show the right size i want .

I found this close issue is very similar. 
https://github.com/coil-kt/coil/issues/855#issue-965393194

**Comment by colinrtwhite** [comment]
This issue needs more information. What's the expected vs. actual size? Can you share a code sample that reproduces the issue?

**Comment by colinrtwhite** [comment]
Closing this out as there's not enough info to debug.
