### ISSUE TITLE
Remove Okhttp from coil

### ISSUE THREAD

**Issue by hamedsilver** [coil-kt/coil#1412]
**Problem**
adding coil to my project adds okhttp lib to my project which is a third party library and I do not want to add okhttp to it.

**Solution**
Remove okhttp and handle request's in Kotlin .

**Comment by colinrtwhite** [comment]
OkHttp is pretty core to Coil and is necessary for Coil's network image loading functionality. OkHttp is also exposed in Coil's public API so there'd be no way to remove it without a major version increment, which there are no plans to do at the moment.
