### ISSUE TITLE
Potential memory leaks when no lifecycle is specified in ImageRequest

### ISSUE THREAD

**Issue by XiteZ** [coil-kt/coil#1416]
**Describe the bug**
The problem is with `resolveLifecycle` private function of `ImageRequest`. 
```kotlin
        private fun resolveLifecycle(): Lifecycle {
            val target = target
            val context = if (target is ViewTarget<*>) target.view.context else context
            return context.getLifecycle() ?: GlobalLifecycle
        }
```
What this method does is it tries to find the "view's `Context`" and get Lifecycle out of it by using the `getLifecycle` extension function. The extension function finds the view's closest `LifecycleOwner` among composed ContextWrappers. This would be fine, if all the `ImageView`'s we would try to load the image into are in the scope of Activity layout. As Activity is the nearest ContextWrapper and LifecycleOwner to any view. However, if one uses Fragments, then they are not `ContextWrapper`s, but they are `LifecycleOwner`s, what is more, `Fragment` have specific `LifecycleOwner` for their view's lifecycle (see: [Fragment.getViewLifecycleOwner()](https://developer.android.com/reference/androidx/fragment/app/Fragment#getViewLifecycleOwner())), which is exactly what should be used as a `Lifecycle` to control image loading.

Basically, at this moment, the default resolved `Lifecycle` will always be the `Lifecycle` of an `Activity` and not the `Lifecycle` of a `View`, if `Fragment`s are used.

**Version**
2.2.0

**Fix proposal**
To be able to find proper `Lifecycle` having only the `View` object, a [ViewTreeLifecycleOwner.get()](https://developer.android.com/reference/androidx/lifecycle/ViewTreeLifecycleOwner#get(android.view.View)) can be used. But this method will return something other than `null` only if caller use  "[Activity 1.2.0](https://developer.android.com/jetpack/androidx/releases/activity#1.2.0) and [Fragment 1.3.0](https://developer.android.com/jetpack/androidx/releases/fragment#1.3.0), and [AppCompat 1.3.0-alpha01](https://developer.android.com/jetpack/androidx/releases/appcompat:1.3.0-alpha01) or higher" - see: [androidx.lifecycle 2.3.0 Release Notes](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.0).

```kotlin
        private fun resolveLifecycle(): Lifecycle {
            val target = target
            val view = (target as? ViewTarget<*>).view
            return view?.let(ViewTreeLifecycleOwner::get)?.lifecycle 
                ?: view?.context?.getLifecycle() 
                ?: GlobalLifecycle
        }
```

**Comment by colinrtwhite** [comment]
This should be covered by the [`ViewTargetRequestManager`](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/request/ViewTargetRequestManager.kt#L91) as when the fragment is detached, its view is also detached, and the request is disposed. Requests can also only be started on attached views.
