### ISSUE TITLE
Error in building the app apk with Jetpack Compose 

### ISSUE THREAD

**Issue by alzin** [coil-kt/coil#1420]
I've installed the library after creating a new project in Jetpack Compose (Android Studio Chipmunk):

`implementation("io.coil-kt:coil-compose:2.2.0")`

Async the project is working fine but when building its **APK**  it gives the following error!

`C:/Users/ghaith/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.`

Is it a bug from the library or from Android Studio (Kotlin versions or sth)?

Please note I can build the app bundle **APK** successfully with the version **1.4.0**
`
implementation("io.coil-kt:coil-compose:1.4.0")`

**Comment by colinrtwhite** [comment]
Sorry I can't help with this issue as it's not a Coil bug. It looks like it could be a Gradle caching issue; I'd try invalidating your caches.
