### ISSUE TITLE
Loosing tint when using together with crossfade 

### ISSUE THREAD

**Issue by mlilienberg** [coil-kt/coil#143]
**Describe the bug**
When using tint and crossfade together the tint that is defined on the ImageView is not applied on the loaded image.

**To Reproduce**
Using following layout definition
```
<ImageView
        android:id="@+id/imageview"
        android:layout_width="24dp"
        android:layout_height="24dp"
        android:tint="?colorAccent"
        android:scaleType="centerInside"/>
```
together with crossfade:

```
imageview.load(imageUrl) {
        placeholder(R.drawable.ic_placeholder)
        crossfade(2000)
}
```

**Expected behavior**
Tint is applied during and after crossfade animation

**Library version**
0.0.7

**Comment by colinrtwhite** [comment]
Thanks for the report. I just added a fix for this; you can get the fix asap by [depending on `0.8.0-SNAPSHOT`](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots).
