### ISSUE TITLE
Crash or error when using DecodeFactory

### ISSUE THREAD

**Issue by lcsphantom** [coil-kt/coil#1434]
**Describe the bug**
I am currently attempting to use SubcomposeAsyncImage to load images from an url, the images are encrypted and thus I (tried) using a decode factory since the error messages says the BitmapFactory was unable to load the image.

I encountered the following issues while attempting to make my bitmap factory work:
1. Using my custom implementation of a decoder with an **image loader**, the app crashes completely even when wrapped in a try catch;
2. Using my custom implementation of a decoder with an **image request**, the app crashes completely even when wrapped in a try catch;
3. Copying and pasting the implementation of the default [BitmapFactoryDecoder](https://github.com/coil-kt/coil/blob/481fa962f29c137eab07aca91944f783208acab7/coil-base/src/main/java/coil/decode/BitmapFactoryDecoder.kt) also completely crashes the app;
4. Using the default BitmapFactoryDecoder in an **image loader** also doesn't work but doesn't crash the app (see last log).

I tried:
ImageLoader
```
                    .components {
                        add(
                            ChatMessageImageDecoder.Factory(
                                "secretPassword"
                            )
                        )
                    }
```
and also:
ImageRequest
```
                val imageRequest = ImageRequest.Builder(context)
                    .data(messageUiState.message.image?.url)
                    .decoderFactory(
                        ChatMessageImageDecoder.Factory(
                            "secretPassword"
                        )
                    )
                    .build()
```

From my testing the breakpoint in the first line inside my decode implementation is never reached and the app crashes.

**To Reproduce**
```
                val imageRequest = ImageRequest.Builder(context)
                    .data(messageUiState.message.image?.url) //String
                    .build()

                val imageLoader = context.imageLoader.newBuilder()
                    .components {
                        add(
                            ChatMessageImageDecoder.Factory(
                                "secretPassword"
                            )
                        )
                    }
                    .build()

                 SubcomposeAsyncImage(
                    model = imageLoader.enqueue(imageRequest),
                    contentDescription = "other user sent image",
                    modifier = Modifier
                        .fillMaxSize()
                        .align(Alignment.Center)
                        .clip(
                            RoundedCornerShape(6.dp)
                        ),
                    contentScale = ContentScale.FillBounds,
                    onError = {
                        Log.i(TAG, "something went wrong ${it.result.throwable.localizedMessage}")
                    },
                )
```

**Logs/Screenshots**

Log 1,2,3
```
 java.lang.IllegalStateException: pending composition has not been applied at androidx.compose.runtime.CompositionImpl.drainPendingModificationsForCompositionLocked(Composition.kt:546)
at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:583)
at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:811)
at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3712)
at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3712)
at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3712)
```
Log 4
`Unable to create a fetcher that supports: coil.request.OneShotDisposable@355f7dc`

**Version**
```
compose_ui_version = '1.2.1'
compose_compiler_version = '1.2.0'
implementation("io.coil-kt:coil-compose:2.2.0")
```

My testing is being done in Android API 33, Pixel 3A.

**Comment by colinrtwhite** [comment]
Going to close this out. Let me know if the previous comment doesn't solve the issue.

**Comment by lcsphantom** [comment]
@colinrtwhite 
If you see scenario 4, where I copy and paste the code for BitmapFactoryDecoder which is I suppose the default decoder for regular images, the code still doesn't work but throws an error.

The decoder doesn't seem to work in the `ImageRequest` or `ImageLoader`.

**Comment by lcsphantom** [comment]
@colinrtwhite bump
