### ISSUE TITLE
Crash in SystemCallbacks.onTrimMemory()

### ISSUE THREAD

**Issue by xiejinpeng007** [coil-kt/coil#1443]
**Describe the bug**
Hi, we have receive some crash reports from crashlytics.
The crash happened when loading image in background after receive a notification from fcm.
I see this issue has been marked solved in changelog and https://github.com/coil-kt/coil/issues/1211
Could you please take a look again , thanks.

**To Reproduce**
I can't 100% reproduce it in local.

**Logs/Screenshots**
<img width="441" alt="2022-09-09 17 35 48" src="https://user-images.githubusercontent.com/12725289/189322631-61cd06dc-a091-4575-ab98-6359ef623baf.png">

**Version**
Coil version : 2.1.0
Android plugin version : 7.1.1

**Comment by colinrtwhite** [comment]
Interesting - how frequent is the crash? Also does it occur 100% of the time in the background? The code still has [this work-around](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/RealImageLoader.kt#L216) to check for if `memoryCacheLazy` is null (even though it never should be). I think the next step is to wrap that call site and catch the exception.

**Comment by xiejinpeng007** [comment]
We have receive just a few reports from latest version of our app (we used coil 2.0.0 - rc02 in last version), so I think the frequent is low until now.
And yes it occur 100% of the time in the background.
It's weird the issue is still exist with null check.

**Comment by colinrtwhite** [comment]
@xiejinpeng007 Just to confirm, you've gotten crash reports for this issue on a build running Coil 2.1.0? The fix was released in Coil 2.0.0-rc03.

**Comment by xiejinpeng007** [comment]
Yes , got crash issue reposrts on a build running Coil 2.1.0.
