### ISSUE TITLE
Video not load file in a folder in asset

### ISSUE THREAD

**Issue by maichanchinh** [coil-kt/coil#1459]
**Describe the bug**
If to video in directory, could not be load.

RealImageLoader: 🚨 Failed - file:///android_asset/video/video_8.mp4 - java.io.FileNotFoundException: video_8.mp4
file:///android_asset/video/video_8.mp4 -> not work. 

move file to file:///android_asset/video_8.mp4  -> work

**Logs/Screenshots**
```
I/RealImageLoader: 🚨 Failed - file:///android_asset/video/video_8.mp4 - java.io.FileNotFoundException: video_8.mp4
I/RealImageLoader: 🚨 Failed - file:///android_asset/video/video_6.mp4 - java.io.FileNotFoundException: video_6.mp4
I/RealImageLoader: 🚨 Failed - file:///android_asset/video/video_11.mp4 - java.io.FileNotFoundException: video_11.mp4
I/RealImageLoader: 💾 Successful (DISK) - file:///android_asset/video_2.mp4
```
**Version**
2.2.1

**Comment by colinrtwhite** [comment]
Sorry, but there isn't enough information to investigate this. I'd recommend asking for help on StackOverflow or Github discussions.
