### ISSUE TITLE
AsyncImage doesn't render success image in Compose 1.3.0-beta03 if one dimension is unbounded

### ISSUE THREAD

**Issue by colinrtwhite** [coil-kt/coil#1473]
**Describe the bug**
Images with an unbounded dimension (either width or height) and no placeholder don't render when upgrading to Compose 1.3.0-beta03. Compose 1.3.0-beta02 doesn't have this issue. e.g. this layout would have the issue (because the `AsyncImage`'s height is unbounded):

```kotlin
LazyList {
  items(item) {
    AsyncImage(
      model = "https://example.com/image.jpg",
      contentDescription = null,
      modifier = Modifier.fillMaxWidth()
    )
  }
}
```

This appears to be a regression in Compose 1.3.0-beta03. Filed an issue in the Compose issue tracker here: https://issuetracker.google.com/issues/248100419

**To Reproduce**
Coil's `AsyncImagePainter` tests reproduce this. See this PR: https://github.com/coil-kt/coil/pull/1472

**Version**
2.2.1

**Comment by TheMelody** [comment]
You need to calculate the width and height or set the ratio into it。Example: BoxWithConstraint? This is not a coil bug
