### ISSUE TITLE
Support for QR image

### ISSUE THREAD

**Issue by anhanh11001** [coil-kt/coil#1474]
Might be out of scope for Coil, but it never hurts to ask.

Can Coil support generating QR Image from a string (URL, phone number,...)? I think there are no current good solution for QR image support for Compose UI.

**Comment by colinrtwhite** [comment]
Thanks for the suggestion, but I think this is a good candidate for an external library since it's a bit of a less common use case. You could use a custom `Fetcher` to achieve this.
