### ISSUE TITLE
Clear Coil Cache

### ISSUE THREAD

**Issue by kuuuurt** [coil-kt/coil#148]
**Is your feature request related to a problem? Please describe.**
I have a project where I update the user's profile photo. It just uses the same URL but updates the content. When I try to reload it, (I think) it just gets the value from the cache. 

**Describe the solution you'd like**
Maybe a `load(url) { clearCache() } `
or a ` load(url, useCache = false) { ... }`

Or am I missing something here? Using either the `networkCachePolicy`, `diskCachePolicy`, or `memoryCachePolicy` doesn't seem to work

**Comment by colinrtwhite** [comment]
Using this will guarantee that your request is always loaded from the network:

```
load(url) {
    diskCachePolicy(CachePolicy.DISABLED)
    memoryCachePolicy(CachePolicy.DISABLED)
}
```

**Comment by kuuuurt** [comment]
Thanks, Colin! Works as expected. I might've just missed this 🙂
