### ISSUE TITLE
Support `MediaMetadataRetriever.BitmapParams` on API 28 (+)

### ISSUE THREAD

**Issue by mhelder** [coil-kt/coil#1481]
**Is your feature request related to a problem? Please describe.**
While working on an app that uses `VideoFrameDecoder` to render a still preview of videos, I noticed the resulting image has quite some visual banding (see 1st image below). I traced this back to where `VideoFrameDecoder` uses the `MediaMetadataRetriever` to decode a frame:

https://github.com/coil-kt/coil/blob/6ac35963bb3b1c06caca47ee43dd8370e9336f49/coil-video/src/main/java/coil/decode/VideoFrameDecoder.kt#L82;L89

The `rawBitmap` (as decoded by `MediaMetadataRetriever`) already displays the banding, and that's the result of the decoded bitmap config being `RGB_565`. Although Coil isn't directly to blame for this because it didn't decode or transform the bitmap, it also doesn't make use of the [MediaMetadataRetriever.BitmapParams](https://developer.android.com/reference/android/media/MediaMetadataRetriever.BitmapParams) that were added in API 28. By providing these, we could avoid the banding. (see 2nd image below).

**Describe the solution you'd like**
It'd be great it Coil could provide `MediaMetadataRetriever.BitmapParams` to the relevant `MediaMetadataRetriever` functions on platforms that support it. These `BitmapParams` should probably be based on the configuration of the `ImageRequest` options, to control the bitmap config used for decoding. Specifically, `allowRgb565` and `bitmapConfig` would be relevant (perhaps more options?). 

I also noted that the docs for e.g. [`MediaMetadataRetriever.getScaledFrameAtTime`](https://developer.android.com/reference/android/media/MediaMetadataRetriever#getScaledFrameAtTime(long,%20int,%20int,%20int)) mention that the current behaviour of supplying `null` for the `BitmapParams` result in _"that the device will choose the actual [Bitmap.Config](https://developer.android.com/reference/android/graphics/Bitmap.Config) to use"_. So the current behaviour of decoding video frames may differ from device to device and vendor to vendor. So far, I've been able to confirm that at least the Google Pixel 6 (Android 13) and Samsung S21 5G (Android 12) select `RGB_565` by default. 

I'm happy to take a crack at implementing and submitting a PR for this, but could use some guidance on some details:
- How do the `allowRgb565` and `bitmapConfig` options relate to each other? Am I correct if I state that the bitmap config is merely a *preferred* config, and `allowRgb565` (and some other scenarios) may override this?
- Do you think we should *always* provide `BitmapParams` on supported platforms? It'll then effectively default to `ARGB_8888`. Or should we keep it `null` in case no explicit `bitmapConfig` option is set in the image request (for backwards compatible behaviour, so the device will still _"choose the actual config_")? (I'm leaning towards the latter.)

**Additional context**
`RGB_565` bitmap with banding:
![`RGB_565` bitmap with banding](https://user-images.githubusercontent.com/9018028/193238038-727519ef-1a95-4cc9-80a7-743ebc6a3a50.png)

`ARGB_8888` bitmap without banding
![`ARGB_8888` bitmap without banding](https://user-images.githubusercontent.com/9018028/193238476-b05a89ee-10bb-432c-921b-f1922c5f1256.png)

I've also pushed a sample video in a fork if you want to play around with this yourself. Run `coil-sample-view` from:
https://github.com/mhelder/coil/tree/bug/videoframedecoder-banding

**Comment by colinrtwhite** [comment]
Thanks for the detailed bug report! I took a quick stab at it [here](https://github.com/coil-kt/coil/pull/1487). Unfortunately, we can't use `BitmapParams` until API 30 since Android didn't add `getFrameAtTime` and `getScaledFrameAtTime` overloads with both an `option` and `params` until API 30.

**Comment by mhelder** [comment]
That was quick! Nice catch and also a bummer that `getFrameAtTime` and `getScaledFrameAtTime` are only available on API 30 and above - I didn't look beyond the `BitmapParams` class when I opened the issue 😅. Thanks for fixing this!
