### ISSUE TITLE
[Documentation] Error in the Image Loaders docs

### ISSUE THREAD

**Issue by G00fY2** [coil-kt/coil#1484]
In the example code `DiskCache.Builder` takes a `context` parameter, but this Builder actually has no constructor argument: https://github.com/coil-kt/coil/blob/6ac35963bb3b1c06caca47ee43dd8370e9336f49/docs/image_loaders.md?plain=1#L25

**Comment by colinrtwhite** [comment]
Good catch! Fixed here: https://github.com/coil-kt/coil/pull/1486
