### ISSUE TITLE
Expose Coil.reset as public API

### ISSUE THREAD

**Issue by yschimke** [coil-kt/coil#1501]
Overriding Coil for Previews or Paparazzi shows the need to override, and then ideally reset the ImageLoader.  But reset is not currently exposed.

https://github.com/google/horologist/blob/5273e181b123a6f87af7a5ca4f6ecf7af95dbb1a/compose-tools/src/main/java/com/google/android/horologist/compose/tools/coil/FakeImageLoader.kt#L56-L66

**Comment by colinrtwhite** [comment]
I've been a bit cautious to make this method public since it shouldn't be called in production code (ideally `setImageLoader` is only called once), but I agree it's important for testing.
