### ISSUE TITLE
`VideoFrameDecoder` not working for video files without extension

### ISSUE THREAD

**Issue by AchrafAmil** [coil-kt/coil#1510]
**Context**
Migrating from `1.4.0` to `2.2.2`, more precisely replacing following usage **in image request builder**:
`decoder(VideoFrameDecoder(context))`  -> `decoderFactory(VideoFrameDecoder.Factory())`

**Describe the bug**
Loading a video file **that has no extension** (to guess format from) into an image (first frame as thumbnail) is now failing with:
```
BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format.
```

**To Reproduce**
On a fork on the sample app:
- 9d2adaf loading a video thumbnail from assets with extension = working
- 8793877 loading a video thumbnail from assets **without extension** = not working

**Logs/Screenshots**
After a little investigation it seems like:
- FileFetcher is replying on `android.webkit.MimeTypeMap.getMimeTypeFromExtension` which will give a null mime type if no extension.
- `VideoFrameDecoder.Factory::isApplicable` says false if mime type is null.
- No video decoder is created/used and it's falling back to image.

**Version**
2.2.2

**Comment by colinrtwhite** [comment]
Hmm I'm not sure how this worked in 1.x as as far as I know `VideoFrameDecoder` has always relied on the extension to determine the file type. This is mentioned in [the docs](https://coil-kt.github.io/coil/videos/):

> The ImageLoader will automatically detect any videos and extract their frames if the request's filename/URI ends with a [valid video extension](https://developer.android.com/guide/topics/media/media-formats#video-formats). If it does not, you can [set the Decoder explicitly](https://coil-kt.github.io/coil/api/coil-base/coil.request/-image-request/-builder/decoder-factory) for the request.

To fix you can set `decoderFactory(VideoFrameDecoder.Factory())` manually on the `ImageRequest`.

**Comment by AchrafAmil** [comment]
It's actually about setting the `decoderFactory(VideoFrameDecoder.Factory())` that does not act as expected/mentioned in the doc. If you run the sample in 8793877 you can see it's still not working even if a decoder is set on the request.

As mentioned in the issue, the `VideoFrameDecoder` is not created from the provided factory as it says no to `isApplicable(mimeType)`.

**Comment by colinrtwhite** [comment]
Ah sorry, my mistake! The docs need to be updated, as the file format detection logic and decoding logic were separated in Coil 2.0. This allows users to control when to use a specific decoder without rewriting the decoding logic. The correct way to force a specific decoder now is to always return it from `Decoder.Factory`. The can be done locally with an anonymous class:

```kotlin
decoderFactory { result, options, _ -> VideoFrameDecoder(result.source, options) }
```

Reopening this to track doc improvements.
