### ISSUE TITLE
EncryptingFileSystem

### ISSUE THREAD

**Issue by mandrachek** [coil-kt/coil#1511]
See #245
Now that coil has it's own cache, and no longer relies on OkHttp's, theoretically, we should be able to encrypt the cache contents.  Has anyone implemented this?  It looks like it would require implementing an encrypted FileSystem.  (I've done similar with OkHttp, but it's internal FileSystem isn't an okio.FileSystem and seem substantially easier to implement (despite the difficulties with it being internal and having to use reflection to create a Cache with one).

**Comment by colinrtwhite** [comment]
I did a quick search and couldn't find one, but I think this should support writing to/reading from files on disk:

```kotlin
class CipherFileSystem(
    private val cipher: Cipher,
    delegate: FileSystem = SYSTEM,
) : ForwardingFileSystem(delegate) {

    override fun sink(file: Path, mustCreate: Boolean): Sink {
        return super.sink(file, mustCreate).buffer().cipherSink(cipher)
    }

    override fun source(file: Path): Source {
        return super.source(file).buffer().cipherSource(cipher)
    }
}
```

You can set it on your `DiskCache` using `DiskCache.Builder.fileSystem(CipherFileSystem(cipher))`. Disclaimer: I haven't tested this.

**Comment by mandrachek** [comment]
Ah.  I "fixed" this by having sink check for the existence of the file before passing to getEncryptedFile - this lets is get downloaded and encrypted (source gets called, and I can see the file).  Unfortunately "tink" doesn't support renaming files, and since it gets renamed from x.number.tmp to x.number, decryption will always fail.
