### ISSUE TITLE
Version 2.2.2 uri load bug

### ISSUE THREAD

**Issue by JYLEE1988** [coil-kt/coil#1513]
**Describe the bug**
uri starting with `file:///` is not loaded.
A change occurred in the file creation method in version `2.2.2`, which is expected to be related to this.
#1466
```kotlin
override fun map(data: Uri, options: Options): File? {
        if (!isApplicable(data)) return null
        val uri = if (data.scheme == null) data else data.buildUpon().scheme(null).build()
        return File(uri.toString())
    }
```

In version `2.2.1`, the uri image loads well.

**To Reproduce**
Try to load a uri starting with `file:///`.
For example `file:///storage/emulated/0/android/data/{package-name}/cache/images/temp.jpg`

**Version**
2.2.2

**Comment by colinrtwhite** [comment]
Thanks for the report - I'll take a look. As a work-around looks like removing the `file://` prefix should work?

**Comment by JYLEE1988** [comment]
Yes, but in version 2.2.2, the File path is created like this
`///storage/emulated/0/android/data/{package-name}/cache/images/temp.jpg`

**Comment by colinrtwhite** [comment]
@JYLEE1988 Where are you getting this file URI from? There's already a regression test for `file://` URIs, which is passing.

**Comment by JYLEE1988** [comment]
@colinrtwhite 
The file name contained a `+`, which seems to be the cause.
When I remove the `+`, it works fine.

**Comment by DjakaTechnology** [comment]
I encountered this problem and ended up downgrading the version to 2.2.1. Here's the URI:
`file:///storage/emulated/0/Download/Foo%20Bar/732234b189214a33a84d77609f60012e.jpg`
