### ISSUE TITLE
ImageView.load() and ImageView.dispose() may be able to exist in the `coil-base` artifact

### ISSUE THREAD

**Issue by StylianosGakis** [coil-kt/coil#1525]
**Is your feature request related to a problem? Please describe.**
I was using the `coil` artifact and was using the `ImageView.load()` and `ImageView.dispose()` in various places. Then I started using my own `ImageLoader` and to enforce its use I decided to go away from the `coil` artifact and use the `coil-base` directly. This however means that these two functions no longer exist in that artifact.

**Describe the solution you'd like**
I guess what I was looking for was to have the `inline fun ImageView.dispose()` function to simply exist in that artifact too, and the [load](https://github.com/coil-kt/coil/blob/6d744c119f674110fd1150e9ae502d2020676eec/coil-singleton/src/main/java/coil/Extensions.kt#L54-L65) to also exist, just without the default ImageLoader, but with the signature of `fun ImageView.load(data: Any?, imageLoader: ImageLoader, builder: ImageRequest.Builder.() -> Unit = {}): Disposable`.

I just added these two to my own project myself
```
fun ImageView.dispose() {
  CoilUtils.dispose(this)
}

fun ImageView.load(
  data: Any?,
  imageLoader: ImageLoader,
  builder: ImageRequest.Builder.() -> Unit = {},
): Disposable {
  val request = ImageRequest.Builder(context)
    .data(data)
    .target(this)
    .apply(builder)
    .build()
  return imageLoader.enqueue(request)
}
```
But I imagine this would be useful for others too.

What are your thoughts on this? Is there any gotcha by doing it this way that you wanted to avoid by not adding these APIs to the `-base` artifact?

**Comment by colinrtwhite** [comment]
Yep Coil could add these to the main artifact however I've avoided adding them so far since `coil-base` is intended to be just `ImageLoader` and its associated types. It intentionally doesn't include any extension functions for public types so you can't accidentally mix Coil's image loading methods with `ImageView`'s built-in methods.

The extension functions are useful, but they work better when you plan to use the static singleton `ImageLoader`.

**Comment by StylianosGakis** [comment]
Hey Colin, yes that makes sense. I will keep going forward with having our own implementation of them as written in the first comment, and keep the coil-base artifact's API cleaner.
Maybe I'm the only one who's had this request anyway, so maybe not worth it adding to the artifact itself :D So maybe not worth it to add another artifact on top of coil-base which adds them, or anything drastic like that.
Thanks for answering, I think we can close this now unless more people come with the same request 😊
