### ISSUE TITLE
Image loading WTF with RecyclerView/ViewPager2

### ISSUE THREAD

**Issue by Pitel** [coil-kt/coil#153]
**Describe the bug**
Imagine a screen for some profile editing. It has an option to select from few predefined avatars, and upload a custom one.

The avatar picker is ViewPager2 (so basicaly RecyclerView) with ImageViews.

Adapter:
```kotlin
class AvatarsAdapter : RecyclerView.Adapter<AvatarsAdapter.AvatarViewHodler>() {
	var photo: Uri? = null

	init {
		setHasStableIds(true)
	}

	override fun onCreateViewHolder(parent: ViewGroup, viewType: Int) = AvatarViewHodler(ImageView(parent.context).apply {
		Timber.v("Create")
		layoutParams = ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
	})

	override fun getItemCount() = 5

	override fun onBindViewHolder(holder: AvatarViewHodler, position: Int) {
		Timber.v("Bind $position")
		if (position < itemCount - 1) {
			Timber.v("R")
			holder.containerView.setImageResource(when (position) {
				0 -> R.drawable.avatar1
				1 -> R.drawable.avatar2
				2 -> R.drawable.avatar3
				3 -> R.drawable.avatar4
				else -> 0
			})
		} else {
			Timber.v("Coil $photo")
			holder.containerView.load(photo) {
				memoryCachePolicy(CachePolicy.WRITE_ONLY)
			}
		}
	}

	override fun getItemId(position: Int) = position.toLong()

	inner class AvatarViewHodler(override val containerView: ImageView) : RecyclerView.ViewHolder(containerView), LayoutContainer
}
```

Now, when the screen is first opened, and user has custom avatar, the following thing happens:
```kotlin
adapter.photo = "https://foo.bar/image".toUri()
recycler.setCurrentItem(4, false)
```

So far so good, the image is downloaded and displayed. And I see the following output in logcat:
```
V/AvatarsAdapter: Create
V/AvatarsAdapter: Bind 4
V/AvatarsAdapter: Coil https://foo.bar/image
### Starts swiping all the way to the lefat and back ###
V/AvatarsAdapter: Create
V/AvatarsAdapter: Bind 3
V/AvatarsAdapter: R
V/AvatarsAdapter: Create
V/AvatarsAdapter: Bind 2
V/AvatarsAdapter: R
V/AvatarsAdapter: Create
V/AvatarsAdapter: Bind 1
V/AvatarsAdapter: R
V/AvatarsAdapter: Create
V/AvatarsAdapter: Bind 0
V/AvatarsAdapter: R
V/AvatarsAdapter: Bind 4
V/AvatarsAdapter: Coil https://foo.bar/image
```

Now for the WTF part. When I select some other image from phone storage, the following code is run:
```kotlin
adapter.photo = newUri
recycler.currentItem = Int.MAX_VALUE
adapter.notifyItemChanged(avatars.currentItem)
```
Logcat:
```
V/AvatarsAdapter: Bind 4
V/AvatarsAdapter: Coil content://com.google.android.apps.muzei.documents/document/3288
```

It still look ok. The image from `content://` is loaded and displayed.

But, when I start swiping again, the previous image is displayed instead of first avatar. Even when Logcat says it should be loaded from resources and there is no longer any mention about `https://` Uri.
```
V/AvatarsAdapter: Bind 0
V/AvatarsAdapter: R
```

**To Reproduce**
Recreate the code above.

**Expected behavior**
Old image is not loaded instead of first avatar.

**Logs/Screenshots**
[Video](https://youtu.be/u4VKwzX3xkM)

**Library version**
0.7.0

**Comment by Pitel** [comment]
It seem to me, like Coil is somehow bound to this 'ImageView' in `ViewHolder`, but since it got recycled, it should become unbound, but it does not.

**Comment by Pitel** [comment]
Also happens with brand new 0.8.0.

**Comment by Pitel** [comment]
Can I somehow manually unbind Coil from `ImageView`?

There is this [`onViewRecycled()`](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter.html?hl=en#onViewRecycled(VH)) method which might be good place to do it. But it sould still be just workaround, because other libs (Glide, Picasso) can handle this without forcing developer to modify Adapter.

Coil is aslo responding to to attach/detach properly. Because when I swipe from from custom avatar to 4 and back to custom, HTTP request is fired (I have memory caching disabled) and when overriding adapter's `onViewAttachedToWindow` and `onViewDetachedToWindow` methods, they are being called properly.

**Comment by Pitel** [comment]
Ok, adding this to adapter fixes the issue:
```kotlin
override fun onViewRecycled(holder: AvatarViewHodler) {
	holder.containerView.clear() // containerView is the ImageView
}
```

But as I said earlier, I consider this just a workaround and I'm not closing the issue.

**Comment by colinrtwhite** [comment]
@Pitel If you replace `holder.containerView.setImageResource` with `holder.containerView.load` this should solve the issue.

The image is being recycled in `onViewRecycled` since the view is detached, however the image will be reloaded when the view is re-attached. This is required to correctly support Fragments and RecyclerViews (I believe Glide has similar behaviour).

I'd recommend not mixing `load` and other `ImageView` setters since Coil can't know when `setImageResource` is called. If the other image loading libraries have a good way to handle this, I'm up for adding it to Coil.

**Comment by Pitel** [comment]
Oh, that makes sense. And fixed my issue. :+1:

**Comment by yeduakira** [comment]
Incase this helps someone, In my bind function I call `imageView.clear()` before doing anything on the imageView.

**Comment by ElegyD** [comment]
I just found out about this issue. For anyone else coming to this thread, the function is now called `ImageView.dispose()` instead of `ImageView.clear()`
