### ISSUE TITLE
CircleCropTransformation() does not work on LayerDrawable

### ISSUE THREAD

**Issue by mario** [coil-kt/coil#154]
**Describe the bug**
CircleCropTransformation() does not work on LayerDrawable

**To Reproduce**
```
      layers[0] = context.getDrawable(R.drawable.ic_launcher_background)
      layers[1] = context.getDrawable(R.drawable.ic_launcher_foreground)
      val layerDrawable = LayerDrawable(layers)

      holder.imageView?.load(layerDrawable) {
        transformations(CircleCropTransformation())
      }
```

**Library version**
0.8.0

**Comment by colinrtwhite** [comment]
This is currently intended behaviour, as `Transformations` are ignored for non-`BitmapDrawables`. However, I think it makes sense to allow users to apply `Transformations` by converting the input `Drawable` into a `BitmapDrawable`. I've added a fix in #155.

**Comment by steve-pollack** [comment]
Thank you very much for that!

**Comment by mario** [comment]
Thanks!
