### ISSUE TITLE
Webm videos aren't playing

### ISSUE THREAD

**Issue by MinaMohsen** [coil-kt/coil#1542]
**Describe the bug**
I'm trying to play video webm in compose but it just load an image and no playback 
                val context = LocalContext.current
                val imageLoader = ImageLoader.Builder(context)
                    .components {
                        add(VideoFrameDecoder.Factory())
                    }
                    .logger(DebugLogger())
                    .build()

                val painter = rememberAsyncImagePainter(
                    model = "file:///android_asset/videos/test.webm",
                    imageLoader = imageLoader
                )

                Image(
                    painter = painter,
                    contentDescription = null,
                    contentScale = ContentScale.Crop,
                    alignment = Alignment.Center,
                    modifier = imageModifier
                )
                LaunchedEffect(key1 = true) {
                    imageLoader.execute(painter.request)
                }

**Comment by colinrtwhite** [comment]
`VideoFrameDecoder` only decodes individual video frames and won't play the whole video. You'll need to use [`ExoPlayer`](https://github.com/google/ExoPlayer) to play full videos inside of Compose.
