### ISSUE TITLE
VideoFrameDecoder#computeFrameMicros fallback value should be negative.

### ISSUE THREAD

**Issue by lyh8577** [coil-kt/coil#1547]
**Describe the bug**
See param timeUs doc: android.media.MediaMetadataRetriever#getScaledFrameAtTime(long, int, int, int, android.media.MediaMetadataRetriever.BitmapParams)
<img width="653" alt="屏幕截图 2022-11-27 205956" src="https://user-images.githubusercontent.com/16410503/204136603-b4d3d7ce-7c8f-45ae-a63f-5f15dbd021cd.png">

**Version**
2.2.2

**Comment by colinrtwhite** [comment]
`getScaledFrameAtTime ` isn't used on all API levels and `getFrameAtTime` doesn't mention that behaviour. Overall, it's better to consistently use the first frame across all API levels than rely the platform's default behaviour, which can change between API levels and devices.
