### ISSUE TITLE
Exif Interface Interception?

### ISSUE THREAD

**Issue by mandrachek** [coil-kt/coil#1549]
I have an a custom decoder that reads images that have been encrypted (using AndroidX Crypto's EncryptedFile). When I save the images captured from the camera without encryption, they are rotated to their proper orientation from the exif data.  

Encrypted images are decoded correctly, but it appears that the Exif processing does not use the decoder, and so it fails to get the requested orientation.

Is there any way to get coil to use an EncryptedFile.inputStream to read the Exif data?

**Comment by colinrtwhite** [comment]
@mandrachek Sorry for the delay! Did you manage to solve this? It sounds like you might be better off writing a custom fetcher that gets your `EncryptedFile` and returns `ImageSource(encryptedFile.inputStream.source().buffer(), context)`. That'll let it be decoded by `BitmapFactoryDecoder`, which will handle the EXIF rotation.

**Comment by mandrachek** [comment]
@colinrtwhite - no worries, thanks for the reply.  I'll take a look at that approach and see if I can get it to work.

**Comment by mandrachek** [comment]
So, it looks like I need to use my DecryptingDecoder, but I need to handle the rotation myself, like coil's `BitmapDecoderFactory` does.  Multiple sequential reads seem to work, so something like this -

```kotlin
            encryptedFile.openFileInput().use { exifInputStream ->
                ExifInterface(exifInputStream).let { exifInterface ->
                    isFlipped = exifInterface.isFlipped
                    rotationDegress = exifInterface.rotationDegrees
                }
            }
            
            Timber.e("IS FLIPPED: $isFlipped")
            Timber.e("IS ROTATED: $rotationDegress")

            encryptedFile.openFileInput().use { inStream ->
                val bitmap = BitmapFactory.decodeStream(inStream)
                return DecodeResult(bitmap.toDrawable(context.resources), false)
            }
```

The flipped and rotation values are correctly reported in my logging output.  I just need to do something with them. ;)

**Comment by colinrtwhite** [comment]
@mandrachek Interesting - I'd expect `BitmapFactoryDecoder` to work with an `InputStream` that can only be read sequentially as input streams from Android assets and resources can only be read sequentially too and there are [tests covering those cases](https://github.com/coil-kt/coil/blob/main/coil-base/src/androidTest/java/coil/RealImageLoaderAndroidTest.kt#L186). If it's not too much trouble could you add a [test case](https://github.com/coil-kt/coil/blob/main/coil-base/src/androidTest/java/coil/decode/BitmapFactoryDecoderTest.kt) for `BitmapFactoryDecoder` that attempts to decode an encrypted file? Thanks!

**Comment by colinrtwhite** [comment]
Going to close this out to keep the issue tracker tidy. To sum up, I'd ideally avoid implementing this as a decoder and only create a `EncryptedImageFetcher` class that exposes the encrypted file `InputStream`. That way `BitmapFactoryDecoder` can handle decoding the image + rotating based on EXIF orientation. If `BitmapFactoryDecoder` is unable to read encrypted file streams please open another issue as that should be fixed.
