### ISSUE TITLE
Load the network image in RecyclerView. The size will become lager in secondary load

### ISSUE THREAD

**Issue by ChawLoo** [coil-kt/coil#1556]
**Describe the bug**
I have a recyclerView and item in it have a imageView widget, i load network image to it, when loading for the second time, the imageView become large

**To Reproduce**
It occurs in our production environment project and it is inconvenient to provide source code

**Logs/Screenshots**
it is first load, they are same size
![image](https://user-images.githubusercontent.com/26214519/205241537-41132e77-98cf-49b2-8332-9613b38d5a41.png)
![image](https://user-images.githubusercontent.com/26214519/205241618-5501f119-9e0a-4a22-bc16-9d154585963a.png)

when load second with same network image , it become larger
![image](https://user-images.githubusercontent.com/26214519/205242260-a8ffeb0b-7258-4ace-94e1-513f1aac7697.png)
![image](https://user-images.githubusercontent.com/26214519/205242296-34ab252d-ec1b-453f-a7ff-e239d84d5c4d.png)

**Version**
2.2.2

**Comment by ChawLoo** [comment]
I found something when i test, My imageView set width 44dp height 44dp and conversion px is 138px, the network image size is 300px*300px. if set scaleType.Fill, it be resolved, but why? why image can not fill the imageView 

it is the image
![1658803710639avatar](https://user-images.githubusercontent.com/26214519/205252740-5bf94858-d80c-4f41-862d-4b5419178239.png)

**Comment by colinrtwhite** [comment]
It's tough to say without a way to reproduce the issue, but it's likely you're loading the image at a larger size after the first load. Coil only keeps the larger version of the image in the memory cache. To force Coil to load the image at the exact requested size you can set `precision(Precision.EXACT)` on your `ImageRequest`.
