### ISSUE TITLE
The gif cannot be loaded normally after the coil is set with rounded corners

### ISSUE THREAD

**Issue by xqh0927** [coil-kt/coil#1563]
@BindingAdapter("urlRounded")
fun loadRounded(imageView: ImageView?, url: String?) {
    imageView?.load(url) {
        RoundedCornersTransformation(imageView.context.resources.getDimension(R.dimen.dp_16))
        scale(Scale.FILL)
        placeholder(R.mipmap.img)   //添加占位图
        error(R.mipmap.img)   //加载失败的情况

    }
}

        <ImageView
            android:id="@+id/iv_image"
            urlRounded="@{item.coverPic}"
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_220"
            android:scaleType="centerCrop" />

**Comment by colinrtwhite** [comment]
Applying a `RoundedCornersTransformation` to a gif will convert it into a static image. Check out `AnimatedTransformation`.
