### ISSUE TITLE
Apply content scaling to placeholder/error Painter as well

### ISSUE THREAD

**Issue by digitalheir** [coil-kt/coil#1568]
**Is your feature request related to a problem? Please describe.**

I load an image. I know the dimensions beforehand, so I can reserve the space with a simple `Painter` which paints a solid color so that the layout will not jump. The painter has an intrinsic size equal to the image.

```
    AsyncImage(
        model = ImageRequest.Builder(context).data("https://raw.githubusercontent.com/coil-kt/coil/main/logo.svg").crossfade(true).build(),
        placeholder = PlaceholderPainter(
            MaterialTheme.colorScheme.surfaceVariant,
            width = 403, height = 202,
        ),
        contentDescription = contentDescription,
        contentScale = ContentScale.FillWidth
        modifier = modifier,
        alignment = Alignment.Center, 
    )
```

However, Coil draws the placeholder exactly at the intrinsic size, and does not scale it according to the parameter. The layout still jumps.

**Describe the solution you'd like**

I would like Coil to respect the `contentScale` setting for the passed placeholder, so that it takes the exact same size as the loaded image.

I know I can scale the intrinsic size of the `Painter` according to the container dimensions, but I think it would be nice if Coil resized it automatically.

Coil version 2.2.2

**Comment by colinrtwhite** [comment]
@digitalheir I'm not able to reproduce this locally. I updated the sample app in this repo to use:

```kotlin
AsyncImage(
    model = ImageRequest.Builder(LocalContext.current)
        .data(screen.image.uri)
        .crossfade(2_500)
        .build(),
    placeholder = object : Painter() {
        override val intrinsicSize get() = Size(100f, 100f)

        override fun DrawScope.onDraw() {
            drawRect(Color.Blue)
        }
    },
    contentScale = ContentScale.FillWidth,
    alignment = Alignment.Center,
    contentDescription = null,
    modifier = Modifier.fillMaxSize()
)
```

And the placeholder filled the width of the `AsyncImage`:

[device-2023-03-16-223600.webm](https://user-images.githubusercontent.com/5580160/225821303-c0d48f3b-60fb-411a-97ad-9c7e9161a965.webm)
