### ISSUE TITLE
rememberAsyncImagePainter 这个方法很耗时

### ISSUE THREAD

**Issue by lic2050** [coil-kt/coil#1570]
Use Compose :
               println(" time1 = ${System.currentTimeMillis()}")
                Image(
                    rememberAsyncImagePainter(ImageRequest.Builder(LocalContext.current)
                        .data("imgUrl")
                        .build()),
                    contentDescription = null,
                    modifier = Modifier
                        .size(60.dp)
                )
                println(" time1 = ${System.currentTimeMillis()}")

time2 - time1 was about 4-6ms, 

Use AndroidView ImageView:
                                println(" time1 = ${System.currentTimeMillis()}")
                                AndroidView(
                                    modifier = Modifier
                                        .size(20.dp),
                                    update = {
                                             it.load("imgUrl")
                                    },
                                    factory = {
                                        ImageView(it)
                                    }
                                )
                                println(" time1 = ${System.currentTimeMillis()}")
time2 - time1 was about 0-1ms, 
release环境下使用Compose会很卡顿，使用AndroidView就会很流畅。rememberAsyncImagePainter会影响性能

App BuildType: Release
Phone: huawei meta 30 
Compose version: 1.3.1

**Comment by colinrtwhite** [comment]
There's not enough info to make this bug report actionable.
