### ISSUE TITLE
Keep aspect ratio of local vector drawables

### ISSUE THREAD

**Issue by 145k0v** [coil-kt/coil#158]
When loading a local vector image into a fix-sized `ImageView` (with `centerCrop` and/or `Scale.FILL`), the aspect ratio is not preserved.

**To Reproduce**
Take a look at the sample project [here](https://github.com/145k0v/coil-sample). Just add an `ImageView` with fixed dimensions:

```
    <ImageView
        android:id="@+id/image_2"
        android:layout_width="200dp"
        android:layout_height="120dp"
        android:scaleType="centerCrop"/>
```

and load a local vector drawable into it:

```
    image_2.load(R.drawable.vector_ic_wall_clock) {
        scale(Scale.FILL)   // With or without Coil scaling
    }
```

**Expected behavior**
The image should maintain its square aspect ratio and not appear stretched.

**Screenshots**
Vector drawables do not preserve aspect ratio
![vector](https://user-images.githubusercontent.com/13486209/67932021-6862a300-fbc3-11e9-8ad2-2bed83e0a455.png)

However, with PNGs there is no such problem
![png](https://user-images.githubusercontent.com/13486209/67932094-91833380-fbc3-11e9-8e96-b40fbef7d32d.png)

**Library version**
0.8.0

**Comment by colinrtwhite** [comment]
Thanks for the report. I'll take a look at this this weekend.
