### ISSUE TITLE
DiskCache is never used

### ISSUE THREAD

**Issue by zkoalas** [coil-kt/coil#1584]
**Describe the bug**
A clear and concise description of what the bug is. **Please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.** Bug reports without reproduction steps are likely to be closed.

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?
version: 2.2.2

When the image is not in the memoryCache, you should go to diskCache to find it, but Coil is not, but directly to initiate a network request, request back the image, save to DiskCache, and save to MemoryCache.
Then go to memoryCache to load, diskCache is not used at all.

The correct logic should be to look for it from memoryCache first, if you can't find it, go to DiskCache to find it, if you can't find it, initiate a network request and go to the server to find it.

**Comment by colinrtwhite** [comment]
Sorry, but there isn't enough information to reproduce the issue. It's possible the headers on your network request are preventing caching. If that's the case you can disable cache control header support using [`ImageLoader.Builder.respectCacheHeaders(false)`](https://coil-kt.github.io/coil/api/coil-base/coil/-image-loader/-builder/respect-cache-headers.html?query=fun%20respectCacheHeaders(enable:%20Boolean):%20ImageLoader.Builder).
