### ISSUE TITLE
only callback onCancel ;no callback onSuccess

### ISSUE THREAD

**Issue by geekwwzhang** [coil-kt/coil#1586]
**Describe the bug**
Call image loading multiple times in a short period of time. There will be only cancel callback

**To Reproduce**
![image](https://user-images.githubusercontent.com/52212469/211197581-2e706b93-f2b7-47c9-b428-6f005431d7d5.png)

**Logs/Screenshots**
![image](https://user-images.githubusercontent.com/52212469/211197613-bbe30bdd-8ece-4bc7-bd3e-00da9ec3b106.png)

![image](https://user-images.githubusercontent.com/52212469/211197562-795e06a4-fbfb-4b44-8d83-f538c788c338.png)

**Version**
1.1.1-1.4.0

**Comment by geekwwzhang** [comment]
I user four url test this case。please help me

**Comment by colinrtwhite** [comment]
Each `ImageView` can only have at most one active request attached to it. It's expected behaviour that launching a new request on an `ImageView` cancels any in-flight requests attached to that view.
