### ISSUE TITLE
gif

### ISSUE THREAD

**Issue by Nurtaz440** [coil-kt/coil#1587]
**Describe the bug**

 implementation "io.coil-kt:coil-gif:2.2.2"

  val memoryCache = coil.memory.MemoryCache.Builder(requireContext()).build()

        val imageLoader = ImageLoader.Builder(requireContext())
            .components{
               
                add(StorageReferenceFetcher.Factory())
                if (SDK_INT >= P) {
                    add(ImageDecoderDecoder.Factory())
                } else {
                    add(GifDecoder.Factory())
                }
            }
            .memoryCache(memoryCache)
            .memoryCachePolicy(CachePolicy.ENABLED)
            .build()

        binding.ivGif.load(navArgs.gifUrl, imageLoader = imageLoader)

My code but do not show gif in android

**Comment by colinrtwhite** [comment]
There isn't enough info in this report to reproduce the issue. To force the GIF Decoder to handle the request you could try:

```kotlin
binding.ivGif.load(navArgs.gifUrl) {
    decoderFactory { result, options, imageLoader ->
        if (SDK_INT >= P) {
            ImageDecoderDecoder(result.source, options)
        } else {
            GifDecoder(result.source, options)
        }
    }
}
```
