### ISSUE TITLE
Unable to access `get` methods

### ISSUE THREAD

**Issue by igorwojda** [coil-kt/coil#16]
**Describe the bug**
I am using `io.coil-kt:coil-base` because I want to take advantage of DI.

However, I am not sure how to use `ImageVIew`. There seems to be some IDE wired behavior where `get` methods are visible in code completion but missing in the actual code.

**To Reproduce**
How can we reproduce this?

```
import android.os.Bundle
import androidx.navigation.findNavController
import androidx.navigation.ui.setupWithNavController
import coil.ImageLoader
import com.igorwojda.showcase.R
import com.igorwojda.showcase.base.presentation.activity.BaseActivity
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : BaseActivity() {

    override val layoutResId = R.layout.activity_main

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val imageLoader = ImageLoader(this)
        
		CoroutineScope(Dispatchers.Main).launch {
            imageLoader.get("url")
        }
    }
}
```

Code completion seems to show all posibilitie overloads (inclusing `ImageView` extensions)
![image](https://user-images.githubusercontent.com/530122/62930092-9e0da200-bdb3-11e9-8762-f1929a20b8aa.png)

...but they can't be used 🤔 
![image](https://user-images.githubusercontent.com/530122/62930263-fba1ee80-bdb3-11e9-809c-6542dbe61278.png)

**Expected behavior**
Just load an image using the get method
`imageLoader.get("url")`

(ideally, `ImageView` instance will be injected - this is a simplified example)

**Library version**
e.g. 0.6.0

**Comment by colinrtwhite** [comment]
Have you added `import coil.api.get`? The type-safe `ImageLoader` functions are extension functions since they're essentially "sugar" on top of the base `ImageLoader` APIs.

**Comment by igorwojda** [comment]
thx - your suggestion worked.


I use auto import and imports are usually added on the fly. This case, however, is different and it looks like Kotlin plugin bug to me (mainly because this import should be added automatically and if not there should be a quick fix to add it).
Reported to Kotlin issue tracker
https://youtrack.jetbrains.com/issue/KT-33318
