### ISSUE TITLE
Image shows rotated on samsung device.

### ISSUE THREAD

**Issue by nicemak** [coil-kt/coil#160]
**Describe the bug**
I picked an image from gallery and load it, image is rotated on samsung device/tab.

**To Reproduce**
select an image from gallery and load it imageview on samsung device.

**Expected behavior**
image should show correctly angle/rotated as seen in gallery.

**Library version**
0.8.0

**Comment by colinrtwhite** [comment]
@nicemak Do you have a sample image I could use to reproduce the issue? Coil looks at the [EXIF data](https://en.wikipedia.org/wiki/Exif) to determine rotation, though maybe this is being stripped by the system.

**Comment by nicemak** [comment]
sure.
![20191101_090058](https://user-images.githubusercontent.com/34672155/68101084-ade9dd80-feed-11e9-88c2-1494a841c299.jpg)
![20191101_090111](https://user-images.githubusercontent.com/34672155/68101085-ae827400-feed-11e9-8ec0-6c8d8073ab93.jpg)

**Comment by colinrtwhite** [comment]
@nicemak I haven't been able to reproduce this on a Samsung Note 8 running 8.0. The image contains the correct EXIF orientation after decoding the uri returned by `Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI)`.

What device + OS version can you reproduce this on? Could you create a sample project to reproduce the issue? Thanks.

**Comment by nicemak** [comment]
Thanks for your time, i have managed to do it myself. :)

**Comment by kiviabrito** [comment]
> Thanks for your time, i have managed to do it myself. :)

How did you manage it? I am getting the same problem.

**Comment by nicemak** [comment]
i create a function

`@Throws(IOException::class)
private fun rotateImageIfRequired(img: Bitmap?, selectedImage: String): Bitmap? {
    
    val ei = ExifInterface(selectedImage)
    val orientation =
            ei.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_NORMAL)
    
    return when (orientation) {
        ExifInterface.ORIENTATION_ROTATE_90  -> rotateImage(img, 90)
        ExifInterface.ORIENTATION_ROTATE_180 -> rotateImage(img, 180)
        ExifInterface.ORIENTATION_ROTATE_270 -> rotateImage(img, 270)
        else                                 -> img
    }
}

private fun rotateImage(img: Bitmap?, degree: Int): Bitmap
{
    val matrix = Matrix()
    matrix.postRotate(degree.toFloat())
    val rotatedImg = Bitmap.createBitmap(img!!, 0, 0, img.width, img.height, matrix, true)
    img.recycle()
    return rotatedImg
}`

and use it like

`bm = rotateImageIfRequired(bm, path)`
