### ISSUE TITLE
Strange error after use coil

### ISSUE THREAD

**Issue by prsolucoes** [coil-kt/coil#161]
**Describe the bug**
Fatal Exception: coil.network.HttpException: HTTP 504: Unsatisfiable Request (only-if-cached)
       at coil.fetch.HttpUrlFetcher.fetch + 57(HttpUrlFetcher.kt:57)
       at coil.fetch.HttpUrlFetcher$fetch$1.invokeSuspend + 16(:16)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith + 33(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run + 241(Dispatched.kt:241)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely + 594(CoroutineScheduler.kt:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely + 60(CoroutineScheduler.kt:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run + 740(CoroutineScheduler.kt:740)

**Logs/Screenshots**
If applicable, add logs or screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/395096/68228153-b4528500-ffd3-11e9-8504-08608fe83639.png)

**Library version**
0.8.0

THIS ERROS WAS CAPTURED FROM FABRIC

**Comment by colinrtwhite** [comment]
An `HTTP 504` error occurs if an OkHttp request is started with both data sources (network and disk) disabled. Coil automatically disables querying from the network if the device is offline. If you also disable the disk cache for this request using `diskCachePolicy(CachePolicy.DISABLED)` while the device is offline, this is intended behaviour as the request cannot be satisfied.

**Comment by prsolucoes** [comment]
Hi,

But it will generate a crash?

In my case it is crashing the app.

???

**Comment by colinrtwhite** [comment]
@prsolucoes Are you using `Coil.get`? That will propagate the exception into your `CoroutineScope`. You'll need to surround the call in a `try/catch` or [add a `CoroutineExceptionHandler`](https://kotlinlang.org/docs/reference/coroutines/exception-handling.html#exceptions-in-supervised-coroutines) to your scope.

**Comment by prsolucoes** [comment]
Hi @colinrtwhite,

Yes, is this that i do. I put a try/catch there and solve the problem.

Can you put after in docs something about it? I think other can have problems with it too.

Im coming from picasso/glide and i think some things are missing or you will add in future like methods: fit, fitCenter, rounded images after resize [some libs don't apply rounded corners when image is resized], centerCrop etc.

But it is a great library until now. Good work.

Thanks anyway.

**Comment by uberchilly** [comment]
I have the same issues and I not disabling disc cache 
```
utilityLogo.load(
	imageUrl
) {
	setHeader(
		"Authorization",
		NetworkUtils.getAuthorizationHeader(accessToken)
	)
	memoryCacheKey(imageUrl)
	diskCachePolicy(CachePolicy.ENABLED)
	memoryCachePolicy(CachePolicy.ENABLED)
}
```
I can see the whole request being stored on the disc on emulator in data -> data -> app_package_folder -> cache -> image_cache. 
Only thing that can maybe cause this is 
```
Cache-Control: public, max-age=0 
```
in the request. But then it is kind of weird that the okhttp stores it on the disc after all
