### ISSUE TITLE
Scrolling is laggy using jetpack compose LazyVerticalGrid and Coil

### ISSUE THREAD

**Issue by alirezaeiii** [coil-kt/coil#1610]
I tried to implement pagination in my app using compose. Here you can find full source code : https://github.com/alirezaeiii/TMDb-Compose

First I am showing a loading indicator, and then loads items from TMDb API. So I have following composable method :

    @Composable
    fun <T : TMDbItem> PagingScreen(
        viewModel: BasePagingViewModel<T>,
        onClick: (TMDbItem) -> Unit,
    ) {
        val lazyTMDbItems = viewModel.pagingDataFlow.collectAsLazyPagingItems()
    
        when (lazyTMDbItems.loadState.refresh) {
            is LoadState.Loading -> {
                TMDbProgressBar()
            }
            is LoadState.Error -> {
                val message =
                    (lazyTMDbItems.loadState.refresh as? LoadState.Error)?.error?.message ?: return
    
                lazyTMDbItems.apply {
                    ErrorScreen(
                        message = message,
                        modifier = Modifier.fillMaxSize(),
                        refresh = { retry() }
                    )
                }
            }
            else -> {
                LazyTMDbItemGrid(lazyTMDbItems, onClick)
            }
        }
    }

As you see in the else section it calls LazyTMDbItemGrid composable function :

    @Composable
    private fun <T : TMDbItem> LazyTMDbItemGrid(
        lazyTMDbItems: LazyPagingItems<T>,
        onClick: (TMDbItem) -> Unit
    ) {
        LazyVerticalGrid(
            columns = GridCells.Fixed(COLUMN_COUNT),
            contentPadding = PaddingValues(
                start = Dimens.GridSpacing,
                end = Dimens.GridSpacing,
                bottom = WindowInsets.navigationBars.getBottom(LocalDensity.current)
                    .toDp().dp.plus(
                        Dimens.GridSpacing
                    )
            ),
            horizontalArrangement = Arrangement.spacedBy(
                Dimens.GridSpacing,
                Alignment.CenterHorizontally
            ),
            content = {
    
                items(lazyTMDbItems.itemCount) { index ->
                    val tmdbItem = lazyTMDbItems[index]
                    tmdbItem?.let {
                        TMDbItemContent(
                            it,
                            Modifier
                                .height(320.dp)
                                .padding(vertical = Dimens.GridSpacing),
                            onClick
                        )
                    }
                }
    
                lazyTMDbItems.apply {
                    when (loadState.append) {
                        is LoadState.Loading -> {
                            item(span = span) {
                                LoadingRow(modifier = Modifier.padding(vertical = Dimens.GridSpacing))
                            }
                        }
                        is LoadState.Error -> {
                            val message =
                                (loadState.append as? LoadState.Error)?.error?.message ?: return@apply
    
                            item(span = span) {
                                ErrorScreen(
                                    message = message,
                                    modifier = Modifier.padding(vertical = Dimens.GridSpacing),
                                    refresh = { retry() })
                            }
                        }
                        else -> {}
                    }
                }
            })
    }

In order to load images in the ImageView asynchronously, I have following function :

    @Composable
    private fun BoxScope.TMDbItemPoster(posterUrl: String?, tmdbItemName: String) {
        val painter = rememberAsyncImagePainter(
            model = posterUrl,
            error = rememberVectorPainter(Icons.Filled.BrokenImage),
            placeholder = rememberVectorPainter(Icons.Default.Movie)
        )
        val colorFilter = when (painter.state) {
            is AsyncImagePainter.State.Loading, is AsyncImagePainter.State.Error -> ColorFilter.tint(
                MaterialTheme.colors.imageTint
            )
            else -> null
        }
        val scale =
            if (painter.state !is AsyncImagePainter.State.Success) ContentScale.Fit else ContentScale.FillBounds
    
        Image(
            painter = painter,
            colorFilter = colorFilter,
            contentDescription = tmdbItemName,
            contentScale = scale,
            modifier = Modifier
                .fillMaxSize()
                .align(Alignment.Center)
        )
    }

The problem is when I am scrolling very fast in the part of screen that images are not loaded yet, it is quite laggy. Based on my research there is no problem with my image loading using coil library, but I do not know why it is laggy. Is it any issue with using coil in LazyVerticalGrid ?

**Comment by colinrtwhite** [comment]
Did you test the performance using the `release` variant? [Jetpack Compose is much slower in debug mode](https://developer.android.com/jetpack/compose/performance).

**Comment by alirezaeiii** [comment]
Yes, I know. But still it seems it is laggy when loading images in LazyVerticalGrid. You can try my sample on your device and see how much laggy it is. Thank you for the link.

**Comment by colinrtwhite** [comment]
@alirezaeiii After configuring the app for release mode, enabling R8, and running it, the app runs fine on my Pixel 3:

https://user-images.githubusercontent.com/5580160/217415396-b8c0fdf6-c7e2-42b8-8793-5f5dfc0d6223.mp4

I'd check out the Android [CPU profiler](https://developer.android.com/studio/profile/cpu-profiler) tools if you want to go deeper on performance.

**Comment by TheAlter71** [comment]
I also noticed the lag while scrolling

**Comment by imandaliya** [comment]
I have same lagging issue with LazyVerticalGrid with coil

**Comment by BitMavrick** [comment]
> @alirezaeiii After configuring the app for release mode, enabling R8, and running it, the app runs fine on my Pixel 3:
> 
>  device-2023-02-07-184323.mp4 
> I'd check out the Android [CPU profiler](https://developer.android.com/studio/profile/cpu-profiler) tools if you want to go deeper on performance.

How to enable R8? actually, I don't know what R8 is!

**Comment by umardev500** [comment]
Jetpack compose really really trouble in performance so what is the future of jetpack compose i think so bad

**Comment by muhammadawaisshan** [comment]
Any workaround this??
