### ISSUE TITLE
Show incorrect images when load too fast

### ISSUE THREAD

**Issue by morningos** [coil-kt/coil#1622]
**Describe the bug**
I use it in LazyColumn,but when I update LazyColumn,it shows incorrect images.

Log:
```log
...
2023-02-17 17:42:54.933 19537-19537 RealImageLoader  cc.imorning.chat          I  💾 Successful (DISK) - /storage/emulated/0/Android/data/cc.imorning.chat/cache/avatarCache/b887da7a886a9a23e738dafb40b79ebf
2023-02-17 17:42:56.750 19537-19537 RealImageLoader  cc.imorning.chat          I  💾 Successful (DISK) - /storage/emulated/0/Android/data/cc.imorning.chat/cache/avatarCache/d0b9c5d87ff140e0eda222abe2ace7a1
2023-02-17 17:42:56.751 19537-19537 RealImageLoader  cc.imorning.chat          I  💾 Successful (DISK) - /storage/emulated/0/Android/data/cc.imorning.chat/cache/avatarCache/b887da7a886a9a23e738dafb40b79ebf
2023-02-17 17:42:56.751 19537-19537 RealImageLoader  cc.imorning.chat          I  💾 Successful (DISK) - /storage/emulated/0/Android/data/cc.imorning.chat/cache/avatarCache/d0b9c5d87ff140e0eda222abe2ace7a1
2023-02-17 17:42:56.751 19537-19537 RealImageLoader  cc.imorning.chat          I  💾 Successful (DISK) - /storage/emulated/0/Android/data/cc.imorning.chat/cache/avatarCache/b887da7a886a9a23e738dafb40b79ebf
...
```

init code:

```kotlin
override fun newImageLoader(): ImageLoader {
    return ImageLoader.Builder(this)
        .diskCachePolicy(CachePolicy.DISABLED)
        .memoryCachePolicy(CachePolicy.DISABLED)
        .logger(DebugLogger())
        .build()
}
```

use:
```kotlin
AsyncImage(
    model = getAvatarFilePath(user),
    modifier = Modifier
        .padding(horizontal = 16.dp)
        .size(42.dp)
        .border(1.5.dp, borderColor, CircleShape)
        .border(3.dp, MaterialTheme.colorScheme.surface, CircleShape)
        .clip(CircleShape)
        .align(Alignment.Top),
    contentDescription = null
)
```

I have tried to enable or disable cache,but it still not works.What's more,it even loads the other image in the same directory.

**To Reproduce**
I'm not sure how to reproduce it, maybe you can try load lots of images in same time.

**Logs/Screenshots**

Before LazyColumn update:
![image](https://user-images.githubusercontent.com/44289789/219610337-4c67f263-89ca-41af-b2d2-2b0b32713845.png)

After LazyColumn update:
![image](https://user-images.githubusercontent.com/44289789/219610444-81487150-cbbc-4415-83f8-49203ee79001.png)

**Version**

`implementation 'io.coil-kt:coil-compose:2.2.2'`

Andoroid API 30

**Comment by morningos** [comment]
I solved the bug just by replacing `AsyncImage` with `GlideImage` ...

**Comment by colinrtwhite** [comment]
Sorry but there isn't enough information to debug this issue. I tried updating the `coil-sample` app in this repo with your `ImageLoader` + `AsyncImage` configuration and it loads the correct image when scrolling quickly.

**Comment by PrimoDev23** [comment]
@colinrtwhite I am facing the same issue as you can see in the video.
I can't really provide the repo for reproduction, since this is closed source. Anyways I will provide everything needed in here.

We are currently using a fragment with a compose view in it. In there we have a normal column that generates its contents according to a list of projects.

```
@Composable
fun ProjectList(
    projects: List<Project>,
    currentSort: SortType,
    onSortTypeSelected: (SortType) -> Unit,
    onProjectClicked: (Project) -> Unit,
    modifier: Modifier = Modifier
) {
    Column(modifier = modifier) {
        ProjectListHeader(
            modifier = Modifier.fillMaxWidth(),
            currentSort = currentSort,
            onSortTypeSelected = onSortTypeSelected
        )

        Spacer(modifier = Modifier.height(16.dp))

        projects.forEachIndexed { index, project ->
            ProjectListItem(
                modifier = Modifier
                    .height(151.dp)
                    .fillMaxWidth(),
                project = project,
                onClick = {
                    onProjectClicked(project)
                }
            )

            if (index != projects.lastIndex) {
                Spacer(modifier = Modifier.height(16.dp))
            }
        }
    }
}
```

Each ProjectListItem contains an image defined by a mediaId on our backend. We wrap this behavior inside this block

```
@Composable
fun SAsyncImage(
    mediaId: String,
    modifier: Modifier = Modifier,
    mediaInfoFetcher: MediaInfoFetcher = get(),
    transform: (AsyncImagePainter.State) -> AsyncImagePainter.State = AsyncImagePainter.DefaultTransform,
    onState: ((AsyncImagePainter.State) -> Unit)? = null,
    alignment: Alignment = Alignment.Center,
    contentScale: ContentScale = ContentScale.Fit,
    alpha: Float = DefaultAlpha,
    colorFilter: ColorFilter? = null,
    filterQuality: FilterQuality = DrawScope.DefaultFilterQuality,
) {
    val context = LocalContext.current
    val mediaInfo by produceMediaInfoFromMediaId(
        mediaInfoFetcher = mediaInfoFetcher,
        mediaId = mediaId
    )

    val model = remember(mediaInfo) {
        mediaInfo?.let { info ->
            ImageRequest.Builder(context)
                .data(info.url)
                .decoderFactory(SvgDecoder.Factory())
                .diskCachePolicy(CachePolicy.ENABLED)
                .diskCacheKey("${info.id}-${info.lastModified}")
                .memoryCachePolicy(CachePolicy.ENABLED)
                .memoryCacheKey("${info.id}-${info.lastModified}")
                .build()
        }
    }

    AsyncImage(
        modifier = modifier,
        model = model,
        contentDescription = mediaInfo?.altText,
        transform = transform,
        onState = onState,
        alignment = alignment,
        contentScale = contentScale,
        alpha = alpha,
        colorFilter = colorFilter,
        filterQuality = filterQuality
    )
}
```

I also tried removing the remember block to have this updated on recompositions, but that does not work as well. I would be glad if you could tell me why this happens or if this is actually a bug in the coil library.

https://github.com/coil-kt/coil/assets/46970398/35b9ec4b-d979-4c19-a268-41d5603023d0

**Comment by morningos** [comment]
Finally I found it's my incorrect code, before fixing it：
```kotlin
    fun getUserAvatar(uid: Int): String {
        var path: String
        if (hasLocalCache(uid)) {
            path = getLocalCache(uid)
        }
        path = getFromInternet(uid)
        return path
    }
```
Now you can see, it always return internet data because I forgot return it in `if` , so I fix it like this:

```kotlin
  fun getUserAvatar(uid: Int): String {
      var path: String
      if (hasLocalCache(uid)) {
          path = getLocalCache(uid)
          return path
      }
      path = getFromInternet(uid)
      return path
  }
```

**Comment by PrimoDev23** [comment]
So here is a small update from my side. I was able to fix this issue by using a LazyColumn. In this case this may be possible, but I also discovered this bug in another place where we need to use a scrollable row, that has to load all elements on composition.
After some debugging I also found out that this only happens with this specific image and only with the shown order of selecting sort options. It was not possible to reproduce this in any other case.



> Finally I found it's my incorrect code, before fixing it：
> 
> ```kotlin
>     fun getUserAvatar(uid: Int): String {
>         var path: String
>         if (hasLocalCache(uid)) {
>             path = getLocalCache(uid)
>         }
>         path = getFromInternet(uid)
>         return path
>     }
> ```
> 
> Now you can see, it always return internet data because I forgot return it in `if` , so I fix it like this:
> 
> ```kotlin
>   fun getUserAvatar(uid: Int): String {
>       var path: String
>       if (hasLocalCache(uid)) {
>           path = getLocalCache(uid)
>           return path
>       }
>       path = getFromInternet(uid)
>       return path
>   }
> ```

I would really like to call this the solution for me, but it isn't, since it works with LazyColumn without changing any logic. Also we always load from a remote url, without any manual caching
