### ISSUE TITLE
Does not include AsyncImage composable

### ISSUE THREAD

**Issue by hmdevelo** [coil-kt/coil#1624]
I've just added the latest coil library but I can't use AsyncImage composable

![Untitled](https://user-images.githubusercontent.com/122331431/220321938-a590a0bf-7030-484c-889d-3068099b4d09.png)

**Comment by colinrtwhite** [comment]
I'd double check that you've included the `coil-compose` dependency: https://github.com/coil-kt/coil#jetpack-compose

**Comment by hmdevelo** [comment]
> I'd double check that you've included the `coil-compose` dependency: https://github.com/coil-kt/coil#jetpack-compose

Yes, I've added. I've tried adding in an empty project, but it doesn't work as well. Is there anything wrong? This is my gradle file.
![Untitled](https://user-images.githubusercontent.com/122331431/220504831-fa04d095-17e1-4eaa-98d6-f07b00d1e006.png)

**Comment by imneeraj** [comment]
Same.
Cannot find AsyncImage Composable
using  :  implementation 'io.coil-kt:coil:2.2.2'

![image](https://user-images.githubusercontent.com/16626659/224550925-9a95047b-321e-4ed7-93aa-1550b127c1eb.png)
