### ISSUE TITLE
Image Load From URL failed in emulator.

### ISSUE THREAD

**Issue by netDinger** [coil-kt/coil#1630]
**Describe the bug**
I can't load the url image using AsyncImage on Emulator. My emulator is SDK 29(Pixel 3) and Coil version "2.2.2". It is working fine on real device.

**To Reproduce**
Here is my code to reproduce the error,

```kotlin  
AsyncImage(model = ImageRequest.Builder(context)
                    .data("https://www.heatheronhertravels.com/wp-content/uploads/2013/10/Lac-Blanc1.jpg")
                    .crossfade(true) // I tried adding this and still doesn't work .allowHardware(false)
                    .size(200)
                    .build(),
                    contentDescription = null,
                    modifier = Modifier.size(Dimens.avatarSize2)) 
```
and simply 
```kotlin 
AsyncImage("https://www.heatheronhertravels.com/wp-content/uploads/2013/10/Lac-Blanc1.jpg",
                    contentDescription = null,
                    modifier = Modifier.size(Dimens.avatarSize2)) 
```
I got no error log. Just don't load in enmulator and work fine on real device.

**Version**
Coil version -> 2.2.2
Emulator SDK version -> 29(Pixel 3)
Laptop -> Macbook air M1

**Comment by colinrtwhite** [comment]
What exception do you get when you [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging)? You can also see if you get an exception in `AsyncImage`'s `onError` callback.

**Comment by netDinger** [comment]
I do apologize. May be I just had internet connection yesterday. Now its working fine on emulator.
