### ISSUE TITLE
we use coil to show gif, when change the source, some time will loss the widget, how to fix?

### ISSUE THREAD

**Issue by 12ndxu** [coil-kt/coil#1640]
https://user-images.githubusercontent.com/20382095/221506697-4501f40a-23d9-47b3-870b-8e74258cc6e2.mp4

**Comment by colinrtwhite** [comment]
Sorry, but I'm not sure what the issue is in this report and there's no way to reproduce it.

**Comment by 12ndxu** [comment]
you can see the 4 second, when I click "change" to change the source of gif, the AsyncImage and the "refresh" are dismiss, and then show again, how can I do to promise  the AsyncImage and the "refresh" will no dismiss? the follow is the code:

`@Composable
fun mainView(context: Context) {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0x66333333))
        ,
        contentAlignment = Alignment.BottomCenter
    ){
        Box(
            modifier = Modifier
                .fillMaxWidth(0.9F)
                .height(380.dp)
                .padding(bottom = 54.dp)
                .background(Color.White, RoundedCornerShape(30.dp))
            ,
//            contentAlignment = Alignment.Center
        ) {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                var count by remember { mutableStateOf(0) }
                var animate by remember { mutableStateOf(R.drawable.animal_first) }
                Log.i(TAG,"AsyncImage refresh")
                TextButton(onClick = {
                    Log.i(TAG,"Button onClick")
                    animate = when((++count) % 3) {
                        0 -> R.drawable.animal_first
                        1 -> R.drawable.animal_second
                        2 -> R.drawable.animal_third
                        else -> R.drawable.animal_first
                    }
                }) {
                    Text(text = "change")
                }
                AsyncImage(
                    modifier = Modifier.fillMaxWidth(),
                    model = ImageRequest
                        .Builder(context)
                        .repeatCount(0)
                        .onAnimationStart {
                            Log.i(TAG,"onAnimationStart")
                        }
                        .onAnimationEnd {
                            Log.i(TAG,"onAnimationEnd")
                        }
                        .data(animate)
                        .decoderFactory(ImageDecoderDecoder.Factory())
                        .build()
                    ,
                    contentDescription = null
                )
            }
            Text(text = "refresh")
            }
        }
    }
}`
