### ISSUE TITLE
when change the source of gif, some time the AsyncImage will dismiss a moment

### ISSUE THREAD

**Issue by SuperDan630** [coil-kt/coil#1643]
In the 4 second, when I click "change" to change the source of gif, the AsyncImage and the "refresh" are dismiss, and then show again, how can I do to promise the AsyncImage and the "refresh" will no dismiss? the follow is the code:

https://user-images.githubusercontent.com/20382095/221733329-978705e8-e69c-4280-860c-0fd19931f53e.mp4

@Composable
fun mainView(context: Context) {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0x66333333))
        ,
        contentAlignment = Alignment.BottomCenter
    ){
        Box(
            modifier = Modifier
                .fillMaxWidth(0.9F)
                .height(380.dp)
                .padding(bottom = 54.dp)
                .background(Color.White, RoundedCornerShape(30.dp))
            ,
//            contentAlignment = Alignment.Center
        ) {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                var count by remember { mutableStateOf(0) }
                var animate by remember { mutableStateOf(R.drawable.animal_first) }
                Log.i(TAG,"AsyncImage refresh")
                TextButton(onClick = {
                    Log.i(TAG,"Button onClick")
                    animate = when((++count) % 3) {
                        0 -> R.drawable.animal_first
                        1 -> R.drawable.animal_second
                        2 -> R.drawable.animal_third
                        else -> R.drawable.animal_first
                    }
                }) {
                    Text(text = "change")
                }
                AsyncImage(
                    modifier = Modifier.fillMaxWidth(),
                    model = ImageRequest
                        .Builder(context)
                        .repeatCount(0)
                        .onAnimationStart {
                            Log.i(TAG,"onAnimationStart")
                        }
                        .onAnimationEnd {
                            Log.i(TAG,"onAnimationEnd")
                        }
                        .data(animate)
                        .decoderFactory(ImageDecoderDecoder.Factory())
                        .build()
                    ,
                    contentDescription = null
                )
            }
            Text(text = "refresh")
            }
        }
    }
}

**Comment by colinrtwhite** [comment]
If the `refresh` text is also flashing that means the flash is affecting the outer container and isn't caused by the `AsyncImage` itself. I don't think this is a bug with Coil.
