### ISSUE TITLE
Allow R8 to strip okhttp when unused

### ISSUE THREAD

**Issue by OxygenCobalt** [coil-kt/coil#1648]
**Is your feature request related to a problem? Please describe.**
My app only loads images with custom fetchers based on local app data, and nothing from the web or through other sources. However, since the default `ImageLoader` still bundles `HttpUriLoader` (among other okhttp-related code) in it's `ComponentRegistry`, which then adds ~200kb of dead code to my APK.

I could work around this by writing my own `ImageLoader`, but I don't want to reinvent the wheel.

**Describe the solution you'd like**
Some way to override the entire `ComponentRegistry` used by the *default* `ImageLoader`, so proguard could minify the unused components without me having to vendor my own `ImageLoader`.

**Comment by colinrtwhite** [comment]
@OxygenCobalt If you set a custom `ComponentRegistry` using [this method](https://coil-kt.github.io/coil/api/coil-base/coil/-image-loader/-builder/components.html?query=fun%20components(components:%20ComponentRegistry):%20ImageLoader.Builder) does it solve the issue? If that doesn't work you can use `-assumenosideeffects` to allow `HttpUriLoader` to be stripped.

**Comment by OxygenCobalt** [comment]
I'm already using that method. The issue is that `RealImageLoader` [always appends it's components](https://github.com/coil-kt/coil/blob/d9995ec33f857c5a687af7dd1f0b537d2ca730ce/coil-base/src/main/java/coil/RealImageLoader.kt#L83) on top of the given `ComponentRegistry`. I don't know where to add `-assumenosideeffects`.

**Comment by colinrtwhite** [comment]
@OxygenCobalt You'll need to set a custom R8 config. [Check out this guide to configure it](https://developer.android.com/studio/build/shrink-code#keep-code).

Also you can override `ImageLoader.components` through delegation, though I think that R8 will still keep `HttpUriFetcher` in that case:

```kotlin
class MyImageLoader(context: Context) : ImageLoader by ImageLoader(context) {
    override val components = ComponentRegistry()
}
```

**Comment by OxygenCobalt** [comment]
Yeah, I don't feel comfortable with tinkering with R8 at all. I'll try the delegation trick and see if R8 minifies it.

Alternatively, I could do some kind of PR that attempts to isolate the okhttp code paths with something like the following, inspired by the way ExoPlayer makes components minifiable:
- Make `ComponentRegistry` an interface and move the default component declaration to something like `RealComponentRegistry`, which will be produced by `ComponentRegistry.Builder`
- Move okhttp-related configuration to `ComponentRegistry.Builder`.
- Deprecate `ImageLoader.Builder.components` in favor of something like `ImageLoader.Builder.componentRegistry` that overrides the `ComponentRegistry` instance.

**Comment by colinrtwhite** [comment]
@OxygenCobalt I think that sounds reasonable, though it'd have to be done in a way that doesn't break binary compatibility. Additionally we can't make changes that would significantly change the existing behaviour. Given those constraints I think it might be tough to refactor in a way that allows R8 to strip `OkHttpClient`.

**Comment by OxygenCobalt** [comment]
> though it'd have to be done in a way that doesn't break binary compatibility. 

I'm assuming this means that I have to make a new interface-based `ComponentRegistry` rather than iterate on the old class, okay.

> Additionally we can't make changes that would significantly change the existing behaviour.

I'm not sure how different the behavior it would be. For example:

```
builder.components(
     ComponentRegistry.Builder()
         // Something...
         .build()   
)
```

Should have the same behavior between the current implementation and this proposed change, as:
- Without the change, the configured `ComponentRegistry` is appended with the default components in `RealImageLoader.
- With the change, the `ComponentRegistry.Builder` returns the default components plus the additional components applied.

Not sure if I'm missing anything.

**Comment by OxygenCobalt** [comment]
Ah, I see. When I get time I can look into it further and see what's exactly needed to strip it. Again, since this is the same kind of abstraction setup ExoPlayer uses in their Builders to allow R8 to strip out superfluous components, I can't help to imagine with enough changes it could be implemented here. Renaming the issue.

**Comment by OxygenCobalt** [comment]
Hey! I'm still meaning to work on this myself eventually, but I noticed that you've been starting work on a 3.x branch too. Are you planning to resolve this yourself for 3.x @colinrtwhite? If not, I'm still open to doing it eventually.

**Comment by colinrtwhite** [comment]
@OxygenCobalt Sorry, missed this message! If you can figure out a backwards-compatible solution to get this done in 2.x then it'd be great to have, otherwise I'm planning to hopefully address this in 3.x. The `coil-base` artifact won't include any networking support to avoid forcing a Ktor dependency on all consumers. The `coil` artifact will still include sensible defaults like the singleton `ImageLoader` and support for loading images from the network.

**Comment by colinrtwhite** [comment]
Going to close this out as this is supported in Coil 3.x as the OkHttp and Ktor dependencies are removed from `coil-core`. Unfortunately it's not possible to backport this to Coil 2.x.
