### ISSUE TITLE
File name encode/decode error.

### ISSUE THREAD

**Issue by Hooooong** [coil-kt/coil#1649]
**Describe the bug**

If file scheme is called through Coil, an encoding error occurs. The actual file exists, but an error occurs when a file path expressed in space or Korean is encoded and loaded.

**To Reproduce**

There are no separate projects.

**Logs/Screenshots**

RealImageLoader: 🚨 Failed - file:///storage/emulated/0/DCIM/Screenshots/Screenshot_20220929-140003_Samsung%20Internet.jpg - java.io.FileNotFoundException: /storage/emulated/0/DCIM/Screenshots/Screenshot_20220929-140003_Samsung%20Internet.jpg (No such file or directory)
RealImageLoader: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Screenshots/Screenshot_20220929-140003_Samsung%20Internet.jpg (No such file or directory)

RealImageLoader: 🚨 Failed - file:///storage/emulated/0/Download/%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg - java.io.FileNotFoundException: /storage/emulated/0/Download/%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg (No such file or directory)
RealImageLoader: java.io.FileNotFoundException: /storage/emulated/0/Download/%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg (No such file or directory)

**Version**

coil version : 2.2.2

**Comment by colinrtwhite** [comment]
@Hooooong What's an example filename that reproduces this?

**Comment by Hooooong** [comment]
@colinrtwhite The File name is 'Screenshot_20220929-140003_Samsung Internet', '다운로드'

**Comment by colinrtwhite** [comment]
@Hooooong This should be fixed in `2.3.0`.
