### ISSUE TITLE
Support for ImageVector in fallback, error, and placeholder, data

### ISSUE THREAD

**Issue by bpappin** [coil-kt/coil#1656]
**Is your feature request related to a problem? Please describe.**

Compose uses a now icon format ImageVector, so that you no longer need to store any xml resources. This might be used like `val image = Icons.Default.Person`
However Coil ignores this format pretty much entirely, forcing us to use xml files when we want to set one of the defaults

**Describe the solution you'd like**

Any place an image is set should accept ImageVector as well as the existing resource id and Drawable types.

**Comment by colinrtwhite** [comment]
It's already possible to use `ImageVector` with `AsyncImage` and `rememberAsyncImagePainter`. Here's an example:

```kotlin
AsyncImage(
  model = url,
  placeholder = rememberVectorPainter(Icons.Default.Person),
  contentDescription = null,
)
```

In terms of setting as a default, it's a little tough with the current setup as the base `ImageLoader` class has no knowledge of Compose UI primitives like `ImageVector`. I think we'll eventually need to migrate off of `Drawable` into an intermediate interface, though that can't be done until Coil 3.x as it would be a breaking change.

The best way to use `ImageVector` as a default with `AsyncImage` today is probably to create a custom composition local and wrap `AsyncImage` and pass the composition local's value as the `placeholder`.

**Comment by bpappin** [comment]
For some reason you can't apply a transform to the one that takes the placeholder.

**Comment by colinrtwhite** [comment]
For transformation support I'd recommend using Compose's toolkit for transforming images instead of Coil's `Transformation` interface. Going to close this out since it's already possible to use `rememberVectorPainter` to use an `ImageVector` as a fallback/error/placeholder.
