### ISSUE TITLE
Fetcher added to component registry is never called.

### ISSUE THREAD

**Issue by christopherperry** [coil-kt/coil#1658]
I'm attaching a `Fetcher<String>` that handles a custom URL format to the `ImageLoader` and it is never called. Just to be sure I have things wired up correctly I also added an `Interceptor`. The `Interceptor` is called, while the `Fetcher<String>` is never called. Here's a sample of how that's wired up:

```kotlin
imageLoader
  .newBuilder()
  .componentRegistry {
    add(customUrlFetcher)
  }
  .build()
```

**Comment by colinrtwhite** [comment]
Do you have a sample that reproduces the issue?

**Comment by christopherperry** [comment]
Not one I can share, it's in our codebase at Uber. What could cause this, so I know what to look for? The docs don't say much in the way of how Interceptors, Mappers and Fetchers work together.

**Comment by christopherperry** [comment]
@colinrtwhite I figured it out. Seems the `StringMapper` added automatically in the component registry interferes. I changed my `Fetcher<String>` to a `Fetcher<Uri>` and now it's being called.
