### ISSUE TITLE
avif格式加载不出来

### ISSUE THREAD

**Issue by wanghongjia** [coil-kt/coil#1666]
**Describe the bug**
A clear and concise description of what the bug is. **Please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.** Bug reports without reproduction steps are likely to be closed.

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?

**Comment by colinrtwhite** [comment]
AVIF is only supported on Android 12 and up.
