### ISSUE TITLE
Replace image when loaded

### ISSUE THREAD

**Issue by pnehren** [coil-kt/coil#167]
** Description
I want to use one ImageView to show a slideshow of images from disk. If i use this library there is a small gap between the loaded images so that image 1 is shown, then nothing, then image 2 and so on. Is it possible to replace the image in view when the new is loaded in background?

Thanks!

**Comment by colinrtwhite** [comment]
As a workaround you could use the ImageView's current Drawable as the `placeholder` for the next request. Not clearing the previous Drawable in `onStart` add complexity to how `PoolableViewTarget` works.
