### ISSUE TITLE
Decode too large avif image failed

### ISSUE THREAD

**Issue by asuka-mio** [coil-kt/coil#1671]
Currently on API 31 ~ 33, skia use codec2 framework to decode heif and avif. https://android.googlesource.com/platform/frameworks/av/+/refs/tags/android-13.0.0_r35/media/libheif/
Avif(av1) software codec max output size is limited with 1080P
https://android.googlesource.com/platform/frameworks/av/+/refs/tags/android-13.0.0_r35/media/libstagefright/data/media_codecs_google_c2_video.xml#81
It means if no hardware codec available, decoding larger than 1080P image will failed.
This limitation may be mitigated on Android 14 with https://github.com/google/skia/commit/60cf6fc1725628cf739c7d499652aca983a83d4c

**Comment by colinrtwhite** [comment]
Unfortunately I don't think there's anything Coil can do to work around this. Coil relies on the platform's decoders and adding custom support for AVIF only on API 31-33 is out of scope.
