### ISSUE TITLE
i cannot import coil,please help me

### ISSUE THREAD

**Issue by clearflame236** [coil-kt/coil#1692]
Build Info:
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Problems reading data from Binary store in C:\Users\Win\.gradle\.tmp\gradle1897334204714875788.bin offset 68253 exists? true
Corrupt serialized resolution result. Cannot find selected module (740) for constraint releaseVariantReleaseRuntimePublication -> androidx.lifecycle:lifecycle-process:2.6.1

**Comment by colinrtwhite** [comment]
Sorry I can't provide support for this, though this looks like a local build issue or an invalid version constraint (you might need to update `androidx.lifecycle`).

**Comment by NamtarR** [comment]
> Build Info: Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'. Problems reading data from Binary store in C:\Users\Win.gradle.tmp\gradle1897334204714875788.bin offset 68253 exists? true Corrupt serialized resolution result. Cannot find selected module (740) for constraint releaseVariantReleaseRuntimePublication -> androidx.lifecycle:lifecycle-process:2.6.1

Had the same problem, solved by explicitly adding `androidx.lifecycle:lifecycle-process:2.6.1` as a dependency to the same module like this:

```
implementation 'androidx.lifecycle:lifecycle-process:2.6.1'
implementation ("io.coil-kt:coil-base:2.3.0")
```

Now it works fine.

**Comment by arkivanov** [comment]
Same here. Perhaps this should be either documented or fixed.
