### ISSUE TITLE
When preloading - IllegalStateException: BitmapFactory returned a null bitmap...

### ISSUE THREAD

**Issue by valeriyo** [coil-kt/coil#1695]
**Describe the bug**
I'm using the Preloading technique (https://coil-kt.github.io/coil/getting_started/#preloading) to download .mp4 files because I want to have them stored in Coil's cache. The downloading part works, but then the request fails with `onError` and Coil error reads:

"IllegalStateException: BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format."

So, it seems that Coil is trying to do more than just preload the file. I tried adding `.allowConversionToBitmap(false)` and 
```
        .decoderFactory { _, _, _ ->
          Decoder {
            DecodeResult(
              drawable = ColorDrawable(Color.Transparent.toArgb()),
              isSampled = false,
            )
          }
        }
```
-- these didn't help??? At a minimum, the "Preloading" documentation is not accurate, and possibly there are code issues.

**To Reproduce**
```
    imageLoader.execute(
      ImageRequest.Builder(context)
        .data("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4")
        .memoryCachePolicy(CachePolicy.DISABLED)
        .listener(
          onError = { _, _ -> TODO() },
        )
        .build()
    )
```

**Logs/Screenshots**
```
E  🚨 Failed - http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 - java.lang.IllegalStateException: BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format.
```

**Version**
2.2.2

**Comment by valeriyo** [comment]
NOTE: adding same Decoder to the ImageLoader.components - works! (i.e. no more error)

**Comment by colinrtwhite** [comment]
This is expected behaviour, though we should update the docs to clarify. In the current preloading example, Coil won't skip the decode step as the image is still returned in the `ImageResult` that's returned from `execute`.

If you want to skip decoding entirely you can set a custom `Decoder.Factory` for that request that returns an empty `DecodeResult`:

```kotlin
Decoder.Factory { _, _, _ -> 
    Decoder { DecodeResult(ColorDrawable(Color.BLACK), false) }
}
```
