### ISSUE TITLE
Can't show image from redirected url.

### ISSUE THREAD

**Issue by 779556215** [coil-kt/coil#1699]
**Describe the bug**
can't show image from this [url](
http://image.baidu.com/search/down?url=https://tvax4.sinaimg.cn/large/006BNqYCly1hcc87milgwg30go0m87wp.gif)

**To Reproduce**
```
imageView.load("http://image.baidu.com/search/down?url=https://tvax4.sinaimg.cn/large/006BNqYCly1hcc87milgwg30go0m87wp.gif")
```
**Logs/Screenshots**

**Version**
Coil: 2.3.0

**Comment by colinrtwhite** [comment]
[What's the failure stacktrace?](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging)

**Comment by colinrtwhite** [comment]
The `content-length` returned by your server is incorrect, which results in a `ProtocolException`.
