### ISSUE TITLE
Coil with caching 

### ISSUE THREAD

**Issue by vegeta2102** [coil-kt/coil#17]
**Is your feature request related to a problem? Please describe.**
Can you write something doc or example about usage of cache image with Coil ?
I really consider about cache image in Android ( Just refer to Glide cache at link : https://bumptech.github.io/glide/doc/caching.html#cache-keys )

**Comment by isfaaghyth** [comment]
are you looking for this one? 
https://github.com/coil-kt/coil/blob/master/docs/faq.md

**Comment by franciscoaleixo** [comment]
Also, does Coil have a multi-layered cache and does it support transformation caching? I.e., does it ever cache to memory, besides disk? Does it cache transformed images? These are very important things (to me) that would be really useful (and present in Glide, for example).

**Comment by colinrtwhite** [comment]
I added a section about disk caching to the FAQ here: https://coil-kt.github.io/coil/faq/#how-do-i-set-up-disk-caching

Coil does not support writing `Transformations` back to the disk cache - they're only cached in memory. This let's us remove a lot of complexity that exists within Glide and let's us avoid re-implementing OkHttp's disk cache.

Coil keeps an in-memory cache for `BitmapDrawables`, though I'm in the process of adjusting it to support all `Drawables`.

**Comment by vegeta2102** [comment]
@colinrtwhite 
I have looked into . Thanks!
https://github.com/coil-kt/coil/blob/master/docs/faq.md

btw, does Coil support setting up memory cache for specific image ?
If we configure image cache  as above URL. It'll be affect all .

**Comment by colinrtwhite** [comment]
@vegeta2102 You can disable memory caching on a per-request basis like this:

```kotlin
imageView.load(url) {
    memoryCachePolicy(CachePolicy.DISABLED)
}
```

**Comment by lucianoluzzi** [comment]
> @vegeta2102 You can disable memory caching on a per-request basis like this:
> 
> ```kotlin
> imageView.load(url) {
>     memoryCachePolicy(CachePolicy.DISABLED)
> }
> ```

Was looking for a way to do so.
Maybe should this be documented in the ImageLoaders or Caching part of the docs?

**Comment by davidcode43w** [comment]
> > @vegeta2102 You can disable memory caching on a per-request basis like this:
> > ```kotlin
> > imageView.load(url) {
> >     memoryCachePolicy(CachePolicy.DISABLED)
> > }
> > ```
> 
> Was looking for a way to do so.
> Maybe should this be documented in the ImageLoaders or Caching part of the docs?

It is: https://coil-kt.github.io/coil/getting_started/#preloading
