### ISSUE TITLE
Support for `key: Any?` in `rememberAsyncImagePainter`

### ISSUE THREAD

**Issue by divyanshdxn** [coil-kt/coil#1707]
**Is your feature request related to a problem? Please describe.**
All the `remember` calls have a key passed to them for recalculating the result whenever the key changes. The utility `rememberAsyncImagePainter` uses `remember` internally by doesn't forwards the parameter key. 

There is a situation where I want to recompute the painter, and I can't now because the actual change is happening in the file whoose Uri I'm passing to `rememberAsyncImagePainter`. Since Uri doesn't changes, painter is not getting updated and so does recomposition not occurs.

**Describe the solution you'd like**
Just forward the parameter key
```kotlin
@Composable
fun rememberAsyncImagePainter(
    model: Any?,
    imageLoader: ImageLoader,
    transform: (State) -> State = DefaultTransform,
    onState: ((State) -> Unit)? = null,
    contentScale: ContentScale = ContentScale.Fit,
    filterQuality: FilterQuality = DefaultFilterQuality,
    key: Any? = null
): AsyncImagePainter {
    val request = requestOf(model)
    validateRequest(request)

    val painter = remember(key = key) { AsyncImagePainter(request, imageLoader) }
    painter.transform = transform
    painter.onState = onState
    painter.contentScale = contentScale
    painter.filterQuality = filterQuality
    painter.isPreview = LocalInspectionMode.current
    painter.imageLoader = imageLoader
    painter.request = request // Update request last so all other properties are up to date.
    painter.onRemembered() // Invoke this manually so `painter.state` is set to `Loading` immediately.
    return painter
}
```

**Additional context**

**Comment by divyanshdxn** [comment]
@colinrtwhite any comments?

**Comment by colinrtwhite** [comment]
@divyanshdxn I think [this](https://github.com/coil-kt/coil/issues/884) might solve your use case.

**Comment by divyanshdxn** [comment]
@colinrtwhite Thanks for the solution, really appreciate. But don't you think it would be an improvement to allow key to forward, if no, then why?

**Comment by colinrtwhite** [comment]
@divyanshdxn Adding a key param adds complexity for the end user. What's the benefit to adding an extra `key` param when we're effectively already using `ImageRequest` as the key?
