### ISSUE TITLE
Wrong Documentation

### ISSUE THREAD

**Issue by didvenashka** [coil-kt/coil#1708]
**Describe the bug**
when u use 
`    implementation "io.coil-kt:coil-compose:2.3.0"`
as documentation says,
it does not apply any changes to proj and does not add any functions at all.

**To Reproduce**
just follow documentation and try to use `AsyncImage()` after implementation coil-compose

**To Fix**
change 
`    implementation "io.coil-kt:coil-compose:2.3.0"`
 to 
`    implementation "io.coil-kt:coil-compose-base:2.3.0"`

**Comment by colinrtwhite** [comment]
This sounds like it might be a local config issue. `coil-compose` adds `AsyncImage` overloads for the singleton `ImageLoader`. I applied it locally and it works as expected.
