### ISSUE TITLE
Does Coil support imageByteArray? 

### ISSUE THREAD

**Issue by clint22** [coil-kt/coil#171]
When I'm trying to pass imageByteArray as a parameter into the load function it's throwing some error such as 'None of the following functions can be called with the argument supplied'. But it's working perfectly using Glide. Sharing my code snippet of what I have done using Coil and Glide. 

Using Coil 
----------

> val imageBytes = it.locationImage
                            val imageByteArray = Base64.decode(imageBytes, Base64.DEFAULT)

>ivFloorMap.load(imageByteArray) {
                                crossfade(true)
                                placeholder(R.drawable.image_placeholder)
                                transformations(CircleCropTransformation())}

Using Glide 
------------

> val imageBytes = it.locationImage
                            val imageByteArray = Base64.decode(imageBytes, Base64.DEFAULT)

>Glide.with(context)
                                    .asBitmap()
                                    .dontTransform()
                                    .placeholder(R.drawable.image_placeholder)
                                    .load(imageByteArray)
                                    .into(ivFloorMap)

Did anyone face the same issue?

**Comment by colinrtwhite** [comment]
It's not part of the base library, but it could be added pretty easily with a custom `Fetcher`:

```kotlin
class ByteArrayFetcher : Fetcher<ByteArray> {

    override fun key(data: ByteArray): String? = null

    override suspend fun fetch(
        pool: BitmapPool,
        data: ByteArray,
        size: Size,
        options: Options
    ): FetchResult {
        return SourceResult(
            source = ByteArrayInputStream(data).source().buffer(),
            mimeType = null,
            dataSource = DataSource.DISK
        )
    }
}
```

You can then add it to your `ComponentRegistry` when constructing the default `ImageLoader`. [Check out here for an example](https://github.com/coil-kt/coil/blob/master/coil-sample/src/main/java/coil/sample/Application.kt).

**Comment by clint22** [comment]
Wow. It worked perfectly. Thank you.
