### ISSUE TITLE
FakeImageLoaderEngine is not working with Image + asyncImagePainter

### ISSUE THREAD

**Issue by NaromKuoch** [coil-kt/coil#1711]
**Describe the bug**
A clear and concise description of what the bug is. **Please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.** Bug reports without reproduction steps are likely to be closed.

`FakeImageLoaderEngine` is NOT intercepting a request when I use `androidx.compose.foundation.Image` with `AsyncImagePainter`. I don't have this problem when I use my custom FakeImageLoader.  I wasn't sure if this is an intentional behavior, but it would be great if `FakeImageLoaderEngine` would just work so I can remove the custom FakeImageLoader that I wrote.

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.

Here is the test I used to confirm the behavior. 
Result:

- testContentComposeAsyncImage: Results in Red screen
- testContentComposeAsyncImagePainter: Results in a blank screen (I'm expecting this to be Red as well)

```
@RunWith(JUnit4::class)
class FakeImageLoaderEngineTest {

  @get:Rule
  val paparazzi = Paparazzi()

  @Before
  fun before() {
    val engine = FakeImageLoaderEngine.Builder()
      .intercept("https://www.example.com/image.jpg", ColorDrawable(Color.RED))
      .intercept({ it is String && it.endsWith("test.png") }, ColorDrawable(Color.GREEN))
      .default(ColorDrawable(Color.BLUE))
      .build()
    val imageLoader = ImageLoader.Builder(paparazzi.context)
      .components { add(engine) }
      .build()
    Coil.setImageLoader(imageLoader)
  }

  @Test
  fun testContentComposeAsyncImage() {
    paparazzi.snapshot {
      AsyncImage(
        model = "https://www.example.com/image.jpg",
        contentDescription = null,
      )
    }
  }

  @Test
  fun testContentComposeAsyncImagePainter() {
    paparazzi.snapshot {
      Image(
        painter = rememberAsyncImagePainter(model = "https://www.example.com/image.jpg"),
        contentDescription = null
      )
    }
  }


}
```

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?

- `coil 2.3.0` 
-  `paparazzi 1.1.0-sdk33-alpha04`

**Comment by colinrtwhite** [comment]
@NaromKuoch This is an issue with how Coil converts `ColorDrawable` into `ColorPainter` when loaded using `rememberAsyncImagePainter`. It's possible to work-around it by wrapping `ColorDrawable` in a [`LayerDrawable`](https://github.com/coil-kt/coil/blob/main/coil-test-paparazzi/src/test/java/coil/test/PaparazziTest.kt#L55). Still thinking about how to best solve this internally...

**Comment by ivk1800** [comment]
@colinrtwhite your workaround not working with `contentScale = ContentScale.Fill Bounds` :(

**Comment by ychescale9** [comment]
is it expected that the `FakeImageLoaderEngine` only works with `ColorDrawable` when [`contentScale = ContentScale.None`](https://github.com/coil-kt/coil/blob/e0411dd23c40dc05d69b8d05cb19b725f2d83a36/coil-test-paparazzi/src/test/java/coil/test/PaparazziTest.kt#LL73C17-L73C50)? If so does it make sense to have a mechnism to override `contentScale` through 
`ImageLoader.Builder` or `FakeImageLoaderEngine`?
