### ISSUE TITLE
Adding a NOOP decoder to Image Loader causes animated GIFs and WEBPs to be static

### ISSUE THREAD

**Issue by valeriyo** [coil-kt/coil#1720]
**Describe the bug**
Adding a "no-op" decoder, which according to the documentation

<img width="632" alt="image" src="https://user-images.githubusercontent.com/7052801/232919903-2c38fa15-49b3-428e-bf6a-ef648d3be28e.png">

should have no side-effects, causes animated GIFs and WEBPs to no longer be animated

**To Reproduce**
1. To an ImageLoader builder, add `.components { add(Decoder.Factory { _, _, _ -> Decoder { null } }) }`
2. Try to load an animated GIF or WEBP
3. The image loads as a static image

**Logs/Screenshots**
No errors are logged

**Version**
2.2.2

**Comment by colinrtwhite** [comment]
This is expected behaviour. Returning `null` from a `Decoder` delegates to the next decoded, which is likely `BitmapFactoryDecoder` which decodes animated images as static.

**Comment by valeriyo** [comment]
> This is expected behaviour. Returning `null` from a `Decoder` delegates to the next decoder, which is likely `BitmapFactoryDecoder` which decodes animated images as static.

And why is "next" decoder not the one that understands how to decode animated GIF/WEBP ? This is not expected at all.
