### ISSUE TITLE
Disk cache works only after second request for an image

### ISSUE THREAD

**Issue by DoronTorangy** [coil-kt/coil#1734]
**Describe the bug**

I have Coil set up in an Android project (with both xml views and composables).
I have a list of urls that I preload like so:
```kt
  fun preloadImages(images: List<String>) {
    images.forEach { imageUrl ->
        val request = ImageRequest.Builder(context)
				.data(imageUrl)
				.memoryCachePolicy(CachePolicy.DISABLED)
				.build()

        context.imageLoader.enqueue(request)
     }
  }
```

In `ActivityA`, the images load directly from cache without a network request, as expected.

However, when I navigate to `ActivityB` and render the same images, there is a network request to fetch each one again.

I started debugging coil source code, I noticed something weird:

Whenever I navigate from `ActivityA` to `ActivityB` the `cache_image` directory (which coil uses) is emptied (meaning all the images cached initially are deleted)

I followed the docs, this is how I initialize the image loader, in my application class:

```kt
override fun newImageLoader(): ImageLoader {
   return ImageLoader.Builder(context)
	.components {
		add(SvgDecoder.Factory())
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
			add(ImageDecoderDecoder.Factory())
		} else {
			add(GifDecoder.Factory())
		}
	}
	.logger(DebugLogger())
	.build()
  }
```

And I load the image like so:

```kt
  imageView.load(this.url)
```

**Version**

```groovy
 implementation "io.coil-kt:coil:2.3.0"
 implementation "io.coil-kt:coil-svg:2.2.2"
 implementation "io.coil-kt:coil-compose:2.3.0"
 implementation "io.coil-kt:coil-gif:2.3.0"
```

Does anyone know why/when the `cache_image` is deleted?

**Comment by colinrtwhite** [comment]
I'd double check that the `cache-control` header for your images allows disk caching. You can disable `cache-control` header support by using `ImageLoader.Builder.respectCacheHeaders(false)`.
