### ISSUE TITLE
Unresolved reference: DrawableWrapper

### ISSUE THREAD

**Issue by m-khalili** [coil-kt/coil#1735]
**Describe the bug**

Hello. 
after adding coil, I can't build project, it seems has conflict with appcompat
because when I remove coil everything is working fine

error: 
Unresolved reference: DrawableWrapper
import androidx.appcompat.graphics.drawable.DrawableWrapper
appCompat version : 1.6.1
coil version : 2.3.0

**Comment by colinrtwhite** [comment]
Hmm I'd add a reference to appcompat 1.6.1 in your build file:

```
implementation "androidx.appcompat:appcompat:1.6.1"
```

It's likely there's a dependency conflict with other libraries your app uses.
