### ISSUE TITLE
Show last loaded image as placeholder until new image not loaded

### ISSUE THREAD

**Issue by rizwan3742** [coil-kt/coil#1738]
First of all thanks for your great work. 

I have a requirement to Load an image from URL
Where image can be updated any time and URL will remain same 
If there is image exist show that image and default drawable as placeholder 
and If image updated then show Old image as a placeholder 
meanwhile load new image and when new image download load that new image into ImageView

i tried alot but different techniques but the only thing i could not acheived to show old image as placeholder. 

It would be great if you can help me to acheive this. I will be greatfully thankful to you

**Comment by colinrtwhite** [comment]
Placeholders must be synchronous and can be set with `ImageRequest.Builder.placeholder`. It sounds like you need to check if an image has been updated asynchronously? In that case returning a custom image from an `Interceptor` may be useful.

If you'd like to skip replacing the existing image in an `ImageView` you can create a custom `ImageViewTarget` with a no-op for `onStart`.

**Comment by rizwan3742** [comment]
@colinrtwhite thank you very much for your reply. 

what i read in documentation once coil try to load image it clear cache first and then try to load image. and after success it loads image.  

So with this behaviour it show thumbnail for a seconds and show updated image. Basically i don't want to show placeholder once image is updated. I want to show old image until new image load into image view. 

can you please help me with sample code. it would be great. 

```
imageView.load(url) {
            memoryCacheKey(lastUpdatedTime)
            diskCacheKey(lastUpdatedTime)
            addHeader("Authorization", token)
            listener(onError = { request, result ->
                Log.e("Error", "${result.throwable}")
                pgBar.isVisible = false
            }, onStart = {
                pgBar.isVisible = true
            }, onSuccess = { result, data ->
                pgBar.isVisible = false
            })
        }
```


```
class App : Application(), ImageLoaderFactory {

    override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(this)
            .respectCacheHeaders(false)
            .logger(DebugLogger())
            .diskCachePolicy(CachePolicy.ENABLED)
            .crossfade(true)
            .build()
    }


}

```
