### ISSUE TITLE
Coil-Compose: Race condition while loading multiple images

### ISSUE THREAD

**Issue by yanniks** [coil-kt/coil#1739]
**Describe the bug**
Our app contains multiple (SVG) images that are loaded using Coil in Jetpack Compose. In some scenarios, the loading fails with the following error message:
```
java.io.FileNotFoundException: /data/user/0/com.example.myapp/cache/mycachefolder/journal.tmp -> /data/user/0/com.example.myapp/cache/mycachefolder/journal
```

I believe that is is a race condition that occurs when image caching is enabled.

**To Reproduce**
This is the implementation that we're using in order to load an image:
```
val context = LocalContext.current
    val imageLoader = ImageLoader.Builder(context)
        .components {
            add(SvgDecoder.Factory())
        }
        .diskCache {
            DiskCache.Builder()
                .directory(context.cacheDir.resolve("mycachefolder"))
                .build()
        }
        .build()

    AsyncImage(
        model = ImageRequest.Builder(context)
            .data("https://myimageurl")
            .build(),
        colorFilter = ColorFilter.tint(tint),
        imageLoader = imageLoader,
        modifier = modifier
            .height(30.dp)
            .width(30.dp),
        onError = {
            println("Could not load icon!")
            println(it.result.throwable)
            println(it)
        },
        contentDescription = null,
        contentScale = ContentScale.Fit
    )
```

**Version**
The problem occurs across all Android devices, tested with Coil 2.3.0.

**Comment by colinrtwhite** [comment]
Thanks - I've heard a few reports of this so this definitely needs investigation.

**Comment by yanniks** [comment]
Let me know if there is anything we can support you with.

**Comment by colinrtwhite** [comment]
Thanks! If you're able to create a project that reproduces the issue consistently that'd be a big help.

@yanniks Are you creating multiple `DiskCache` instances that use the same `directory`?

**Comment by yanniks** [comment]
@colinrtwhite sure thing. This is the sample project: [CoilTest.zip](https://github.com/coil-kt/coil/files/11472229/CoilTest.zip)
I haven't implemented a cache clearing so you'll need to reinstall the app in order to reproduce the issue.

And yes, I'm creating multiple `DiskCache` instances as I don't save it in some kind of `State` / `ViewModel` / … . I just tried it out and it seems to be a workaround. For me, it is also fine if that would be the expected behavior - in that case, some note in documentation would be great.
