### ISSUE TITLE
how much is the disk cache will be valid? #2077

### ISSUE THREAD

**Issue by aplha98** [coil-kt/coil#1740]
I just want to know after the image is loaded what is the disk cache lifetime when that image will be fetched from the URL again,
I know it supposes the URL as keys, but is there any time considering, what if this image is not used for a month ?

is there anything like kingFister on IOS
// Memory image expires after 10 minutes.
cache.memoryStorage.config.expiration = .seconds(600)

// Disk image never expires.
cache.diskStorage.config.expiration = .never

**Comment by colinrtwhite** [comment]
The memory cache only evicts images once it runs out of space. The disk cache also evicts image when it runs out of space. The disk cache also supports standard HTTP `cache-control` header values so you can control the expiration of the disk cache value that way.
