### ISSUE TITLE
Leftover disk cache editors on completion of instrumented tests

### ISSUE THREAD

**Issue by saket** [coil-kt/coil#1763]
**Describe the bug**
I'm not sure about this, but I think Coil is leaving leftover disk cache editors on completion of instrumented tests. This is causing `SuccessResult#diskCacheKey` to be set as null because [HttpUriFetcher#L148](https://github.com/coil-kt/coil/blob/df42295c5974ec45ddcf33b38ccf4789f7508bd1/coil-base/src/main/java/coil/fetch/HttpUriFetcher.kt#L148) is failing to create new cache entries. 

**To Reproduce**
I'm unable to create a reproducible sample for this, but here are some hints:
- Only happens when a custom disk cache key is set.
- My test is parameterized so it runs multiple times for the same image URL. The first test succeeds as expected, but following tests fail because `SuccessResult#diskCacheKey` comes out as null.

I'm able to temporarily fix this by using an in-memory disk cache that is cleared after each test run. Calling `ImageLoader#shutdown()` or `DiskCache#clear()` does not help.

**Logs/Screenshots**
Coil's logs don't contain anything useful for this.

**Version**
Coil: 2.3.0
Android SDK: 31

**Comment by colinrtwhite** [comment]
Chatted on Slack - tracking the fix here: https://github.com/saket/telephoto/issues/13
