### ISSUE TITLE
RoundedCornersTransformation crops non-1:1 images when size is 1:1

### ISSUE THREAD

**Issue by OxygenCobalt** [coil-kt/coil#1777]
**Describe the bug**
When `RoundedCornersTransformation` is used with any Size with a 1:1 aspect ratio and an input image with a non 1:1 aspect ratio, the image is cropped to 1:1 instead of being scaled gracefully to the specified Size.

This is not ideal for my app, since I:
1. Have no knowledge over the aspect ratio of the image I am loading, so I can't pre-set a `Size` to handle this automatically.
2. Cannot feasibly resize the `ImageView` target to be anything but square, which results in the obtained `Size` information always being square as well.

I've managed to work around it though this patch:

```diff
68c68
<                 scale = Scale.FILL
---
>                 scale = Scale.FIT
98,102d97
<         val (dstWidth, dstHeight) = size
<         if (dstWidth is Dimension.Pixels && dstHeight is Dimension.Pixels) {
<             return dstWidth.px to dstHeight.px
<         }
< 
108c103
<             scale = Scale.FILL
---
>             scale = Scale.FIT
```

It *seems* to work, but I don't know if this has any knock-on effects.

**To Reproduce**

This is intrinsic to the transform, so any ImageRequest in similar form to this would cause the issue:

```
val request =
    ImageRequest.Builder(context)
        .data(nonSquareBitmap)
        .transformations(RoundedCornersTransformation(64f))
        .size(dimension)
        .target(...)
        .build()
```

**Logs/Screenshots**

What occurs normally:
![markup_1000014801](https://github.com/coil-kt/coil/assets/65370175/c99e9add-57a1-48e8-bc73-01091248ffb6)

What should occur (With my hack applied):
![Screenshot_20230528-155007_1](https://github.com/coil-kt/coil/assets/65370175/7ce64ad4-deb3-4272-a34a-165c6f7c185f)

**Version**
Coil 2.4.0, API 33, Pixel 5

**Comment by colinrtwhite** [comment]
This is expected behaviour and is [mentioned in the docs](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/transform/RoundedCornersTransformation.kt#L25). If you'd like to avoid cropping to the target size you can set `size(Size.ORIGINAL)` or create a custom transformation by modifying `RoundedCornersTransformation` that uses the source image size as the target size.

**Comment by OxygenCobalt** [comment]
Ah, okay. Sorry for missing that in the documentation @colinrtwhite. Your suggestions aren't really very applicable, as I can't expect a particular image size and have to pin it to something to make the corners consistent. I've decided to stick with my workaround, as it does everything I need to.
