### ISSUE TITLE
the Target function improvements.

### ISSUE THREAD

**Issue by neo-turak** [coil-kt/coil#1779]
**Is your feature request related to a problem? Please describe.**
I have an image url, after the Drawable got from Ciol target. onSuccess. I need to do a task, cut the bitmap to triangle for example.
 the onError will trigger when the tak fail. However, I realy need the error with Exception.

**Describe the solution you'd like**
the target functions before:
```
        val request = ImageRequest.Builder(this)
            .data(IMAGE_URL)
            .target(
                onStart = { placeholder ->
                    // Handle the placeholder drawable.
                },
                onSuccess = { result ->
                    binding.image.load(result)
                   cutTriangle((result as BitmapDrawable).bitmap)
                },
                onError = { error ->
                   //handle the error drawable.
                }
            )
            .build()
```
the desired functions which I like:
```
        val request = ImageRequest.Builder(this)
            .data(IMAGE_URL)
            .target(
                onStart = { placeholder ->
                    // Handle the placeholder drawable.
                },
                onSuccess = { result ->
                    binding.image.load(result)
                   cutTriangle((result as BitmapDrawable).bitmap)
                },
                onError = { error:Drawable?, errorMsg:Exception?->
                   //when the onError triggers, I want the errorMsg.
                }
            )
            .build()
```

**Additional context**
I am thinking the onError for like fails to load the data, but If it also provides the error information it will be very usefull.

**Comment by colinrtwhite** [comment]
It's not possible to change this as it would be a binary incompatible change. If you need the exception I'd use the `listener` method which has access to `result.exception`.
