### ISSUE TITLE
Svg icon not shown in release apk with R8 enabled

### ISSUE THREAD

**Issue by tienanh306201z** [coil-kt/coil#1781]
here is my implementation: 

//coil image
implementation 'io.coil-kt:coil-compose:2.4.0'
implementation 'io.coil-kt:coil-svg:2.4.0'
implementation 'io.coil-kt:coil-gif:2.4.0'

@Composable
fun SvgImage(
    svgLink: String,
    modifier: Modifier = Modifier,
    contentScale: ContentScale = ContentScale.Crop,
    color: Color = Color.Black
) {
    AsyncImage(
        model = ImageRequest.Builder(LocalContext.current).data(svgLink)
            .decoderFactory(SvgDecoder.Factory()).allowHardware(true).crossfade(true)
            .networkCachePolicy(CachePolicy.ENABLED).diskCachePolicy(CachePolicy.ENABLED)
            .memoryCachePolicy(CachePolicy.ENABLED).diskCacheKey(svgLink).memoryCacheKey(svgLink)
            .diskCacheKey(svgLink).memoryCacheKey(svgLink).bitmapConfig(Bitmap.Config.ARGB_8888)
            .build(),
        onError = { Log.d("Hello", "Error:" + it.result.throwable.message.toString()) },
        onLoading = { Log.d("Hello", "Loading:" + it.painter.toString()) },
        onSuccess = { Log.d("Hello", "Success:" + it.result.toString()) },
        contentDescription = null,
        modifier = modifier,
        contentScale = contentScale,
        colorFilter = ColorFilter.tint(color)
    )
}

//Implementation
SvgImage(
    svgLink = "file:///android_asset/icons/topic_icons/topic_icon_1.svg”,
    modifier = Modifier.padding(5.dp),
)

//In android debug view shows: 
Error:Class 'com.android.org.kxml2.io.KXmlParser' does not implement interface 'vi.a' in call to 'void vi.a.setFeature(java.lang.String, boolean)' (declaration of 'k9.k2' appears in /data/app/~~sdONz65JlPgi_46O6Wtsew==/com.abc.teastest-OI_-54phA8WxM0EbpTTwRQ==/base.apk)

//and no svg icon shown

**Comment by colinrtwhite** [comment]
Which version of the Android Gradle plugin are you using?

**Comment by tienanh306201z** [comment]
> Which version of the Android Gradle plugin are you using?
> 
> This seems related to R8 full mode being enabled in AGP 8.0. If you update to the latest AGP alpha version does that fix it?

I'm currently using AGP 8.1 but I think it's not the cause.

**Comment by colinrtwhite** [comment]
@tienanh306201z If you add these rules to your R8 config does it fix it? Also do you have a way I can reproduce this?

```
-keep,allowobfuscation class * extends org.xmlpull.v1.XmlPullParser
-keep,allowobfuscation class * extends org.xmlpull.v1.XmlSerializer
```

**Comment by tienanh306201z** [comment]
> @tienanh306201z If you add these rules to your R8 config does it fix it? Also do you have a way I can reproduce this?
> 
> ```
> -keep,allowobfuscation class * extends org.xmlpull.v1.XmlPullParser
> -keep,allowobfuscation class * extends org.xmlpull.v1.XmlSerializer
> ```

I finally somehow figured it out by adding this to proguard file:
`-keepclasseswithmembers class com.android.org.kxml2.io.KXmlParser {
    public <init>(org.xmlpull.v1.XmlPullParser);
    public boolean getFeature(java.lang.String);
    public void setFeature(java.lang.String, boolean);
}`
thanks man

**Comment by colinrtwhite** [comment]
I'm not able to reproduce this locally with the sample app, but I suspect this is related to R8 full mode being enabled in AGP 8.1. If that's the case and someone is able to confirm locally, feel free to open a PR that adds the correct rules to `coil-svg`.
