### ISSUE TITLE
illegalStateException: Unable to create fetchers for <image link>

### ISSUE THREAD

**Issue by DarshReddy** [coil-kt/coil#1787]
**Describe the bug**
While trying to load this image link ` https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/033/009/original/06_05_2023_-_SOLID_Principles_every_developer_must_know_by_Pragy_Agarwal_%281%29.png?1682675828` we are getting error `java.lang.IllegalStateException: Unable to create a fetcher that supports:  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/033/009/original/06_05_2023_-_SOLID_Principles_every_developer_must_know_by_Pragy_Agarwal_%281%29.png?1682675828`

**To Reproduce**
Try to load this URL - `https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/033/009/original/06_05_2023_-_SOLID_Principles_every_developer_must_know_by_Pragy_Agarwal_%281%29.png?1682675828`

**Logs/Screenshots**
NA

**Version**
2.1.0

**Comment by colinrtwhite** [comment]
Please file a new issue with a repro if this is still failing.
