### ISSUE TITLE
[coil-video] Support `MediaDataSource` implementations

### ISSUE THREAD

**Issue by lukaspieper** [coil-kt/coil#1790]
**Is your feature request related to a problem? Please describe.**
Currently Coil-Video only supports a small range of inputs (see [`MediaMetadataRetriever.setDataSource(...)`](https://github.com/coil-kt/coil/blob/e311caf5118d14c881b6bdf09f03d500c5811ab4/coil-video/src/main/java/coil/decode/VideoFrameDecoder.kt#L184) and if I understand it correctly with a fallback that writes a whole file to disk that is way to slow for large files like videos. In my case the files are encrypted, therefor they cannot directly be used by coil.

**Describe the solution you'd like**
I have a `MediaDataSource` implementation that handles the decryption on the fly. However, I haven’t found a way to pass it down to coil without extending Coil's image pipeline by adding a class that is similar to [`VideoFrameDecoder`](https://github.com/coil-kt/coil/blob/main/coil-video/src/main/java/coil/decode/VideoFrameDecoder.kt) but forwards the `MediaDataSource` to the `MediaMetadataRetriever`.

I just barely checked the code base, so there could be better solutions. The `VideoFrameDecoder` would need to recognize `MediaDataSource` to apply them directly. I think this could be done by adding an `ImageSource` that accepts `MediaDataSource` as parameter.

I have seen issue [#25](https://github.com/coil-kt/coil/issues/25#issuecomment-565754360) so this new API would only be available on > API 23.

**Additional context**
While I was able to implement this myself by mostly copying `VideoFrameDecoder`, I think it would be nice to see support upstream.

**Comment by colinrtwhite** [comment]
Hmm this might be slightly tough to implement. An `ImageSource` implementation needs to be able to return a `Source` so it can be ready by any fetcher. A `MediaDataSource` could be wrapped as a `Source`, however when read by `VideoFrameDecoder` it would create a temporary file on disk, which we want to avoid. Additionally, we can't add this to the main artifact - it would need to exist as part of `coil-video`.

I think the best way to implement this is probably create a custom `MediaDataSourceFetcher` that wraps `MediaDataSource` as a `Source`-backed `ImageSource` and attaches a `MediaSourceMetadata` object, which can then be read by `VideoFrameDecoder`. Open to a PR that adds this!
