### ISSUE TITLE
Support non-GET HTTP request types

### ISSUE THREAD

**Issue by oluismarques** [coil-kt/coil#1809]
At the moment only GET requests are allowed, please add option for POST.

**Comment by colinrtwhite** [comment]
It's possible to accomplish this with an OkHttp interceptor. Here's the code: https://github.com/coil-kt/coil/discussions/985

I think we could potentially support more HTTP method configuration in Coil 3.x.

**Comment by colinrtwhite** [comment]
This is a supported feature in Coil 3.0 using `ImageRequest.Builder.httpMethod("POST")`.
