### ISSUE TITLE
Coil not retrieving from cache when the request data is invalid

### ISSUE THREAD

**Issue by vladmircan** [coil-kt/coil#1815]
**Describe the bug**
`Coil` only tries to fetch from the cache if the request data is not null.
This is fine in most cases as the cache key is computed based on the request url.
However there are situations in which knowing the url to fetch from is not possible without an active network connection. With that being said, one might be able to provide the cache key and therefore expect the image to be loaded from the cache. As I've explained before, this is not the case as requests without valid data are always rejected.

To be noted, for anyone running into this issue, specifying a dummy url ("https:" seems to be the bare minimum that passes requirements) will work but it is not intuitive at all in my opinion.

**To Reproduce**
This issue can be easily reproduced by running an app and loading an image (with a custom cache key) and then going offline and trying to fetch from an invalid url the aforementioned cache key.
This will result in `Coil` failing silently inside the `executeMain` method of the `RealImageLoader` class.

**Possible solutions**
1. Check whether the user has explicitly disabled the network fetching before rejecting the request
2. Check whether a custom cache key has been provided before rejecting

**Version**
Tested on `2.4.0` as well as earlier versions going back to `2.0.0`.

**Comment by colinrtwhite** [comment]
We can't assume that `ImageRequest.data` is not required if the network cache is disabled as it's possible for someone to write a custom fetcher that supports disabling the network cache, but still requires a valid `ImageRequest.data` value. Additionally, it would be unintuitive and an unexpected change if we start allowing `ImageRequest`s to be executed with `NullRequestData` as their `ImageRequest.data` value so we can't change that part of Coil's model.

If you're sure `ImageRequest.data` won't be required to execute your request, you can pass an example URL as you mentioned.
