### ISSUE TITLE
Cache control

### ISSUE THREAD

**Issue by Ravshan1Uz** [coil-kt/coil#182]
When device is offline coil show image from cache. And when device become online, coil redownload images from network, which were downloaded from cache. How to disable this?

**Comment by colinrtwhite** [comment]
Sounds like the server you're downloading from is setting a short `cache-control` value. You can have OkHttp rewrite this using a network interceptor. [Here's how it's done in the sample app](https://github.com/coil-kt/coil/blob/master/coil-sample/src/main/java/coil/sample/Application.kt#L45).

**Comment by colinrtwhite** [comment]
Feel free to reopen this issue if intercepting the `cache-control` header didn't fix your issue.
