### ISSUE TITLE
Coil AsyncImage: Can't set error or fallback as gradient in Jetpack Compose

### ISSUE THREAD

**Issue by ndriqimh** [coil-kt/coil#1821]
**Describe the bug**
Error/Fallback accepts a painterResource, if that is set as a color it works
`AsyncImage(
        error = ColorPainter(Color.Gray),
    )`

If it's set as a gradient doesn't work, It shows as Black background
` AsyncImage(
        error = BrushPainter(
            Brush.verticalGradient(
                colorStops = arrayOf(
                    0.0f to Color.Gray,
                    0.5f to Color.White
                )
            )
        )
    )`

**To Reproduce**
Try to load an image without internet. It should then show error/fallback painter.

**Version**
Currently using Android 13, coil version latest: coil-compose:2.4.0

**Comment by colinrtwhite** [comment]
Thanks for the report. This seems like an issue with how `BrushPainter` returns its size. Interestingly, `Image` doesn't render this painter properly:

```kotlin
Image(
    painter = BrushPainter(
        Brush.verticalGradient(
            0.0f to Color.Gray,
            0.5f to Color.White,
        ),
    ),
    contentDescription = null,
)
```
