### ISSUE TITLE
Zooming in on large images, makes the image blurry likely due to downsampling, support "resampling"

### ISSUE THREAD

**Issue by MV-GH** [coil-kt/coil#1833]
**Is your feature request related to a problem? Please describe.**
Loading a large image and then zooming in on the image makes it blurry. This is likely due to downsampling. 

**Describe the solution you'd like**
Support a way to "resample" the viewed portion of the image so that it is displayed in high resolution.

**Additional context**

The example image: https://media.rimworld.gallery/15/2e/152ec41221eee10c9a8e5610bcd3f3f3cd24f919d9f14ddabf31c107c55a4809.jpg (33MB)

The relevant code used
```kt
 AsyncImage(
                    model = url,
                    contentDescription = null,
                    modifier = Modifier
                        .fillMaxSize()
                        .zoomable( // A thirdparty lib https://github.com/usuiat/Zoomable
                            zoomState = rememberZoomState(),
                            onTap = {  },
                        ),
                )
```
Used in https://github.com/dessalines/jerboa

https://github.com/coil-kt/coil/assets/67873169/130027ff-44f6-4f3d-9995-907053abb88b

An example that supports this
https://github.com/davemorrissey/subsampling-scale-image-view

**Comment by colinrtwhite** [comment]
Zooming and subsampling of large images is outside the scope of this library as it introduces a lot of constraints. Check out [Telephoto](https://github.com/saket/telephoto) (which has Coil integration) for a good solution that supports zooming.
