### ISSUE TITLE
Multiple listeners for ImageRequest

### ISSUE THREAD

**Issue by Koitharu** [coil-kt/coil#1846]
**Is your feature request related to a problem? Please describe.**
Support for multiple listeners for `ImageRequest`

**Describe the solution you'd like**
Now `ImageRequest.Builder` allow to set only one `Listener`, so call `listener()` overrides previous listener value. It would be nice to add something like `addListener()`

**Additional context**
None

**Comment by l2hyunwoo** [comment]
Can I take this issue?

**Comment by colinrtwhite** [comment]
Would creating your own composite listener fulfill this use case?

```
class CompositeListener : ImageRequest.Listener {
    val listeners = mutableListOf<ImageRequest.Listener>()

    override fun onStart(request: ImageRequest) {
        listeners.forEach { it.onStart(request) }
    }

    override fun onCancel(request: ImageRequest) {
        listeners.forEach { it.onCancel(request) }
    }

    override fun onSuccess(request: ImageRequest, result: SuccessResult) {
        listeners.forEach { it.onSuccess(request, result) }
    }

    override fun onError(request: ImageRequest, result: ErrorResult) {
        listeners.forEach { it.onError(request, result) }
    }
}
```

- [ ] 

- [ ]

**Comment by colinrtwhite** [comment]
Going to close this as it's possible to do the above. ^
