### ISSUE TITLE
Disk cache doesn't work as intended

### ISSUE THREAD

**Issue by UKMIITB** [coil-kt/coil#1857]
**Version**
What library version are you using? Does this occur on a specific API level or Android device?
2.40.

As per the documentation, memory cache & disk cache both are enabled by default.
But the case where 1st time images get loaded from URL.
For later purpose I observed that if memory cache is not available & user is connected to internet (And internet speed is slow), its trying to fetch the data from internet itself rather than fetching from disk cache.
I want that every time data is to be shown, first try to fetch from memory cache, if not available then try to fetch from disk cache & in parallel try to fetch from internet & update the cache.

Also there is no way I can set the TTL for memory cache or disk cache.

Also regarding the documentation mentioned for singleton instance by implementing ImageLoaderFactory in application class, in my code I don't use imageLoader instance directly, do I still need to override it to add cacheHeader as false ?

**Comment by colinrtwhite** [comment]
> its trying to fetch the data from internet itself rather than fetching from disk cache.

Coil respects the [`Cache-Control` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) set by response from the image server. I'd verify that the server isn't sending a header that prevents caching or requires reverification of the image. Optionally, you can set `ImageLoader.Builder.respectCacheHeaders(false)` to disable this behaviour.

> Also there is no way I can set the TTL for memory cache or disk cache.

TTL can be enforced using the `Cache-Control` header.

> in my code I don't use imageLoader instance directly, do I still need to override it to add cacheHeader as false ?

If you use the singleton `ImageLoader` (`ImageView.load` uses it) then you need to implement `ImageLoaderFactory` to configure the singleton instance.

**Comment by UKMIITB** [comment]
@colinrtwhite Thank you for your response.
Have one more query, in my codebase I use AsyncImage & in model pass the url.
So in my case how would this be applicable ?
