### ISSUE TITLE
Unfinished Trace sections when Composition Tracing Enabled

### ISSUE THREAD

**Issue by mlykotom** [coil-kt/coil#1871]
**Describe the bug**
Compose Compiler had a bug [b/274499044](https://issuetracker.google.com/issues/274499044) that's causing unfinished trace sections when Composition Tracing is enabled. The problem is when using `@ReadOnlyComposable` with an [early return statement](https://github.com/coil-kt/coil/blob/d0644b9a5a96627a09d5ac724b8a4fd6578fea6e/coil-compose-base/src/main/java/coil/compose/Utils.kt#L21).

This issue has been fixed in Compose Compiler 1.5.1 ([release notes](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.5.1)), but libraries that were using such a flow would need to recompile and release a new version with the new Compose compiler to fix the problem downstream.

I see the Compose Compiler version has been updated already ([commit](https://github.com/coil-kt/coil/commit/d0cff984d30da8b77506b3318233c5ce211efa26)) so the question is: 
**Could you release a new version of Coil** to prevent this issue for consumers of the library?

✅  Verified that 2.5.0-SNAPSHOT doesn't cause the problem

**To Reproduce**
Start a Composition Tracing ([DAC](https://developer.android.com/jetpack/compose/tooling/tracing)) with latest coil version.

**Logs/Screenshots**
![image](https://github.com/coil-kt/coil/assets/3973717/918d6f25-04fa-472c-b4fd-2cea964f089d)

**Version**
latest coil - 2.4.0

Thank you!

**Comment by colinrtwhite** [comment]
Thanks for the heads up! I'll cut a new release for this in the next few days.

**Comment by borisdamato** [comment]
Hi @colinrtwhite, do you have a timeline for when the new release will be cut? Thanks

**Comment by colinrtwhite** [comment]
This is fixed in Coil `2.5.0`.
