### ISSUE TITLE
Ugly cached vector

### ISSUE THREAD

**Issue by Pitel** [coil-kt/coil#188]
**Describe the bug**
I have a list a with avatars. The avaras are `VectorDrawable`s. When select some avatar and going to edit screen, when the avatar si larger, it's ugly, like resized low-res. I've figured out it's caused by memory caching, because adding `memoryCachePolicy(CachePolicy.DISABLED)` to each avatar `load()` fixes the issue. But then, the `ViewPager` for avatar selection is ineffective, because when swiping to start and back, the avatars are always reloading causing visible pop-ins.

**Expected behavior**
Always sharp `VectorDrawable`s with sane caching.

**To Reproduce**
1. Have 2 Fragments, first with tiny (16 dp) `ImageView`, another with `match_parent` sized `ImageView` and some `VectorDrawable` (maybe this also happens with bitmaps?)
2. Have some button or something which replaces first fragment with second.
3. Se ugly "pixelated" vector.

**Logs/Screenshots**
![List](https://user-images.githubusercontent.com/113248/69952254-18933680-14f7-11ea-9635-360589fbd1ca.png)
![Detail](https://user-images.githubusercontent.com/113248/69952255-192bcd00-14f7-11ea-89c5-a74c2bd0112b.png)

**Version**
0.8.0

**Comment by colinrtwhite** [comment]
@Pitel Could you try using the [latest snapshot](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots) and let me know if you still see the issue?

**Comment by Pitel** [comment]
Looks fixed in 9.0.1. Thanks. :+1:

**Comment by Pitel** [comment]
Sorry, my bad, still broken in 0.9.1 and 0.10.0-SNAPSHOT. :(

**Comment by sheckspir** [comment]
reproduced this bug on version 0.9.1. 
I also tried the version from branch #232 . It was fixed

**Comment by colinrtwhite** [comment]
@sheckspir Thanks for checking. The fix is now in master and will be released soon as part of `0.9.2`.
