### ISSUE TITLE
Image scaling quality is different on landscape & portrait mode?

### ISSUE THREAD

**Issue by arsonistAnt** [coil-kt/coil#189]
Hi not too sure if this is a bug so I decided to label it as a question. 

**Setup:**
I basically have a `RecyclerView` of items that will take me to an `ImageView` when I tap on it. I've also set the `scaleY` & `scaleX` to `8.0F` with the help of `Request.Listener` when the image has finished loading from the URL.

**Problem:**
When I tap on my item in portrait mode and switch to landscape the image quality is fine.

If I tap on my item when I'm in landscape mode the image quality is actually a lot worse.

Seems like switching from Portrait to Landscape when the `ImageView` is already shown retains the image quality. Now if I start off from landscape before loading the `ImageView` the image quality degrades.

**Is there a reason as to why this is happening?**

Image quality comparison below:

![image](https://user-images.githubusercontent.com/15347566/70015270-b4da2f00-1531-11ea-95c4-62b121ac610f.png)

**Comment by colinrtwhite** [comment]
Hmm that definitely isn't intentional. Does the image load with the correct resolution if you don't set `scaleX` or `scaleY`? What happens if you disable the memory cache with `memoryCachePolicy(CachePolicy.DISABLED)`? Also do you have a small code snippet, project or another way I can reproduce this?

**Comment by arsonistAnt** [comment]
> Does the image load with the correct resolution if you don't set `scaleX` or `scaleY`? 

The image resolution is different even if I don't set the `scaleX` and `scaleY`. 

I checked the drawable size in my image view and compared from first & second method of going to the image which was:

1. In portrait mode
2. Go to image
3. Switch to landscape.

_Versus_

1. In landscape mode
2. Go to image

Both landscaped image drawables were different sizes.

> What happens if you disable the memory cache with `memoryCachePolicy(CachePolicy.DISABLED)`? 

Tried this but it seems like there isn't any difference.

> Also do you have a small code snippet, project or another way I can reproduce this?

**I'll whip up a small project and re-edit this comment to include the link to it. Please let me know if I can clarify anything in the meantime.**
