### ISSUE TITLE
Provide original size and/or scale values in image request

### ISSUE THREAD

**Issue by Innova133** [coil-kt/coil#1890]
**Is your feature request related to a problem? Please describe.**
Sometimes a remote source has a really large image that we would like Coil to resize for us.  This can be done by using the .size() option on the ImageRequest.Builder().  However, once downloaded and resized we may need to know the original image dimensions (for example to draw on top of the bitmap after download).

**Describe the solution you'd like**
The onSuccess method of the ImageRequest.Builder().target() should provide information about the original image (heightxwidth) or scale used to downsize/upsize.

**Additional context**

**Comment by colinrtwhite** [comment]
Duplicate: https://github.com/coil-kt/coil/issues/1213

**Comment by Syed0040** [comment]
Any updates on this i also needed the solution for this if it gives original size after compress it will be very helpful and to get this now any methods there in coil3?
