### ISSUE TITLE
Crash app when loading GIF on Android 9.0

### ISSUE THREAD

**Issue by GeniusRUS** [coil-kt/coil#19]
**Describe the bug**
Crash on Android 9.0 when loading GIF-image

**To Reproduce**
1. Add `io.coil-kt:coil-gif` to dependencies
2. Try to load this GIF-file:
![success](https://user-images.githubusercontent.com/24453308/62932870-05d2e580-bdd2-11e9-833a-87d26d36c3b2.gif)
3. Image will freeze at start frame
4. After ~2 seconds crash will happened

**Expected behavior**
GIF picture will load and move

**Logs/Screenshots**
```
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8197 (AnimatedImageTh), pid 8010 (app.package.name)
```
Usage:
<img width="611" alt="Code screenshot" src="https://user-images.githubusercontent.com/24453308/62932778-e1770900-bdd1-11e9-8f77-9afa58487164.png">
Image container:
<img width="727" alt="Image view container" src="https://user-images.githubusercontent.com/24453308/62933478-5139c380-bdd3-11e9-9276-7c0cb9e72971.png">
Tested on devices:
- Nokia 6.1 (Android 9.0)
- Honor 9 Lite (Android 9.0)

**Library version**
version `0.6.0`

**Comment by colinrtwhite** [comment]
Thanks for the report. My gut feeling says this is an issue with Android's [ImageDecoder](https://developer.android.com/reference/android/graphics/ImageDecoder), but will explore further.

As a work-around I would use `GifDecoder` for all API levels at the moment.

**Comment by colinrtwhite** [comment]
Confirmed that it's an issue with Android's `ImageDecoder` APIs and not Coil. I filed a bug with a project that reproduces the issue (without Coil) on the Android bug tracker [here](https://issuetracker.google.com/issues/139371066).

To work around this crash, I would only register `GifDecoder` for all API levels.

**Comment by bveenvliet** [comment]
I am getting this issue as well on Pixel 2XL running latest Android 9 firmware and can confirm if you use GifLoader it works without crashing.

**Comment by colinrtwhite** [comment]
@bveenvliet Yes, `GifDecoder` should still work fine on Android P and above.
