### ISSUE TITLE
OutOfMemoryError when Bitmap gets decoded

### ISSUE THREAD

**Issue by pnehren** [coil-kt/coil#190]
Hello together,

thanks for that wonderful framework, it just works! But i experience some OutOfMemoryErrors on a device with less RAM, do you have any suggestions how to avoid them? 
I disabled disk cache, because the images are only valid for a few minutes. is it better to disable memory cache too? 

Thanks for your help! 

coil.decode.BitmapFactoryDecoder.decode (BitmapFactoryDecoder.java:142)
coil.RealImageLoader$loadData$2.invokeSuspend (RealImageLoader.java:359)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:241)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.java:594)
kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely (CoroutineScheduler.java:60)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.java:740)

**Comment by colinrtwhite** [comment]
If you're running out of memory, the best way to work around this is to reduce the amount of memory `ImageLoader` can hold. Coil defaults to 25% of the app's memory, but you can change that value using [`ImageLoaderBuilder.availableMemoryPercentage`](https://coil-kt.github.io/coil/api/coil-base/coil/-image-loader-builder/available-memory-percentage/).
