### ISSUE TITLE
Utilizing GIFs as Avatars in RecyclerView Items Leads to Significant Memory Allocation for GIF Loading

### ISSUE THREAD

**Issue by Edger** [coil-kt/coil#1904]
**Describe the bug**
I've implemented a message list using RecyclerView, where each message is accompanied by a user avatar loaded into an ImageView using the Coil image loading library.

However, when the list contains a large number of messages, scrolling through it results in a significant increase in the app's memory usage. Eventually, the system begins to recycle all activities in my app, sparing only the activity hosting my message list. This leads to a suboptimal user experience.

Upon examining a memory heap dump (hprof) using the Android Studio Profiler, and subsequently analyzing it with the Memory Analyzer Tool (MAT), I found an abundance of Gif instances.

Furthermore, I manually triggered garbage collection (GC) in Android Studio Profiler, but discovered that certain memory, predominantly within the Graphics sector, remained unreleased even post-GC.

**To Reproduce**
Create a list populated with numerous items, each featuring a GIF avatar sourced from the network. As you continuously scroll through this list, you'll notice a rapid surge in memory usage.

**Logs/Screenshots**
<img width="791" alt="image" src="https://github.com/coil-kt/coil/assets/18591042/f4bf28ac-12ff-4d4b-8999-d23f45e8ea18">

**Version**
2.4.0

**Comment by colinrtwhite** [comment]
How large are the gifs you're loading? GIFs aren't downsampled when loaded into memory. Also this is also likely related to the fact that Coil doesn't memory cache GIFs so the are reloaded when scrolling up and down.

For the graphics memory, are the images still displayed on screen or attached to an `ImageView` in a `RecyclerView` view pool? Also what API level did you test on and which `Decoder` did you use?

**Comment by Edger** [comment]
> How large are the gifs you're loading? GIFs aren't downsampled when loaded into memory. Also this is also likely related to the fact that Coil doesn't memory cache GIFs so the are reloaded when scrolling up and down.
> 
> For the graphics memory, are the images still displayed on screen or attached to an `ImageView` in a `RecyclerView` view pool? Also what API level did you test on and which `Decoder` did you use?

I have thoroughly reviewed the issues and understand that Coil only caches Bitmaps in memory.

The GIF I am utilizing can be downloaded from [here](https://gifer.com/en/iFc), it is roughly 2M in size.

For the graphics memory, When I manually initiate a Garbage Collection (GC), the images are neither displayed on the screen nor attached to an ImageView in a RecyclerView view pool. This occurs after I have closed the messaging page of my app.

Below is the decoder configuration in my app:

```
class App : MultiDexApplication(), ImageLoaderFactory {

    override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(this)
            .components {
                if (Build.VERSION.SDK_INT >= 28) {
                    add(ImageDecoderDecoder.Factory())
                } else {
                    add(GifDecoder.Factory())
                }
            }
            .memoryCache { MemoryCache.Builder(this).maxSizePercent(0.25).build() }
            .diskCache {
                DiskCache.Builder()
                    .directory(this.cacheDir.resolve("image_cache"))
                    .maxSizePercent(0.02)
                    .build()
            }
            .build()
    }
}
```

**Comment by colinrtwhite** [comment]
Which API level and device did you encounter this on?

**Comment by Edger** [comment]
> The large number of 2 MB allocations are mostly due to the fact that each new `RecyclerView` row triggers a new image request and allocates new graphics memory. This isn't ideal, but is currently working as intended as Coil doesn't cache GIF images in memory. You can work around this by manually caching the GIFs when the image request completes successfully.
> 
> I believe the native graphics memory isn't affected by manually initiated JVM GC so it will be freed on its own timeline.

Okay, got it. Thanks you for your time.
