### ISSUE TITLE
rememberAsyncImagePainter doesn't render correctly with Roborazzi/Paparazzi

### ISSUE THREAD

**Issue by colinrtwhite** [coil-kt/coil#1910]
**Describe the bug**
`rememberAsyncImagePainter` doesn't render properly when used with Roborazzi and Paparazzi. The issue appears to be related to the fact that it it needs to wait for a valid `drawSize`, which is set in `DrawScope.onDraw` immediately before the painter is then drawn. `AsyncImage` avoids this timing issue by using `ConstraintsSizeResolver` to listen to its own composable constraints, which are set before the draw stage.

Interestingly, Paparazzi and Roborazzi both render `rememberAsyncImagePainter` incorrectly, but differently. When `intrinsicContentSize` is set to a fixed value this fixes the issue on Roborazzi, but not Paparazzi. It's possible there are different root causes, but this needs to be debugged further.

**Work-around**
It's possible to work-around this issue by setting any custom size:

```kotlin
rememberAsyncImagePainter(
    model = ImageRequest.Builder(LocalContext.current)
        .data("https://www.example.com/image.jpg")
        .size(Size.ORIGINAL)
        .build(),
    contentDescription = null,
)
```

**To Reproduce**
See `RoborazziComposeTest.rememberAsyncImagePainter` and `PaparazziTest.rememberAsyncImagePainter` in this repository.

**Version**
Reproduced with Coil `2.4.0`, Roborazzi `1.6.0`,  and Paparazzi `1.3.1`.

Related: https://github.com/cashapp/paparazzi/issues/1123

**Comment by takahirom** [comment]
I'm not sure about the issue with Roborazzi. Does "to specify an immediate size" mean we shouldn't use ".size(Size.ORIGINAL)"? Could you let me know if this is correct?
Expected: 
![coil test RoborazziComposeTest rememberAsyncImagePainter](https://github.com/coil-kt/coil/assets/1386930/e4670a49-e960-4427-9a9c-4cfc676e9e29)

Actual: 
![coil test RoborazziComposeTest rememberAsyncImagePainter](https://github.com/coil-kt/coil/assets/1386930/32bfce28-55a3-4673-b620-f160d35d5ebe)

**Comment by takahirom** [comment]
I'm not sure about the issue with Roborazzi. Does "to specify an immediate size" mean we shouldn't use ".size(Size.ORIGINAL)"? Could you let me know if this is correct?
Expected:
![coil test RoborazziComposeTest rememberAsyncImagePainter](https://github.com/coil-kt/coil/assets/1386930/2a6605a0-d03d-4708-9a34-39968913f41c)

Actual:
![coil test RoborazziComposeTest rememberAsyncImagePainter](https://github.com/coil-kt/coil/assets/1386930/cbb02743-1926-447d-91eb-5a4db802955f)

**Comment by colinrtwhite** [comment]
@takahirom Yep, the expected + actual are what I'm seeing too. Part of the reason `AsyncImage` works, but `rememberAsyncImagePainter` doesn't is `rememberAsyncImagePainter` has to grab the size for the image request [here](https://github.com/coil-kt/coil/blob/main/coil-compose-base/src/main/java/coil/compose/AsyncImagePainter.kt#L205) during `onDraw`. This occurs after `intrinsicSize` is called, so `intrinsicSize` is initially `Size.Unspecified`. This gets updated to the painter's size after `onDraw` which seems to be OK on-device but is too late for the Roborazzi capture.

Paparazzi is doing something differently as it doesn't render the image at all - even if `intrinsicSize` is hardcoded to an exact pixel size.

**Comment by kartik-prakash** [comment]
Any updates here? This has become a huge blocker for us.

**Comment by colinrtwhite** [comment]
@kartik-prakash I haven't had a chance to take a look at this further as I'm focused on the 3.x work. If you're able to track down the issue locally, I'd accept a PR that patches the issue.

**Comment by colinrtwhite** [comment]
This has been fixed in the `3.x` alpha releases.

**Comment by colinrtwhite** [comment]
Closing as this is fixed in the 3.x release branch. For earlier versions check out the work-around above.
