### ISSUE TITLE
Support loading resource files in the Android Studio preview

### ISSUE THREAD

**Issue by Quyunshuo** [coil-kt/coil#1915]
I am using `AsyncImage` to load a **webp** image in a resource file, but I have no way to preview it, is there any way to provide a preview without affecting the logic?  For example, are there any `tools` attributes similar to those in xml?

**To Reproduce**
Load a resource file

**Logs/Screenshots**
![image](https://github.com/coil-kt/coil/assets/40329952/d502ff35-d1b0-499a-8eb5-ef86f82dc43d)
![image](https://github.com/coil-kt/coil/assets/40329952/6c363f43-9ad3-4cbf-a1a3-3b227553ddd1)

**Version**
version: 2.5.0

**Comment by colinrtwhite** [comment]
This is currently intended behaviour. Coil only loads the `placeholder` in the preview environment - mostly since we can guarantee that the `placeholder` isn't a URL or another data type that can't be loaded in the preview environment. That said, we should re-evaluate this behaviour and likely make it possible to load known-loadable data types (resource ints, bitmaps) in previews.

I'm thinking we could support something like this:

```
AsyncImage(
    model = if (LocalInspectionMode.current) {
        "https://example.com/image.jpg"
    } else {
        R.drawable.preview_placeholder
    },
    contentDescription = null,
)
```

**Comment by Quyunshuo** [comment]
Looking forward to the follow-up

**Comment by colinrtwhite** [comment]
Let's keep this open to track.

**Comment by colinrtwhite** [comment]
This is now more important given [androidx's new screenshot testing library](https://developer.android.com/studio/preview/compose-screenshot-testing) sets `isPreview = true` and doesn't set a `Dispatchers.Main` implementation. This means `FakeImageEngine` can't easily be used in that environment.

As a stopgap I think it probably makes sense to introduce a `LocalAsyncImagePainterPreviewHandler` to allow overriding `AsyncImagePainter`'s preview behaviour.

**Comment by colinrtwhite** [comment]
This is now supported in `3.0.0-alpha07` so you can do:

```kotlin
AsyncImage(
    model = R.drawable.sample,
    contentDescription = null,
)
```

It's not possible to load files or access the network in the preview environment so for those cases you can use:

```kotlin
AsyncImage(
    model = if (LocalInspectionMode.current) {
        "https://example.com/image.jpg"
    } else {
        R.drawable.preview_placeholder
    },
    contentDescription = null,
)
```

or set a custom `LocalAsyncImagePreviewHandler`. Overall, the rendering should now be more predictable. For instance, the `error` painter will now be rendered if the image request fails.

**Comment by tgyuuAn** [comment]
@OKatrych 

I'd like to take on this issue, but I can't reproduce it. 

In my case, when I tried rendering fi_flag with svg vector drawable and eu_flag with webp in version 3.0.0 alpha 10, both came out fine.

Could you please tell me more about the issue?

<img width="1327" alt="image" src="https://github.com/user-attachments/assets/246c23bd-3876-4459-94cc-db8d22db1429">
