### ISSUE TITLE
Loading Speed Improvement

### ISSUE THREAD

**Issue by Starscream9559** [coil-kt/coil#192]
**Is your feature request related to a problem? Please describe.**
Aint no problem. Coil helps me load images on AppBar but Glide is not. So if this is very possible as it is heading to 1.0, why use 2 image loading libraries that do the same thing, right?

**Describe the solution you'd like**
Improvement on loading speed to defeat Glide as the game changer. Refering to the test done here, https://proandroiddev.com/coil-vs-picasso-vs-glide-get-ready-go-774add8cfd40?gi=e652bc45f134 where Coil still placed in second even with cache load.

**Comment by Starscream9559** [comment]
I should've put that Milestone flair.. but I missed it.

**Comment by colinrtwhite** [comment]
Yep! I agree. I'm still focused on stability + features, but after that I'll be focusing on speed before the 1.0 release. Also check out my response to that article [here](https://www.reddit.com/r/androiddev/comments/d6cd43/coil_vs_picasso_vs_glide_get_ready_go/f0t997m/).

Tracking support for speed measurement + improvements [here](https://github.com/coil-kt/coil/issues/71).
