### ISSUE TITLE
Same URL with updated image shows same old image on AsyncImage.

### ISSUE THREAD

**Issue by vikskod** [coil-kt/coil#1923]
I have an image URL which may provide the different images in unknown time. I can not disable the caching because it makes performance issue on the app.
Furthermore, I have an option to use the header value (ETag or Last-Modified), which is unique for each new image.

How can I use the header value to set the image cache key? Or is there any alternative way to fix this issue?
FYI: I'm using `AsyncImage` to load image.

**Comment by colinrtwhite** [comment]
Coil will handle standard `Cache-Control` headers (including reverification) by default. It's likely the image isn't changing as it's still being served by the memory cache. You can manually clear that image from the memory cache if you'd like it to be refetched.

If you're looking for the image to be served from the memory cache in parallel while it's being reverified with the server then you'll have to do something more custom as that's currently not supported.

**Comment by vikskod** [comment]
The protocol cache policy means there might be 
`Last-Modified`, `ETag`, `Cache-Control`, `Expires`
Does coil use all of above policy to control the caching? Seems like only `Cache-Control` is used to control cache if I'm not wrong.

**Comment by josenaves** [comment]
Do we have any update on this? I'm also facing some issues with `eTag` headers...
