### ISSUE TITLE
Request to add 'noClipContent: Boolean = false' parameter to Compose's AsyncImage

### ISSUE THREAD

**Issue by panpf** [coil-kt/coil#1925]
An image zoom component [ZoomImage](https://github.com/panpf/zoomimage) that I am developing that supports Compose encountered problems when adapting to AsyncImage.

Because ContentScale.None needs to be supported, and the user can also drag to view content that cannot be seen at first, AsyncImage needs to add a `noClipContent: Boolean = false` parameter to control not clip the content.

The final modified location is at [AsyncImage.kt](https://github.com/coil-kt/coil/blob/main/coil-compose-base/src/main/java/coil/compose/AsyncImage.kt) at line 168:

```kotlin
/** Draws the current image content. */
@Composable
internal fun Content(
    modifier: Modifier,
    painter: Painter,
    contentDescription: String?,
    alignment: Alignment,
    contentScale: ContentScale,
    alpha: Float,
    colorFilter: ColorFilter?,
) = Layout(
    modifier = modifier
        .contentDescription(contentDescription)
        .clipToBounds()
        .then(
            ContentPainterModifier(
                painter = painter,
                alignment = alignment,
                contentScale = contentScale,
                alpha = alpha,
                colorFilter = colorFilter
            )
        ),
    measurePolicy = { _, constraints ->
        layout(constraints.minWidth, constraints.minHeight) {}
    }
)
```

The modification is as follows:

```kotlin
/** Draws the current image content. */
@Composable
internal fun Content(
    modifier: Modifier,
    painter: Painter,
    contentDescription: String?,
    alignment: Alignment,
    contentScale: ContentScale,
    alpha: Float,
    colorFilter: ColorFilter?,
    noClipContent: Boolean = false,
) = Layout(
    modifier = modifier
        .contentDescription(contentDescription)
        .let { if (!noClipContent) it.clipToBounds() else it }
        .then(
            ContentPainterModifier(
                painter = painter,
                alignment = alignment,
                contentScale = contentScale,
                alpha = alpha,
                colorFilter = colorFilter
            )
        ),
    measurePolicy = { _, constraints ->
        layout(constraints.minWidth, constraints.minHeight) {}
    }
)
```

AsyncImage and SubcomposeAsyncImage needs to add the noClipContent: Boolean = false parameter:

```kotlin
@Composable
fun AsyncImage(
    model: Any?,
    contentDescription: String?,
    imageLoader: ImageLoader,
    modifier: Modifier = Modifier,
    transform: (State) -> State = AsyncImagePainter.DefaultTransform,
    onState: ((State) -> Unit)? = null,
    alignment: Alignment = Alignment.Center,
    contentScale: ContentScale = ContentScale.Fit,
    alpha: Float = DefaultAlpha,
    colorFilter: ColorFilter? = null,
    filterQuality: FilterQuality = DrawScope.DefaultFilterQuality,
    noClipContent: Boolean = false,
)
```

Please also consider my request!

If can't add parameters to support my request, I will have to clone all the source code of AsyncImage and modify the implementation myself, but this will not be able to synchronize the updates of AsyncImage in time, resulting in a split situation, which I don't want to see.

**Comment by colinrtwhite** [comment]
I think this probably makes sense to add, though I would make the param `clipToBounds = true` to match the property name. Does your library also integrate with the `Image` composable? Coil's `clipToBounds` usage is copied from the `Image` composable, which also always adds `clipToBounds` and doesn't provide a param to disable it.

**Comment by panpf** [comment]
Yes, I created a new [NoClipContentImage](https://github.com/panpf/zoomimage/blob/main/zoomimage-compose/src/commonMain/kotlin/com/github/panpf/zoomimage/compose/internal/NoClipContentImage.kt), which copies the standard Image component, removes clipToBounds(), and gives it to the base [ZoomImage](https://github.com/panpf/zoomimage/blob/main/zoomimage-compose/src/commonMain/kotlin/com/github/panpf/zoomimage/ZoomImage.kt) component usage

The coil version of the component [CoilZoomAsyncImag](https://github.com/panpf/zoomimage/blob/main/zoomimage-compose-coil/src/main/java/com/github/panpf/zoomimage/CoilZoomAsyncImage.kt) is currently Copied your code modifications

**Comment by panpf** [comment]
我同意你的看法，该参数应该定义为 `clipToBounds = true`
