### ISSUE TITLE
How to set scale fitxy?

### ISSUE THREAD

**Issue by nicemak** [coil-kt/coil#193]
hi,

i set scale type to fitXY, but it is not working, i used scale(Scale.FILL) but image shows as centerCrop. what i am missing or how can i set image to fitXY?

**Comment by colinrtwhite** [comment]
Did you set `android:scaleType="fitXy"` on your `ImageView` as well?

**Comment by nicemak** [comment]
yes

**Comment by colinrtwhite** [comment]
@nicemak Could you try using the [latest snapshot](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots) and let me know if you still see the issue? Also do you have a code snippet and screenshot I could use to debug?

**Comment by nicemak** [comment]
actually we have overcome the issue with different approach, but if we need to this again with some other scenario i will use your latest snapshot.

Code Snippet:
`<ImageView
            android:id="@+id/product_image"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:scaleType="fitXY"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            tools:src="@drawable/dummy_image" />`

`val imageLoader = ImageLoader(context) {
                okHttpClient { OkHttpClient.Builder().cache(CoilUtils.createDefaultCache(context)).build() }
            }

            view.load(image_from_server, imageLoader) { scale(Scale.FILL) }`

**Comment by colinrtwhite** [comment]
:+1: Sounds good. Feel free to open another issue if you run into this again and can reproduce it on the snapshot.

**Comment by aashrai** [comment]
This is probably because you are using a transformation. Coil adds a Scale.FILL for any transformation overriding any scale type that you must have set on your image view.
