### ISSUE TITLE
I found that using ImageDecoderDecoder to play the gif image once on Android 13

### ISSUE THREAD

**Issue by HoltChas** [coil-kt/coil#1932]
val imageLoader = ImageLoader.Builder(context).components {coil gif loader
    if (Build.VERSION.SDK_INT >= 28) {
        add(ImageDecoderDecoder.Factory())
    } else {
        add(GifDecoder.Factory())
    }
}.build()
  AsyncImage(
        model = ImageRequest.Builder(context).data(drawableOrUrl).build(),
        contentDescription = null,
        modifier = modifier,
        contentScale = contentScale,
        imageLoader = imageLoader
    )
I found that using ImageDecoderDecoder to play the gif image once on Android 13   Use add(GifDecoder.Factory()) and it will be ok  I don't know if it's just me or if it's a bug

**Comment by colinrtwhite** [comment]
Please follow the issue template - it's not clear what the issue is or how to reproduce it.
