### ISSUE TITLE
[Coil 3] Make ImageDecoderDecoder used by default when available 

### ISSUE THREAD

**Issue by VDostoyevskiy** [coil-kt/coil#1943]
ImageDecoder has better IO performance compared to BitmapFactory, since we can pass a File or DirectByteBuffer directly and the image blob doesn't go through art heap, where we use inputstream of a BufferedSouce for BitmapFactory, image data is always copied between native heap and art heap

For scenario that we are not allowed to have a DiskCache, (i.e. only on memory stream is available) we can fallback to BitmapFactory.

**Comment by colinrtwhite** [comment]
Does passing a file reference directly have better IO performance vs. exposing a stream to the file? Please share a benchmark if possible. My understanding was `BitmapFactory` and `ImageDecoder` are backed by the same Skia decoder. We should avoid `DirectByteBuffer` as it requires loading the image data completely into memory before decoding, which could cause OOMs on large files.

Depending only on `BitmapFactory` is much better for consistency and maintenance so I'd prefer to continue with only one decoder unless there are demonstrable performance gains.

**Comment by VDostoyevskiy** [comment]
> Does passing a file reference directly have better IO performance vs. exposing a stream to the file? Please share a benchmark if possible. My understanding was `BitmapFactory` and `ImageDecoder` are backed by the same Skia decoder. We should avoid `DirectByteBuffer` as it requires loading the image data completely into memory before decoding, which could cause OOMs on large files.
> 
> Depending only on `BitmapFactory` is much better for consistency and maintenance so I'd prefer to continue with only one decoder unless there are demonstrable performance gains.

Aha, DirectByteBuffer allocated through ByteBuffer.allocateDirect(), backing memory is on dalvik heap and can cause OOM,
But If user provide DirectByteBuffer through JNI method, the backing memory is on native heap (Actually we use libarchive do something like this), it will not cause OOM
Besides if DirectByteBuffer is a file mapping(create it through FileChannel or just mmap), will not cause OOM as well

Will provide a benchmark when I'm free

**Comment by colinrtwhite** [comment]
Gotcha, If there's a measurable performance improvement then we should consider using it on API 28+, though it will add extra maintenance burden.

**Comment by VDostoyevskiy** [comment]
@colinrtwhite 
I have wrote a simple benchmark and run with sm7250, UP1A.231105.003

```
import coil3.decode.BitmapFactoryDecoder
import coil3.decode.ImageDecoderDecoder
import coil3.decode.ImageSource
import coil3.request.Options
import coil3.size.Size
import io.ktor.client.request.prepareGet
import io.ktor.client.statement.bodyAsChannel
import io.ktor.util.cio.readChannel
import kotlin.system.measureTimeMillis
import splitties.init.appCtx

suspend fun ByteReadChannel.copyTo(file: File) {
    RandomAccessFile(file, "rw").use {
        copyTo(it.channel)
    }
}

suspend fun benchmarkAll() {
    val keys = (0..9).map { "BitmapFactoryCache$it" to "ImageDecoderCache$it" }
    val diskCache = imageCache
    val ktorClient = ktorClient

    suspend fun benchMark(url: String, options: Options) {
        val temp = diskCache.openEditor("temp")!!
        ktorClient.prepareGet(url).execute { it.bodyAsChannel().copyTo(temp.data.toFile()) }
        temp.commit()

        // Prepare data
        diskCache.openSnapshot("temp")!!.use { tempFile ->
            keys.flatMap { (a, b) -> listOf(a, b) }.forEach { key ->
                val editor = diskCache.openEditor(key)!!
                tempFile.data.toFile().readChannel().copyTo(editor.data.toFile())
                editor.commit()
            }
        }
        diskCache.remove("temp")

        // Use different file in case page cache
        val result = keys.map { (key1, key2) ->
            // BitmapFactory
            val t1 = diskCache.openSnapshot(key1)!!.use { snapshot ->
                val source = ImageSource(snapshot.data)

                measureTimeMillis {
                    BitmapFactoryDecoder(source, options).decode()
                }.also {
                    println("BitmapFactory pass $key1, time $it ms")
                }
            }

            // ImageDecoder
            val t2 = diskCache.openSnapshot(key2)!!.use { snapshot ->
                val source = ImageSource(snapshot.data)

                measureTimeMillis {
                    ImageDecoderDecoder(source, options, false).decode()
                }.also {
                    println("ImageDecoder pass $key2, time $it ms")
                }
            }

            diskCache.remove(key1)
            diskCache.remove(key2)

            t1 to t2
        }.unzip()

        val avgBitmapFactory = result.first.average()
        println("BitmapFactoryDecoder avg$avgBitmapFactory")

        val avgImageDecoder = result.second.average()
        println("ImageDecoderDecoder avg$avgImageDecoder")
    }

    // 22.7K, may not have obvious difference since BitmapFactory inner buffer is 16K bytearray
    benchMark(
        "https://i.insider.com/5c8bd064daa50752c9735657?width=1000&format=jpeg&auto=webp",
        Options(appCtx),
    )
    // Result: BitmapFactory avg 53 ms, ImageDecoder 49 ms

    // Benchmark again sampled
    benchMark(
        "https://i.insider.com/5c8bd064daa50752c9735657?width=1000&format=jpeg&auto=webp",
        Options(appCtx, Size(640, 480)),
    )
    // Result: BitmapFactory avg 37 ms, ImageDecoder 30 ms

    // Let's benchmark 1M png
    benchMark(
        "https://github.com/Ehviewer-Overhauled/Art/blob/2209f8e48e2025790c679198301bf70e28dbf010/screenshot-01.png?raw=true",
        Options(appCtx),
    )
    // Result: BitmapFactory avg 226 ms, ImageDecoder 216 ms

    // Let's benchmark 1M png
    benchMark(
        "https://github.com/Ehviewer-Overhauled/Art/blob/2209f8e48e2025790c679198301bf70e28dbf010/screenshot-01.png?raw=true",
        Options(appCtx, Size(640, 480)),
    )
    // Result: BitmapFactory avg 168 ms, ImageDecoder 159 ms

    // Then 4M png
    benchMark(
        "https://github.com/Ehviewer-Overhauled/Art/blob/2209f8e48e2025790c679198301bf70e28dbf010/screenshot-02.png?raw=true",
        Options(appCtx),
    )
    // Result: BitmapFactory avg 253 ms, ImageDecoder 233 ms

    // Then 4M png sampled
    benchMark(
        "https://github.com/Ehviewer-Overhauled/Art/blob/2209f8e48e2025790c679198301bf70e28dbf010/screenshot-02.png?raw=true",
        Options(appCtx, Size(640, 480)),
    )
    // Result: BitmapFactory avg 206 ms, ImageDecoder 183 ms
}
```

As we can see, the main cost is "Decode", but we can still save some IO overhead(and additionally, some gc pressure overhead?)

**Comment by colinrtwhite** [comment]
@VDostoyevskiy That looks like a solid decode time improvement! Would you be open to submitting a PR for this? We can target it to the `3.x` branch.

**Comment by VDostoyevskiy** [comment]
> @VDostoyevskiy That looks like a solid decode time improvement! Would you be open to submitting a PR for this? We can target it to the `3.x` branch.

Yeah, I will do it
