### ISSUE TITLE
[Coil 3] Any future idea to migrate to kotlinx-io?

### ISSUE THREAD

**Issue by VDostoyevskiy** [coil-kt/coil#1944]
Ktor is going to take kotlinx-io as their fundamental IO library.
https://youtrack.jetbrains.com/issue/KTOR-6030
And kotlinx-io will provide off-heap IO primitive support
https://github.com/Kotlin/kotlinx-io/issues/239

Since platform image decoder is not written with Java/Kotlin (i.e. we will not parse image data within art/jvm heap), transfer them natively will be a good idea

Due to kotlinx-io is under development, I'm not expecting this to be implemented in few weeks(or months?)

**Comment by colinrtwhite** [comment]
No plans at the moment. Coil needs Okio's `FileSystem` class to read/write files to disk and I don't believe kotlinx-io has plans to add similar functionality soon.

**Comment by colinrtwhite** [comment]
Actually it looks like `kotlinx-io` has [filesystems](https://github.com/Kotlin/kotlinx-io/blob/master/core/common/src/files/FileSystem.kt) now! Going to look into this and chat with other folks to see what they think. My main concern is kotlinx-io is still under development so this might have to wait for Coil 4.x.

**Comment by VDostoyevskiy** [comment]
> Actually it looks like `kotlinx-io` has [filesystems](https://github.com/Kotlin/kotlinx-io/blob/master/core/common/src/files/FileSystem.kt) now! Going to look into this and chat with other folks to see what they think. My main concern is kotlinx-io is still under development so this might have to wait for Coil 4.x.

Yeah, land it in Coil 4.0 should be a fair choice

**Comment by revonateB0T** [comment]
https://github.com/ktorio/ktor/commit/40042dc845e38dcdc2ba2fee0224fbfd2b13d172

ktor migrated to kotlinx-io in 3.0-beta2, What's our plan? @colinrtwhite

**Comment by revonateB0T** [comment]
We failed upgrade ktor without a new coil release.
https://github.com/FooIbar/EhViewer/actions/runs/9950836261/job/27489338373

**Comment by revonateB0T** [comment]
Some ByteReadChannel extensions moved to io.ktor.utils.io package, see
https://github.com/FooIbar/EhViewer/commit/b793223cb046e6815910e27c177527fcc73de1b2
