### ISSUE TITLE
Support caching transformed images on disk

### ISSUE THREAD

**Issue by Mathnerd314** [coil-kt/coil#1959]
**Is your feature request related to a problem? Please describe.**
I am creating a gallery-like app and I want Coil to act like a thumbnail generator: it takes the image, resizes it, *saves the thumbnail to disk*, and then loads the thumbnail from disk (not the original on-disk image) when requested. But it appears Coil has no provisions for saving anything besides original network-retrieved images to disk.

**Describe the solution you'd like**
I think it would just be an additional option or two on the caching policy like `cacheTransformedImage = true`. This would save whatever bitmap was last in the render path. Glide supports this, so refer to them for implementation details.

**Additional context**
This is based on the information in https://github.com/coil-kt/coil/discussions/1733 and https://github.com/coil-kt/coil/issues/756 and my inspection of Coil's [code](https://github.com/coil-kt/coil/blob/f7c7cdff9ae7be1e6b622a2cd26544a5393e001c/coil-base/src/main/java/coil/intercept/EngineInterceptor.kt#L78), which all suggest this feature is missing. I have not tested it out in an app; if Coil already supports it I would of course be happy and sorry for the trouble.

**Comment by colinrtwhite** [comment]
Thanks for the enhancement request, however I don't think this is the best fit for Coil for a couple reasons:

- With Jetpack Compose, `Transformation`s aren't recommended and can often be implemented more efficiently with `Modifier`s. For instance, using `Modifier.clip(RoundedCornerShape(radius))` will be more efficient (time and memory) than using `RoundedCornersTransformation`.
- For resizing specifically, even if a large image is saved on disk, Coil subsamples it while decoding it into memory so a large image and a small variant of that image will use the same amount of memory when decoded into the same-sized target.
- It adds complexity. Coil's image pipeline's steps are always in the same order so it's easy to understand. Currently, images . Adding this feature creates a special case where disk caching can be delayed to after the transformation step. Additionally, `Transformation`s should be cached with their size information (as the size influences the result), which adds complexity.

That said, if you need this feature it's likely possible to implement with an `Interceptor`. Here's some pseudocode:

```kotlin
suspend fun intercept(chain: Interceptor.Chain): ImageResult {
    // Include the image's size in the request's disk cache key.
    val request = chain.request.newBuilder()
        .diskCacheKey(chain.request.data + ":${chain.size}")
        .build()

    val result = chain.withRequest(request).proceed()

    val diskCacheKey = result.diskCacheKey
    if (diskCacheKey != null) {
        imageLoader.diskCache.openEditor(diskCacheKey)?.use {
            // Replace the non-transformed entry in the disk cache by write `result.drawable` to the disk cache.
        }
    }

    return result
}
```
