### ISSUE TITLE
ComponentRegistry associated DefaultRequestOptions

### ISSUE THREAD

**Issue by roomtek** [coil-kt/coil#1960]
**Is your feature request related to a problem? Please describe.**
I am currently initializing a singleton ImageLoader, and have set some defaults for error Drawable and placeholder Drawable. While this works for all requests, there is no way to set them for specific components. This way the placeholders can also be provided by the registered components

```
override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(applicationContext)
        .error(D_NoAlbumArtError()) // for all requests
        .placeholder(D_NoAlbumArtAlbum()) // for all requests
         .components {
                add(CoilAlbumArtFetcher.AlbumFactory()) // Album - Need different placeholder drawable 
                add(CoilAlbumArtFetcher.TrackFactory()) // Track - Need different placeholder drawable 
                add(CoilArtistArtFetcher.Factory()) // Artist - Need different placeholder drawable 
                add(CoilCompositeArtFetcher.Factory()) // Composite - Need different placeholder drawable and cachepolicy
                add(CoilAlbumArtFetcher.PlayableFactory()) // Playable - Need different placeholder drawable  and cachepolicy
        }
        .build()
    }
```

**Describe the solution you'd like**
Can the DefaultRequestOptions be looked up from the component Fetcher? If the fetcher does not provide the option, then fallback to the defaults.

**Comment by colinrtwhite** [comment]
This isn't something that's supported out of the box. Unfortunately it's not possible to add this either as placeholders are set immediately on the main thread and and image request's `Fetcher` is decided later in the image pipeline after we're on a worker thread.

Your best bet is probably to set the `placeholder`/`error` values on `ImageRequest` before you launch the image request.
