### ISSUE TITLE
[Coil 3] Having compile time error: Could not find io.ktor:ktor-io-cinterop-mutex

### ISSUE THREAD

**Issue by rustamsmax** [coil-kt/coil#1967]
Android app is built successfully but couldn't build ios app. Shared code is exported as static library

Showing Recent Messages
Could not find "io.ktor:ktor-io-cinterop-mutex" in [/Users/rustam/Projects/***, /Users/rustam/.konan/klib, /Users/rustam/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/common, /Users/rustam/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/platform/ios_simulator_arm64]

`ktor-bom = "2.3.7"`

![telegram-cloud-photo-size-2-5199607573588856794-y](https://github.com/coil-kt/coil/assets/36570577/797a9a40-843f-4e9d-bf39-9daac50a1f8e)

When I remove `coil-network` dependency it passes

**Comment by colinrtwhite** [comment]
This sounds like it could be a local Gradle caching issue or potentially an issue with `ktor-bom`. I'd file an issue on the Ktor tracker and also try declaring the dependencies without the bom. It's tough to say what the exact issue is without a way to reproduce it.

**Comment by rustamsmax** [comment]
It's not related to cache deleted all gradle caches and rebuilt. Showing the same error. I've tried without bom.
