### ISSUE TITLE
[Coil 3] Introduce ByteBufferMetadata

### ISSUE THREAD

**Issue by VDostoyevskiy** [coil-kt/coil#1971]
Now that we prefer ImageDecoderDecoder for API above 28
https://github.com/coil-kt/coil/pull/1969
ImageDecoder can efficiently decoding a ByteBuffer
After https://github.com/coil-kt/coil/issues/1970 we lazily create a BufferedSource (Write the ByteBuffer totally to art heap)
When ImageDecoder is available, we no longer pay for the overhead, as ByteBuffer maybe a DirectByteBuffer allocated in native heap or file mapping
See https://github.com/coil-kt/coil/issues/1943#issuecomment-1848350924

**Comment by colinrtwhite** [comment]
Do you know how much overhead this avoids? I'm not totally opposed to it, but ideally we want to use `ImageSource.Metadata` sparingly as it couples `Fetcher`s and `Decoder`s.

Originally `AssetMetadata`, `ContentMetadata`, and `ResourceMetadata` were added as the gains were significant since it avoided copying a full video file for `VideoFrameDecoder`.

**Comment by VDostoyevskiy** [comment]
> Do you know how much overhead this avoids? I'm not totally opposed to it, but ideally we want to use `ImageSource.Metadata` sparingly as it couples `Fetcher`s and `Decoder`s.
> 
> Originally `AssetMetadata`, `ContentMetadata`, and `ResourceMetadata` were added as the gains were significant since it avoided copying a full video file for `VideoFrameDecoder`.

This can totally avoid heap thrashing and OOM if user want to decode a DirectByteBuffer
Actually, we'd better implement a ByteBufferImageSource, not Metadata
Then we also provide a okio Buffer, but data is lazily copied to okio Buffer(art heap) when user need it

**Comment by VDostoyevskiy** [comment]
The most interesting thing is, unlike ByteArray, ByteBuffer may represent a range of virtual address, where its page cache maybe not even populated yet

**Comment by VDostoyevskiy** [comment]
Also, https://github.com/coil-kt/coil/blob/03df3445cdd5da1f31cf160df7a2c678d72096a2/coil-network/src/commonMain/kotlin/coil3/fetch/NetworkFetcher.kt#L254

This will squash the whole http body to art heap if no diskcache available
May cause OOM if image blob too large

**Comment by colinrtwhite** [comment]
Sounds good, I think we can probably add this after https://github.com/coil-kt/coil/pull/1969 is merged. I'll leave the implementation to you
