### ISSUE TITLE
AsyncImage not recomposing when retrieving data from DataStore Preferences

### ISSUE THREAD

**Issue by RoxasKH** [coil-kt/coil#1978]
I've made a minimal reproducible example, so that anyone check it, and pushed it to a repository here:

https://github.com/RoxasKH/CoilComposeBug

Basically this is linked to storing locally image URIs and then retrieving them on app restart.

**Step to reproduce:**
1. Make sure to have at least a couple of local images in your gallery, i suggest drag and drop them to the emulator as opening Chrome makes the emulator crash, at least for me.
2. Build an run the app: you'll see a simple layout, with a section at the top that displays your name and the image URIs, and a grid containing different loading options for the image, you should have:
- Coil 
- Alternative Coil (uses rememberAsyncImagePainter with Image instead of AsyncImage directly)
- Coil, but the URI that it loads it's saved to the classical SharedPreferences instead (this was to exclude the possibility of a DataStore issue)
- Glide (uses Glide instead of Coil, to check if it was common behaviour or not)
3. Now the app works quite in a simple way: you can change your name by clicking on the edit button next to the textbox, and load an image through the ImagePicker you can open either with the button or clicking on any image. Change the name if you want, but it's not needed, it was mostly to check DataStore working correctly again.
4. Select any image you want: it should load correctly in all of the 4 Image components.
5. Both the name and the image chosen are gonna be saved to DataStore Preferences when you select them.
6. Now close the app
7. Reopen the application: you will now see your new name loading correctly, the URI saved in preferences updating correctly, but only the Glide component loading the image. The coil components will display the error placeholder i set instead.
8. Trying to reload the same image (by picking it again from the image picker) will not reload it either: to make the image appear, you'll now have to load a different image, and reload the old one, so that it can detect the state change.

It seems like coil detects that the state changes (and so as trying to reload the same image won't change the URI state won't doing anything) but it's not able to recompose when the application start.

Inspired by #884 found while looking for an already existing issue about this, i've added some Logging to the painter based Coil component, and the painter do give this error:

```
Error(painter=com.google.accompanist.drawablepainter.DrawablePainter@889c978, result=coil.request.ErrorResult@c706500f)
```

Clicking on the Retry TextButton won't manage to reload the image either, and will still just throw a similar error.

At the moment, the only library i found that was able to do this is Glide, and as it works perfectly fine with Glide, i'm assuming it's some kind of bug. At least while programming a similar thing in an actual application i was assuming it would have worked, but it didn't, and that's why i digged a bit more in this.
That said, even if Glide works on it, i trained my workflow with Coil up to now, and things with Glide are slightly different, so even if at the moment i can still use Glide for that single instance where i need it, i hope it'll get fixed cause i don't find using 2 different image loading libraries to be ideal.

(Unrelated, but you can also activate the beta PicassoCompose component in the list of items in the User.kt file by decommenting it, and it can't reload the image on application start either, although that is clearly stated to be in a beta state at the moment.)

**Version**
The Coil version used was 2.4.0, latest at the time of writing

Sorry if this was kinda long, and thank you

**Comment by colinrtwhite** [comment]
What's that value of `result.throwable`?

**Comment by VDostoyevskiy** [comment]
It is expected, Coil will not have a copy of the image photopicker shared.
Once app restart, we lost the permission of uri(i.e. you shouldn't store that uri in datastore and assume it is valid after restart)
Then coil failed to load it due to SecurityException, when you repick the same image, although permission granted, Uri is the same so Composer will skip that AsyncImage

**Comment by RoxasKH** [comment]
> It is expected, Coil will not have a copy of the image photopicker shared. Once app restart, we lost the permission of uri(i.e. you shouldn't store that uri in datastore and assume it is valid after restart) Then coil failed to load it due to SecurityException, when you repick the same image, although permission granted, Uri is the same so Recomposer will skip that AsyncImage

Hmmm, understandable and it's like you say, if i repick the image through the picker and force recomposition, the image does get loaded. I thought about something like that but couldn't easily get the error. Also i have no idea how Glide manages to pull it off at this point, or if this is actually a Glide behaviour bug instead.

So i'm guessing the app would need storage read permission to get it to work, or i could do some other tricky stuff. Storage permission feels a little overkill for a single image saving, but i guess this is outside the scope of the issue anyways.

I think this can be closed, then, as it's not actually an issue, but expected behaviour.
Thanks again for your help

**Comment by colinrtwhite** [comment]
Yep @VDostoyevskiy is right. I'm not 100% sure how Glide is handling this, though it's possible they're saving the image to their local disk cache then reloading it from there. Coil only saves images it downloaded from the network to its disk cache.

For reloading the image once permissions for that URI are acquired again we need something like https://github.com/coil-kt/coil/issues/884.
