### ISSUE TITLE
[Coil 3] Introduce DiskCache scoped operation?

### ISSUE THREAD

**Issue by VDostoyevskiy** [coil-kt/coil#2000]
- Easy to use: Coil's API leverages Kotlin's language features for simplicity and minimal boilerplate.

Just to give an example
```
inline fun DiskCache.edit(key: String, crossinline block: DiskCache.Editor.() -> Unit): Boolean {
    val editor = openEditor(key) ?: return false // Or error(msg)
    editor.runCatching {
        block(this)
    }.onFailure {
        editor.abort()
        throw it
    }.onSuccess {
        editor.commit()
    }
    return true
}

inline fun <T> DiskCache.read(key: String, block: DiskCache.Snapshot.() -> T): T? = openSnapshot(key)?.use(block)
```

**Comment by colinrtwhite** [comment]
Hmm generally I prefer avoiding adding functions like these to Coil for a couple reasons:

- It creates two ways to do something. Should I prefer using `DiskCache.edit` or `DiskCache.openEditor`? Providing one way to do something makes it more intuitive and clear.
- If users prefer the `edit`/`read` syntax users can add these functions themselves. If a user prefers `openSnapshot`/`openEditor` then the extension functions just increase Coil's size.
- We have to make opinionated choices. Should `openEditor` throw if it's null? Generally I try to avoid throwing as much as possible, but this behaviour might be preferable to some users. By requiring users to handle `openEditor`'s null result, we force them to make their own decision.

**Comment by VDostoyevskiy** [comment]
Gotcha
