### ISSUE TITLE
Could not resolve io.coil-kt:coil-bom:2.4.0 for AGP 8.2.0

### ISSUE THREAD

**Issue by venkatn41** [coil-kt/coil#2023]
**Describe the bug**
Have been getting "Could not resolve io.coil-kt:coil-bom:2.4.0" when trying to upgrade to AGP 8.2.0
Same dependency is working fine for AGP 8.1.2. Tried using 2.5.0 as well. 

Error Log : 

`- Could not resolve all files for configuration ':abc:devDebugCompileClasspath'.
   - Could not resolve io.coil-kt:coil-bom:2.4.0.
     Required by:
         project :abc
      - No matching variant of io.coil-kt:coil-bom:2.4.0 was found. The consumer was configured to find a library for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:default' with value 'dev', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.2.0', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'apiElements' capability io.coil-kt:coil-bom:2.4.0 declares a component for use during compile-time:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.2.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:default (required 'dev')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'enforcedApiElements' capability io.coil-kt:coil-bom-derived-enforced-platform:2.4.0 declares a component for use during compile-time:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.2.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:default (required 'dev')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'enforcedRuntimeElements' capability io.coil-kt:coil-bom-derived-enforced-platform:2.4.0 declares a component for use during runtime:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.2.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:default (required 'dev')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'runtimeElements' capability io.coil-kt:coil-bom:2.4.0 declares a component for use during runtime:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.2.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:default (required 'dev')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
   - Could not find io.coil-kt:coil-compose:.
     Required by:
         project :abc
`

**Comment by colinrtwhite** [comment]
This is likely as you've declared the BOM as `implementation("io.coil-kt:coil-bom:2.5.0")`. Updating it to this should fix the issue:

```kotlin
implementation(platform("io.coil-kt:coil-bom:2.5.0"))
```
