### ISSUE TITLE
[Coil 3] Uri `pathSegment` generates unexpected empty segments

### ISSUE THREAD

**Issue by SimonMarquis** [coil-kt/coil#2031]
**Describe the bug**

`coil3.Uri.pathSegments` extension generates unexpected empty segments (when compared with Android's Uri).

**To Reproduce**

```kotlin
"https://example.org".toUri().pathSegments // Doesn't work at the moment because of #2029
"https://example.org/".toUri().pathSegments // [""]
"https://example.org/foo".toUri().pathSegments // ["foo"]
"https://example.org/foo/".toUri().pathSegments // ["foo", ""]
```

Android's `Uri.pathSegments` will never return empty segments, is this coil behavior on purpose?

https://github.com/coil-kt/coil/blob/9dd4ad7e14e9dd596dd7c60dad4c5b5d5ef52736/coil-core/src/commonMain/kotlin/coil3/Uri.common.kt#L29-L33

**Comment by colinrtwhite** [comment]
I don't think this is expected - we should shoot for compatibility with Android's Uri where it makes sense.
