### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by Kiru3014** [coil-kt/coil#2050]
**Describe the bug**
 I have changed my devices dates to further dates. during that time images not able to load.

**To Reproduce**
Step 1: Check System Current date to further date (1 month from current day) 
Step 2: Try to load Any image using coil lib.

Error : javax.net.ssl.SSLHandshakeException: Chain validation failed

**Version**
2.4.0 is the version i am using

**Comment by colinrtwhite** [comment]
This is [expected behaviour](https://stackoverflow.com/a/69278955/4475057) for an HTTPS API.
