### ISSUE TITLE
Support Compose Multiplatform image resources

### ISSUE THREAD

**Issue by colinrtwhite** [coil-kt/coil#2077]
**Is your feature request related to a problem? Please describe.**
We should add support to load [Compose Multiplatform image resources](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-beta01) via Coil.

**Describe the solution you'd like**
I should be able to do:

```kotlin
AsyncImage(
  model = Res.drawable.example_icon,
  contentDescription = null,
)
```

**Additional context**
I think we're probably going to have to rely on internal semantics to load these resources in customer `Fetcher`s for each platform (similar to how resources are included in the `sample:compose` app) as we can't use the generated composable functions.

This probably makes sense as an external artifact instead of being bundled with `coil-compose-core` as these `Res` classes are only necessary for Compose Multiplatform users - not Compose AndroidX users.

Open to a PR if someone wants to contribute this!

**Comment by colinrtwhite** [comment]
We could map the `Int`s to `Uri`s (similar to how we handle Android res IDs), but we'll still need a fetcher to convert the `Uri` into an `ImageSource`.

**Comment by colinrtwhite** [comment]
This is now supported as of `3.0.0-alpha10`.

**Comment by Philio** [comment]
> This is now supported as of `3.0.0-alpha10`.

Is it supposed to work with vector drawables? I tried a few and none of them displayed anything (works find with an `Image`)

**Comment by timhuang1018** [comment]
same, I try 3.0.0-alpha10 with project generated by project wizard

`
                    AsyncImage(
                        model = painterResource(Res.drawable.compose_multiplatform),
                        contentDescription = null,
                        imageLoader = ImageLoader(LocalPlatformContext.current)
                    )`
                    
will run into error:
```
kotlin.IllegalStateException: Unable to create a fetcher that supports: org.jetbrains.compose.resources.DrawableResource@318f6ee3
```

**Comment by jdvp** [comment]
@timhuang1018 way late but if you still have this issue, try
```
Res.getUri("drawable/compose_multiplatform.xml")
```
instead of 
```
Res.drawable.compose_multiplatform
```
for the model parameter
(or whatever the file is called). I had issues loading an svg the way you mentioned but found that using `Res.getUri` seemed to work for me

**Comment by colinrtwhite** [comment]
@jdvp @Monabr It's not possible for Coil to support `Res.drawable` resources with the current APIs provided by Compose Multiplatform because there is no API to convert a `DrawableResource` into either a `Uri` or bytes. You must use `Res.getUri`

If you would like this functionality please follow [this ticket](https://youtrack.jetbrains.com/issue/CMP-4360).

**Comment by cy745** [comment]
```kotlin
@OptIn(ExperimentalResourceApi::class)
private val drawableReverseMap = Res.allDrawableResources
    .entries.associate { it.value to it.key }

@OptIn(ExperimentalResourceApi::class)
fun DrawableResource.toUri(): String? {
    val key = drawableReverseMap[this] ?: return null
    val ext = listOf(
        "webp",
        "jpg",
        "png",
        "jpeg"
    ) // "xml" while using xml: Failed to create image decoder with message 'unimplemented'Input contained an error.
    var uri: String? = null

    for (s in ext) {
        uri = runCatching { Res.getUri("drawable/${key}.$s") }.getOrNull()
        if (!uri.isNullOrBlank()) break
    }

    return uri
}
```

try this, replace the `Res` reference to your specify module's one, it runs well on android but have not tested on IOS. @Monabr

**Comment by adamglin0** [comment]
https://youtrack.jetbrains.com/issue/CMP-7487/Compose-Resources-An-additional-parameter-needs-to-be-added-to-DrawableResource-to-obtain-the-Uri
