### ISSUE TITLE
ImageLoader in Compose

### ISSUE THREAD

**Issue by DavidUps** [coil-kt/coil#2083]
**Describe the bug**
In XML you can change the okHttpClient:
`val imageLoader = ImageLoader.Builder(view)
                .okHttpClient { UnsafeClient.getPicassoUnsafeClient() }.build()`

But in compose I can't find any documentation of how to do it. I try to get more deep with `ImageRequest` but i don't find nothing

**Version**
(io.coil-kt:coil-compose:2.5.0)

**Comment by colinrtwhite** [comment]
There isn't a Compose-specific API to set the image loader in Coil 2.x. You'll have to use an `Application` factory or `Coil.set`: https://coil-kt.github.io/coil/getting_started/#image-loaders

**Comment by DavidUps** [comment]
the way to do it is the next:

`
val loader = ImageLoader.Builder(LocalContext.current)
                    .okHttpClient { Client() }
                    .build()

                AsyncImage(
                    model = ImageRequest
                        .Builder(LocalContext.current)
                        .data("url").crossfade(true)
                        .networkCachePolicy(CachePolicy.DISABLED)                     
                        .build(),
                    imageLoader = loader, 
                    contentDescription = "info",
                    contentScale = ContentScale.Crop,
                )`
                
But there aren't any kind of documentation, please add for the future same that https://coil-kt.github.io/coil/recipes/#using-a-custom-okhttpclient

**Comment by colinrtwhite** [comment]
@DavidUps It's recommended to set it with an `Application` factory like in the docs I linked above. With your current example you'll create a new `ImageLoader` for each composition, which is expensive.
