### ISSUE TITLE
Can't resolve depends

### ISSUE THREAD

**Issue by shmezi** [coil-kt/coil#2089]
**Describe the bug**
I've tried a few times with a few different versions but can't seem to get it to work ( gradle kts).
I have mavenCentral(), ive also tried using the bom and still cant get it to work. I am currently on java 19.
**Logs/Screenshots**
Could not resolve: io.coil-kt:coil:2.5.0
Could not resolve: io.coil-kt:coil-compose:2.5.0
Could not resolve: io.coil-kt:coil:2.5.0
Could not resolve: io.coil-kt:coil-compose:2.5.0

**Version**
2.5.0 java 19

**Comment by colinrtwhite** [comment]
Sorry, I can't help with local build issues, but [it is on maven central](https://search.maven.org/search?q=g:io.coil-kt).
