### ISSUE TITLE
Asynchronous initialization of ImageLoader

### ISSUE THREAD

**Issue by mlykotom** [coil-kt/coil#2097]
**Is your feature request related to a problem? Please describe.**
In Now in Android we had the `Application` implement `ImageLoaderFactory` and initialize the `ImageLoader` with the `newImageLoader()` method.
We realised that the initialization happens on the **main thread** with the composition of the first image on screen, which causes some frames to be skipped (~15ms on Pixel 6 in `benchmark` build).

What we did was to start initialization of Coil on a background thread and in case it'd take too long, block the first image to wait for the initialization (https://github.com/android/nowinandroid/pull/1190).

**Describe the solution you'd like**

I think it's not 100% obvious that Coil will initialize on the main thread and given it's initializing OkHttp, it may take significant time to do so.

a) Could there be a similar way baked-in to Coil to do initialization in a non-blocking way?
b) Should this be documented in the documentation so that people are aware this might happen?
c) ?

**Additional context**
![image](https://github.com/coil-kt/coil/assets/3973717/fd725c0e-1126-469f-a1ef-4de835cc4cb5)

**Comment by colinrtwhite** [comment]
It looks like you were initializing your `OkHttpClient` eagerly [here](https://github.com/android/nowinandroid/pull/1190/files#diff-580d68f5de901c1f87e9a17ad52e4782efa2ce6dc65d32d39f73f9bc72bbb477L78). Coil already supports lazy initialization of the `OkHttpClient` using the `ImageLoader.Builder.callFactory { }` function that accepts a callback.

It's not possible to initialize `ImageLoader` asynchronously as it needs to be created when a request is started to manage the image request's lifecycle. Though in practice I don't think this is an issue. The `OkHttpClient` and `DiskCache` are all created lazily on a background thread. I'd be curious to see what else is taking up the bulk of the initialization time as everything else should be pretty quick.

**Comment by colinrtwhite** [comment]
I ran a quick benchmark on a Pixel 7 emulator and an `ImageLoader` with default arguments takes 0.1 milliseconds to initialize. Here's the code:

```kotlin
val iterations = 1_000
var sum = 0L
var imageLoader: ImageLoader?
repeat(iterations) {
    sum += measureNanoTime {
        imageLoader = ImageLoader(context)
    }
    imageLoader?.shutdown()
}
println("BENCHMARK OUTPUT: ${sum / iterations.toDouble()}")
```

**Comment by mlykotom** [comment]
There's a couple of problems measuring the timing this way:
1. In general, you shouldn't measure performance on emulator as this way you effectively measure how powerful hosting machine you have
2. This way, you are can be hitting all the system caches, which doesn't show in the real app.

What I did to benchmak this, was using Macrobenchmark in the real app with `StartupMode.COLD` to see the worst-case scenario.

For 10 iterations, I see these results
```
NiaImageLoaderMs                        min     2.0,   median     4.2,   max     6.9
Traces: Iteration 0 1 2 3 4 5 6 7 8 9
```

I further started digging into what's happening and I think I know now.

I followed you advice to only have `OkHttp` asynchronously, but keep the `ImageLoader` on-demand and this is what I see in the traces.

When the first image is shown on screen (in NIA it's the `SingleTopicButton`), it starts to initialize Coil, which takes ~7ms.
If this was during startup, it wouldn't be much of an issue, but with a first composition, it might be problematic ([trace here](https://ui.perfetto.dev/#!/?s=f205ecf4f09356af3237cfa760e668962faa3005ce7ba9e88fda1a704791c351)).

<img width="539" alt="image" src="https://github.com/coil-kt/coil/assets/3973717/d32f55bf-5a4b-4fe5-8e3a-987a61ef34df">

The cause are (my hypothesis) the `binder transaction` sections, which comes from the [`SystemCallbacks`](https://github.com/coil-kt/coil/blob/main/coil-core/src/androidMain/kotlin/coil3/util/SystemCallbacks.kt).

I think Coil should be able to register the system services on a `Default` thread to prevent the initialization hit and then it won't matter when the `ImageLoader` is actually initialized.

**Comment by colinrtwhite** [comment]
Fixed [here](https://github.com/coil-kt/coil/pull/2104) in the 3.x release. I'll also backport the change to the next release, `2.6.0`.

I tried running my own macrobenchmark test after the changes, but the initialization method didn't appear in the measured methods.

**Comment by mlykotom** [comment]
Awesome! Thanks! 🎉 

If you'd like to help diagnose the macrobenchmark tests, maybe ping me on ASG?

**Comment by yschimke** [comment]
PR for a cautionary fix on OkHttp 5.x

https://github.com/square/okhttp/pull/8248/files
