### ISSUE TITLE
How to CustomTarget<Bitmap> Listener

### ISSUE THREAD

**Issue by khaleeljageer** [coil-kt/coil#21]
Trying to implement Coil on my existing application where Glide already using.
Need to achieve this...

        val bitmapTarget = object : CustomTarget<Bitmap>(DeviceUtils.dpToPx(282), DeviceUtils.dpToPx(159)) {
            override fun onLoadCleared(placeholder: Drawable?) {

            }

            override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                if (activity != null && isAdded) {
                    row.setImageBitmap(mContext, resource)
                    arrayAdapter!!.notifyArrayItemRangeChanged(0, arrayAdapter!!.size())
                }
            }
        }
        GlideApp.with(mContext)
            .asBitmap()
            .load(thumbImage)
            .into(bitmapTarget)

**Comment by colinrtwhite** [comment]
The recommended way to do this is cast the returned `Drawable` to a `BitmapDrawable`. Glide does this cast internally when you call `asBitmap`:

```kotlin
Coil.load(context, thumbImage) {
    size(DeviceUtils.dpToPx(282), DeviceUtils.dpToPx(159))
    target { result ->
        if (activity != null && isAdded) {
            row.setImageBitmap(mContext, (result as BitmapDrawable).bitmap)
            arrayAdapter!!.notifyArrayItemRangeChanged(0, arrayAdapter!!.size())
        }
    }
}
```
