### ISSUE TITLE
Coil won't show cached response for 201 when offline

### ISSUE THREAD

**Issue by mario** [coil-kt/coil#214]
**Describe the bug**
1) Use Coil master (or 0.8)
2) Load an image from an endpoint that generates 201
3) Close the app and go Airplane mode
4) Open the app and see all other images loaded from cache except the one that got 201 as response previously

**Expected behavior**
Everything should be cached if we've got the image and the result shown.

**To Reproduce**
I understand that OKHttp is used for caching, but this behaviour seems off somewhere. Since I'm not familiar with Coil that intimately yet, I thought I'd ask.

**Comment by colinrtwhite** [comment]
Thanks for the report. Sounds like it might be an issue with [NetworkObserver](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/network/NetworkObserver.kt). I'll take a look next week if no one beats me to it.

**Comment by mario** [comment]
Just to be clear - I've looked into the OKHttp cache files and it's indeed missing the cache entries for responses which have 201 as response code - why? Dunno, it baffles me as 201 is also a succesful response in all the standard book.

**Comment by mario** [comment]
OkHttp does not cache 201.

https://github.com/square/okhttp/blob/24413c1bbf675d63b07fab3ed7a4acfe1a45cf0a/okhttp/src/test/java/okhttp3/CacheTest.java#L108

Sorry for the hassle - I've managed to workaround this by means of Network interceptor and rewriting the response code.

If anyone comes along this problem:

```
    httpClient.addNetworkInterceptor { chain ->
        var response = chain.proceed(chain.request())

        if (response.code() == 201) {
            response = response.newBuilder().code(200).build()
        }

        response
    }
```
