### ISSUE TITLE
Crashing when trying to load image.9.png using coil compose function rememberAsyncImagePainter

### ISSUE THREAD

**Issue by takmilul** [coil-kt/coil#2160]
**Description**
My app is crashing when I use a 9 patch image in coil function rememberAsyncImagePainter to load a placeholder image in Android 5, and 6 devices. Is there any solution to fix the issue for older devices? it starts with the following error message.
android.graphics.drawable.NinePatchDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

**Logs**
android.graphics.drawable.NinePatchDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
androidx.compose.ui.res.ResourceResolutionException: Error attempting to load resource: res/drawable-night-xhdpi-v8/placeholder.9.png
    androidx.compose.ui.res.ResourceResolutionException.<init>(ResourceResolutionException.java:121)
    androidx.compose.ui.res.PainterResources_androidKt.loadImageBitmapResource(PainterResources.android.kt:111)
    androidx.compose.ui.res.PainterResources_androidKt.access$loadImageBitmapResource(PainterResources.android.kt:1)
    androidx.compose.ui.res.PainterResources_androidKt.painterResource(PainterResources.android.kt:70)
    com.example.test.util.CoilUtils.getAsyncImagePainter-ycFWDq0(CoilUtils.kt:40)

**Version**
Coil version: 2.5.0

**Comment by colinrtwhite** [comment]
It looks the stack trace doesn't contain any Coil classes and you're calling `painterResource`, which is performing the hard cast to a `BitmapDrawable`. To load a resource using `rememberAsyncImagePainter` use:

```
val painter = rememberAsyncImagePainter(R.drawable.my_image)
```

**Comment by aa563011992** [comment]
If you use `val painter = rememberAsyncImagePainter(R.drawable.my_image)`, the stretching information of the .9 image will be lost. @colinrtwhite 
version:3.4.0,
If you use `rememberAsyncImagePainter(ContextCompat.getDrawable(context, R.mipmap.ic_btn_bg))`, an infinite recursion loop will occur
