### ISSUE TITLE
Excessive API Calls in Image Loading with RecyclerView When Using custom fetcher

### ISSUE THREAD

**Issue by IntelliJAbhishek** [coil-kt/coil#2165]
I'm experiencing a problem where the Coil image loading library, specifically with a custom fetcher, is making excessive API calls when loading images within a RecyclerView. Despite implementing caching mechanisms, the API is being called repeatedly, leading to performance issues and unnecessary network usage.

I've written a custom fetcher because I'm obtaining the image IDs from my backend, and based on these IDs, I need to call an API to fetch the corresponding images.

**Steps to Reproduce:**
- Set up a RecyclerView to display a list of images using Custom ImageIdFetcher.
- Scroll rapidly through the list of images, triggering image loading for multiple items.
- Monitor network requests and observe the frequency of API calls being made.

**Expected Behavior:**
The image loading library should efficiently cache images and avoid redundant API calls, especially when scrolling rapidly through a list of items in a RecyclerView.

**Actual Behavior:**
The library is making excessive API calls, even after implementing caching mechanisms, resulting in performance degradation and increased network usage.

**Version**
Coil Version : 2.6.0

**Custom Fetcher Code**

       import android.util.Base64
        import coil.ImageLoader
        import coil.annotation.ExperimentalCoilApi
        import coil.decode.DataSource
        import coil.decode.ImageSource
        import coil.disk.DiskCache
        import coil.fetch.FetchResult
        import coil.fetch.Fetcher
        import coil.fetch.SourceResult
        import coil.request.Options
        import com.myapp.core.extension.isNotNullOrBlank
        import com.myapp.core.functional.Either
        import com.myapp.features.model.common.fileUpload.GetImageRequest
        import com.myapp.features.ui.common.usecases.GetImageById
        import com.myapp.features.utils.ImageID
        import okhttp3.internal.closeQuietly
        import okio.Buffer
        import java.nio.ByteBuffer
    
        @OptIn(ExperimentalCoilApi::class)
        class ImageIdFetcher(
            private val imageId: String,
            private val options: Options,
            private val diskCache: DiskCache?,
            private val getImageById: GetImageById,
        ) : Fetcher {
        
            override suspend fun fetch(): FetchResult {
                var snapshot = readFromDiskCache()
                try {
                    // Fast path: fetch the image from the disk cache without performing a network request.
                    if (snapshot != null) {
                        return SourceResult(
                            source = snapshot.toImageSource(),
                            dataSource = DataSource.DISK,
                            mimeType = null,
                        )
                    }
                    val response = getImageById(GetImageRequest(imageId))
                    val base64String =
                        if (response is Either.Success) response.value.data?.data else null
                    if (!base64String.isNullOrBlank()) {
                        snapshot = writeToDiskCache(snapshot, base64String)
                        if (snapshot != null) {
                            return SourceResult(
                                source = snapshot.toImageSource(),
                                dataSource = DataSource.NETWORK,
                                mimeType = null,
                            )
                        }
                    }
                    val byteBuffer = ByteBuffer.wrap(Base64.decode(base64String, Base64.DEFAULT))
                    val source = Buffer().apply { write(byteBuffer) }
                    return SourceResult(
                        source = ImageSource(source, options.context),
                        dataSource = DataSource.NETWORK,
                        mimeType = null
                    )
                } catch (e: Exception) {
                    snapshot?.closeQuietly()
                    throw e
                }
            }
        
        
            private fun readFromDiskCache(): DiskCache.Snapshot? {
                return if (options.diskCachePolicy.readEnabled) {
                    diskCache?.openSnapshot(diskCacheKey)
                } else {
                    null
                }
            }
        
            private fun writeToDiskCache(
                snapshot: DiskCache.Snapshot?,
                response: String,
            ): DiskCache.Snapshot? {
                // Short circuit if we're not allowed to cache this response.
                if (!options.diskCachePolicy.writeEnabled) {
                    snapshot?.closeQuietly()
                    return null
                }
                // Open a new editor.
                val editor = if (snapshot != null) {
                    snapshot.closeAndOpenEditor()
                } else {
                    diskCache?.openEditor(diskCacheKey)
                }
        
                // Return `null` if we're unable to write to this entry.
                if (editor == null) return null
        
                try {
                    fileSystem.write(editor.data) {
                        val imgBytesData = Base64.decode(response, Base64.DEFAULT)
                        this.write(imgBytesData)
                    }
                    return editor.commitAndOpenSnapshot()
                } catch (e: Exception) {
                    editor.abortQuietly()
                    throw e
                }
            }
        
            private fun DiskCache.Editor.abortQuietly() {
                try {
                    abort()
                } catch (_: Exception) {
                }
            }
        
            private fun DiskCache.Snapshot.toImageSource(): ImageSource {
                return ImageSource(data, fileSystem, diskCacheKey, this)
            }
        
            private val diskCacheKey
                get() = options.diskCacheKey
                    ?: "code:${imageId};width:${options.size.width};height:${options.size.height}"
        
            private val fileSystem get() = diskCache!!.fileSystem
        
            class Factory(private val getImageById: GetImageById) : Fetcher.Factory<ImageID> {
        
                override fun create(data: ImageID, options: Options, imageLoader: ImageLoader): Fetcher? {
                    if (!isApplicable(data)) return null
                    return ImageIdFetcher(data.value!!, options, imageLoader.diskCache, getImageById)
                }
        
                private fun isApplicable(data: ImageID): Boolean {
                    return data.value.isNotNullOrBlank()
                }
            }
        }

**Comment by colinrtwhite** [comment]
Please include a small sample project that reproduces this issue. I can't offer much help without a way to debug the issue.

The sample app in this repo has a similar list of images that caches as expected so it's possible the issue could be with some custom code.

**Comment by IntelliJAbhishek** [comment]
Hi @colinrtwhite 

It is not possible for me to provide sample as API's are having lot's of sensitive header information and encryption.
Only I tell my code is going inside catch block and exception is `kotlinx.coroutines.JobCancellationException: DeferredCoroutine was cancelled` and this exception is coming again n again.

**Comment by colinrtwhite** [comment]
Sorry I can't provide more help without a way to reproduce the issue.

**Comment by nikclayton** [comment]
@IntelliJAbhishek Your `try ... catch` block is catching all exceptions, including the cancellation exception Kotlin uses for structured concurrency.

Where you have code like:

``kotlin
            } catch (e: Exception) {
                snapshot?.closeQuietly()
                throw e
            }
```

in a coroutine you probably want to replace that with:

```kotlin
            } catch (e: Exception) {
                coroutineContext.ensureActive()
                snapshot?.closeQuietly()
                throw e
            }
```

More details in https://betterprogramming.pub/the-silent-killer-thats-crashing-your-coroutines-9171d1e8f79b
