### ISSUE TITLE
2.6.0 AsyncImage doesn't work on AndroidStudio - Attempted all variants

### ISSUE THREAD

**Issue by ganeshmal5** [coil-kt/coil#2172]
**Describe the bug**
A clear and concise description of what the bug is. **Please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.** Bug reports without reproduction steps are likely to be closed.
I'm trying to load a plain simple image in my application, but it doesn't work. I have imported 2.6.0 coil-compose.
I have tried with
1. AsyncImage
2. Image with rememberasyncimagepainter

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.
Create a plain Android project. Import coil-compose:2.6.0. Have AsyncImage with a image url and check if it's loads on preview or emulator

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.
![image](https://github.com/coil-kt/coil/assets/41984515/261dd218-a2f0-4d4c-b4ac-dffd5eb1060d)

@Preview(showBackground = true)
@Composable
fun Default1Preview() {
    MyApp {

        val movieurl = "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg";
        Surface(modifier = Modifier.fillMaxSize()) {

//            val painter = rememberAsyncImagePainter(
//                model = ImageRequest.Builder(LocalContext.current)
//                    .data(movieurl)
//                    .size(Size.ORIGINAL) // Set the target size to load the image at.
//                    .build()
//            )
//
//            if (painter.state is AsyncImagePainter.State.Success) {
//                // This will be executed during the first composition if the image is in the memory cache.
//            }
//
//            Image(
//                painter = painter,
//                contentDescription = "Hello"
//            )
//            AsyncImage(
//                model = ImageRequest.Builder(LocalContext.current)
//                    .data(movieurl)
//                    .crossfade(true)
//                    .build(),
//                placeholder = painterResource(R.drawable.ic_launcher_background),
//                contentDescription = "movie",
//                contentScale = ContentScale.Crop,
//                modifier = Modifier.clip(CircleShape)
//            )
//            AsyncImage(model = movieurl, contentDescription = "Hi")
            val newurl = "https://images.pexels.com/photos/20483533/pexels-photo-20483533/free-photo-of-woman-posing-by-the-river-in-black-and-white.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
            AsyncImage(
                    model = newurl,
                    contentDescription = "Movie Poster",
                    modifier = Modifier.fillMaxSize(),
                    contentScale = ContentScale.Fit
                )
        }
    }
}

Note: The commented codes are few things that I've tested. And it doesn't work.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?
Emulator: Pixel 3a API 34
Android Studio Hedgehog | 2023.1.1 Patch 2

**Comment by colinrtwhite** [comment]
This is expected behaviour. See: https://github.com/coil-kt/coil/issues/1915

**Comment by ganeshmal5** [comment]
It's not only on the Preview. It doesn't load on the emulator as well.
Emulator: Pixel 3a API 34
