### ISSUE TITLE
no image when changing image in Jetpack Compose

### ISSUE THREAD

**Issue by akardas16** [coil-kt/coil#2179]
**Describe the bug**
When changing image URL in compose, process is going **old image -> nothing -> new image**. What I would expect is if new image is not loaded, still show old image, if it is loaded show new image.

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?

**Comment by akardas16** [comment]
https://github.com/coil-kt/coil/assets/28716129/108e1f91-16c2-4657-96a1-ea36e6ed6848

**Comment by colinrtwhite** [comment]
This is expected behaviour. You'll need to use the current image as a `placeholder` for the second request. You can grab the image from the first request using `onSuccess`.
