### ISSUE TITLE
Support retrieving video image by frame index on VideoFrameDecoder

### ISSUE THREAD

**Issue by tnj** [coil-kt/coil#2180]
**Is your feature request related to a problem? Please describe.**
There is no way to decode an image by its frame index using coil-video.

MediaMetadataRetriever has [getFrameAtIndex](https://developer.android.com/reference/android/media/MediaMetadataRetriever#getFrameAtIndex(int,%20android.media.MediaMetadataRetriever.BitmapParams)) that is added on API 28, but it is not implemented on `VideoFrameDecoder` yet.

**Describe the solution you'd like**
Add a video frame index option to `VideoFrameDecoder` in addition to the current `videoFrameMillis`, `videoFrameMicros` and `videoFramePercent`

**Additional context**
I've implemented this for my project https://github.com/coil-kt/coil/compare/main...tnj:coil:video-index-support

**Comment by colinrtwhite** [comment]
Thanks, your branch looks good. Feel free to submit it as a PR!
