### ISSUE TITLE
AsyncImagePainter should use `rememberCoroutineScope`

### ISSUE THREAD

**Issue by ansman** [coil-kt/coil#2181]
**Is your feature request related to a problem? Please describe.**
Currently, `AsyncImagePainter` uses `Dispatchers.Main.immediate`. This normally works fine but during Paparazzi screenshot tests they use a custom dispatcher for composables to synchronize time.

**Describe the solution you'd like**
If possible `AsyncImagePainter` should use `rememberCoroutineScope` instead.

**Comment by ansman** [comment]
As long as `rememberCoroutineScope()` handles it

**Comment by colinrtwhite** [comment]
@tamimattafi That is intended behaviour and not a bug. See [here](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-main.html) and [here](https://github.com/coil-kt/coil/issues/2009).

**Comment by tamimattafi** [comment]
@colinrtwhite Thank you, I already added swing but still getting the error, it seems like some other library is overriding the main dispatched, will look into it.
