### ISSUE TITLE
I imported compose but AsyncImage doesn't load!

### ISSUE THREAD

**Issue by franquicidad** [coil-kt/coil#2182]
Hello I added into my Gradle as follows. Both are 2.5 I didnt add 2.6 because I wanted to see if it was the new version the problem.

<img width="681" alt="Screenshot 2024-03-25 at 1 21 25 PM" src="https://github.com/coil-kt/coil/assets/28768991/f1cb6fa9-cfcd-4b9f-8ecf-6a4cd59bf546">

<img width="557" alt="Screenshot 2024-03-25 at 1 21 05 PM" src="https://github.com/coil-kt/coil/assets/28768991/bd7d9cef-5922-4625-b86d-4bad5a8b3b36">

Build is successful.
<img width="521" alt="Screenshot 2024-03-25 at 1 24 35 PM" src="https://github.com/coil-kt/coil/assets/28768991/09a544ff-bbf0-4923-9157-442e040df743">

As you can see I can't use AsyncImage.

<img width="628" alt="Screenshot 2024-03-25 at 1 23 31 PM" src="https://github.com/coil-kt/coil/assets/28768991/0736ff98-eddf-4d99-84ff-c6487bbb895e">

**Comment by colinrtwhite** [comment]
Sorry I can't help with local build issues.
