### ISSUE TITLE
[Coil 3] Heap corruption detected when returning from an Interceptor in iOS

### ISSUE THREAD

**Issue by realcbnewham** [coil-kt/coil#2185]
**Describe the bug**

In Kotlin Native, when returning an image from a cached image file in a custom Interceptor, Heap corruption detected is reported and the process terminates. The file being returned (as an Image from a bitmap.asCoilImage() ) reports the correct width, height and size in a debug println().

I have the AsyncImage() in a Compose page that is not immediately displayed on start up. If I choose the page and display it immediately after the app starts up then the image is displayed correctly. If I leave it for several seconds before displaying the page then the app crashes with the error. This indicates perhaps something is being freed a few seconds after Coil is set up.

I set up Coil as:

```
val imageLoader = ImageLoader.Builder(PlatformContext.INSTANCE)
        .components {
            add(interceptor)
            add(s3ImageFetcherFactory)
        }
        .build()

    SingletonImageLoader.setUnsafe(imageLoader)
```

I have made interceptor and s3ImageFetcherFactory global, just to be sure the references remained without garbage collection and I can rule it out as a cause. The Fetcher works as expected and downloads the image (the first time) from S3 and it is displayed correctly. Subsequently the image is stored on disk and it is then that the problems start as detailed.

I do note that .setUnsafe() is a "delicate Coil API", but I have no idea how an ImageLoader is otherwise supposed to be set in Coil 3. But as I said, the Fetcher works correctly.

**To Reproduce**

Create a custom class implementing Interceptor, then override:

`override suspend fun intercept(chain: Interceptor.Chain): ImageResult`

Then:

```
readSkiaBitmapFromPath(cacheFullPath)!!.asCoilImage().let { cachedImage ->
                println("Delivering image from file cache.")

                println("cachedImage: height=${cachedImage.height}  width=${cachedImage.width}  size=${cachedImage.size}")

                return SuccessResult(
                    image = cachedImage,
                    request = chain.request,
                    dataSource = DataSource.DISK,
                    diskCacheKey = key
                )
            }

```
**Logs/Screenshots**

The following is printed to the console:
Delivering image from file cache.

cachedImage: height=240  width=180  size=172800

Keyholder(2318,0x203d63f00) malloc: Heap corruption detected, free list is damaged at 0x300d38320

*** Incorrect guard value: 12898746368

**Version**
Coil version 3.0.0-alpha06
Kotlin version 1.9.23
Compose version 1.6.4

**Comment by colinrtwhite** [comment]
Thanks for the heads up. I wasn't able to reproduce this locally in my tests either unfortunately. Let's close this for now and open a new issue that links to this ticket if it pops back up.
