### ISSUE TITLE
SVG href or xlink:href not working

### ISSUE THREAD

**Issue by MKelman** [coil-kt/coil#2189]
**Describe the bug**
Trying to bring in an SVG image from a web url that contains either href or xlink:href is not displaying an image. 

**To Reproduce**
Use any image with href or xlink:href and try to call that image into a browser and try to call that image from your phone that has coil svg. Here is an example svg below.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?
tried on 2.4.0 and 2.5.0

![testttt](https://github.com/coil-kt/coil/assets/10063610/e2887ae0-2d76-480f-9e35-22c728272f10)

**Comment by colinrtwhite** [comment]
Please report this to [`androidsvg`](https://github.com/BigBadaboom/androidsvg), which is the underlying SVG renderer used by Coil.
