### ISSUE TITLE
[Coil 3] `ImageLoaderFactory` + Dependency Injection (missing docs?)

### ISSUE THREAD

**Issue by langsmith** [coil-kt/coil#2190]
**Describe the bug**

@colinrtwhite , I'm trying to upgrade my project to Coil 3 but not sure how to handle the unavailability of `ImageLoaderFactory`.  Per the instructions at https://coil-kt.github.io/coil/image_loaders/#singleton-vs-dependency-injection, I was doing 👇🏽  in my custom `Application` class.

<img width="673" alt="318490595-c9a76a08-0b59-4be9-9466-27cca43b7337" src="https://github.com/coil-kt/coil/assets/4394910/c0d081bd-bca2-4343-9908-0a3f988fd5cd">

However, when I upgraded to Coil `3.0.0-alpha06`, `ImageLoaderFactory` was no longer available. The docs don't seem to be updated for this change. 

- Docs at  https://coil-kt.github.io/coil/image_loaders/#singleton-vs-dependency-injection need updating? 

- Needs to be mention of `ImageLoaderFactory` removal in https://coil-kt.github.io/coil/upgrading_to_coil3  and/or https://github.com/coil-kt/coil/blob/main/CHANGELOG.md ?

@colinrtwhite , any thoughts on how I can recreate my custom `Application` class setup with Coil `3.0.0-alpha06`?

**To Reproduce**

Convert a project using Coil's `2.6.0` version to Coil 3.x

See that `ImageLoaderFactory` is no longer available.

**Logs/Screenshots**

**Version**

3.0.0-alpha06

**Comment by langsmith** [comment]
I guess the new version is `SingletonImageLoader.Factory`?

**Comment by colinrtwhite** [comment]
Yep, you'll want to use `SingletonImageLoader.Factory` as a replacement for `ImageLoaderFactory`. The main docs haven't been updated yet since their APIs are still subject to change. We could add a note to https://coil-kt.github.io/coil/upgrading_to_coil3/ calling out the change (PR welcome).

**Comment by langsmith** [comment]
Ok, thanks for confirming, @colinrtwhite . Will try to open a pr in the next couple of days when I have some down time.

**Comment by langsmith** [comment]
and for anyone else reading this, here's what is working for me

```kotlin
@HiltAndroidApp
class CustomApplication : Application(), SingletonImageLoader.Factory {...
```

and then 

```kotlin
 override fun newImageLoader(context: PlatformContext): ImageLoader = ImageLoader.Builder(this)
        .crossfade(true)
        .also {
            if (BuildConfig.DEBUG) {
                it.logger(DebugLogger())
            }
        }
        .build()
```

**Comment by langsmith** [comment]
> Will try to open a pr in the next couple of days when I have some down time.

It's been more than a couple of days since April 2024, but I finally got around to it 😄 

https://github.com/coil-kt/coil/pull/2559

**Comment by leinardi** [comment]
Hi @langsmith, after migrating to`SingletonImageLoader.Factory` I'm struggling to find a way to set the `.okHttpClient { okHttpClient }` like it was possible in Coil 2:

```kotlin
    override fun newImageLoader(): ImageLoader = ImageLoader.Builder(this)
        .memoryCache {
            MemoryCache.Builder(this)
                .maxSizePercent(COIL_MEMORY_CACHE_SIZE_PERCENT)
                .build()
        }
        .diskCache {
            DiskCache.Builder()
                .directory(filesDir.resolve(COIL_DISK_CACHE_DIRECTORY_NAME))
                .maxSizeBytes(COIL_DISK_CACHE_SIZE)
                .build()
        }
        .okHttpClient { okHttpClient }
        .crossfade(true)
        // Ignore the network cache headers and always read from/write to the disk cache.
        .respectCacheHeaders(false)
        // Enable logging to the standard Android log if this is a debug build.
        .apply {
            if (BuildConfig.DEBUG) {
                logger(DebugLogger(Log.VERBOSE))
            }
        }
        .build()
```
Is there a new way to do it?

**Comment by leinardi** [comment]
I think I found a way, does this look ok?
```kotlin
    override fun newImageLoader(context: PlatformContext): ImageLoader = ImageLoader.Builder(context)
        .memoryCache {
            MemoryCache.Builder()
                .maxSizePercent(context, COIL_MEMORY_CACHE_SIZE_PERCENT)
                .build()
        }
        .diskCache {
            DiskCache.Builder()
                .directory(filesDir.resolve(COIL_DISK_CACHE_DIRECTORY_NAME).toOkioPath())
                .maxSizeBytes(COIL_DISK_CACHE_SIZE)
                .build()
        }
        .components { add(OkHttpNetworkFetcherFactory(callFactory = { okHttpClient })) }
        .crossfade(true)
        // Enable logging to the standard Android log if this is a debug build.
        .apply {
            if (BuildConfig.DEBUG) {
                logger(DebugLogger(Logger.Level.Verbose))
            }
        }
        .build()
```

**Comment by langsmith** [comment]
@leinardi , I've been blessed to never have to deal with custom OkHttp and cache setups, so I'm afraid I can't help much in this area. Your setup generally looks good though.

You've probably already seen it, but if not, FYI about this docs section: https://coil-kt.github.io/coil/recipes/#using-a-custom-okhttpclient
