### ISSUE TITLE
[Coil 3] ImageRequest.Builder.crossfade(enable: Boolean) ignores argument

### ISSUE THREAD

**Issue by Ribesg** [coil-kt/coil#2192]
**Describe the bug**
`ImageRequest.Builder.crossfade(enable: Boolean)` has the following implementation:
```kotlin
actual fun ImageRequest.Builder.crossfade(enable: Boolean) =
    crossfade(DEFAULT_CROSSFADE_MILLIS)
```
This is very weird. It should either take the argument into account, or not have an argument at all.
Right now you can call `.crossfade(false)` and it enables it.

**Version**
3.0.0-alpha06

**Comment by colinrtwhite** [comment]
Good catch! Fixed here: https://github.com/coil-kt/coil/issues/2192
