### ISSUE TITLE
AsyncImage cancels image request when onDispose? Which version is good?

### ISSUE THREAD

**Issue by nakhmedovonline** [coil-kt/coil#2196]
AsyncImage cancels image request when onDispose? Which version is good?

1. 

     fun LoadImage(url: String) {
    // Creates a Coil ImageLoader
    val imageLoader = LocalContext.current.imageLoader
    
    // Creates a mutable state to update the image result
    val imageResult = remember(url) { mutableStateOf<ImageResult?>(null) }
    
    // Launch effect coroutine and handle cancellation/remember lifecycle
    LaunchedEffect(url) {
        val disposable = imageLoader.enqueue(
            ImageRequest.Builder(LocalContext.current)
                .data(url)
                .target(
                    onStart = { /* handle start */ },
                    onSuccess = { result -> imageResult.value = result },
                    onError = { /* handle error */ }
                )
                .build()
        )

        // Cancel request on compose disposal
        onDispose {
            if (!disposable.isDisposed) {
                disposable.dispose()
            }
        }
    }

    // use imageResult
}

2. 

@Composable
fun CustomImage(
    data: Any,
    modifier: Modifier = Modifier,
) {
    val context = LocalContext.current
    val request = remember(context, data) {
        ImageRequest.Builder(context = context)
            .data(data = data)
            .crossfade(true)
            .build()
    }
    AsyncImage(
        model = request,
        modifier = modifier,
    )
}

_Originally posted by @nakhmedovonline in https://github.com/coil-kt/coil/discussions/2195_

**Comment by colinrtwhite** [comment]
Please do not repost questions in the issue tracker.
