### ISSUE TITLE
Forcing JVM target 1.8 causes incompatibility with Android SDK < 24

### ISSUE THREAD

**Issue by blazeroni** [coil-kt/coil#22]
**Describe the bug**
Since Coil uses JVM target 1.8, this must be used in the application project as well.  However, setting that target JVM can cause the Kotlin compiler to generate byte code that incompatible with Android SDK versions less than 24.  See https://youtrack.jetbrains.com/issue/KT-19968.

**To Reproduce**
Use code similar to the code in the linked Kotlin issue.  Try to run on a device with SDK version < 24.

**Expected behavior**
No hashCode related errors.

**Logs/Screenshots**
```
java.lang.NoSuchMethodError: No static method hashCode(J)I in class Ljava/lang/Long; or its super classes (declaration of 'java.lang.Long' appears in /system/framework/core-libart.jar)
```

**Library version**
0.6.0

**Comment by colinrtwhite** [comment]
Which Android Gradle Plugin version are you using? I believe if you're using the latest stable version (`3.4.2`) or greater D8 should be able to desugar the hashCode methods.

Coil follows suite from OkHttp, which [added this requirement](https://square.github.io/okhttp/upgrading_to_okhttp_4/#gradle) a few months ago.

**Comment by blazeroni** [comment]
Ah, we're using `3.4.0`.  Thanks for the heads up!
