### ISSUE TITLE
Optimize placeholder and error

### ISSUE THREAD

**Issue by mario** [coil-kt/coil#220]
I use the following syntax to set both the placeholder and an error:

```
                                    placeholder(drawable)
                                    error(drawable)
```

Note that they are the same. What happens though is the following:

- Placeholder is set
- Loading of URL fails thus setting the error drawable WHICH Is the same causing the UI to refresh

Any way we can avoid setting the drawable again if they're the same? That would make for a nicer experience.

**Comment by mario** [comment]
Alternatively (and this would be my preferred solution) if I set a placeholder and I don't set an error drawable, upon failure it should not clear the placeholder.

If you'd accept such a change, I'm happy to dive in further into the code and submit a PR - would be a nice way to get involved more as I really appreciate all you're doing.

**Comment by colinrtwhite** [comment]
I don't think we'd want to skip calling lifecycle methods as it makes the `Target` lifecycle less predictable. Part of the strength of Coil is that a request will always call either `onSuccess` or `onError` exactly once after calling `onStart`.

You mentioned it's causing the UI to refresh when calling `onError`. What do you mean by that? Ideally, calling `Target.onError` should be an inexpensive call.

**Comment by mario** [comment]
Well, the call itself is inexpensive, but on some phones there is flickering as the image is re-set even though the actual images are the same. I tried using it without error(drawable) but then the imageview becomes empty on error (because error drawable is not set) which is also not a solution for me.

**Comment by colinrtwhite** [comment]
Hmm the image should redraw synchronously as part of the next layout pass and avoid flickering. Just to confirm you're loading into an `ImageView` using `imageView.load(url)`?

**Comment by mario** [comment]
Yes - I've actually seen a similar behaviour few years back with ImageView when images were set in quick succession. Anyway, that's a whole different matter that I'll investigate myself - since you feel the feature request is not warranted here, I'll go ahead and close it.

As always, thanks for being informative and friendly!
