### ISSUE TITLE
Crash with Coil 0.9.0

### ISSUE THREAD

**Issue by ShaishavGandhi** [coil-kt/coil#221]
**Describe the bug**
After upgrading to Coil 0.9.0, I get an exception `java.lang.IllegalArgumentException: durationMillis must be > 0.`

**Expected behavior**
In 0.8.0, this wouldn't crash.

**To Reproduce**
How can we reproduce this?
The code that's triggering it:
```kotlin
coverImageView.load(volumeInfo.imageLinks?.getImageLink()) {
  crossfade(false)
}
```
**Version**
0.9.0

**Comment by colinrtwhite** [comment]
Thanks! Taking a look.

**Comment by ShaishavGandhi** [comment]
I guess i'm kinda misusing the API since crossfade is false by default. But I would still consider this a bug :)

**Comment by colinrtwhite** [comment]
Definitely a regression related to the new `Transition`s API. Likely going to release 0.9.1 with a quick fix for this.
