### ISSUE TITLE
IRLinkage error on Kotlin/Js

### ISSUE THREAD

**Issue by N7ghtm4r3** [coil-kt/coil#2231]
**Describe the bug**
Hi, using Coil3 on a `Kotlin/Js` project using the `AsyncImage` api this error occurred:

```json
{
    "message": "Function 'setContent$composable' can not be called: No function found for symbol 'androidx.compose.runtime/ControlledComposition.setContent$composable|9062691686831257511[0]'",
    "name": "IrLinkageError"
}
```
and the related web page will be blank with no content displayed

**To Reproduce**
In a `Kotlin/Js` project using the `AsyncImage` api and the error occurs ispecting the webpage in the `Console` tab will be printed the error

**Logs/Screenshots**
Following there is a screenshot about how the web page results and the error printed in the `Console` section of the browser
![Screenshot 2024-05-06 173601](https://github.com/coil-kt/coil/assets/64226606/0f34f0c5-ea1b-4ab8-9a39-d267385fd55b)
 

**Version**

Implemented in the `commonMain.dependencies` resources set:

`io.coil-kt.coil3:coil-compose:3.0.0-alpha06`
`io.coil-kt.coil3:coil-network-ktor:3.0.0-alpha06`

**Comment by colinrtwhite** [comment]
This seems like it might be a Compose error unrelated to Coil as Coil isn't mentioned in the error. Are you able to reproduce error only importing Compose Multiplatform?

**Comment by N7ghtm4r3** [comment]
The error occurred only when the dependencies I said in the previous comment are imported, without these the composition goes well and the content of the page is not blank, I don't understand the usages of the comment you said `./gradlew samples:compose:jsRun` I need to run and share to you the result or is the proof that for you works correctly?

**Comment by colinrtwhite** [comment]
> To Reproduce: In a Kotlin/Js project using the AsyncImage api and the error occurs ispecting the webpage in the Console tab will be printed the error

I'm not able to reproduce the exception using the sample JS app in this repo which imports `AsyncImage`. Do you have a sample that reproduces the issue?

**Comment by N7ghtm4r3** [comment]
Yes, I share with you the demo project where I am trying to implement the Coil library, it works based on the [Kobweb](https://github.com/varabyte/kobweb) library, so I think you should install if the project has not the gradle tasks required.
You can download the demo project [here](https://github.com/N7ghtm4r3/democoil/releases/tag/0.0.0)

**Comment by colinrtwhite** [comment]
Kobweb is based on [Compose HTML](https://github.com/JetBrains/compose-multiplatform#compose-html), but Coil uses [Compose Multiplatform](https://github.com/JetBrains/compose-multiplatform). It's likely that you need to set up your project for Compose Multiplatform similar to [here](https://github.com/coil-kt/coil/blob/main/samples/compose/src/jsMain/kotlin/sample/compose/main.kt#L10).

**Comment by N7ghtm4r3** [comment]
Yes I'm sorry I totally forgot this requirement about Compose HTML is not Compose Multiplatform, thanks for the help
