### ISSUE TITLE
Not able to find ImageRequest in coil3 for multiplatform project

### ISSUE THREAD

**Issue by youranshul** [coil-kt/coil#2232]
**Describe the bug**
I have been using coil3 libraries for loading images for my KMP demo app. I want to use the Image Request apis to load images and handle a few more use cases. However, I am not able to find the ImageRequest in the library. 

**To Reproduce**
<img width="825" alt="Screenshot 2024-05-06 at 11 14 36 PM" src="https://github.com/coil-kt/coil/assets/618667/15e7dc90-13cf-484a-9f46-28d8e708a467">

**Version**
coil = "3.0.0-SNAPSHOT"

coil-coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor", version.ref = "coil" }

**Comment by colinrtwhite** [comment]
According to the screenshot you have a typo: `ImageReques`.
