### ISSUE TITLE
automatically load placeholder when loading empty or null URI

### ISSUE THREAD

**Issue by alanleedev** [coil-kt/coil#224]
Using the following code
```
imageView.load(url) {
    placeholder(R.drawable.image)
}
```

If the `url` is empty or null then it would be great if the placeholder is loaded automatically.
It doesn't seem to do that currently.

**Comment by mario** [comment]
Can't you just do imageView.load(context.getDrawable(R.drawable.image)) instead?

**Comment by colinrtwhite** [comment]
You can also use:

```kotlin
imageView.load(url) {
    fallback(R.drawable.image)
}
```

to set a fallback drawable if the url is null.

**Comment by mario** [comment]
@colinrtwhite so can we close this?

**Comment by colinrtwhite** [comment]
Yep, let's close.

**Comment by alanleedev** [comment]
Sorry for the late reply. 
I've also realized there were similar request and discussions in the past.
`fallback` seems to be what I've been looking for so okay to close.
