### ISSUE TITLE
New field in ImageRequest.Builder to be able to recompose

### ISSUE THREAD

**Issue by ElFames** [coil-kt/coil#2242]
When I choose an image from the gallery to send to my server, having only one image per user the url of the image does not change, the name of the image does not change and it is not recomposed.
You also can't use a LaunchEffect because we choose the image from a LauncherForActivityResult.

The solution I found was when choosing the new image from the gallery, change a state boolean and add it to the Coil request within the crossfade so that it is recomposed. This is not entirely correct but since I don't need the crossfade it works for me.
It would simply be adding a new field inside the ImageRequest.Build called recomposition that allows us to pass a key for the recomposition.

![image](https://github.com/coil-kt/coil/assets/127795711/72976964-1f2a-4cf9-b2ae-84db9591f574)

**Comment by colinrtwhite** [comment]
It looks like you're looking for a retry API. Here's the ticket to follow: https://github.com/coil-kt/coil/issues/884

**Comment by ElFames** [comment]
I am not referring to that since my request is not in error.
If you load an image from the server with a url, send a new image that overwrites it, the url never changes, the screen is not recomposed and the request is not made again.
In 95% of cases, the image that is on the device can be displayed and that second request is not necessary, but it is not an option since the image has to first pass through filters on the server. 
How do you make a second request without doing weird things and without changing the url?
