### ISSUE TITLE
Method name `error()` conflicts with `kotlin.error()`

### ISSUE THREAD

**Issue by chimbori** [coil-kt/coil#225]
I’m using `Coil.get` in a suspend function, and passing a trailing lambda. I can include other methods such as `allowHardware(false)` in the trailing lambda, but calling `error(R.drawable.any)` calls the Kotlin `error(message: Any)` instead.

```
Coil.get(sampleUrl) {
  error(R.drawable.empty)
}
```

The problem only affects `error`, not other method names (obviously). And I also don’t see an explicit import for `kotlin.error`, so there’s no way to set an error drawable for Coil when using `Coil.get`.

**Comment by mario** [comment]
I don't think that's how "get" is supposed to work - error and placeholder are used to set an image to a view, and with "get" that's not what happens.

You should be able to accomplish the same with something like this:

```
                var drawable: Drawable? = null
                try {
                    drawable = Coil.get(sampleUrl)
                } catch (exception: Exception) {
                    drawable = context.getDrawable(R.drawable.empty)
                }
```

**Comment by chimbori** [comment]
That’s what I tried first, but `.get` returns `Drawable`, not `Drawable?`. So the natural assumption was that an error drawable would be decoded and returned.

And the other options do work fine, which must be passed along to `Coil.get` for a successful fetch (e.g. `allowHardware`)

**Comment by mario** [comment]
Yes it returns a Drawable, but it also throws an exception if something goes wrong (i.e. 404 on the request).

**Comment by colinrtwhite** [comment]
@mario is right. `Coil.get` creates a [`GetRequest`](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/request/Request.kt#L210) which doesn't support an error drawable (or placeholder).

This is currently intended behaviour as setting an error drawable would suppress any exceptions thrown by `Coil.get`. Similarly, removing the `error` setter from a `Coil.get` call would make it throw exceptions again, which could be surprising.
