### ISSUE TITLE
 Duplicate class androidx.lifecycle.ViewModel in coil 2.2.0

### ISSUE THREAD

**Issue by iamromec** [coil-kt/coil#2252]
https://github.com/coil-kt/coil/issues/1423

PFA
<img width="1728" alt="Screenshot 2024-05-12 at 9 44 27 PM" src="https://github.com/coil-kt/coil/assets/50284628/a657387c-37f0-449e-8970-f8eadb2a87a2">

**Comment by iamromec** [comment]
Why closed?

**Comment by colinrtwhite** [comment]
You didn't follow the issue template and it's not possible for me to help with local build issues.

**Comment by colinrtwhite** [comment]
You didn't follow the issue template and I can't help with local build issues.

**Comment by iamromec** [comment]
I have replied to the previous issue I mentioned in this issue but replied either...so had to create a new one with referring to old one. But you've closed this either.
