### ISSUE TITLE
How to access Exif Data after image is loaded from remote source?

### ISSUE THREAD

**Issue by MaggiWuerze** [coil-kt/coil#226]
Hi,
I am building a Gallery App and was wondering if there is a way to access the EXIF Data of the image retrieved from server (i read in anopther issue that you read exif data already for orientation) after `View.load` is done, maybe in `listener` or `target`.

Any help would be greatly appreciated

**Comment by mario** [comment]
You'll have to do this on your own as far as I know - take a look at ExifInterface - https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface.html

**Comment by MaggiWuerze** [comment]
I did and my problem is, that i would have to download the image again, since i can't read EXIF Data from a `Drawable` or `Bitmaps` created from one. That seems wasteful when the library already reads that data during processing but only keeps the orientation data.
Would be nice if i could grab that data via the `Imageloader` or something like that.

**Comment by colinrtwhite** [comment]
Coil relies on `OkHttp` for its disk cache. Unfortunately, the cache isn't set up for easy access, however you could probably access its files using [`Cache.urls()`](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-cache/urls/) and [`Cache.key()`](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-cache/key/). That'll let you iterate over its files then you can read its EXIF data using `ExifInterface` like @mario mentioned. You can get the default Coil `Cache` instance using [`CoilUtils.createDefaultCache`](https://coil-kt.github.io/coil/api/coil-base/coil.util/-coil-utils/create-default-cache/).
