### ISSUE TITLE
[Coil 3] make crossfade support using different scale type for placeholder vs final image

### ISSUE THREAD

**Issue by nift4** [coil-kt/coil#2277]
**Is your feature request related to a problem? Please describe.**
My placeholder is a vector drawable and can adjust to bounds itself properly. In a RecyclerView where all ImageViews have same bounds but final images are different resolution, the placeholder, which is rendered in final image's resolution when using crossfade (because well, CrossfadeDrawable does need some bounds and cannot just change them during the animation - but this in itself is not a problem for me as my placeholder is a vector drawable) will then be cropped if I set Scale.FILL in ImageRequest builder. I do want to crop my final image, but my placeholder should use Scale.FIT instead.

**Describe the solution you'd like**
Simple API where I can set scale type for placeholder to avoid it being cropped.

**Additional context**
I can work around this missing feature by copy pasting around 500 lines from coil3 into my project and setting a custom transition factory which has a very hacky workaround for this - but it's very annoying.
Thanks for the great library, other than this one I encountered no issues :D

**Comment by nift4** [comment]
That works and is a lot cleaner, thanks :) any chance to get this moved out of gif into another package?

**Comment by colinrtwhite** [comment]
Yep, I think it's fair to move it if we're recommending it for this use case. It's a small class and R8 will easily strip it if it's unused.
