### ISSUE TITLE
How to specify the width of an image？

### ISSUE THREAD

**Issue by bjhexn** [coil-kt/coil#2286]
Hope the image occupies full width and has adaptive height。

But in reality, the picture is very small。How to scale images proportionally, such as displaying them at full width.
![image](https://github.com/coil-kt/coil/assets/9999952/dae3029a-d585-4b66-8b5f-649af3e8803e)

xml
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".activity.ImageActivity">

    <ImageView
        android:id="@+id/imageView1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scaleType="centerInside"
        android:background="@color/black"/>

    <ImageView
        android:id="@+id/imageView2"
        android:layout_marginTop="10dp"
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:background="@color/black"/>

</LinearLayout>
Code:
url=https://e.hiphotos.baidu.com/baike/s%3D220/sign=4f92cff48401a18bf4eb154dae2e0761/0df3d7ca7bcb0a463659c2e16863f6246a60afeb.jpg&product=dictwiki"

        val imageView1 = findViewById<ImageView>(R.id.imageView1)
        val imageView2 = findViewById<ImageView>(R.id.imageView2)

        imageView1.load(url)
        imageView2.load(url)

**Comment by bjhexn** [comment]
Found the method for relevant configuration

imageView1.load(url) {
            precision(Precision.EXACT)
}

![image](https://github.com/coil-kt/coil/assets/9999952/e069f13f-8668-4cc5-8d5b-484093273e7c)

**Comment by colinrtwhite** [comment]
`Precision.EXACT` will ensure the image is scaled up to fit the dimensions when decoding - as opposed to having the `ImageView` scale it (which is faster and consumes less memory).
