### ISSUE TITLE
Coil 3 + GIF w/o delay + Xiaomi Android 14 = GIF isn't playing

### ISSUE THREAD

**Issue by Andrew0000** [coil-kt/coil#2287]
**Describe the bug**
Basically that's it. If GIF has no delay property - it is not playing.
I saw your comment in the **maybeWrapImageSourceToRewriteFrameDelay** function:
```
internal fun maybeWrapImageSourceToRewriteFrameDelay(
    source: ImageSource,
    enforceMinimumFrameDelay: Boolean,
): ImageSource {
    // https://android.googlesource.com/platform/frameworks/base/+/2be87bb707e2c6d75f668c4aff6697b85fbf5b15
    if (enforceMinimumFrameDelay && SDK_INT < 34 && DecodeUtils.isGif(source.source())) {
        // Wrap the source to rewrite its frame delay as it's read.
        return ImageSource(
            source = FrameDelayRewritingSource(source.source()).buffer(),
            fileSystem = source.fileSystem,
            // Intentionally don't copy any metadata.
        )
    } else {
        return source
    }
}
```
But in case of Xiaomi seems like it wasn't fixed on Android side. Please see the screenshot with the OS version below.

My suggestion is to keep adding the default delay on API 34+ because the check for Android version seems unreliable.

**Version**
Coil: 
io.coil-kt.coil3:coil-compose-core (and other) 3.0.0-alpha06

Android:
Xiaomi Android 14
<img width="326" alt="image" src="https://github.com/coil-kt/coil/assets/4018244/6129f541-8e4d-41e3-9a35-3a9023465903">

**Comment by colinrtwhite** [comment]
Yep, I think let's remove the `SDK_INT < 34` check. The `enforceMinimumFrameDelay` work-around shouldn't conflict with the AOSP fix. My hunch is there are other devices that haven't properly integrated this AOSP fix. If users want to disable the fix they can pass `enforceMinimumFrameDelay = SDK_INT < 34` in the constructor of the decoder.

**Comment by colinrtwhite** [comment]
@Andrew0000 Can you confirm you're using `AnimatedImageDecoder` and not `GifDecoder`?

**Comment by Andrew0000** [comment]
> @Andrew0000 Can you confirm you're using `AnimatedImageDecoder` and not `GifDecoder`?

Seems like `GifDecoder`. This is my config:
```
ImageLoader.Builder(context)
            .components {
                add(SvgDecoder.Factory())
                add(GifDecoder.Factory())
            }
            .build()
```
It invokes the **maybeWrapImageSourceToRewriteFrameDelay**  function under the hood as I see: 

<img width="808" alt="image" src="https://github.com/coil-kt/coil/assets/4018244/9f1d071b-ab09-4f42-9d84-e3cb684ca1c8">

**Comment by colinrtwhite** [comment]
Ah I think the issue is the AOSP fix only applies when using `AnimatedImageDecoder`, but the `SDK_INT < 34` check was being applied to `GifDecoder` as well. The linked PR should fix the issue.

**Comment by MV-GH** [comment]
I have this bug on Android 11. using 2.6
 
Using `ImageDecoderDecoder`
https://github.com/coil-kt/coil/assets/67873169/3970bd2e-60a5-40a4-b0f1-58d49dcd8c93

using `GifDecoder`
https://github.com/coil-kt/coil/assets/67873169/938aac49-dfa7-4675-89e4-8f0195e3470a

The gif
![tenor](https://github.com/coil-kt/coil/assets/67873169/09d64f26-3c37-4f94-9d6a-aa7e0742d1fe)


Since that check only disables it for Android 14 I do not believe it will fix it.

**Comment by lr555** [comment]
> I have this bug on Android 11. using 2.6
> 
> Using `ImageDecoderDecoder`
> 
>  studio64_fErgoIi7qN.mp4 
> using `GifDecoder`
> 
>  studio64_aI4YcAifBW.mp4 
> The gif
> Since that check only disables it for Android 14+ I do not believe it will fix it.
> 
> Also not sure if relevant but in the logs I see this being spammed 10x sec:
> 
> ```
> Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
> updateAcquireFence: Did not find frame.
> Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
> updateAcquireFence: Did not find frame.
> Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
> updateAcquireFence: Did not find frame.
> Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
> ```

same to me, @colinrtwhite , can you take a look at this question？
