### ISSUE TITLE
Unsupported type: ImageBitmap

### ISSUE THREAD

**Issue by pankaj1920** [coil-kt/coil#2297]
AsyncImage(
        model = image,
        contentDescription = null,
        modifier = modifier
    )

java.lang.IllegalArgumentException: Unsupported type: ImageBitmap. If you wish to display this ImageBitmap, use androidx.compose.foundation.Image.

**Comment by colinrtwhite** [comment]
> If you wish to display this ImageBitmap, use androidx.compose.foundation.Image.
