### ISSUE TITLE
Support animated-WebP for all API level

### ISSUE THREAD

**Issue by diousk** [coil-kt/coil#23]
In our projects with minimal API 21, 
we use fresco library to load an amount of animated-webp 
(from local file in assets and also from url)

I can see there's a GifDecoder for gif decoding/loading for all API level.
Would Coil support a decoder like WebPDecoder prior to Android P?

**Comment by colinrtwhite** [comment]
Unfortunately, this isn't very straightforward to support. Fresco uses native libraries to load animated WebP images on pre-Android P, which I'm against adding to the Coil main repo.

I think this would be a good candidate for an external repository that depends Coil. If anyone writes a `Decoder` for this, let me know and I'll add it to the documentation.

**Comment by skgmn** [comment]
Hello @colinrtwhite! It's quite long ago, but I've done this recently using libwebp so I'm just letting you know as you said. 🙂 
Check this out: https://github.com/skgmn/AnimatedWebPDecoder
Thank you.
