### ISSUE TITLE
coil3 loading long image will be crash

### ISSUE THREAD

**Issue by 1006245347** [coil-kt/coil#2300]
**Describe the bug**
coil3 loading long image will be crash,

`Box{ 
//Column {//超长图在外面套一层column不会崩溃
//                SubcomposeAsyncImage(
//                    model = ImageRequest.Builder(LocalPlatformContext.current)
//                        .data(url).build(),
//                    contentDescription = null,
//                    modifier = Modifier.padding(1.dp)
//                ) {
//                    if (painter.state is AsyncImagePainter.State.Loading ||
//                        painter.state is AsyncImagePainter.State.Error
//                    ) {
//                        CircularProgressIndicator()
//                    } else {
//                        SubcomposeAsyncImageContent()
//                    }
//                }
//            }
}
`

will be crash 
` Box() {//超长图不在外面套一层会崩溃
                SubcomposeAsyncImage(
                    model = ImageRequest.Builder(LocalPlatformContext.current)
                        .data(url).build(),
                    contentDescription = null,
                    modifier = Modifier.padding(1.dp)
                ) {
                    if (painter.state is AsyncImagePainter.State.Loading ||
                        painter.state is AsyncImagePainter.State.Error
                    ) {
                        CircularProgressIndicator()
                    } else {
                        SubcomposeAsyncImageContent()
                    }
                }
            }
`

**To Reproduce**
https://ark-cdn.gree.com/ark/1f42e33985d6c348aca8191679b94ecc9848_1671058244501.jpg?sign=920e0211e4b48c0d32a3d4a117fbbb94&t=1717398000

but it could show 2 hours....

<img width="543" alt="image" src="https://github.com/coil-kt/coil/assets/24426708/61c84152-4094-4eed-aa61-2a2138f2a68a">

**Version**
[[What library version are you using? Does this occur on a specific API level or Android device?](io.coil-kt.coil3:coil-compose)](io.coil-kt.coil3:coil-compose)
io.coil-kt.coil3:coil-compose   coil3 = "3.0.0-alpha06"

**Comment by colinrtwhite** [comment]
What is the exception?

**Comment by colinrtwhite** [comment]
It looks like your image is 26k pixels and the containing `Box` has an unbounded height. 26k pixels is larger than the max size Android can support. You need to set a size on your `ImageRequest` or bound the `Box`'s height.

**Comment by FooIbar** [comment]
Might be related to #2211, you could try `allowHardware(false)`.
