### ISSUE TITLE
Can we encrypt and decrypt a disk cached image using Coil library?

### ISSUE THREAD

**Issue by DeepPSingh** [coil-kt/coil#231]
I have just started using Coil and I love it. I have a requirement in my project to encrypt and decrypt a disk cached image for security reasons. I have been trying to find out a solution for the same online without any luck.

Can you please let me know if coil supports it or provide a sample how to do it?

This is an important feature we need to implement else I have to move to Glide.

Thanks in advance for your help.

**Comment by colinrtwhite** [comment]
I don't think this is possible, unfortunately. Coil relies on OkHttp's disk cache, which [doesn't look like it can be encrypted easily](https://stackoverflow.com/questions/22373763/encrypting-okhttps-httpresponsecache).

**Comment by DeepPSingh** [comment]
Thanks for the quick response.
