### ISSUE TITLE
Execute image request on spot from compose resources

### ISSUE THREAD

**Issue by nilufer32** [coil-kt/coil#2310]
**Describe the bug**
I want to be able to execute an image request from compose resources in a blocking way.
I should be able to call execute blocking on the main thread.
Currently if I attempt to do this my app will crash

**To Reproduce**
```
var imageRequest: ImageRequest? = null

fun initializeResource(
    context: PlatformContext,
    imageLoader: ImageLoader,
    byteArray: ByteArray,
) {
    imageRequest =
        ImageRequest.Builder(context)
            .decoderFactory { result, options, _ ->
                SvgDecoder(result.source, options)
            }
            .data(byteArray)
            .crossfade(0)
            .build()

    runOnMainDispatcher {
        imageLoader.execute(imageRequest!!)
    }
}
```

**Version**
Coil 3.0.0-alpha06

**Comment by colinrtwhite** [comment]
What's the exception?

**Comment by colinrtwhite** [comment]
There's not enough info here to reproduce the issue. This should be supported, but it's recommended to not load resources on the main thread as it will block the main thread and drop frames.
