### ISSUE TITLE
Add support for HEIC images in Compose Multiplatform

### ISSUE THREAD

**Issue by antailyaqwer** [coil-kt/coil#2318]
**Is your feature request related to a problem? Please describe.**
In skia (as well as in [skiko](https://github.com/JetBrains/skiko/issues/942)) HEIC format doesn't supported.
This leads to incorrect flow on modern ios devices for image rendering (for example, custom media picker).

My idea is to add support of it inside a library. 

**Describe the solution you'd like**
I have a simple workaround of this problem: convert heic image to jpeg.
My solution isn't elegant enough as I don't have access to coil internal methods.
I think there is a better way to support it

```kotlin
var builder = ImageRequest.Builder(LocalPlatformContext.current)
    .data(uri) // uri is usually a path. For example, /var/storage/image.HEIC

if (uri.substringAfterLast('.').equals("HEIC", ignoreCase = true)) {
    builder = builder.decoderFactory { result, options, imageLoader ->
        HEICImageDecoderFactory().create(result, options, imageLoader)
    }
}

AsyncImage(
    model = builder.build(),
    contentDescription = null,
)


expect class HEICImageDecoder(
    source: ImageSource,
    options: Options,
) : Decoder

// Decoder logic
class HEICImageDecoderFactory : Decoder.Factory {

    override fun create(
        result: SourceFetchResult,
        options: Options,
        imageLoader: ImageLoader,
    ): Decoder {
        return HEICImageDecoder(result.source, options)
    }
}


// ios implementation of expect class
private const val COMPRESSION = 0.3

actual class HEICImageDecoder actual constructor(
    private val source: ImageSource,
    private val options: Options
) : Decoder {

    @OptIn(ExperimentalCoilApi::class)
    override suspend fun decode(): DecodeResult {
        val originalBytes = source.source().use { it.readByteArray() }
        val jpegBytes = originalBytes.toJpegBytes()
        val image = Image.makeFromEncoded(jpegBytes)

        val isSampled: Boolean
        val bitmap: Bitmap
        try {
            bitmap = Bitmap.makeFromImage(image, options)
            bitmap.setImmutable()
            isSampled = bitmap.width < image.width || bitmap.height < image.height
        } finally {
            image.close()
        }

        return DecodeResult(
            image = bitmap.asCoilImage(),
            isSampled = isSampled,
        )
    }
}

@OptIn(ExperimentalForeignApi::class)
private fun ByteArray.toJpegBytes(): ByteArray = memScoped {
    val image = UIImage(data = this@toJpegBytes.toNSData())

    return UIImageJPEGRepresentation(image, compressionQuality = COMPRESSION)!!.toByteArray()
}
```

**Comment by Anthony17serrato** [comment]
Hi @antailyaqwer have you managed to get a working HEIC decoder for coil 3? Facing the same problem...

**Comment by antailyaqwer** [comment]
> Hi @antailyaqwer have you managed to get a working HEIC decoder for coil 3? Facing the same problem...

Hi. We changed the way we render images. It was a wrong way to parse images uri's in ios, as it consumes a lot of resources. Now we using thumbnails from ios, without using coil.

**Comment by shubhamMonga777** [comment]
Hi, I am using coil for loading images in my compose multiplatform app, Can you please help me how to render heic extension image using coil

**Comment by Anthony17serrato** [comment]
Hi Shubam, I managed to get this working by writing a custom coil fetcher that converts HEIC to JPEG, which allows coils decoder to display the image. This performs relatively well. Please check my implementation 

https://github.com/Anthony17serrato/Phovo/blob/main/feature%2Fphotos%2Fsrc%2FiosMain%2Fkotlin%2Fcom%2Fserratocreations%2Fphovo%2Ffeature%2Fphotos%2Futil%2FPhAssetFetcher.kt

**Comment by reinaldoriant** [comment]
> Hi. We changed the way we render images. It was a wrong way to parse images uri's in ios, as it consumes a lot of resources. Now we using thumbnails from ios, without using coil.

Do you mean add kingfisher to implement it or how?
