### ISSUE TITLE
Image loading on main thread

### ISSUE THREAD

**Issue by GarikKhachaturyan** [coil-kt/coil#234]
**Is your feature request related to a problem? Please describe.**
We have application with a canvas on which we are drawing different shapes and images. We are trying to load images from a file in custom view onDraw method, but the coil does not allow to call _get_ method on the main thread.

**Describe the solution you'd like**
To be allowed to call the _get_ method in the main thread.

**Comment by colinrtwhite** [comment]
`onDraw` is going to be called many times and needs to be fast so you should avoid any long running operations (like a `get`) inside of it. I'd recommend you load the image outside of the drawable (a `ViewModel` is a good place for this operation) and pass it to the drawable's constructor.

That said, technically it is possible to make `get` a blocking call on the main thread by wrapping it in `runBlocking`, however I **highly discourage** this approach as it will cause your UI to freeze while the image is loading.

**Comment by GarikKhachaturyan** [comment]
> onDraw is going to be called many times and needs to be fast so you should avoid any long running operations (like a get) inside of it. I'd recommend you load the image outside of the drawable (a ViewModel is a good place for this operation) and pass it to the drawable's constructor.

Yes, that would be the ideal solution. However we cannot change that part of the architecture at this moment and a quick workaround would be nice.

> That said, technically it is possible to make get a blocking call on the main thread by wrapping it in runBlocking, however I highly discourage this approach as it will cause your UI to freeze while the image is loading.

We tried this solution already and if it should work as you said. Here is [a sample project](https://github.com/GarikKhachaturyan/CoilRunblockingTest) with a runBlocking in the onDraw method. It actually does not work and freezes inside the _get_ method.

**Comment by colinrtwhite** [comment]
@GarikKhachaturyan Try:

```kotlin
runBlocking {
    Coil.get(data) {
        dispatcher(Dispatchers.Main.immediate)
    }
}
```

A better solution would be to load the image async and make `onDraw` draw nothing until the image is loaded. Blocking the UI like this is a bad idea!

**Comment by GarikKhachaturyan** [comment]
Thanks a lot, it worked, this is what I needed. Also thanks for a quick reply.
I know that it's too bad to do so, I'll change it in the future.
