### ISSUE TITLE
AsyncImage fills the screen if one dimension is not specified and the image is not resolved

### ISSUE THREAD

**Issue by ParsleyJ** [coil-kt/coil#2349]
**Describe the bug**
The AsyncImage composable takes up all the possible space when the image (provided via URL) is not resolved.

**To Reproduce**
In the following snippet, the rendered screen should contain just a red box. Instead nothing is displayed, as the _empty_ AsyncImage takes up the full height of the screen, pushing the box to the bottom, outside the screen.

```Kotlin
@Composable
fun TestScreen() {
    Column(Modifier.fillMaxSize()) {

        AsyncImage(
            modifier = Modifier.fillMaxWidth(.5f),
            model = "https://inexistent.url/missingImage.png",
            contentDescription = "Test image",
            contentScale = ContentScale.FillWidth
        )

        Box(Modifier.background(color = Color.Red).size(50.dp))
        
    }
}
```

**Version**
kt-coil, coil-compose 2.6.0

**Comment by RobertTadevosyan** [comment]
@ParsleyJ the expected result is that the async image would have a 0 height ?

**Comment by ParsleyJ** [comment]
@RobertTadevosyan 

Yes
