### ISSUE TITLE
Can we force cache image on disk when server response has Pragma: no-cache using Coil library?

### ISSUE THREAD

**Issue by DeepPSingh** [coil-kt/coil#235]
I don't have control on server apis where images are stored. By default all the server response header have **Pragma: no-cache** which is blocking Coil library to cache the image on disk.

I have tried adding ResponseHeaderInterceptor("Cache-Control", "max-age=31536000,public") to the request but it doesn't work.

Can you please help me by letting me know if Coil can do force disk cache in this case?

**Comment by colinrtwhite** [comment]
You can remove the `Pragma` header with another `Interceptor`:

```kotlin
object : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
        val response = chain.proceed(chain.request())
        return response.newBuilder().removeHeader("Pragma").build()
    }
}
```

**Comment by DeepPSingh** [comment]
Thanks it worked.

**Comment by asissuthar** [comment]
Set global ImageLoader if you want to disable cache headers.

`Coil.setImageLoader(ImageLoader.Builder(this).respectCacheHeaders(false).build())`
