### ISSUE TITLE
AsyncImage flickers while parent recomposes

### ISSUE THREAD

**Issue by oblakr24** [coil-kt/coil#2355]
**Describe the bug**
In a multiplatform project, the AsyncImage (with data being a url) flickers while the parent recomposes, e.g. during a fadeout/swipe animation.

**To Reproduce**
```
        AsyncImage(
                            model = "https://picsum.photos/id/237/200/300",
                            contentDescription = null,
                            imageLoader = ImageLoader(LocalPlatformContext.current).newBuilder()
                                .logger(
                                    DebugLogger()
                                ).build(),
                            modifier = Modifier.fillMaxSize()
                            contentScale = ContentScale.Crop,
                        )
```

**Version**
3.0.0-alpha07

**Comment by colinrtwhite** [comment]
Creating a new `ImageLoader` on each composition will cause `AsyncImage` to restart the request. If you cache the `ImageLoader` does it fix the issue?

**Comment by oblakr24** [comment]
Thank you! This does indeed solve the problem.
