### ISSUE TITLE
ByteArrayFetcher not saved on disk

### ISSUE THREAD

**Issue by SilvioPulitano** [coil-kt/coil#2367]
Hello,

**Describe the bug**
ByteArrayFetcher don't save data on disk. Same problem with AssetUriFetcher

**To Reproduce**
I have tried with Coil3 compose sample on android device and I see in the log
💾 Successful (DISK) - file:///android_asset/video.mp4
but nothing on the disk

**Logs/Screenshots**
💾 Successful (DISK) - file:///android_asset/video.mp4

**Version**
3.0.0-alpha08

[EDIT]
Same problem with coil-sample-view Android and coil 2.6.0

**Comment by colinrtwhite** [comment]
It looks like you're loading a file URI. In this case it's expected that the file isn't saved to the `DiskCache` as it's already stored on disk and we want to avoid duplicating the data. The `DiskCache` is only used for fetching images from the network at the moment.
