### ISSUE TITLE
add new decoder: coil3.svg.ResvgDecoder(use resvg to decode svg image)

### ISSUE THREAD

**Issue by Gaubee** [coil-kt/coil#2369]
Current SVG support is quite limited, even on Android devices. For Example: `<filter>`.

As a result, we often receive negative feedback in actual projects. My team has to use WebView to render complex SVGs and then encode them into PNG for rendering.

we known SVG is a very complex technology, and the Coil project has put a lot of effort into this. But the SvgDecoder can only solve some simple decoding needs. If the SVG image comes from the Internet, then it has to face its diversity and complexity.

Therefore, I propose to add ResvgDecoder to provide the Coil ecosystem with a more professional SVG decoding solution. [Resvg](https://github.com/RazrFalcon/resvg) is developed using Rust, and its SVG support is more complete and professional. It is also compiled to a size of only [3MB](https://github.com/RazrFalcon/resvg?tab=readme-ov-file#zero-bloat) and has [good performance](https://github.com/RazrFalcon/tiny-skia?tab=readme-ov-file#performance).

**Comment by Gaubee** [comment]
By the way, I'll start on my project [dweb-browser](https://github.com/BioforestChain/dweb_browser) usin resvg for alternative [webview renderer 
 which is mixing with coil](https://github.com/BioforestChain/dweb_browser/blob/d8ba555685dda472d173dd837b3a1e21102a5b61/next/kmp/pureImage/src/commonMain/kotlin/org/dweb_browser/pure/image/compose/PureImageLoader.kt#L19-L41).
In my project, there are a lot of svg in the first frame rendering, and webview requires a certain startup time and occupies a certain amount of memory, and the communication with webview is also costly, and the whole process needs to go through many memory copies.

My project use [uniffi](https://gitlab.com/trixnity/uniffi-kotlin-multiplatform-bindings) to solve the rust to build connection between KMP project.

**Comment by colinrtwhite** [comment]
I think this is a good candidate for an external library. It's a lot of scope to support another SVG decoder and I'd like to avoid native libraries in Coil's dependencies. Feel free to list it [here](https://coil-kt.github.io/coil/works_with_coil/) once it's ready.
