### ISSUE TITLE
Update NetworkObserver to call connectivityManager.registerDefaultNetworkCallback instead of connectivityManager.registerNetworkCallback

### ISSUE THREAD

**Issue by daniellevass** [coil-kt/coil#2374]
Hi,

We'd like to update the [NetworkObserver](https://github.com/coil-kt/coil/blob/main/coil-core/src/androidMain/kotlin/coil3/util/NetworkObserver.kt#L53) to call `connectivityManager.registerDefaultNetworkCallback` instead of `connectivityManager.registerNetworkCallback` to ensure images load across our Android Automotive app regardless of the network assigned.

Android Automotive OEMs use a feature called [Per-application network selection (PANS)](https://source.android.com/docs/automotive/connectivity) to separate network traffic amongst various cellular network interfaces. OEMs generally prioritize critical car functionality to an "OEM-paid" network and keep entertainment functionality to a "Customer-paid" network.

Calling registerNetworkCallback is not recommended to track the default network assigned - Google recommend using registerDefaultNetworkCallback to track the default network assigned to the app. 

I'm happy to open a pull request for this change, if there are no concerns with this?

Thank you,

Danielle.

**Comment by colinrtwhite** [comment]
Thanks for the context. I think it's possible changing `NetworkObserver` to use `registerDefaultNetworkCallback` could have side effects for existing users so I think we should probably add `ImageLoader.Builder.observeDefaultNetwork(true/false)` to allow opting into the change. By default we only load over the default network, but [it's possible](https://stackoverflow.com/a/45868554/4475057) a user could be supplying a custom `SocketFactory` to use a different network. PR welcome!

I think this is also a good reason to make `NetworkObserver` public in Coil 3.x so the behaviour can be custom.

**Comment by daniellevass** [comment]
Thank you so much for your quick feedback! I've opened a PR over here : https://github.com/coil-kt/coil/pull/2379 - any feedback on the PR welcome 🙇‍♀️  I ran the ./test.sh locally, but it looks like CI won't let me know if I did everything okay until someone approves the build 🙈

**Comment by colinrtwhite** [comment]
This will be available in `2.8.0` - unfortunately I don't have a timeline for when the next release will be.

**Comment by daniellevass** [comment]
hi @colinrtwhite - apologies for the post on an old thread! Do you have any updates on when the next release might be? Would it be possible to make a patch release (2.7.1) with the fix instead of a minor release (2.8.0)? Is there anything I can do to help facilitate making a release sooner? We'd really appreciate being able to access this fix sooner rather than later! Thank you 🙇‍♀️
