### ISSUE TITLE
Turn off network cache, clear app file will not be able to load images

### ISSUE THREAD

**Issue by Liangwenb** [coil-kt/coil#2381]
**Describe the bug**

Turn off network cache, clear app file will not be able to load images

**To Reproduce**

```
class MainApplication : Application(), ImageLoaderFactory {

    override fun onCreate() {
        super.onCreate()

    }

    override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(this)
            .crossfade(true).allowRgb565(true)
            .diskCachePolicy(CachePolicy.ENABLED)
            .networkCachePolicy(CachePolicy.DISABLED)
            .memoryCachePolicy(CachePolicy.ENABLED)
            .build()
    }
}

```

Then use the android studio plugin "adb Idea" Adb Clear Data

**Logs/Screenshots**

none

**Version**

```
    compileSdk 34

    api("io.coil-kt:coil-compose:2.7.0")
    api("io.coil-kt:coil:2.7.0")

```

 Android device : xiaomi 22031116BG

**Comment by colinrtwhite** [comment]
There isn't enough information here to reproduce the issue, but it sounds like expected behaviour. If you disable the network cache it isn't possible for the image loader to fetch images from the internet.
