### ISSUE TITLE
Why does Coil always refresh when loading different images with the same URL by default? Is it a bug?

### ISSUE THREAD

**Issue by liyuhaolol** [coil-kt/coil#2388]
Recently, I tried this project and encountered an issue, and I'm not sure if it's a bug.
Normally, if the URL of an image remains the same but the file changes, due to local caching, the default behavior should be to load the image from the disk cache associated with that URL. This can result in the image not being refreshed in real-time. Other projects like `Glide` address this by allowing the setting of a `signature` on the loaded image. When the `signature` changes, the image is reloaded from the network.
In this project, there is a similar attribute called `diskCacheKey`. However, when I tested version `2.7.0`, I found that there was no need to set `diskCacheKey`. As long as the image file changes, Coil automatically loads the new image, seemingly ignoring the disk cache completely. Is this a bug? If not, could you please explain the implementation logic behind this behavior?

**Comment by colinrtwhite** [comment]
This is expected behaviour. The behaviour is controlled by [this API](https://coil-kt.github.io/coil/api/coil-core/coil3/add-last-modified-to-file-cache-key.html?query=fun%20ImageLoader.Builder.addLastModifiedToFileCacheKey(enable:%20Boolean):%20ImageLoader.Builder).
