### ISSUE TITLE
Support fonts on SVG files

### ISSUE THREAD

**Issue by abdelba** [coil-kt/coil#2394]
### Is your feature request related to a problem? Please describe.
Coil SVG currently does not support SVG fonts, so they don’t display correctly. This limitation impacts the appearance and functionality of SVG files that use custom SVG fonts.

### Describe the solution you'd like
I’d like Coil SVG to support SVG fonts so that they render properly. This enhancement would improve the design capabilities and visual fidelity of SVGs that use these fonts.

### Additional context
Supporting SVG fonts will make Coil SVG more versatile for designers. Here’s a small SVG example using SVG fonts to illustrate the issue:

```xml
<svg width="200" height="100" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <font id="MyFont" horiz-adv-x="1000">
      <font-face font-family="MyCustomFont" units-per-em="1000" />
      <glyph unicode="A" d="M100 0 L200 0 L150 100 Z" />
      <glyph unicode="B" d="M100 0 L200 0 L200 100 L100 100 Z" />
    </font>
  </defs>
  <text x="10" y="50" font-family="MyCustomFont" font-size="50">
    AB
  </text>
</svg>
```

The example defines a simple SVG font with two glyphs ("A" and "B") and uses it in the <text> element. When SVG fonts are supported, this example should render the letters "A" and "B" using the custom shapes defined in the font.

Here’s a screenshot showing the issue with the current rendering in Coil SVG:
![Capture d’écran 2024-07-24 à 21 55 34](https://github.com/user-attachments/assets/e18095d0-815e-4e8d-b51f-e4967fcb2b99)

And here’s a screenshot of the correct rendering with SVG font support:

![Capture d’écran 2024-07-24 à 21 56 05](https://github.com/user-attachments/assets/b266038f-2c34-4d76-a671-588e85af8e79)

**Comment by colinrtwhite** [comment]
Thanks for the suggestion, but unfortunately this isn't something Coil can support. SVG rendering in Coil is handled by https://github.com/BigBadaboom/androidsvg on Android so I'd file an issue there to support it.
