### ISSUE TITLE
Support loading Uri Strings

### ISSUE THREAD

**Issue by colinrtwhite** [coil-kt/coil#24]
**Is your feature request related to a problem? Please describe.**
Currently `load(String)` must always be a valid URL, but we could support automatically switching between `Uris` and `HttpUrls`.

**Describe the solution you'd like**
This should load the file/asset Uri correctly:

```
imageView.load("file:///android_asset/starrynight.jpg")
```

**Additional context**
Glide and Picasso already handle this.

Previous discussion: https://github.com/coil-kt/coil/issues/10

**Comment by isMeiying** [comment]
Should analyze the string to determine whether it is a file type，Glide has made a judgment.

like:

> if (str.startsWith("http"))
>     load(str, imageLoader, builder) 
> else
>     load(File(str), imageLoader, builder)
