### ISSUE TITLE
ImageBitmap Support for multiplatform 

### ISSUE THREAD

**Issue by harish-zuper** [coil-kt/coil#2405]
Looking for support for composeImageBitmap() for multiplatform

**Comment by colinrtwhite** [comment]
Supporting Compose's multiplatform graphics classes are out of scope for this library since it adds a lot of complexity. Coil uses its own thin `Image` class to abstract over the graphics systems and I want to avoid increasing the API surface.

**Comment by GvHarish9894** [comment]
Okay
