### ISSUE TITLE
[wasmJS] Build Error.

### ISSUE THREAD

**Issue by NakiriYuuzu** [coil-kt/coil#2422]
**Describe the bug**
Using the new coil alpha-09 version with the ktor3 will getting this error log.

**To Reproduce**
Using this version and build will getting this error.

**Logs/Screenshots**
```
Execution failed for task ':composeApp:compileDevelopmentExecutableKotlinWasmJs'.
```

**Version**
```
kotlin = "2.0.10"
compose-plugin = "1.7.0-alpha02"
coil = "3.0.0-alpha09"
ktor = "3.0.0-wasm2"

coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
```

**Comment by colinrtwhite** [comment]
There's not enough information here to debug this, though you likely need to update to `3.0.0-beta-2`.
