### ISSUE TITLE
[Coil-3] SVG flickering while scrolling

### ISSUE THREAD

**Issue by slickorange** [coil-kt/coil#2423]
**Describe the bug**
My SVGs which are loaded from internal storage flickers while scrolling on a Jetpack compose screen. I have confirmed that the images are constantly recomposing which is causing the issue. I am unfortunately unable to determine the reason for the recomposing at this stage.
The flickering only started after I upgraded to Coil3 though..

I realize I need to solve the re-composition (this is on a complex screen and I am unable to find the cause now), but do you have any idea why it would flicker since upgrading to Coil-3? Any ideas to get rid of it?  Thank you!

**Version**
Coil 3 (Alpha 9)

**Comment by colinrtwhite** [comment]
If you're using loading the image on desktop make sure you're [importing an coroutine main dispatcher](https://coil-kt.github.io/coil/upgrading_to_coil3/#compose). If you're using `rememberAsyncImagePainter().state` and changing the image based on the state, keep in mind the state will always be loading for the first composition.

**Comment by slickorange** [comment]
@colinrtwhite Thank you for coming back to me and sorry for failing to mention that this is on Android, not on desktop.

This is how I render the image. The image is an SVG loaded from internal storage.
I solved my continuous recomposition issue when scrolling, so it is better, but there is still a delay or a bit of flashing going on which was not there in previous versions.

```
val painter = rememberAsyncImagePainter(model = ImageRequest.Builder(LocalContext.current)
                .data(imagePath)
                .decoderFactory(SvgDecoder.Factory())
                .size(Size.ORIGINAL)
                .build())

            Image(painter = painter, contentDescription = "",
                colorFilter = ColorFilter.tint(
                colorResource(R.color.colorAccent)
            ),
                modifier = Modifier.size(60.dp),)
```
