### ISSUE TITLE
SSL Certificate handshake exception 

### ISSUE THREAD

**Issue by developerConjoinix** [coil-kt/coil#243]
Image not loading when trying to load from https:://.
Where the certificate is working.

**Comment by Jawnnypoo** [comment]
Can you give more information, such as the error you are seeing and possibly what URL you are trying to load? You can always provide your own `OkHttpClient` instance if you know your needed configuration via the `ImageLoaderBuilder`
```
val imageLoader = ImageLoader(context) {
    okHttpClient {
                OkHttpClient.Builder()
                    .cache(CoilUtils.createDefaultCache(context))
                    .forceTls12()
                    .build()
            }
}
Coil.setDefaultImageLoader(imageLoader)
```
You can find the `forceTls12()` method in the sample app, if that is indeed the problem you are facing, but this gives you an idea of what you might need to do to fix your https loading issue.

**Comment by mario** [comment]
This is pretty much an issue with the configuration of OKHttp and the way you handle SSL exceptions - if such a case arises, depending on your use case, you should present the certificate to the end user and ask them to accept it.

Not an issue with Coil per-se., like @Jawnnypoo said.

**Comment by colinrtwhite** [comment]
As mentioned this is likely a certificate or TLS issue related to OkHttp - not Coil.
