### ISSUE TITLE
Coil disk cache doesn't work when loading an icon file manually

### ISSUE THREAD

**Issue by Shinokuni** [coil-kt/coil#2430]
**Describe the bug**
Loading in disk cache a base64 icon manually fails. I am getting a base64 icon from an API json file I would like to put in cache with a key to be able to load it later.

```kotlin
val imageLoader = context.imageLoader

val request = ImageRequest.Builder(context)
    .diskCacheKey(DISK_CACHE_KEY)
    .data(loadIconByteArray(context))
    .build()

imageLoader.execute(request)

...

AsyncImage(
    model = DISK_CACHE_KEY,
    contentDescription = null,
    modifier = Modifier.size(24.dp)
)

```

On the other hand, the exact same code with memory cache works:
```kotlin
val imageLoader = context.imageLoader

val request = ImageRequest.Builder(context)
    .memoryCacheKey(MEMORY_KEY)
    .data(loadIconByteArray(context))
    .build()

imageLoader.execute(request)

...

AsyncImage(
    model = MEMORY_KEY,
    contentDescription = null,
    modifier = Modifier.size(24.dp)
)

```

`ImageLoader` configuration:
```kotlin
override fun newImageLoader(): ImageLoader {
    return ImageLoader.Builder(this)
        .memoryCachePolicy(CachePolicy.ENABLED)
        .diskCachePolicy(CachePolicy.ENABLED)
        .diskCache {
            DiskCache.Builder()
               .directory(this.cacheDir.resolve("image_cache"))
               .maximumMaxSizeBytes(104900000) // 100 MB
               .build()
      }
         .crossfade(true)
         .build()
}
```

Am I missing something, like an expected different behavior depending on cache type?

**To Reproduce**
I did a little [sample project](https://github.com/Shinokuni/coil-diskcache-bug) to reproduce the issue.

**Version**
Coil 2.7.0
Compose 2024.04.01/2024.06.00

**Comment by colinrtwhite** [comment]
Thanks for the repro project. Passing the memory cache and disk cache key directly to the `AsyncImage` `model` isn't supported. I'm not sure why the memory cache key case is working, but it's not intended. Coil's `DiskCache` isn't queried automatically - a `Fetcher` has to do it (currently only the `OkHttpFetcher` does for URLs).

Based on your use case I'd look into creating a custom `Fetcher` so you can pass it a URI (or something similar) and either read it from the disk cache or load the data using `loadIconByteArray`. Alternatively you could read and write your data directly using `DiskCache`'s APIs. If you pass a `ByteArray` as the `AsyncImage(model = ` that is supported.
