### ISSUE TITLE
[Coil 3] Frequent `ImageDecoder$DecodeException: Input was incomplete.` when displaying an Uri from the Android PhotoPicker in Compose Multiplatform.

### ISSUE THREAD

**Issue by kihaki** [coil-kt/coil#2434]
**Describe the bug**
I implemented an expect/actual wrapper for the [Android PhotoPicker](https://developer.android.com/training/data-storage/shared/photopicker) and use it to pick photos which reside in the google cloud.

I am returning the Uri of the picked images as a String and load them in coil for compose multiplatform like the following:

```
val uriFromPhotoPicker: String = /** This is the uri returned from the native android photo picker as String **/
AsyncImage(
  model = uriFromPhotoPicker,
  contentDescription = null,
)
```

This works **sometimes**, e.g. some of the photos picked are displayed fine, some of them produce the error below. I have not found a pattern to this yet, as all photos picked reside in the google cloud (the photo picker downloads them before returning them to my app).
Subjectively it feels like about 40% success, 60% failure rate, although I have not measured this yet.
To date I have never had this issue when developing a completely native Android App with Jetpack Compose and Coil (2.x.x)

I have granted persisted media access to all returned uris as described [here](https://developer.android.com/training/data-storage/shared/photopicker#persist-media-file-access). 

The uris that work and those that don't work also have the same pattern, here is one that works:
`content://media/picker/0/com.google.android.apps.photos.cloudpicker/media/05ad89e2-eefe-4cb4-b1fe-d725f0984415-1_all_48803`

Here is one that produces the error below:
`content://media/picker/0/com.google.android.apps.photos.cloudpicker/media/05ad89e2-eefe-4cb4-b1fe-d725f0984415-1_all_48822`

The images that work and don't work are from the exact same source (iPhone photo capture HEIC, uploaded into the Google Fotos app and then used on an Android Phone, through the Google Photos cloud, probably converted on the way somewhere).

**Logs/Screenshots**
```
android.graphics.ImageDecoder$DecodeException: Input was incomplete.
	at android.graphics.ImageDecoder.onPartialImage(ImageDecoder.java:2086)
	at android.graphics.ImageDecoder.nDecodeBitmap(Native Method)
	at android.graphics.ImageDecoder.decodeBitmapInternal(ImageDecoder.java:1674)
	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1863)
	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1848)
	at coil3.decode.StaticImageDecoder.decode(StaticImageDecoder.kt:143)
	at coil3.intercept.EngineInterceptor.decode(EngineInterceptor.kt:191)
	at coil3.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:32)
	at coil3.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:121)
	at coil3.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:8)
	at coil3.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at coil3.intercept.EngineInterceptor.execute(EngineInterceptor.kt:120)
	at coil3.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:32)
	at coil3.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**Version**
My coil version is `3.0.0-alpha09`, the artifacts are `io.coil-kt.coil3:coil`, `io.coil-kt.coil3:coil-compose` and `io.coil-kt.coil3:coil-network-ktor2`

**Comment by kihaki** [comment]
I have just tested the same images on Coil 2.x and Jetpack Compose in an Android Native app and the images show fine, no `DecodeException` - if that helps

**Comment by colinrtwhite** [comment]
If you set a custom `ExifOrientationPolicy` in `ImageLoader.Builder` does it fix the issue? This sounds like it could be an underlying issue with [ImageDecoder](https://developer.android.com/reference/android/graphics/ImageDecoder) unfortunately. What APIs are you testing on?

**Comment by revonateB0T** [comment]
I suppose this is because https://github.com/coil-kt/coil/pull/1990, but I can't reproduce it.
If `ContentProvider` provide a `AssetFileDescriptor` that inner FileDescriptor doesn't support `lseek`, the we cannot share that AFD.
Literally we need to do a fallback for AFDs that doesn't support seek(i.e. fallback to not share, use URI directly)
See https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/graphics/java/android/graphics/ImageDecoder.java;drc=18311bd177e42e4a29ac81d4897ddfe6ded5b96c;l=377
IDK if this helps.

**Comment by revonateB0T** [comment]
IMO currently workaround could be forbidden StaticImageDecoder create sources from certain blacklist(com.google.android.apps.photos.cloudpicker) of `ContentProvider`

**Comment by revonateB0T** [comment]
So I mean, If you can still reproduce that, you try `ImageDecoder.createSource` from that URI, and decode that source, if you still got "Incomplete input", then we know it's either a `ImageDecoder` internal bug or "Google Photos" bug.

**Comment by colinrtwhite** [comment]
@revonateB0T Thanks for taking a look! I don't think we can effectively maintain a blocklist for cases like this as it will very tough to maintain. Is there any way to detect if file descriptor supports `lseek`? We can fall back to `BitmapFactoryDecoder` if it doesn't support it.

**Comment by revonateB0T** [comment]
> @revonateB0T Thanks for taking a look! I don't think we can effectively maintain a blocklist for cases like this as it will very tough to maintain. Is there any way to detect if file descriptor supports `lseek`? We can fall back to `BitmapFactoryDecoder` if it doesn't support it.

Yeah! just try `lseek` on that fd.
```
val afd = metadata.assetFileDescriptor
val imageSource = try {
    Os.lseek(afd.fileDescriptor, afd.startOffset, SEEK_SET)
    ImageDecoder.createSource { metadata.assetFileDescriptor }
} catch (e: ErrnoException) {
    ImageDecoder.createSource(options.context.contentResolver, metadata.uri.toAndroidUri())
}
```

**Comment by kihaki** [comment]
I just got back to this and looks like it was solved in the meantime, so I will just say you guys are amazing
