### ISSUE TITLE
Web client fails due to CORS policy

### ISSUE THREAD

**Issue by oblakr24** [coil-kt/coil#2448]
**Describe the bug**
The fetch to an image (in my case, hosted on S3) fails due to:
```
Access to fetch at ... from origin '...' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I am not sure why this is not an issue on Android/iOS/JVM, but it would be good to at least have an easy way for a workaround from the client side, without having to do a proxy. I tried customizing the request but I do not see anything relevant for this in the documentation nor the API surface.

**To Reproduce**
Use the web client to fetch an image hosted on S3 or similarly:
`https://ecmr-rok-test.s3.us-east-2.amazonaws.com/S3_CMR_custom_signature_1_1722456949339_sender_signature.png`

**Version**
3.0.0-alpha10

**Comment by colinrtwhite** [comment]
How would Coil fix this from the client? I don't think it's possible to work around this from the client and any attempt to do so would circumvent the CORS security policy.

**Comment by colinrtwhite** [comment]
Reading more about this I don't this it's possible for Coil to fix. Your server needs to set the `Access-Control-Allow-Origin` header or the browser will block any requests not to that domain.

**Comment by oblakr24** [comment]
I figured out it is indeed an issue on the server side (my bucket). Thank you!
