### ISSUE TITLE
Can a rooted device access cached images using Coil?

### ISSUE THREAD

**Issue by DeepPSingh** [coil-kt/coil#245]
I am working on an app which needs to make sure that cached images are not accessible to anyone. I am using Coil to cache images on the disk.

Can someone who has a rooted device access cached images using Coil? This can be a security issue for us and if you have already done some testing on this area can you please let me know your findings?

Thanks in advance.

**Comment by colinrtwhite** [comment]
I believe a rooted user will be able to access any folder on the device including the cache folder. This will be true of all image loaders.

**Comment by DeepPSingh** [comment]
Thanks for the quick response. Is there a way we can restrict the user accessing it or encrypting and decrypting while saving and retrieving the cached file?

**Comment by colinrtwhite** [comment]
[I don't think it's possible, unfortunately](https://github.com/coil-kt/coil/issues/231).

**Comment by colinrtwhite** [comment]
There's a feature request for encryption [here](https://github.com/square/okhttp/issues/2903#issuecomment-268608758).

**Comment by DeepPSingh** [comment]
Ok thanks.
