### ISSUE TITLE
listener and target not being executed when load animated images

### ISSUE THREAD

**Issue by SofiaTejerina** [coil-kt/coil#2453]
**Describe the bug**
I'm trying to run things using both listener and target but they don't run when I use a gif image or an animated webp for example, formats like jpg do work fine.

**To Reproduce**

```kotlin
val builder = ImageRequest.Builder(context = context.applicationContext)
            .data(data = url)
            .memoryCacheKey(key = url.toString())
            .diskCacheKey(key = url.toString())

builder.target(view)

builder.crossfade(enable = true)
builder.crossfade(durationMillis = 500)
builder.transitionFactory(transition = CrossfadeTransition.Factory())
builder.dispatcher(dispatcher = Dispatchers.IO)
builder.allowConversionToBitmap(enable = false)
builder.decoderFactory(factory = ImageDecoderDecoder.Factory())

builder.listener { _, result ->
     Log.i("Test", result)
}
    .target(target = object : ImageViewTarget(imageView) {
            override fun onStart(placeholder: Drawable?) {
                super.onStart(placeholder = placeholder)
                Log.i("Test", result)
            }

            override fun onSuccess(result: Drawable) {
                super.onSuccess(result = result)
                Log.i("Test", result)
            }

            override fun onError(error: Drawable?) {
                super.onError(error = error)
                Log.i("Test", result)
            }
})
imageLoader(context.applicationContext).enqueue(builder.build())
```

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

I found this that could be related with my issue but didn't help me:
https://github.com/coil-kt/coil/issues/606
https://github.com/coil-kt/coil/pull/676

**Version**
I'm using coil 2.6.0

Thanks!  🙌

**Comment by colinrtwhite** [comment]
Sorry I can't provide 1:1 support for this kind of issue. I'd make sure that `Animatable.start` is being called on your `Drawable`. Also it sounds like you might want to use `onAnimationStart/End` instead of a regular listener.
