### ISSUE TITLE
Reload image periodically

### ISSUE THREAD

**Issue by JJSarrasin** [coil-kt/coil#2457]
I don't know if it's something already present, but I didn't find any documentation about it.

I'm using Coil 3.0 alpha (by the way thanks for the amazing lib) and I'd like to reload an image every 30s with the same url.

I have the following very simple code sample and by disabling the cache I expect at least when I scroll down and come back up to have the image reloaded. It's not the case.

In addition to that, I'd like to automate a reload of the image every 30s. How could i schedule that ?

`
val request = ImageRequest.Builder(context)
                .data(myImageUrl)
                .crossfade(0)
                .memoryCachePolicy(CachePolicy.DISABLED)
                .build()

            AsyncImage(
                modifier = Modifier.fillMaxSize(),
                model = request,
                contentDescription = null
            )
`

**Comment by colinrtwhite** [comment]
You'll need to disable the disk cache with `diskCachePolicy(CachePolicy.DISABLED)` to have it refetch the resource from the URL.

In terms of reloading periodically I think this is best left as to be implemented by the user. You can set up a [coroutines timer flow](https://stackoverflow.com/questions/54827455/how-to-implement-timer-with-kotlin-coroutines) that will [retry the request](https://github.com/coil-kt/coil/issues/884) according to your interval.
