### ISSUE TITLE
Svg image not fill imageview sizes

### ISSUE THREAD

**Issue by davidpladev** [coil-kt/coil#246]
I have an imageview with fixed with and height. When the image is displayed, it doesn't fill the imageview, so blank padding is showing. The doc said that the library autodetect the imageview scale type but these doesn't work. 

<ImageView
            android:id="@+id/image"
            android:layout_width="80dp"
            android:background="@color/bg_app"
            android:layout_height="80dp"
            android:layout_marginBottom="8dp"
            android:scaleType="fitXY"
            android:layout_gravity="center_horizontal"
            />

![device-2020-01-16-133952](https://user-images.githubusercontent.com/57840484/72552803-a50a7600-3865-11ea-990c-e8e80835fcf9.png)

**Comment by colinrtwhite** [comment]
Thanks for the report. Can you attach the SVG that reproduces the issue?

**Comment by davidpladev** [comment]
| <svg width="142" height="40" xmlns="http://www.w3.org/2000/svg"><g fill="#FFFFFE" fill-rule="evenodd"><path d="M10.65 30.31C5.05 30.31 0 26.741 0 18.952 0 11.16 5.05 7.596 10.65 7.596c5.597 0 10.64 3.564 10.64 11.357 0 7.789-5.043 11.356-10.64 11.356m0-17.927c-4.235 0-5.006 3.814-5.006 6.57 0 2.753.77 6.572 5.007 6.572 4.229 0 5.004-3.819 5.004-6.571 0-2.757-.775-6.571-5.004-6.571M25.175 8.164h5.389v2.527c1.029-1.364 3.556-2.971 5.93-2.971.222 0 .502 0 .735.033v5.32h-.28c-2.458 0-5.156.382-6.025 2.294V29.68h-5.75V8.164M52.276 27.807c-2.192 1.444-4.563 2.138-7.116 2.138-4.015 0-6.396-2.669-6.396-6.254 0-4.822 4.429-7.367 13.556-8.393v-1.2c0-1.563-1.185-2.48-3.378-2.48-2.19 0-3.967.87-5.255 2.48L39.87 11.92c2.004-2.807 5.058-4.21 9.164-4.21 5.614 0 8.767 2.432 8.767 6.388 0 0-.01 15.557 0 15.593h-5.022l-.502-1.884zm-7.934-4.534c0 1.45.909 2.803 2.553 2.803 1.778 0 3.512-.738 5.247-2.272v-5.095c-5.295.655-7.8 2.022-7.8 4.564zM62.273 8.735l4.69-.64.517 2.549c2.644-1.939 4.745-2.964 7.385-2.964 4.433 0 6.72 2.35 6.72 7.004v14.978h-5.669v-14c0-2.633-.68-3.818-2.73-3.818-1.688 0-3.379.767-5.31 2.389v15.429h-5.603V8.735M95.44 25.058c4.298-.029 4.67-4.41 4.67-7.25 0-3.379-1.652-6.106-4.703-6.106-2.032 0-4.312 1.49-4.312 6.338 0 2.647.192 7.055 4.345 7.018m10.11-16.97v20.374c0 3.589-.288 9.523-10.535 9.578-4.233.03-8.16-1.665-8.935-5.36l5.582-.898c.229 1.058.88 2.105 4.05 2.105 2.939 0 4.346-1.403 4.346-4.763v-2.506l-.073-.073c-.901 1.611-2.272 3.135-5.552 3.135-5.022 0-8.971-3.484-8.971-10.756 0-7.2 4.076-11.23 8.643-11.237 4.306-.007 5.888 1.953 6.259 2.978l-.073-.007.469-2.57h4.79M119.084 30.076c-6.342 0-10.12-4.087-10.12-11.163 0-7.16 3.829-11.237 10.029-11.237 6.207 0 9.902 3.957 9.902 10.953 0 .375-.044.742-.044 1.113h-14.327c.036 4.083 1.734 6.138 5.065 6.138 2.138 0 3.56-.862 4.887-2.756l4.139 2.298c-1.822 3.054-5.106 4.654-9.531 4.654m4.247-14.007c0-2.873-1.647-4.57-4.338-4.57-2.557 0-4.157 1.657-4.382 4.57h8.72M138.59 0l-2.092 5.393L134.382 0h-1.818v7.113h1.181V1.178h.026l2.33 5.935h.754l2.323-5.935h.037v5.935h1.17V0h-1.796zm-13.1 0v.945h2.223v6.168h1.182V.945h2.229V0h-5.633z"/></g></svg>
-- | --


Sorry, editor doesn't let me upload SVG extension.

**Comment by davidpladev** [comment]
https://testing-chatweb.biduzz.com/images/orange/logo-chats-app.svg

**Comment by colinrtwhite** [comment]
@davidpladev That SVG doesn't render correctly in Chrome. Are you sure it's correct?

**Comment by davisoqt** [comment]
Yes, Glidetovectoryou render ok that svg

**Comment by davisoqt** [comment]
What did you see wrong in the svg code?

**Comment by colinrtwhite** [comment]
Ah I see it has a `#FFFFFE` fill. Changing it to `#000000` shows the SVG. Taking a look.

**Comment by colinrtwhite** [comment]
Looks like this is caused by the SVG not setting a `viewBox`. Adding `viewBox="0 0 142 40"` to the `svg` tag fixes the issue. I'm also adding a fix to `0.9.2` that will set a default `viewBox` if the SVG doesn't specify one.

**Comment by davisoqt** [comment]
When the 0.9.2 will be available? Can you sendme the patch code to solve the issue? The app has more than 100 svg files and add a viewbox to each its not a option.😣

**Comment by colinrtwhite** [comment]
You'll be able to access a [snapshot](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots) build containing the fix once it deploys in a couple minutes. `0.9.2` will likely be available in a couple days.

**Comment by davisoqt** [comment]
So I need use the 0.10.0 snapshot version?

**Comment by colinrtwhite** [comment]
Yes
