### ISSUE TITLE
allowHardware(false) uses on compose multiplatform

### ISSUE THREAD

**Issue by Moozart** [coil-kt/coil#2472]
Hey Coilers, Are there any way to use allowHardware(false) in compose multiplatform via commonMain? or do you plan to add this.

**Comment by colinrtwhite** [comment]
There was a previous discussion around this [here](https://github.com/coil-kt/coil/issues/2429). As of now there aren't any plans to change this behaviour so I'd recommend creating a local `expect`/`actual` for this function.
