### ISSUE TITLE
[Coil 3/coil-video] How to use VideoFrameDecoder in Coil 3?

### ISSUE THREAD

**Issue by MHShetty** [coil-kt/coil#2484]
### Discussed in https://github.com/coil-kt/coil/discussions/2482

<div type='discussions-op-text'>

<sup>Originally posted by **MHShetty** September 12, 2024</sup>
I have imported the following dependencies

```
implementation("io.coil-kt.coil3:coil-compose-core:3.0.0-alpha10")
implementation("io.coil-kt.coil3:coil-core:3.0.0-alpha10")
implementation("io.coil-kt:coil-video:2.7.0")
```

However, I'm only able to import `VideoFrameDecoder` for Coil 2.x in Android Studio using `import coil.decoder.VideoFrameDecoder`

Using `coil.decoder.VideoFrameDecoder` imports the VideoFrameDecoder that extends the `Decoder` of Coil 2.x which is incompatible with the Coil 3's `ImageLoader`

Do I need to import a different set of dependencies to use `VideoFrameDecoder` with Coil 3?</div>

**Comment by colinrtwhite** [comment]
Yep you'll want to import `implementation("io.coil-kt.coil3:coil-video:3.0.0-alpha10")`. After that you can force it to be used for an `ImageRequest` using `ImageRequest.Builder.decoderFactory` or your data will automatically be decoded as a video if the file/url ends with a video suffix (`.mp4`, `webm`, etc.).

**Comment by MHShetty** [comment]
Yes importing the given dependency does help resolve the issue. Thanks a lot for your help and support!
