### ISSUE TITLE
[Coil 3] VectorDrawable @Preview doesn't work

### ISSUE THREAD

**Issue by OKatrych** [coil-kt/coil#2489]
**Describe the bug**
After the [last fix](https://github.com/coil-kt/coil/issues/1915), the AsyncImage `@Preview` render started working only for raster images. If we put a VectorDrawable as an argument, it doesn't render the preview image.

**To Reproduce**
Here, in this case, `eu_flag` is WebP and `fi_flag` is XML:
![346539606-afaa8a34-3d03-45ce-9a96-e82d9019637a](https://github.com/user-attachments/assets/d1af3ff1-bf50-49df-bab6-9d3202a4bee2)
Here is a preview:
![346539612-33abd3a1-0315-4533-9d74-058e4dd68844](https://github.com/user-attachments/assets/78f5c1e3-30aa-4715-be9c-e3f7514a2f01)
And if I move `fi_flag` to be shown before the `eu_flag`, it fails to render both of them:
![346540363-ec6cde69-18bb-4bd4-85de-93438e4bb2f9](https://github.com/user-attachments/assets/3619b77d-6808-483b-aef3-1c995f67b1df)

![346540365-6aa57bfa-fffe-4447-98e1-4ba2b14a20c5](https://github.com/user-attachments/assets/d08a5e44-c06b-41ca-98fc-6d4857abffa7)

**Version**
3.0.0-alpha10

**Comment by colinrtwhite** [comment]
Interesting I wonder if we need to add some special handling for XML drawables inside the preview environment. The current implementation delegates to the same way we load them on a real device so we can ideally keep the loading logic consistent. We probably need to add special handling for this case in [here](https://github.com/coil-kt/coil/blob/main/coil-core/src/androidMain/kotlin/coil3/fetch/ResourceUriFetcher.kt).

**Comment by tgyuuAn** [comment]
@OKatrych 

I'd like to take on this issue, but I can't reproduce it. 

In my case, when I tried rendering fi_flag with svg vector drawable and eu_flag with webp in version 3.0.0 alpha 10, both came out fine.

Could you please tell me more about the issue?

<img width="1342" alt="image" src="https://github.com/user-attachments/assets/0b7205f9-e9a8-441c-a9f2-44a64ab8757d">

**Comment by colinrtwhite** [comment]
@tgyuuAn Thanks for taking a look! I was able to repro the bug [here](https://github.com/coil-kt/coil/commit/430dabc36cf359bb8e52bcf1f523e2f0eb3b6b62) on Android Studio Ladybug 2024.2.1 Patch 1 and Ladybug Feature Drop 2024.2.2 Canary 8.

**Comment by tgyuuAn** [comment]
> @tgyuuAn봐주셔서 감사합니다! Android Studio Ladybug 2024.2.1 Patch 1과 Ladybug Feature Drop 2024.2.2 Canary 8 on Mac Sequoia 15.1에서 [버그 를 재현할 수 있었습니다.](https://github.com/coil-kt/coil/commit/430dabc36cf359bb8e52bcf1f523e2f0eb3b6b62)

Thank you !!! 🙃🙃

**Comment by colinrtwhite** [comment]
@tgyuuAn Were you able to take a look at this issue?

**Comment by tgyuuAn** [comment]
> @tgyuuAn Were you able to take a look at this issue?

Unfortunately, I wasn't able to reproduce the issue, and it seems that there are quite a few bugs in the Ladybug version. I'm looking forward to the next version being released soon...

**Comment by colinrtwhite** [comment]
Yep, I'm still able to reproduce this in Android Studio Ladybug 2024.2.1 Patch 2 and Meerkat 2024.3.1 Canary 3.

**Comment by colinrtwhite** [comment]
@SandraDupreDNA What do you mean by direct vector resources?
