### ISSUE TITLE
How to use start error callbacks in coil ?

### ISSUE THREAD

**Issue by vrsrohit** [coil-kt/coil#249]
**Describe the bug**
I want to download a bitmap using coil and want to show loading indicator until it downloads so i want on error on succses callbacks in custom target to handle my ui.

**Expected behavior**
In Picasso onSuccsess and on Error callbacks are there I am expecting like that

**Version**
What library version are you using? 
0.9.1 - version

**Comment by colinrtwhite** [comment]
You need to create a [Target[(https://coil-kt.github.io/coil/targets/).

**Comment by vrsrohit** [comment]
ya tried it but was not able to get onSuccess and onError overridden methods
Can you please point me towards a Example code.

**Comment by vrsrohit** [comment]
I meant like if I can get on error and onSuccess I need to show a toast, so I need them as callbacks.

**Comment by colinrtwhite** [comment]
@vrsrohit If you're loading into an `ImageView` you could do something like this:

```kotlin
imageView.load(data) {
    listener(
        onError = { /** Show toast. */ },
        onSuccess = { /** Show toast. */ }
    )
}
```

**Comment by vrsrohit** [comment]
Actually I am downloading the image into bitmap for further usage . What can I do in this case

**Comment by colinrtwhite** [comment]
This will handle that case:

```kotlin
Coil.load(context, data) {
    target(
        onError = { /** Show toast. */ },
        onSuccess = { result ->
            val bitmap = (result as BitmapDrawable).bitmap
        }
    )
}
```

**Comment by vrsrohit** [comment]
yaa, It's working thanx man.
Great work with the library !!

**Comment by nonimdiana** [comment]
@colinrtwhite, I found this awesome too! (as of `Coil version 1.2.2`)
```kotlin
imageView.load("link") {
    listener(onSuccess = { _, _ ->
        // do something
    }, onError = { request: ImageRequest, throwable: Throwable ->
        // handle error here
    })
}
```
