### ISSUE TITLE
Image Request will retry multiple times if State.Loading and State.Error have different contentScale value

### ISSUE THREAD

**Issue by kevinzheng-ap** [coil-kt/coil#2494]
**Describe the bug**
Image Request will retry multiple times if `State.Loading` and `State.Error` have different `contentScale` value. However, the expected behaviour should be that the request does not retry simply due to a change in `contentScale` after an error occurs.

**To Reproduce**
```
val state = remember {
    mutableStateOf<AsyncImagePainter.State>(AsyncImagePainter.State.Empty)
}
    
AsyncImage(
     model = "something wrong",
     contentDescription = null,
     contentScale = if (state.value is AsyncImagePainter.State.Error) ContentScale.None else ContentScale.Crop,
     onState = {
         Log.d("Coil sample", "Set state $it")
         state.value = it
     }
)
```

**Logs/Screenshots**
In the log from above sample, state changes multiple times between loading and error before it is finally settled.

<img width="840" alt="Screenshot 2024-09-19 at 9 54 25 PM" src="https://github.com/user-attachments/assets/a3aa4e4c-10f0-43f7-9ec4-446b44ff7359">

**Version**
2.7.0

**Comment by ojasvib** [comment]
Since state is an observable on which the AsyncImage's contentScale is dependent, it is triggering a re-composition of the AsyncImage composable  every time the state changes. I think this is not a bug and is expected behavior.

**Comment by kevinzheng-ap** [comment]
@ojasvib Thanks for replying. I understand this is current behaviour, just thinking if any enhancement can be done here to avoid the state changes from error back to load if just contentScale changes. 

Or what is the recommended way if I need to handle different contentScale values for different states to avoid state changes livelock as the sample code. Thanks

**Comment by colinrtwhite** [comment]
As @ojasvib mentioned, this is working as intended. Changing the `contentScale` can affect the underlying `ImageRequest.scale`, which can change the target's dimensions that image will be loaded into. To change the `contentScale` without triggering a new request you can use `rememberAsyncImagePainter` with a regular `Image` or you might be able to set `ImageRequest.Builder.scale` manually so when it triggers a new request it will resolve from the memory cache instantly.
