### ISSUE TITLE
Images do not fully load on some screens (cropping and incomplete loading)

### ISSUE THREAD

**Issue by Lynnk-S** [coil-kt/coil#2495]
**Describe the bug**
While navigating in my application, some images occasionally do not load completely and appear cropped. This issue occurs on devices with Android 14 (8+4 GB of RAM), but I have also noticed it happens more frequently on earlier API versions. I suspect the problem is exacerbated on lower-performance devices or when handling many images at once, or due to their quality.

I am using a component called AssetImage that loads images from the assets folder using URIs.
 My code : 

    @Composable
        fun AssetImage(
            fileName: String,
            folder: String,
            context: Context,
            mainViewModel: MainViewModel,
            modifier: Modifier = Modifier,
            contentScale: ContentScale = ContentScale.Fit,
            placeholderResId: Int = R.drawable.m1,
            size: Size = Size.ORIGINAL
        ) {
            var isLoading by remember { mutableStateOf(true) }
            val imageUri = mainViewModel.getUriFromAssets(context, fileName, folder)
            val imageRequest = ImageRequest.Builder(context)
                .data(imageUri)
                .size(size)
                .error(placeholderResId) 
                .build()
            val painter = rememberAsyncImagePainter(
                model = imageRequest,
                onLoading = {
                    isLoading = true
                },
                onError = {
                    isLoading = false
                },
                onSuccess = {
                    isLoading = false
                }
            )
            Box(modifier = modifier) {
                if (isLoading) {
                    CircularProgressIndicator(modifier = Modifier.align(Alignment.Center))
                } else {
                    Image(
                        painter = painter,
                        contentDescription = fileName,
                        contentScale = contentScale,
                        modifier = Modifier.fillMaxWidth()
                    )
                }
            }
        }

**To Reproduce**
Navigate to a screen that contains images.  
Observe that some images do not load completely or appear cropped.

**Screenshots**  
**Expected behavior (always):**  
| ![Expected Always](https://github.com/user-attachments/assets/58d1a05b-5ef4-4480-97f8-841b23605ddf) | ![Expected Always](https://github.com/user-attachments/assets/85af78ce-f806-4668-b078-3c22f6032bc1) |
|:--:|:--:|

**Actual behavior (occasionally cropped):**  
| ![Sometimes](https://github.com/user-attachments/assets/3d390e02-1c71-41e0-86d7-46d6889e72cb) | ![Sometimes](https://github.com/user-attachments/assets/aa2ba87e-a2a3-46b3-9dec-dd8165551dfa) |
|:--:|:--:|

**Version**

2.7.0

**Comment by colinrtwhite** [comment]
Can you include a small sample project that reproduces this issue? I tried reproducing locally with your code, but wasn't able to reproduce. Also is a final state always reached (error/success)? If it's error, what is the stacktrace?
