### ISSUE TITLE
Android Compose: GIFs not animating when they have no .gif extension

### ISSUE THREAD

**Issue by MaartenDEV** [coil-kt/coil#2497]
**Describe the bug**
Loading GIFs in the AsyncImage only animates them when the URL ends with ".gif". When they don't, the first frame is displayed.

**Version**
2.7.0, Android with Jetpack Compose

**Comment by colinrtwhite** [comment]
Please provide code to reproduce this including a GIF that causes this issue. Coil's GIF decoder already has detection to check for GIF headers.

**Comment by MaartenDEV** [comment]
Terribly sorry, our server hosts GIFs without an extension, and I assumed that was the reason they weren't animating as other files with extensions did work. I now realise our server probably doesn't include the correct headers, as other GIFs I find online without an extension do work.

**Comment by colinrtwhite** [comment]
@MaartenDEV Sorry by GIF headers I meant a code at the start of the file that indicates the file is a GIF (according to the GIF spec). We check for them [here](https://github.com/coil-kt/coil/blob/main/coil-gif/src/main/java/coil3/gif/decodeUtils.kt#L27). Do you have an example GIF that Coil doesn't detect correctly?

**Comment by MaartenDEV** [comment]
@colinrtwhite As far as I know, Coil works great for GIFs. It turns out our image resizing service wasn't properly configured for GIFs, so the error was on our side, not on Coils.
