### ISSUE TITLE
Exif rotation not applied for locally saved images/images taken with camera on some devices  

### ISSUE THREAD

**Issue by dominikgold** [coil-kt/coil#250]
Hi, first off, thanks for the great work on this library.

We're facing one issue when using Coil for loading images with Exif rotation which are saved on the device, using the `load(Uri)` function. The Exif rotation is not applied at all. This was reproducible on 2 of our test devices, an LG G3 and an LG G2 Mini, both API 21. I'm assuming it's the same on other devices with API 21, though I don't know for sure.

The `ExifInterface.getRotationDegrees()` call used in `BitmapFactoryDecoder.decode()` always returns 0 on these devices.

Here's a small sample app demonstrating the issue:
[https://github.com/dominikgold/CoilExifRotationTest](https://github.com/dominikgold/CoilExifRotationTest)

**Comment by colinrtwhite** [comment]
Thanks for the report. Can you upload the image file taken by the camera? If `ExifInterface.getRotationDegrees()` is returning 0 I'm afraid the image might not have its EXIF orientation set (some devices do this) in which case it's not possible to fix this.

**Comment by dominikgold** [comment]
Hey, thanks for the quick reply,  I'll gladly attach an example image.
I've also extended the example project with our custom implementation for loading bitmaps, which we would like to get rid of in favor of Coil. That one loads the image just fine. Here's the relevant class:

[https://github.com/dominikgold/CoilExifRotationTest/blob/master/app/src/main/java/com/golddev/myapplication/BitmapLoader.kt](https://github.com/dominikgold/CoilExifRotationTest/blob/master/app/src/main/java/com/golddev/myapplication/BitmapLoader.kt)

![20200120_095104](https://user-images.githubusercontent.com/9554308/72716220-26b61880-3b72-11ea-811f-f6d304bd1749.jpg)

**Comment by mario** [comment]
@colinrtwhite I'll take a look at this one tomorrow.

**Comment by mario** [comment]
So I looked into this particular issue and the issue regarding rotations in general. @colinrtwhite is, of course, right that EXIF is just a supporting tool to get the rotation. In general, I wouldn't rely on it much since, like you've found, it can be missing. There are alternative ways to handle this, especially in cases like yours when you're doing a camera snapshot:

https://medium.com/@kenodoggy/solving-image-rotation-on-android-using-camera2-api-7b3ed3518ab6

Other than with an emulator, I had no way to reproduce this, and with emulator the issue doesn't appear.

**Comment by dominikgold** [comment]
Hey @mario, thank you for looking into this. Maybe for some clarification, the image definitely has an Exif rotation set, and it's also readable, when using the ExifInterface(String) constructor. Our current suspicion is that the Exif rotation gets lost/can't be read anymore after converting the file to an okio BufferedSource. However, it it is hard to reproduce, since it seems to happen only on a few devices. We'll try to find a fix and then I'll update this issue.
