### ISSUE TITLE
Handle CacheControl, Etag, If-Modified-Since

### ISSUE THREAD

**Issue by alirezanazari** [coil-kt/coil#2510]
**Is your feature request related to a problem? Please describe.**
I want Coil handle image request headers automatically, and having advance control on caching process like when content changed automatically download new version of image or check cached image is valid to keep using cache or not.

**Describe the solution you'd like**
There is Interceptors and we can check it and handle headers but if we are not going to handle advance caching it's better to have some functionality to delete cache by key.

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match

**Comment by colinrtwhite** [comment]
Implemented [here](https://github.com/coil-kt/coil/pull/2507) for Coil 3. This is already supported in Coil 2.
