### ISSUE TITLE
`ImageDecoderDecoder` and `GifDecoder` Unresolved

### ISSUE THREAD

**Issue by Sayum24** [coil-kt/coil#2536]
**Describe the bug**
I'm following the documentation of version `3.0.0-rc0`.
I want to use Coil in our Android-Kotlin-App in a Compose-view to display a GIF.
I added the following lines in my build.gradle:

```
implementation("io.coil-kt.coil3:coil-compose:3.0.0-rc01")
implementation("io.coil-kt.coil3:coil-network-okhttp:3.0.0-rc01")
implementation("io.coil-kt.coil3:coil-gifs:3.0.0-rc01")
```

And copied the following lines from the documentation:

```kt
val imageLoader = ImageLoader.Builder(LocalContext.current)
    .components {
        if (SDK_INT >= 28) {
            add(ImageDecoderDecoder.Factory())
        } else {
            add(GifDecoder.Factory())
        }
    }
    .build()
AsyncImage(
    model = "https://example.com/image.jpg",
    contentDescription = null,
)
```

The classes `ImageDecoderDecoder` and `GifDecoder` could not be found. How can I fix this?

**Version**
- coil: `3.0.0-rc01`
- app: `minSdk 26, targetSdk 34`

**Comment by Sayum24** [comment]
In the changelog.md I read that `ImageDecoderDecoder` was renamed to `AnimatedImageDecoder` but it wasn't found either.

**Comment by Mister-Seven** [comment]
@Sayum24 
change gifs to gif. it's ok

**Comment by Sayum24** [comment]
@Mister-Seven thanks! That fixed it.
So the documentation was wrong.

**Comment by Mister-Seven** [comment]
,你的邮件我已收到，尽快回复。

**Comment by colinrtwhite** [comment]
Whoops! Fixed here: https://github.com/coil-kt/coil/pull/2541
