### ISSUE TITLE
Class 'kotlinx.coroutines.GlobalScope' was compiled with an incompatible version of Kotlin.

### ISSUE THREAD

**Issue by Sayum24** [coil-kt/coil#2537]
**Describe the bug**
When adding the dependency in the build.gradle:app-file: `implementation("io.coil-kt.coil3:coil-gif:3.0.0-rc01")`

I get the following error when building the project:
```
Class 'kotlinx.coroutines.GlobalScope' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.0.0, expected version is 1.8.0.
The class is loaded from /Users/USERNAME/.gradle/caches/transforms-3/55652b38ede45b1e81c462fbd4bb1551/transformed/jetified-kotlinx-coroutines-core-jvm-1.9.0.jar!/kotlinx/coroutines/GlobalScope.class
```

**Version**
- native Android
- jvmTarget = '17'
- compileSdk 34
- implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0' (I also tried Version 1.9.0)

**Comment by colinrtwhite** [comment]
What Kotlin version are you using. You likely need to update to at least `1.9.0` - ideally `2.0.0` or greater.

**Comment by Sayum24** [comment]
We are still using Kotlin Version `1.8.0`.
I got it working with the following dependencies:
```
implementation "io.coil-kt:coil-gif:2.6.0"
implementation "io.coil-kt:coil-compose:2.6.0"
```
Thanks for your help!
