### ISSUE TITLE
Missing proguard/R8 Rules for Android

### ISSUE THREAD

**Issue by androidacy-user** [coil-kt/coil#2546]
**Describe the bug**
Release builds of app using coil3's SingletonImageLoader crash complaining about missing fields.

**To Reproduce**
Build APK as release after defining a SingletonImageLoader on the Application

**Logs/Screenshots**
N/A - multiple variants

**Version**
All devices, coil 3.0.0-rc01.

**Extra:**
Here's the rules we've come up with so far. There does not actually fix all the errors, nor are these particularly optimized.
```kotlin
-keep class coil3.RealImageLoader { *; }
-keep class coil3.util.SystemCallbacks { *; }
-keep class coil3.util.AndroidSystemCallbacks { *; }
-keep class coil3.SingletonImageLoader { *; }
-keep class coil3.SingletonImageLoader$SingletonImageLoader { *; }
```

**Comment by colinrtwhite** [comment]
What is the runtime error you're encountering and which AGP and R8 versions are you using? Coil shouldn't require any extra R8 rules as it doesn't use reflection (aside from a service loader, which R8 handles automatically).

The `sample/view` and `sample/compose` apps in this repo both use the `SingletonImageLoader` and build with R8 without runtime issues or extra rules.

**Comment by colinrtwhite** [comment]
What's the full stack trace (you can omit frames that reference your package)? It sounds like it could be related to [`atomicfu`](https://github.com/Kotlin/kotlinx-atomicfu), however that library doesn't require custom R8 rules either. Do you know how I might be able to reproduce this error in either of the sample apps?

**Comment by colinrtwhite** [comment]
I haven't been able to repro this locally unfortunately. It's possible this is caused by an R8 bug or a combination of local R8 rules, however I don't think it's something we can resolve inside Coil. The existing R8 rules should be OK for Coil 3.0 and work in both the sample apps as well as Cash App.
