### ISSUE TITLE
[Coil3] SVG image display delayed when loaded from memory cache

### ISSUE THREAD

**Issue by PhilipDukhov** [coil-kt/coil#2555]
**To Reproduce**

1. Use the provided code below.
2. Observe the rendering behavior after `isLoading` becomes `false` - at this point all the images are loaded into memory cache, so I expect them to be displayed immediately. 
3. Notice that most SVG images appear with a one-frame delay, while PNG images are displayed immediately.
```kotlin
var isLoading by remember { mutableStateOf(true) }
val images = listOf(
    "https://images.lumacdn.com/gallery-images/nu/9a3765bf-f5df-4fed-98ae-aa8a4735761d",
    "https://www.svgrepo.com/show/4733/samples.svg",
    "https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/ca.svg",
    "https://filesampleshub.com/download/image/svg/sample1.svg",
    "https://coil-kt.github.io/coil/images/coil_logo_black.svg",
) + List(10) { "https://picsum.photos/id/$it/200/200" }
val context = LocalContext.current
if (isLoading) {
    LaunchedEffect(Unit) {
        images
            .map { image ->
                val request = ImageRequest.Builder(context)
                    .data(image)
                    .decoderFactory(SvgDecoder.Factory())
                    .build()
                context.imageLoader
                    .enqueue(request)
                    .job
            }
            .awaitAll()
        isLoading = false
    }
} else {
    LazyVerticalGrid(
        GridCells.Adaptive(100.dp),
        modifier = Modifier
            .systemBarsPadding()
    ) {
        item {
            Text("Title")
        }
        items(images) { image ->
            coil3.compose.AsyncImage(
                image,
                contentDescription = null,
                modifier = Modifier
                    .size(100.dp)
            )
        }
    }
}
```

| First frame  | Second Frame |
| ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/88fbfef7-8dac-4a10-bc25-0e0d3b6e3b06" width="300" /> | <img src="https://github.com/user-attachments/assets/720dcc6e-6b51-4c66-872a-77b8310714cd" width="300" /> |

**Coil Version**: 3.0.0-rc01

It happens on different API versions(31, 35), both emulator and real device.

**Comment by colinrtwhite** [comment]
Thanks for the repro, however I believe this is working as expected:

- Your initial request doesn't specify a size so the SVG's source dimensions are used. In some of the SVGs, these dimensions are small (<200x200).
- When you load the SVG into the `AsyncImage` its dimensions are larger than the dimensions of the SVG image in the memory cache so it is not returned.

To have the SVG image returned from the memory cache, you should set a `ImageRequest.Builder.size` value that is greater or equal to the size of the `AsyncImage`. Alternatively you could set `ImageRequest.Builder.size` for both the initial request and the `AsyncImage` request to have them always match. There's [a log](https://github.com/coil-kt/coil/blob/main/coil-core/src/commonMain/kotlin/coil3/memory/MemoryCacheService.kt#L164) that's emitted in this case to make it easier to debug.
