### ISSUE TITLE
[Coil3?] APNG support using APNG4Android doesn't work

### ISSUE THREAD

**Issue by RobbWatershed** [coil-kt/coil#2557]
**Describe the bug**
I tried to add APNG support by using the method described in #506. The code I came up with for Coil3 is as follows

```kt
class AnimatedPngDecoder(private val source: ImageSource) : Decoder {

    override suspend fun decode(): DecodeResult {
        return DecodeResult(
            image = APNGDrawable.fromFile(source.file().toString()).asImage(),
            isSampled = false
        )
    }

    class Factory : Decoder.Factory {
        override fun create(
            result: SourceFetchResult,
            options: Options,
            imageLoader: ImageLoader
        ): Decoder? {
            return if (APNGParser.isAPNG(result.source.file().toString())) {
                AnimatedPngDecoder(result.source)
            } else {
                null
            }
        }
    }
}
```

Coil has been initialized as follows during app startup

```kt
SingletonImageLoader.setSafe {
            ImageLoader.Builder(context)
                .components {
                    // GIF
                    if (SDK_INT >= 28) {
                        add(AnimatedImageDecoder.Factory(false))
                    } else {
                        add(GifDecoder.Factory(false))
                    }
                    // APNG
                    add(AnimatedPngDecoder.Factory())
                }
                .build()
}
```

When I load the picture from disk, the Factory call works fine but `decode()` always fails because it doesn't find the file that has been successfuly read by the Factory moments before.

```
java.io.FileNotFoundException: /data/user/0/me.devsaki.hentoid.debug/cache/tmp_13103856800822388989: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at com.github.penfeizhou.animation.io.FileReader.<init>(FileReader.java:17)
	at com.github.penfeizhou.animation.loader.FileLoader.obtain(FileLoader.java:26)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:302)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(FrameSeqDecoder.java:287)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8046)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 10 more
```

I wonder if my code is fine, and/or if Coil3 has broken something compared to the sample code written for Coil2 in #506 

**To Reproduce**
Load an APNG file from disk using the above Decoder

**Logs/Screenshots**
See above

**Version**
3.0.0-rc01 on API30 (didn't test on other environments yet)

**Comment by colinrtwhite** [comment]
@RobbWatershed What's the `ImageRequest.data` value? You mentioned you're loading the image from disk, but it looks like it's creating a temp file: `/data/user/0/me.devsaki.hentoid.debug/cache/tmp_13103856800822388989`

**Comment by RobbWatershed** [comment]
Thanks for your reply.

The picture file is on the device's external storage (in Android terms). `ImageRequest.data` is the `Uri` of that file as a `DocumentFile` (e.g. content://com.android.externalstorage.documents/tree/primary%3ATest%2Fext-animated/document/primary%3ATest%2Fext-animated%2Ftest_animated%2Fcell_animation.webp).

I guess that file being copied as a temp internal file has something to do with the way Coil3 handles cache?

**Comment by colinrtwhite** [comment]
Ah yep, `ImageSource` will create a temp file when `source.file()` is called. `content://` uris can't generally be accessed via file system. Ideally, we can provide the `APNGDrawable` an `InputStream`/`Source` instead to avoid copying the image data to disk.

That said, it should still be able to read the temp file inside of `decode`. I'll test it out locally and see what's happening.

**Comment by RobbWatershed** [comment]
> Ideally, we can provide the APNGDrawable an InputStream/Source instead to avoid copying the image data to disk.

Definitely, as long as your implementation doesn't rely too much on low-level `File` stuff

> That said, it should still be able to read the temp file inside of decode. I'll test it out locally and see what's happening.

Thanks in advance. Do ping me if you need anything

**Comment by colinrtwhite** [comment]
Figured out the issue - this didn't really work for Coil either as `APNGDrawable` reads the file outside of `Decoder.decoder`, which is prohibited. Cases where temp files didn't need to be created worked, but had a race condition where the file in the disk cache could be deleted before `APNGDrawable` finishes reading it. Updated the code [here](https://github.com/coil-kt/coil/issues/506#issuecomment-952526682) to buffer the file into memory and it fixes the decode issues.

**Comment by RobbWatershed** [comment]
Thanks a bunch! 😄
