### ISSUE TITLE
Improve ImageLoader documentation to call out ConnectivityManager limitation

### ISSUE THREAD

**Issue by hborders** [coil-kt/coil#2567]
**Is your feature request related to a problem? Please describe.**

I recently had a bug similar to https://github.com/coil-kt/coil/issues/28 because the [javadoc on `ImageLoader`](https://github.com/coil-kt/coil/blob/main/coil-core/src/commonMain/kotlin/coil3/ImageLoader.kt#L26C1-L27C46) only says:

> * Image loaders are designed to be shareable and work best when you create a single
> * instance and share it throughout your app.

This doesn't indicate any hard limits. However, If you create a default `ImageLoader` with `ImageLoader(Context)`, coil will call [`ConnectivityManager.registerNetworkCallback`](https://developer.android.com/reference/android/net/ConnectivityManager#registerNetworkCallback(android.net.NetworkRequest,%20android.net.ConnectivityManager.NetworkCallback)), which says:

> To avoid performance issues due to apps leaking callbacks, the system will limit the number of outstanding requests to 100 per app (identified by their UID), shared with all variants of this method, of [requestNetwork(NetworkRequest, PendingIntent)](https://developer.android.com/reference/android/net/ConnectivityManager#requestNetwork(android.net.NetworkRequest,%20android.app.PendingIntent)) as well as [ConnectivityDiagnosticsManager#registerConnectivityDiagnosticsCallback](https://developer.android.com/reference/android/net/ConnectivityDiagnosticsManager#registerConnectivityDiagnosticsCallback(android.net.NetworkRequest,%20java.util.concurrent.Executor,%20android.net.ConnectivityDiagnosticsManager.ConnectivityDiagnosticsCallback)). Requesting a network with this method will count toward this limit. If this limit is exceeded, an exception will be thrown. To avoid hitting this issue and to conserve resources, make sure to unregister the callbacks with [unregisterNetworkCallback(android.net.ConnectivityManager.NetworkCallback)](https://developer.android.com/reference/android/net/ConnectivityManager#unregisterNetworkCallback(android.net.ConnectivityManager.NetworkCallback)).

Thus, if one creates more than `100` instances of `ImageLoader`, they are likely to start seeing Android throw exceptions, or have exceptions come out of other unexpected areas. In my case, `WorkManager` was throwing a `TooManyRequestsException`.

**Describe the solution you'd like**
The documentation should call out this limitation if your `ImageLoader` has `[networkObserverEnabled](https://github.com/coil-kt/coil/blob/2.7.0/coil-base/src/main/java/coil/util/ImageLoaderOptions.kt#L15) == true` (the default), then Android will crash after `100` instances. You could phrase this some other way for multiplatform concerns, but I think it is important to use stronger language than the current default.

**Additional context**
Thanks so much for this project!

**Comment by colinrtwhite** [comment]
@hborders Good point - though this should be resolved in Coil 3.0 as it no longer registers a connectivity observer. Considering the docs are being updated for Coil 3.0 I think it’s safe to close this ticket?

**Comment by hborders** [comment]
> though this should be resolved in Coil 3.0 as it no longer registers a connectivity observer. 

Nice! Does coil just piggyback on OkHttp now?

> Considering the docs are being updated for Coil 3.0 I think it’s safe to close this ticket?

Yes! I think it's safe to close this ticket.

**Comment by colinrtwhite** [comment]
Coil 3.0 has a new [`ConnectivityChecker`](https://github.com/coil-kt/coil/blob/main/coil-network-core/src/commonMain/kotlin/coil3/network/ConnectivityChecker.kt) interface so it's more configurable. The default implementation on Android uses [imperative APIs](https://github.com/coil-kt/coil/blob/main/coil-network-core/src/androidMain/kotlin/coil3/network/ConnectivityChecker.kt) under the hood that don't keep an observer. It's slightly less efficient than keeping an observer open, but it avoids other issues (like the observer limit) and the speed diff is minimal (<1ms) and is run on a background thread.
