### ISSUE TITLE
Image will not be shown if the parent's size is `IntrinsicSize`

### ISSUE THREAD

**Issue by alexstyl** [coil-kt/coil#2573]
**Describe the bug**

The following code does not render the image, even if the image success callback is triggered:

```kotlin
Column(Modifier.width(IntrinsicSize.Min).height(IntrinsicSize.Max)) {
        AsyncImage(
            model = "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            contentDescription = null
        )
}
```

Removing the IntrinsicSize on the parent works and the image takes as much space as it needs.

In the Intrinsic Size scenario I would expect the async image to take as much space as it needs (similar to wrapContentSize()) after it is loaded.

**Version**
Coil: 3.0.0-alpha06
On CMP: 1.7.0 JVM

**Comment by colinrtwhite** [comment]
Hmm it looks like this could be related to https://github.com/coil-kt/coil/issues/2349. Will take a look.

**Comment by alexstyl** [comment]
@colinrtwhite appreciated. do you have any potential workarounds in the meantime?

**Comment by colinrtwhite** [comment]
@alexstyl Migrating to `rememberAsyncImagePainter` seems to work around the issue:

```kotlin
Column(Modifier.width(IntrinsicSize.Min).height(IntrinsicSize.Max)) {
        Image(
            painter = rememberAsyncImagePainter("https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
            contentDescription = null,
        )
}
```
