### ISSUE TITLE
Performance issue in compose

### ISSUE THREAD

**Issue by JJSarrasin** [coil-kt/coil#2584]
I use the up-to-date coil3 (rc01) in Compose. I really like the API and all the lib so far. My only concerns is about the performance. I have to target low-end TV devices like box operator and it is very laggy (especially if the image aren't in cache.
The behavior in LazyRow and LazyColumn works kind of well, if you display the performance bar on screen, it's not that good, but it's "ok". The main issue is in the grid.

I use the folllowing code to test it quickly:

```kotlin
    val context = LocalContext.current
    val list = remember { List(500) { index -> "Test $index" } }
    val imageList = Array(500, { i -> "https://picsum.photos/seed/${Math.random()}}/600/400" })

    LazyVerticalGrid(
        modifier = Modifier.padding(50.dp),
        columns = GridCells.Fixed(4),
        verticalArrangement = Arrangement.spacedBy(10.dp),
        horizontalArrangement = Arrangement.spacedBy(20.dp)
    ) {
        itemsIndexed(
            items = list,
            key = { index, item -> item }
        ) { index, item ->
            var hasFocus by remember{ mutableStateOf(false) }

            Box(
                modifier = Modifier
                    .size(width = 170.dp, height = 100.dp)
                    .clip(RoundedCornerShape(10.dp))
                    .border(width = if (hasFocus) 5.dp else 0.dp, color = Color.Red)
                    .onFocusChanged { hasFocus = it.hasFocus }
                    .focusable(),
                contentAlignment = Alignment.Center
            ) {
                val request = ImageRequest.Builder(context)
                    .data(imageList[index])
                    .crossfade(0)
                    //.memoryCachePolicy(CachePolicy.DISABLED)
                    //.diskCachePolicy(CachePolicy.DISABLED)
                    .build()

                AsyncImage(
                    modifier = Modifier
                        .fillMaxSize(),
                    contentScale = ContentScale.Crop,
                    alignment = Alignment.Center,
                    model = request,
                    contentDescription = null
                )
            }
        }
    }
```

You can find the video attached showing the result.

I also try to replace Coil with Glide and Fresco. With Glide I have kind of same behavior, but with Fresco the loading is faster.

```kotlin
FrescoImage(
    modifier = Modifier
        .fillMaxSize(),
    imageUrl = imageList[index], // loading a network image using an URL.
    imageOptions = ImageOptions(
        contentScale = ContentScale.Crop,
        alignment = Alignment.Center
    )
)
```

Did I miss something to configure in Coil to get the same result ?

Coil render:
https://github.com/user-attachments/assets/054d8f9b-76a1-4a0f-ab65-a7a05c5cc0ab

Fresco render:
https://github.com/user-attachments/assets/fee87a3d-c4ed-42ae-8187-26df5f1a394a

**Comment by colinrtwhite** [comment]
Check out the performance recommendations from [this post](https://github.com/coil-kt/coil/issues/1866#issuecomment-2261858541). There isn't anything from your code that jumps out to me as incorrect, however I'd highly recommend testing perf with debug disabled and R8 enabled as it should be much better.

**Comment by JJSarrasin** [comment]
I confirm the videos show you release build, if not, it's totally unusable on those kind of devices.
✅ Use latest release -> rc01
✅ Avoid using SubcomposeAsyncImage
✅ Use release mode
✅ Use R8 (fullmode)

**Comment by colinrtwhite** [comment]
@JJSarrasin Hmm are you maybe using `rememberAsyncImagePainter`? There's a bug [here](https://github.com/coil-kt/coil/issues/2574) that I'm working on fixing. I'd also try using [Compose's perf tools](https://developer.android.com/develop/ui/compose/performance/tooling#tracing) to debug the slow runtime performance.

**Comment by JJSarrasin** [comment]
Hello,
I'm not using rememberAsyncImagePainter anymore. I try to use the remember, it doesn't seem to have a significant improvement.
If you want to test in real condition, you'll find this [quick sample](https://github.com/user-attachments/files/17520820/LazyGridPerfSample.zip) attached for Android TV.

In summary, it seems Coil is more main thread consumer when loading image for the first time, but it seems faster once they are cached. (comparing to fresco).

The sample also compare Glide and Kamel.

**Comment by JJSarrasin** [comment]
After testing Coil 3.1.0 and @andkulikov changes, the experience feels just as good in Coil as it does in Fresco.

A big thanks to both of you for the improvements, I will come back to Coil ;)
