### ISSUE TITLE
Access to Drawable after load into ImageView

### ISSUE THREAD

**Issue by tylerwilson** [coil-kt/coil#261]
Good day,

I have a case where I want to load a URL into an ImageView, apply a Transformation and also get the resultant Drawable/Bitmap saved to memory for use later. I tried something like this:

```
            view.pic.load(url) {
                placeholder(R.drawable.loading_icon)
                transformations(RoundedCornersTransformation(8f))
                target {
                    view.pic.setImageDrawable(it)
                    employee.bitmap = it.toBitmap()
                }
            }
```

But the RoundedCorners is not being applied. Plus I need the explicit setDrawable. So basically it appears that having a target block overrides some of the behavior.

What I would love is something like:

```
            view.pic.load(url) {
                placeholder(R.drawable.loading_icon)
                transformations(RoundedCornersTransformation(8f))
                listener { drawable ->
                    employee.bitmap = drawable.toBitmap()
                }
            }
```

Any suggestions on how I might do this?

Thank you!

**Comment by colinrtwhite** [comment]
I'd avoid setting a new target inside the `ImageView.load` function since it overrides the target set by that function. If you need access I'd do something like this:

```kotlin
            view.pic.load(url) {
                placeholder(R.drawable.loading_icon)
                transformations(RoundedCornersTransformation(8f))
                listener {
                    // Note: We copy the bitmap since view.pic.drawable could be pooled at any time.
                    employee.bitmap = (view.pic.drawable as? BitmapDrawable)?.bitmap?.copy(Bitmap.Config.ARGB_8888, true)
                }
            }
```

Also, it's likely `RoundedCornersTransformation` is being applied, but `8f` is a very low value (it's in px).
