### ISSUE TITLE
[Coil 3] Frequent ImageDecoder$DecodeException: Input was incomplete when I try to load an image from PokeAPI

### ISSUE THREAD

**Issue by iesedobleac** [coil-kt/coil#2612]
**Describe the bug**

I've seen that [this bug](https://github.com/coil-kt/coil/issues/2434) was opened a month or so ago and fixed, but I've reproduced it again in Kotlin Multiplatform with Jetpack Compose. I've checked that it loads fine on iOS and Desktop, but it doesn't load fine on Android.

**To Reproduce**

Simply mount an AsyncImage and see that the image does not load and in the logs it gives the error mentioned in the title of the issue, anyway I add it in its corresponding section.

The url that doesn't load is https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png but if we try to load any other url (just increase the number before the .png to change the image) it does, I don't know what's so special about that one.

**Logs/Screenshots**

I  🚨 Failed - https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png - android.graphics.ImageDecoder$DecodeException: Input was incomplete.

**Version**

I'm using 3.0.0-rc2 although it also happened in 3.0.0-rc1.

**Comment by colinrtwhite** [comment]
@iesedobleac I think [this bug](https://github.com/coil-kt/coil/issues/2434) was only an issue for `content://` URIs - not images loaded from the network.

For this bug I tried loading it loading it in an `AsyncImage` in the `samples:compose` app in this repo, but couldn't reproduce. Do you have a code sample that reproduces this?

<img src="https://github.com/user-attachments/assets/6b9539f1-9a9f-4c97-a1ee-47de6f337fce" width=50%/>

**Comment by iesedobleac** [comment]
> @iesedobleac I think [this bug](https://github.com/coil-kt/coil/issues/2434) was only an issue for `content://` URIs - not images loaded from the network.
> 
> For this bug I tried loading the URL in an `AsyncImage` in the `samples:compose` app in this repo, but couldn't reproduce. Do you have a code sample that reproduces this?
> 
> <img alt="" width="50%/" src="https://private-user-images.githubusercontent.com/5580160/381678529-6b9539f1-9a9f-4c97-a1ee-47de6f337fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzU3NTcsIm5iZiI6MTczMDM3NTQ1NywicGF0aCI6Ii81NTgwMTYwLzM4MTY3ODUyOS02Yjk1MzlmMS05YTlmLTRjOTctYTFlZS00N2RlNmYzMzdmY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMTE1MDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBjMjRlZmY2ZTI2NTUwZTkyZThmYzlkYWM1MzM2MzE5NTA2OWEyOTUwNWZlOTkzNjE3YmQwYTc5YzViZTU2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6Se7d_TD2S1Ycqgb6vFrAe5USrCxLAQSu0kJtuskP00">

Mmmm that's weird... I'll pass you the link to the repository of the app, I just tried it again 5 minutes ago and the same thing keeps happening, so let's see if it's a casuistry of how I have the code, although it's very basic: 

https://github.com/iesedobleac/pokedex-multiplatform

**Comment by iesedobleac** [comment]
> Have you configured diskcache? If true, that may because you have a truncated image cache file. If not, StaticImageDecoder is definitely not used for image from network as it doesn't accept stream image source.

No, I'm not using cache for this configuration, so I discard this. The thing is that it loads the rest of the images except this one, which is the one that gives this error, I don't know why.

**Comment by kihaki** [comment]
I have the same issues when using photos from the google photo picker that are stored in the cloud, same as before in here: https://github.com/coil-kt/coil/issues/2434, seems like the issue is not fixed or not completely fixed

**Comment by colinrtwhite** [comment]
@kihaki @iesedobleac If you set `ImageLoader.Builder.bitmapFactoryExifOrientationStrategy` to `ExifOrientationStrategy.IGNORE` does it fix the issue? A side effect of setting that strategy is that it disables the Android `ImageDecoder` and falls back to `BitmapFactoryDecoder`.

**Comment by kihaki** [comment]
@colinrtwhite Setting `ExifOrientationStrategy.IGNORE` *fixes the issue* for the failing content uris from the google photo picker - all of them seem to work when setting the `ExifOrientationStrategy` to `IGNORE`.

FYI: I have also tried loading the images from the photo picker as a bitmap with the following native Android code just to check if native image loading works:

```
val bitmap = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
  ImageDecoder.decodeBitmap(ImageDecoder.createSource(context.contentResolver, image.uri))
} else {
  null
}
```

and it breaks with the same exception as observed further up.

Separately I have checked API 27 and below:
Usually my app works from API 29+ and unfortunately I could not get the google photo picker to work on API 26 yet (it falls back to the files picker, even though it should download the back ported photo picker component from play services) and thus cannot test with the content uris from the photo picker.

So I have tested the url given above (https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png) and it works *without the exif fix* on both my Samsung Fold 4 (34) and my test emulator with API 26.

**Comment by kihaki** [comment]
Could the exif data issues with google photo picker images be related to [this issue](https://issuetracker.google.com/issues/243294058)?

**Comment by kihaki** [comment]
> Does the image looks fine when using BitmapFactory(or coil with exif workaround)?

The results are the same in all cases, `BitmapFactory`, Coil with EXIF workaround and decoding with `ImageDecoder.OnPartialImageListener { true }`. It seems like a bit of the lower part of the image is missing (transparent pixels)

The following is a sample (sorry for the weird screenshot arrangement, it was done quickly).

The small images on the left are decoded with `BitmapFactory` directly, the large images are decoded by Coil with the EXIF workaround. Notice the dogs nose ending exactly at the image edge on the top left of the small images and also on the right image of the big images.

![image](https://github.com/user-attachments/assets/62dab69a-606e-42fa-8c81-d87582fbd296)

This is what the image contains when opening it in the Google Photos app. See the part below the nose is present there, but missing when going through the Google Photos Picker and arricing in coil / the `BitmapFactory`.

![image](https://github.com/user-attachments/assets/4f59bd5f-ad16-4157-b8df-62369c38c9b5)

**Comment by kihaki** [comment]
Here is some meta information about an image that fails with the `DecodeException` (not sure if this helps, but posting it anyways, it might tell you something):

```
Resolution: 3024 x 4032 pixels
Color Space: Display P3
IsAnimated: false
Mime Type: image/jpeg
```

This is one that works without throwing a `DecodeException`:

```
Resolution: 1812 x 2176 pixels
Color Space: sRGB IEC61966-2.1
IsAnimated: false
Mime Type: image/jpeg
```

**Comment by kihaki** [comment]
Thanks @revonateB0T I have opened an issue here: https://issuetracker.google.com/issues/379269843

**Comment by kihaki** [comment]
I just copied from another issue they had with the photo picker.. but lets see what happens :D

**Comment by iesedobleac** [comment]
Hi guys! I haven't been here for a while and today I've seen some movement. I've tried to compile the application without increasing the version number (the one I had is 3.0.0-rc02) and I don't know why now I can't reproduce the problem... the image that didn't load before now does, how is it possible?
