### ISSUE TITLE
Svg is not loading

### ISSUE THREAD

**Issue by zeeshanrasool91** [coil-kt/coil#2622]
**Describe the bug**
A clear and concise description of what the bug is. **Please [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and attach any stack traces.** Bug reports without reproduction steps are likely to be closed.

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?

**Comment by zeeshanrasool91** [comment]
https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg

this same url is working using 
load(url) {
        decoderFactory { result, options, _ ->
            SvgDecoder(result.source, options)
        } this method coil2 but when i update it to coil3 it is not working

**Comment by colinrtwhite** [comment]
The SVG works as expected in the sample project (see screenshot). Please make sure you [imported the okhttp networking library](https://coil-kt.github.io/coil/getting_started/#compose-ui). If you're still running into issues please open a new issue with at least the `onError` stack trace.

<img src="https://github.com/user-attachments/assets/545dbe1b-7b6f-4a5e-8017-f367fc0616f1" width=50%/>

**Comment by zeeshanrasool91** [comment]
it is working as expected with ok http3 dependency.
