### ISSUE TITLE
[Feature] Option to disable animations

### ISSUE THREAD

**Issue by RobbWatershed** [coil-kt/coil#2629]
**Is your feature request related to a problem? Please describe.**
To save CPU and RAM, I need previews for image collections to be displayed without GIF/WEBP animation (think of gallery pages where there are 30+ pictures on screen).

The only trick I found to do that with Coil3 is to use an `ImageLoader` created with `ImageLoader.Builder.serviceLoaderEnabled(false)`

Problem with that is it disables all components, which include decoders _and fetchers_. As a consequence, that loader won't be able to load a picture online (using `coil-network-okhttp`).

=> When the picture is located online, I have no choice but to display it with its animation

**Describe the solution you'd like**
I'd love to get a simple option made to disable image animation specifically for a given picture. Ideally, an agument to pass to `ImageRequest.Builder`.

**Comment by colinrtwhite** [comment]
If you set `ImageLoader.Builder.serviceLoaderEnabled(false)` you can still add your components manually. [Here](https://coil-kt.github.io/coil/recipes/#using-a-custom-okhttpclient)'s an example with the `OkHttpNetworkFetcherFactory`. I'd recommend adding the `OkHttpNetworkFetcherFactory` manually then using `ImageRequest.Builder.decoderFactory(AnimatedImageDecoder.Factory())` when you want to decode an animated GIF.

**Comment by RobbWatershed** [comment]
Alright, I didn't think about that. Thanks for taking the time to explain~
