### ISSUE TITLE
Loading SVGs into different sized ImageViews results in incorrect content resizing

### ISSUE THREAD

**Issue by FrostRocket** [coil-kt/coil#265]
I'm having issues with loading SVGs into different sized ImageViews.

**Scenario:**

1. MainActivity loads a list of images from API into a ViewHolder. These images are SVGs, and are loaded into a 32x32dp ImageView via standard ImageView.load() extension.

2. DetailActivity (which is launched when you click on an item) has a larger ImageView (128x128dp) that loads the exact same URL via ImageView.load() extension.

**Result:**

For some images, Coil appears to be reloading the smaller sized SVG into the larger ImageView, resulting in an image much smaller than the ImageView bounds. To make matters worse, when I return back to the MainActivity, the image somehow gets even smaller still, resulting in the same behavior, though now the image looks closer to a 16x16dp image in a 32x32dp image box.

**Additional info:**

I'm having trouble reproducing this 100% of the time, but I have a hunch some of the SVGs I'm loading may not have sizing information and Coil is trying to make adjustments to accommodate. This may be resulting in an image being reused from the cache but not properly scaled again. Just a guess at this point.

**EDIT:**

I inspected an SVG that appears to be working correctly and an SVG that occasionally has issues. The "working" SVG has a viewBox, width, and height attribute set on it. The SVG with issues does not have a width and height attribute, but does have a viewBox and enable-background attribute. Hope this helps!

I can provide more debugging support (sample images and videos) directly if you're stuck as to what's going on here.

**Comment by FrostRocket** [comment]
Side note: this has been a lingering issue for me since Coil launched with SVG support, was waiting to see if it'd be resolved with the initial wave of bugfixes but it hasn't. :(

**Comment by colinrtwhite** [comment]
@FrostRocket I haven't been able to reproduce this locally with the samples you sent me. Can you try `0.10.1` and see if it fixes the issue? If it doesn't, feel free to reopen with a repro sample.
