### ISSUE TITLE
Image quality decreased when updated coil from 2.7.0 to 3.0.1

### ISSUE THREAD

**Issue by drishyadivan** [coil-kt/coil#2663]
**Describe the bug**
Image quality decreased when updated coil from 2.7.0 to 3.0.1

**To Reproduce**
AsyncImage(
            model = ImageRequest.Builder(LocalContext.current)
                .data(imageLink.value)
                .crossfade(300)
                .memoryCachePolicy(policy = CachePolicy.ENABLED)
                .build(),
            contentDescription = workoutImageDescription,
            modifier = Modifier
                .fillMaxSize()
                .align(Alignment.TopCenter)
                .zIndex(2f),
            contentScale = ContentScale.Crop
        )

This code was running perfectly in 2.7.0, but behaving differently in 3.0.1. Image shown is blurred.

**Version**
3.0.1

**Comment by IndusAryan** [comment]
I have this issue in a shapeable image view with style radius 50% with circle crop transformation using center scale type, this issue is present in 3.0.1, I will check and confirm if it is present in 3.0.0

**Comment by drishyadivan** [comment]
The above code is working in 2.7.0. We updated coil version to latest one and changed imports accordingly to coil3.
In 3.0.0-alpha09 - Not working
     3.0.0-alpha10 - Not working
     3.0.0-rc01 - Not working
     3.0.0-rc02 - Not working
     3.0.0 - Not working
     3.0.1 - Not working
     3.0.2 - Not working
     
     When coil version reverted back to 2.7.0 and changed imports to coil, it is working. No parent composable are changed.
     Only version updates are done.

**Comment by colinrtwhite** [comment]
@drishyadivan I tried running your code and it worked as expected (see below). Please create a new issue with reproducible sample.

<img src="https://github.com/user-attachments/assets/1558ab7f-0a09-4c34-9b01-cc5c4cb7373d" width=50%/>

**Comment by iZakirSheikh** [comment]
> **Describe the bug** Image quality decreased when updated coil from 2.7.0 to 3.0.1
> 
> **To Reproduce** AsyncImage( model = ImageRequest.Builder(LocalContext.current) .data(imageLink.value) .crossfade(300) .memoryCachePolicy(policy = CachePolicy.ENABLED) .build(), contentDescription = workoutImageDescription, modifier = Modifier .fillMaxSize() .align(Alignment.TopCenter) .zIndex(2f), contentScale = ContentScale.Crop )
> 
> This code was running perfectly in 2.7.0, but behaving differently in 3.0.1. Image shown is blurred.
> 
> **Version** 3.0.1

This might be happening because the image on which you click is being loaded by coil in the bigger view. Maybe there is a bug with inMemory of Coil3 whaich doesnt take into account the image dimens. I was having the same issue then I set new memoryCachekey in bigger image view and this got resolved.
Now I observed, the image is loaded slowly.
