### ISSUE TITLE
SVG  tint doesn't work

### ISSUE THREAD

**Issue by jyh149129** [coil-kt/coil#2702]
**Describe the bug**
we want change images（SVG） tint color when image selected：

![QQ20241119-124806](https://github.com/user-attachments/assets/d65e55ac-b18f-49d9-b0f4-8efda0ee1513)

images color doesn't any change when image selected. but glide works fine.

**Version**
3.0.2 ,android 13

**Comment by colinrtwhite** [comment]
Does `BitmapDrawable` support this state? You likely need to register `SvgDecoder.Factory(renderToBitmap = false)`, though this will reduce rendering performance as it won't prerender the bitmap on a background thread.

**Comment by colinrtwhite** [comment]
Seems like this might be an issue with `crossfade`. Are you using that?

**Comment by colinrtwhite** [comment]
Fixed here: https://github.com/coil-kt/coil/pull/2704. Thanks for reporting!
