### ISSUE TITLE
Failed to decode frame at 1000000 microseconds

### ISSUE THREAD

**Issue by aliyanGoally** [coil-kt/coil#2732]
**Describe the bug**
This is specifically a problem when I am using coil to load video frame from a URL.
**For mobile devices:** It is working like a charm.
**For android tablets:** It is failing to decode the frame.

**To Reproduce**
You can check android tablet to load the video frame from a URL.
It is giving me the error in OnError callback: 
Failed to decode frame at 1000000 microseconds.
getFrameAtTime: videoFrame is a NULL pointer
**Version**
Using Coil Version: 3.0.3
But it is also not working on 3.0.4
Specific Devices: Android Tablets
Device: Allwinner QUAD-CORE A133 b7, Android: 33

**Comment by colinrtwhite** [comment]
This sounds like a hardware specific issue. Unfortunately it's not really possible for Coil to work around these. According to [this issue](https://stackoverflow.com/a/28019608/4475057) it sounds like you might be able to work around it by setting `ImageRequest.Builder.videoFrameOption`
