### ISSUE TITLE
[Coil compose 2.5.0] custom image loader cannot support memory cache & disk cache

### ISSUE THREAD

**Issue by susugu-gd** [coil-kt/coil#2749]
Project both use the compose UI and normal xml UI to load image .  owning to project risk , I cannot upgrade the coil version to latest version 3.0.4
`
val fullImageUrl = imageUrl?.let { getFullImageUrl(it) }
    // **val imageLoader1 = Coil.imageLoader(context.applicationContext)**
**val imageLoader2 = ImageLoader.Builder(context.applicationContext)**
     val imageLoader2 = ImageLoader.Builder(context.applicationContext)
         .memoryCache {
             MemoryCache.Builder(context)
                 .maxSizePercent(0.25)
                 .build()
         }
         .diskCache {
             DiskCache.Builder()
                 .directory(context.cacheDir.resolve("image_file_cache"))
                 .maxSizePercent(0.02)
                 .build()
         }
         .logger(DebugLogger())
         .build()

    val imageRequest = ImageRequest.Builder(context).apply {
        decoderFactory(SvgDecoder.Factory())
        allowHardware(allowHardware)
        (placeHolderImage as? Int)?.let { this.placeholder(it) }
            ?: (placeHolderImage as? Drawable)?.let { this.placeholder(it) }
        (placeHolderImage as? Int)?.let { this.error(it) }
            ?: (placeHolderImage as? Drawable)?.let { this.error(it) }
        memoryCachePolicy(CachePolicy.ENABLED)
        diskCachePolicy(CachePolicy.ENABLED)
        placeholderMemoryCacheKey(fullImageUrl)
        data(fullImageUrl)
        size(Size.ORIGINAL)
        target(onStart = { drawable ->
            onStart?.invoke(drawable)
        }, onSuccess = { drawable ->
            loadResult.invoke(drawable)
        }, onError = { drawable ->
            loadResult.invoke(drawable)
        })
    }
    imageLoader.enqueue(imageRequest.build())
`
when I use **the imageloader1,** memory cache worked , page B load image in success ,return back to PageA , and then navigate to page B again ,. the image view will display the memory image . 
BUT about Disk Cache , I saw the "image_cache" file on device file explorer . There's some file in it .  when I  kill the app and restart the app <NOT reinstall > , the image view load the placeholder i set first and then show the remote image  , instead of finding the image from Disk Cache. 
![image](https://github.com/user-attachments/assets/9fe468fb-6e0b-4d8d-807e-5e2204f6bb26)
The coil resource code :  the placeholderBitmap is null
![image](https://github.com/user-attachments/assets/e19cb997-ba43-4ec8-84e3-71e662a04d17)

when I use **the imageloader2** , both memory cache , disk cache cannot work : 
page B load image in success ,return back to PageA , and then navigate to page B again ,. the image view will display the memory image -> The coil resource code :  the placeholderBitmap is null and then displace placeholder i set and then display the remote URL
Kill app and launch ,  the placeholderBitmap is null and then displace placeholder i set and then display the remote URL

Am I using the correct code implementation? I found that  when i create the custom image loader ,  the following behavior cannot implement :
, 
**To Reproduce**
Am I using the correct code implementation?
 I found that  when i create the custom image loader ,  the following behavior cannot implement :
1. memory cache does not work , page B load image in success ,return back to Page A , and then navigate to page B again . 
 actual result :Page B  display placeholder when i set in image request.
expect result : Page B display memory cache image. 
2. 1. disk cache does not work , launch Page B to load image , kill the app <NOT reinstall app> , launch Page B :
actual result : display placeholder when i set in image request.
expect result : display memory cache image. 

**Version**
2.5.0
            coil   : "io.coil-kt:coil-compose:2.5.0",
            coilsvg: "io.coil-kt:coil-svg:2.5.0"

**Comment by colinrtwhite** [comment]
Sorry I can't provide 1:1 support on issues like this. It sounds like your server could be sending cache headers that require reverification or prevent caching? You could try `ImageLoader.Builder.respectCacheHeaders(false)` to ignore cache headers. Alternatively I would try updating to at least `2.7.0`. If it is a bug, please reopen with reproduction sample.
