### ISSUE TITLE
Custom network Timeout?

### ISSUE THREAD

**Issue by Andrew0000** [coil-kt/coil#2757]
**Is your feature request related to a problem? Please describe.**

On our project we have large images to load. Unfortunately, sometimes it is 5 MB (GIF). It seems that users with poor network quality are experiencing timeouts.

**Describe the solution you'd like**

What are the current network timeouts?
Is it possible to configure timeouts? (I couldn't find any documentation on this).
If not, is it possible to add this feature?

**Comment by colinrtwhite** [comment]
You'll have to set the timeout on the `OkHttpClient` or `HttpClient` (ktor) depending on which networking library you use then [register it](https://coil-kt.github.io/coil/network/#using-a-custom-okhttpclient).

**Comment by Andrew0000** [comment]
Thank you.

For anyone else who didn't find an example for Ktor2 in the documentation, here is an example:

```
import coil3.ImageLoader
import coil3.network.ktor2.KtorNetworkFetcherFactory
import io.ktor.client.HttpClient

ImageLoader.Builder(context)
            .components {

                // Your other components ...

                add(
                    KtorNetworkFetcherFactory(
                        httpClient = { 
                            HttpClient {
                                // Do configuration here
                            } 
                        }
                    )
                )
            }
```
