### ISSUE TITLE
version 3.0.4 The uri cannot be loaded correctly. After the first display, the first displayed image is still displayed when it is called again.

### ISSUE THREAD

**Issue by liufeng382641424** [coil-kt/coil#2758]
**Describe the bug**
After taking a photo in Android, I used Coil AsyncImage to load the URI of the successful photo. I set a fixed file path. In versions 3.0.0-alpha10 and earlier, the correct image was displayed every time the URI was loaded after taking a photo. However, after version 3.0.0-alpha10, after I took the photo for the first time and loaded it, the photo I took again would display the image I took for the first time. I tried to disable the cache policy CachePolicy.DISABLED, but it didn't work. I don't understand what was updated in the new version, why this bug occurred, and how can I fix it. Thanks for your help.

**To Reproduce**

    val mImageCapture by remember {
        mutableStateOf(
            ImageCapture.Builder()
                .setFlashMode(ImageCapture.FLASH_MODE_AUTO)
                .setCaptureMode(ImageCapture.CAPTURE_MODE_MINIMIZE_LATENCY)
                .setTargetAspectRatio(AspectRatio.RATIO_16_9)
                .setJpegQuality(50)
                .build()
        )
    }
    var mUri by remember { mutableStateOf<Uri?>(null) }
    val mFile by remember { mutableStateOf(File("${context.filesDir.path}/camera.jpg")) }
    val mOnImageSavedCallback by remember {
            mutableStateOf(object : ImageCapture.OnImageSavedCallback {
                override fun onImageSaved(output: ImageCapture.OutputFileResults) {
                    mUri = output.savedUri
                }
    
                override fun onError(exception: ImageCaptureException) {
                    mUri = null
                }
            })
        }

        mImageCapture.takePicture(
            ImageCapture.OutputFileOptions
                .Builder(mFile)
                .build(),
            Executors.newSingleThreadExecutor(),
            mOnImageSavedCallback
        )

    AsyncImage(
        modifier = Modifier.fillMaxSize(),
        contentScale = ContentScale.Crop,
        model = mUri,
        contentDescription = ""
    )

**Version**
version 3.0.4 All devices

**Comment by colinrtwhite** [comment]
As [mentioned in the changelog](https://github.com/coil-kt/coil/blob/main/CHANGELOG.md#300-rc01---october-8-2024), `addLastModifiedToFileCacheKey` is disabled by default after `3.0.0-alpha10`. You need to set `ImageLoader.Builder. addLastModifiedToFileCacheKey(true)` to reenable that behaviour.
