### ISSUE TITLE
AnimatedImageDecoder onAnimationEnd Bug 

### ISSUE THREAD

**Issue by liuhuan0225** [coil-kt/coil#2764]
**Describe the bug**
onAnimationEnd called incorrectly on second load  
The first load can be displayed and played normally. The next call will not display

**To Reproduce**
    val animLoader by lazy {
        ImageLoader.Builder(BaseApplication.instance).components {
            if (Build.VERSION.SDK_INT >= 28) {
                add(AnimatedImageDecoder.Factory())
            } else {
                add(GifDecoder.Factory())
            }
        }.build()
    }
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/bea1b645-89f9-433b-a103-46d3c1327faa" />

**Version**
3.0.4
 api ("io.coil-kt.coil3:coil-compose:3.0.4")
 api("io.coil-kt.coil3:coil-gif:3.0.4")

Currently I can only copy AnimatedImageDecoder and modify it here to use
<img width="920" alt="image" src="https://github.com/user-attachments/assets/33beae88-ffdc-4d85-a1fb-b2656326e7ca" />

**Comment by colinrtwhite** [comment]
This is expected behaviour, `onAnimationEnd` is called at the end of each animation iteration - not only the first run.

**Comment by liuhuan0225** [comment]
yes ,But the next time onAnimationEnd is not called when the animation ends
