### ISSUE TITLE
Image is showed stretch when apply rounded corner transformations

### ISSUE THREAD

**Issue by prsolucoes** [coil-kt/coil#281]
**Describe the bug**
When apply "RoundedCornersTransformation" it need work for rectangle and square images.

My image is 400x400.

**Expected behavior**
Expect is the image showed with rounded corners

**To Reproduce**

FAIL:

```
val drawable = Coil.get(url) {
    transformations(
        RoundedCornersTransformation(
            8f
        )
    )
}

productCoverImageSquare?.setImageDrawable(drawable)
```

WORK:

```
val drawable = Coil.get(url)
productCoverImageSquare?.setImageDrawable(drawable)
```

**Logs/Screenshots**

Image is showed stretch instead of square.

Applying transformation:
![image](https://user-images.githubusercontent.com/395096/73854434-51aa9880-4811-11ea-964e-99198ad6bc25.png)

Without transformation:
![image](https://user-images.githubusercontent.com/395096/73854487-625b0e80-4811-11ea-8847-d78766f744b6.png)

**Version**
0.9.4 (tried others but the same problem happen)

**Comment by colinrtwhite** [comment]
I'm not sure I understand what the issue is. It looks like those are two different images in the screenshots. `RoundedCornersTransformation` shouldn't affect the aspect ratio of the output image.

**Comment by prsolucoes** [comment]
Hi,

Is the same of:
https://github.com/coil-kt/coil/issues/282

When apply RoundedCornersTransformation with any value, it crop or stretch the image or something like this, like in the screenshot.

Both images are 400x400 and work without transformations, but when apply RoundedCornersTransformation it appear with strange appearance.

The image view is 50x50 with fitCenter (yes, i tried others) and i use the method from coil to get and set the drawable to the component. Everything works fine if i don´t use RoundedCornersTransformation transformations (i don´t tried with others transformations).

Thanks.

**Comment by colinrtwhite** [comment]
@prsolucoes I tried reproducing this with the sample app, but the aspect ratio of the image is maintained. If you have a code sample that reproduces the issue feel free to reopen.
