### ISSUE TITLE
Image don't fill/respect image component

### ISSUE THREAD

**Issue by prsolucoes** [coil-kt/coil#282]
**Describe the bug**
The image is loaded but it appear crop the image, very strange. It only happen when i try apply rounded corners transformations:

**Expected behavior**
Image need be showed without the strange behaviours.

**To Reproduce**

```
launch(Dispatchers.IO) {
    try {
        val drawable = Coil.get(url) {
                transformations(
                    RoundedCornersTransformation(
                        roundedCornerRadius.toFloat()
                    )
                )
        }

        launch(Dispatchers.Main) {
            if (isRectangle) {
                productCoverImageRectangle?.setImageDrawable(drawable)
            } else {
                productCoverImageSquare?.setImageDrawable(drawable)
            }

            latestImageLoaded = url
            remoteDataLoadState = LoadStateEnum.LOADED

            if (isRectangle) {
                showProductCoverImageRectangle()
            } else {
                showProductCoverImageSquare()
            }

            Logger.d("[MainFragment : showLastProductOnCenterButton] Image loaded with success")
        }
    } catch (e: Exception) {
        remoteDataLoadState = LoadStateEnum.LOADED
        Logger.e("[MainFragment : showLastProductOnCenterButton] Error when load image: " + e.message)
    }
}
```

**Logs/Screenshots**

PROBLEM:
![image](https://user-images.githubusercontent.com/395096/73856324-0776e680-4814-11ea-9fb7-738506368a31.png)

WITHOUT APPLY TRANSFORMATIONS:
![image](https://user-images.githubusercontent.com/395096/73856347-1362a880-4814-11ea-888c-29361f3ddf2f.png)

**Version**
0.9.4 (tried others but the same problem happen)

**Comment by colinrtwhite** [comment]
Thanks for the report, but this intended behaviour with `RoundedCornersTransformation`. It will fill the image in the target's dimensions then round the corners.

**Comment by rovkinmax** [comment]
@colinrtwhite but this behaviour not clear. I spent 2 hours to understand why image cropped incorrect. May be you add documentation for it and rename transformation? Because when I see RoundedCornersTransformation class name I expect that only corners will be rounded without any other transformations.

**Comment by colinrtwhite** [comment]
@rovkinmax If you need the image in its exact dimensions use `size(OriginalSize)`.
