### ISSUE TITLE
Coil.load method doesn't exist

### ISSUE THREAD

**Issue by tschellenbach** [coil-kt/coil#284]
**Describe the bug**

The documentation describes the Coil.load method. This method doesn't exist when you import coil:

```
import coil.Coil
```

The documentation should either clarify the correct import or show the right method to load.
This happens on Coil 0.9.4

**Comment by colinrtwhite** [comment]
If you import `io.coil-kt:coil:0.9.4` it should be there. It's implemented as an [extension function](https://github.com/coil-kt/coil/blob/master/coil-default/src/main/java/coil/api/Coils.kt#L31).

**Comment by tschellenbach** [comment]
What could cause the extension function not to register? I am importing io.coil-kt:coil:0.9.4
