### ISSUE TITLE
How to load updated image from same url if internet and load cache image if no internet?

### ISSUE THREAD

**Issue by nicemak** [coil-kt/coil#296]
Hi,

I am trying to get updated image for user profile picture, the image is updated on the server but have the same name as previous one i.e. www.myserver.com/user-123-profile.jpg, if you updated the image of user 123, url will remain the same. now when i am loading the image, coil always load the last image it loaded.

`user_profile_img.load(response[position].user_image){
                memoryCachePolicy(CachePolicy.DISABLED)
            }`

it doesn't help me. 

can some one please help me out here also if there is no network then it should load the last updated one

**Comment by colinrtwhite** [comment]
If you have control of the server's response, your best bet would be to have it set the header `Cache-Control: must-revalidate`. That will force Coil to check that the image is up to date and will save bandwidth if it is. You may be able to use an [`Interceptor`](https://square.github.io/okhttp/interceptors/) this instead, though I'm not sure.

If you can't modify the server, you can do:

```kotlin
user_profile_img.load(response[position].user_image) {
    memoryCachePolicy(CachePolicy.DISABLED)
    diskCachePolicy(CachePolicy.WRITE_ONLY)
}
```

Coil will automatically force reading from the disk cache if the user is offline, but will read from the network if it's available.

**Comment by nicemak** [comment]
`user_profile_img.load(response[position].user_image) {
    memoryCachePolicy(CachePolicy.DISABLED)
    diskCachePolicy(CachePolicy.WRITE_ONLY)
}`

it does not help, i implemented this in recyclerview adapter, by scrolling the list i load some images, then disconnect mobile from internet scroll the list but image disappeared.

**Comment by colinrtwhite** [comment]
Ah you're right. Setting `diskCachePolicy(CachePolicy.WRITE_ONLY)` prevents reading from the cache when you're offline.

You should update your server to send `Cache-Control: must-revalidate` for that image. This will cause it to requery the server and download the new image if it has been updated since the last request timestamp. You may be able to use an [`Interceptor`](https://square.github.io/okhttp/interceptors/) for this instead, though I'm not sure.
