### ISSUE TITLE
Coil singleton object

### ISSUE THREAD

**Issue by svenjacobs** [coil-kt/coil#303]
While the global singleton object `Coil` simplifies usage, it also impairs maintainability and testability. For instance currently it is not possible to provide two differently configured Coil instances through a dependency injection framework. Even if just one instance is required, configuring Coil through a DI framework currently feels more like a "hack", since the singleton object is returned anyway.

Are there any plans for providing Coil's functionality through instances instead of a singleton?

**Comment by colinrtwhite** [comment]
This is actually already possible as documented [here](https://coil-kt.github.io/coil/image_loaders/#singleton-vs-dependency-injection). The `Coil` object is a thin wrapper that holds an `ImageLoader`. If you want to completely forgo the singleton you can depend on the `coil-base` artifact, though you'll lose access to the `ImageView` extension functions. I'm going to do some work on the docs for the next release that should hopefully make that section clearer.

**Comment by svenjacobs** [comment]
Okay, thanks for the clarification 👍
