### ISSUE TITLE
CrossfadeDrawable with zero bounds stalls coroutine

### ISSUE THREAD

**Issue by svenjacobs** [coil-kt/coil#304]
Loading images in a RecylerView with Coil. On initial application start the image of the first (and only) visible RecyclerView item is never loaded. I added `onSuccess` and `onError` listeners but both are never called. Coil logs a `Successful (DISK)` for the requested image. Once I start scrolling and further items are displayed, the first image (along with other images) are displayed. Then I start seeing `Cached` and `Cancelled` log outputs. When I remove `crossfade(true)` everything works as expected. Maybe related to #241? I'm using version 0.9.5 of Coil.

```kotlin
imageLoader.loadAny(
    fragment.requireContext(),
    AkamaiImage(offer.image.imageUrl)
) {
    target(productImage)
    lifecycle(fragment)
    crossfade(true)
    listener(
        onSuccess = { _, _ ->
            setImageProgressBarVisible(false)
        },
        onError = { _, e ->
            Logger.e(e)
        }
    )
}
```

**Comment by svenjacobs** [comment]
I also noticed that with `crossfade(true)`, performance of fast scrolling through the list is greatly reduced. Without `crossfade` scrolling through the list is fluent.

By the way, `AkamaiImage` is associated with a `MeasuredMapper`. Maybe this could be the reason for a performance impact??

**Comment by colinrtwhite** [comment]
Hmm it sounds like your request gets stuck when determining the size of the target. What's `productImage`'s type? Also you probably want to use `lifecycle(fragment.viewLifecycleOwner)`. If you could you make a small sample project that reproduces the bug that would help a lot as well.

**Comment by svenjacobs** [comment]
`productImage` is an `ImageView`. Regarding a sample project I'll see if I find some time. The original project is quite complex so it might be tricky to find a setup that reproduces this issue.

**Comment by colinrtwhite** [comment]
Thanks. Unfortunately, without a sample project it's tough to figure out the root cause.

**Comment by svenjacobs** [comment]
I was able to reproduce this in a small [sample project](https://github.com/svenjacobs/coil-issue-304) 🎉 

The root cause of this problem is that the `ImageView`'s visibility is set to `View.GONE` initially. I do this because I display a `ProgressBar` while the image is loaded. Since the image's bounds are (0,0) (0,0) initially, `draw()` of `CrossfadeDrawable` is never called. Hence the animation is not marked as done and the callback not called which results in the coroutine being stalled.

This might not be a problem of Coil but maybe Coil should log a warning in `CrossfadeDrawable` when it detects that the view's bounds equal `ZERO_BOUNDS_RECT`?

**Comment by colinrtwhite** [comment]
@svenjacobs Awesome, thanks! I agree Coil should at least log this case. Maybe it would be better to skip the transition in this case? That way when you make the view visible, the drawable will show instantly.

Will also check out how Glide/Picasso handle this.
