### ISSUE TITLE
Support ImageLoader event listener API.

### ISSUE THREAD

**Issue by ahetawal-p** [coil-kt/coil#310]
I am looking into migrating my codebase from Picasso to Coil. And one of the debug friendly features which I really liked about Picasso was to support a centralized form of error listener of all failed requests.
Which was setup like this :
```
val picassoInstance = Picasso.Builder(context)
            .listener { _, uri, exception ->
                logger.e("Error fetching image: $uri", exception)
            }
            .build()
```

I am trying to find a similar equivalent for Coil, I understand I can do something like this:
```
imageView.load(data) {
    listener(
        onError = { /** Show toast. */ },
        onSuccess = { /** Show toast. */ }
    )
}
```
But our app has many imageView and adding listeners to all of them, add more to code lines and maintenance.
Any advise on how I can achieve similar use case on Coil ?

**Comment by colinrtwhite** [comment]
Unfortunately, I don't think there's a great way to accomplish this at the moment. That said, I definitely want an even listener API similar to [`OkHttp's`](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-event-listener/) before 1.0. Hopefully it can be part of `0.10.0`, however no promises.

Going to mark this as an enhancement and track progress on the feature here.
