### ISSUE TITLE
GIF is not starting

### ISSUE THREAD

**Issue by ahmaducg** [coil-kt/coil#317]
I'm trying to test the GIF part of the library, but it doesn't seem to start the GIF.

```kotlin
val imageLoader = ImageLoaderBuilder(this).componentRegistry {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
        add(ImageDecoderDecoder())
    } else {
        add(GifDecoder())
    }
}.build()

findViewById<ImageView>(R.id.gif).load(R.drawable.splash_screen_gif, imageLoader)   
```

Is there something I'm doing wrong? I tested it on Android 10, and Android 5.

There are no examples of usage for a GIF, which made it obscure on what could be missing.

**Comment by colinrtwhite** [comment]
Hmm that should work as intended. Maybe the GIF doesn't have the correct file headers? If you run `DecodeUtils.isGif(resources.openRawResource(R.drawable. splash_screen_gif).source().buffer()` does it return true?

**Comment by ahmaducg** [comment]
I tried it with an online gif too, doesn't work.

As a note, the GIF works well with Glide.

**Comment by colinrtwhite** [comment]
Can you link me to the GIF?
