### ISSUE TITLE
Strange behaviour of crossfade

### ISSUE THREAD

**Issue by fjr619** [coil-kt/coil#320]
i have viewpager to display banner, but there are problems:

```
        view.load(bannerList[position].image, imageLoader) {
            crossfade(true)
            placeholder(R.drawable.banner_loading)
            error(R.drawable.banner_no_image)
        }
```
this code will give me : banner will load smaller size first, then when i swipe to next page and back to previous, banner will show correct size  

  --
```
        view.load(bannerList[position].image, imageLoader) {
            crossfade(false)
            placeholder(R.drawable.banner_loading)
            error(R.drawable.banner_no_image)
        }
```
this code will give me : banner will show correct size  

--
```
        view.load(bannerList[position].image, imageLoader) {
            crossfade(true)
        }
```
this code will give me : banner will show correct size

note: bannerList[position].image is URL

so my question who to display correct size with crossfade = true and having a placeholder?

**Comment by colinrtwhite** [comment]
Hmm it sounds the like there might be a scaling issue when adding a placeholder. `crossfade(true)` should correctly scale the drawable inside the view. Is `view` a custom `ImageView`? If you create a small sample project I can take a look.
