### ISSUE TITLE
Does Coil load into Drawable?

### ISSUE THREAD

**Issue by theScrabi** [coil-kt/coil#324]
I currently have the issue that I need to render html with images into TextViews.
This is possible with the [`Html.ImageGetter`](https://developer.android.com/reference/android/text/Html.ImageGetter).
However when I load the html the images are not loaded yet, so I display a placeholder as image and want to load the images by triggering coil. I can do this by using a drawable that first displayes a placeholder and then render into that drawable later with the image loaded by coil.
What I've seen so far is that people created their own DrawablePlaceholder where an arbitrary image loading mechanism could render the image into:
https://gist.github.com/rajeefmk/beb1b79363c12041da7fd540bcf27765

However I wonder if Coil already has such a Drawable placeholder?

**Comment by theScrabi** [comment]
Or to make it more human understandibly: I want a way that Coil can render asynchronously into a drawable.

**Comment by theScrabi** [comment]
Ah just use Kotlin coroutines and `Coil.get()`.
Uff I'm new to kotlin

**Comment by colinrtwhite** [comment]
You can implement a custom [`Target`](https://coil-kt.github.io/coil/api/coil-base/coil.target/-target/) and set the placeholder for your request using [`LoadRequestBuilder.placeholder`](https://coil-kt.github.io/coil/api/coil-base/coil.request/-load-request-builder/).

**Comment by Jawnnypoo** [comment]
BTW @theScrabi , big fan of your work on NewPipe 😄 Here is an implementation of an `Html.Getter` that I created and am using in a few projects: 

https://github.com/Commit451/coil-imagegetter

**Comment by theScrabi** [comment]
:D thank you Same goes to you guys :)
