### ISSUE TITLE
Resizing of the images does not work

### ISSUE THREAD

**Issue by SudarshanGangurde** [coil-kt/coil#325]
**Describe the bug**
I am having 100\*100 pixel thumbnail image & I resize it to the 500\*500 pixel. I am using the same in recycler view so on the first launch it shows the properly resized image but when I go back & come again then the image is not getting resize.

**Expected behavior**
The image should get resized.

**To Reproduce**
1. Take 100\*100 pixel image
2. Show the same image in the recycler view using the below function. Pass width & height as 500
load(url) {
        placeholder(placeholder)
        size(width, height);
}
3. On the first launch, the image will get resized.
4. go to previous activity by pressing the back button.
5. Again launch the same screen.
6. Now the image is not getting resized.

**Logs/Screenshots**
NA

**Version**
Library-Version - 0.9.5

**Comment by colinrtwhite** [comment]
If you need the size to be exact try adding `precision(Precision.EXACT)` to your request.

**Comment by SyedAmmarSohail** [comment]
I have an imageView which has **wrapContent** of his **height** and **width**. But the image is shown as smaller.
The image should resize with its respective icon, instead to give the width and height size. 

        imgItem.load(R.drawable.image) {
            placeholder(R.drawable.place_holder)
            error(R.drawable.broken_image)
            precision(Precision.EXACT)
            scale(Scale.FILL)

        }

**Comment by Squall-Huang** [comment]
```kotlin
binding.imageView.apply {
                                load(R.drawable.image) {
                                    size(256)
                                    scale(Scale.FIT)
                                    precision(Precision.EXACT)
                                }
                                scaleType = ImageView.ScaleType.CENTER_INSIDE
                            }
```

**Comment by mustafaberk1996** [comment]
Hi @Squall-Huang 
I am getting an error with this code on the `scaleType = ImageView.ScaleType.CENTER_INSIDE` (it is weird)

By the way, I did not success resize my images on a circleImageView, any progress with this?


**The real image is this, it is fit.**
<img width="989" alt="Screen Shot 2022-04-19 at 12 02 07" src="https://user-images.githubusercontent.com/57665619/163969481-700b9167-649a-4e5f-8d6c-bbd44bc2b148.png">


**But seem this**

<img width="62" alt="123456" src="https://user-images.githubusercontent.com/57665619/163969196-a5345792-a126-4a21-9443-21974c0f0501.png">
