### ISSUE TITLE
ImageDecoderDecoder does not display GIFs on Android 9

### ISSUE THREAD

**Issue by TalbotGooday** [coil-kt/coil#326]
Faced a problem on Android 9 in which the library does not display GIFs with the ImageDecoderDecoder.
With the GifDecoder it works fine.

There are no errors while loading and decoding the image, but the Drawable is not displayed

I'm using library version 0.9.5
```
    implementation  "io.coil-kt:coil:0.9.5"
    implementation  "io.coil-kt:coil-gif:0.9.5"
```

**Comment by colinrtwhite** [comment]
Hmm if you enable logging (`CoilLogger.setEnabled(true)`) does anything stand out? Also did you test on an emulator or real device? Can you post the GIF that reproduces the issue? Thanks.

**Comment by TalbotGooday** [comment]
I did not turn on the logger, but made a copy of the ImageDecoderDecoder on which I tested.  I tested on the emulator.  Unfortunately, there is no physical device.  I will send a gif and logs asap

**Comment by TalbotGooday** [comment]
Which tag should I track when I turn on the CoilLogger?

**Comment by TalbotGooday** [comment]
I made a test project with this error. Take a look, please:

https://github.com/TalbotGooday/Coil-Bug-Example

**Comment by colinrtwhite** [comment]
@TalbotGooday Thanks for the reproduction project. I'll take a look at this tomorrow.

**Comment by colinrtwhite** [comment]
@TalbotGooday The gifs show successfully on my Nexus 4 (API 28) emulator as well as my hardware Pixel 1. If you update to Android emulator 30.0.5 do you still see the issue?

**Comment by TalbotGooday** [comment]
@colinrtwhite The problem appears even after updating the emulator.
Emulator version: 30.0.5-6306047
Android: 9.0 (Pie) - API 28

Screenshot: https://ucarecdn.com/2109bbb9-aaeb-49bc-8ee2-ba4fa859bebe/

**Comment by colinrtwhite** [comment]
@TalbotGooday Are you able to reproduce this on a hardware device? My guess is this is due to an emulator issue.

**Comment by TalbotGooday** [comment]
Yes, you are probably right. Everything works fine on the physical device. Tested on Lenovo TB-X505L

**Comment by colinrtwhite** [comment]
:+1: Feel free to reopen if you encounter this again on a hardware device.
