### ISSUE TITLE
How to add authentication headers with coil

### ISSUE THREAD

**Issue by ma7moudAziz** [coil-kt/coil#332]
Hi Guys,
In my case downloading remote images from the server requires the user to be authenticated thus I need a way to send authentication headers through the coil.

Thanks in advance for your help.
Best Regards.

**Comment by Jawnnypoo** [comment]
Hey there, see [this section](https://coil-kt.github.io/coil/image_loaders/#caching) on caching. As you can see, you can provide your own `OkHttpClient`. With that client, you can call `addInterceptor` which will allow you to modify any `Request` to include headers, additional query params, etc.

**Comment by ma7moudAziz** [comment]
Hi @Jawnnypoo,
Thank you for your response, it works for me.
Regards.
