### ISSUE TITLE
ImageLoaderFactory

### ISSUE THREAD

**Issue by adesamp** [coil-kt/coil#353]
where i can find ImageLoaderFactory?
i have implement io.coil-kt:coil 
but unresolved reference error

i need implement this https://github.com/coil-kt/coil/blob/master/docs/getting_started.md#singleton

![image](https://user-images.githubusercontent.com/61401530/78763349-3abe2900-79af-11ea-843f-aa9690bd34e5.png)

![image](https://user-images.githubusercontent.com/61401530/78763400-47db1800-79af-11ea-89fb-549454f91b98.png)

**Comment by colinrtwhite** [comment]
It's part of the next release (`0.10.0`), which should be out soon. To get it now you can [depend on the snapshot](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots). Else, you can check out the docs for the current release [here](https://coil-kt.github.io/coil/getting_started/).

**Comment by mochadwi** [comment]
Is this the same we can do instead of using `ImageLoaderFactory interface`: https://coil-kt.github.io/coil/getting_started/#imageloaders

cc @adesamp

**Comment by colinrtwhite** [comment]
@mochadwi Yep, that's the current way in `0.9.5` :+1:
