### ISSUE TITLE
Crossfade + placeholder + wrap_content can result in a streched image

### ISSUE THREAD

**Issue by Stonos** [coil-kt/coil#36]
**Describe the bug**
Loading an image with crossfade and a placeholder enabled can result in a stretched image if the ImageView uses `wrap_content` and the placeholder has a different aspect ratio than the image being loaded.

If the app goes to the background and then to the foreground again, the image appears correctly.

(the placeholder has to be larger than the ImageView for this to occur)

**To Reproduce**
Sample project: [CoilPlaceholderAR.zip](https://github.com/coil-kt/coil/files/3509450/CoilPlaceholderAR.zip)

**Expected behavior**
The loaded image should not appear stretched.

**Logs/Screenshots**
![device-2019-08-16-143148-2](https://user-images.githubusercontent.com/42659/63166113-1b484980-c036-11e9-85c2-2a006d151b5b.gif)

**Library version**
0.6.1 (manually compiled)

**Comment by colinrtwhite** [comment]
Thanks for the report. I'll take a look at this this weekend. Likely an issue with [CrossfadeDrawable](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/drawable/CrossfadeDrawable.kt).
