### ISSUE TITLE
Custom URI scheme support or similar for generated images or non standard storage

### ISSUE THREAD

**Issue by rohitst** [coil-kt/coil#365]
**Is your feature request related to a problem? Please describe.**
My images are either generated on the fly or stored in a place not supported by one of coil's supported data types (as specified here https://coil-kt.github.io/coil/getting_started/)

**Describe the solution you'd like**
e.g for async loading images that are generated from a date input -> Date bitmap
1) be able to use syntax  
`imageView.load("myAppScheme://dateImageGen?date=2002-04-16")`

2) At some point during Coil initialization be able to register a 
```
DateBitmapHandler: CoilCustomUrlHandler() {
        canHandleUri(Uri uri): Boolean { MY_SCHEME == uri.scheme
        handleUri(Uri uri): Bitmap? { parse out params and generate and return Bitmap }
}

```

**Additional context**
This would give devs all the benefits of using an image loading lib and be able to use other sources of images.
Glide -> no support
Picasso does support this https://futurestud.io/tutorials/picasso-custom-request-handlers
Coil -> no support
Android UIL -> did support but it's been a while since I've used it

**Comment by colinrtwhite** [comment]
This is actually already supported in a more generalized form than Picasso. Picasso requires you to use a `Uri` wheres with Coil you can create a custom `Uri` [Fetcher](https://coil-kt.github.io/coil/image_pipeline/#fetchers) or use a custom data type. [Here's an example](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/fetch/ContentUriFetcher.kt#L17) of a custom `Uri` fetcher that checks the scheme and opens a `BufferedSource` to the underlying data. [Here's a more in-depth explanation](https://coil-kt.github.io/coil/image_pipeline/#extending-the-image-pipeline).

**Comment by rohitst** [comment]
Thank you! I will try this. Closing...
