### ISSUE TITLE
SVG image is not shown in dynamically added layout

### ISSUE THREAD

**Issue by neoh-zz** [coil-kt/coil#367]
Here is my simplest reproducible example: I have a linear layout `cell.xml` which is dynamically inflated into a parent `activity_main.xml` layout in the `onCreate` method:

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val linearLayout = findViewById<LinearLayout>(R.id.linearLayout)
        val cell = layoutInflater.inflate(R.layout.cell, linearLayout, false)
        val iv = cell.findViewById<ImageView>(R.id.image_cell)
        iv.load("file:///android_asset/any.svg")
        linearLayout.addView(cell)
    }

My `activity_main.xml`:

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/linearLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">
    </LinearLayout>

My `cell.xml`:

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/image_parent"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <ImageView
            android:id="@+id/image_cell"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:contentDescription="@+string/desc"
            android:gravity="center"/>
    </LinearLayout>

The svg displays correctly if I use attribute `android:layout_height="wrap_content"` inside the image view, but it won't display the svg image if `android:layout_height="match_parent"` is used instead. For the record, I need the `image_parent` linear layout to have `android:layout_height="match_parent"` because the actual layouts of both xml's contain some background drawables which eventually require the height attribute of `image_parent` to be set to `match_parent`.

I believe this problem applies to any svg, but if you cannot reproduce the issue please let me know, I will upload one svg file which I used.

**Comment by colinrtwhite** [comment]
If you call `.load` after adding the view to the hierarchy does it fix the issue? If not can you [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and see if there are any errors?

**Comment by neoh-zz** [comment]
The problem persists if I call `.load` after adding the view. After enabling logging, it raises the error

    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
        at coil.bitmappool.RealBitmapPool.get(RealBitmapPool.kt:90)
        at coil.SvgDecoder.decode(SvgDecoder.kt:92)
        at coil.RealImageLoader$loadData$2.invokeSuspend(RealImageLoader.kt:354)

even though I have width and height values in my svg. It loads without error if I set `android:layout_height="wrap_content"` in my image view. After further digging, I found that the svg decoder does indeed parses svg width and height correctly, but the `DecodeUtils.computeSizeMultiplier ` in `fun decode()` computes a too small multiplier value, causing the final `bitmapWidth` to be zero.

Here are the input arguments to `DecodeUtils.computeSizeMultiplier ` in my case:

    srcWidth = 198.26, srcHeight = 232.75
    dstWidth = 1080.0, dstHeight = 1.0
    scale = FIT

    result:
    multiplier 0.0042964555
    bitmapWidth = 0 , bitmapHeight = 1

**Comment by colinrtwhite** [comment]
@neoh-zz Thanks for the stacktrace. Sounds like it might be an issue with the measurement algorithm in [`ViewSizeResolver`](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/size/ViewSizeResolver.kt). I don't think this is specifically related to SVGs. I'll take a look at this this weekend, but if you figure it out before then feel free to submit a PR.

**Comment by colinrtwhite** [comment]
@neoh-zz Circling back on this. I think this might be caused by your layout being measured as 0 height due to your `LinearLayout` being set to `android:layout_height="wrap_content"` in `activity_main.xml`. Does it work if you change it to `match_parent`? Optionally, you could set `android:scaleType="centerCrop"` on your `ImageView`.

**Comment by neoh-zz** [comment]
I agree that the issue stems from the 0 height measured when the image is loaded (changing `match_parent` in `activity_main.xml` does not work). My views are actually dynamically added, `cell.xml` is just a cell of a table layout, whose cell widths are programmatically calculated. Currently I can solve this problem by (i) use `android:layout_height=wrap_content` instead of `android:layout_height=match_parent` in the imageView, or (ii) force trigger the imageView to redraw by calling `invalidate()` in `OnGlobalLayoutListener()` whenever the view bounds are newly calculated. The second solution is probably the safest way to go.
