### ISSUE TITLE
Cannot Sync gradle with the new version.

### ISSUE THREAD

**Issue by Superblazer** [coil-kt/coil#374]
"ERROR: Failed to resolve: io.coil-kt:coil:0.10.1
Show in Project Structure dialog
Affected Modules: app"

This works with the previous version 0.9.1

**Comment by Amalip** [comment]
@Superblazer what was the problem?

**Comment by colinrtwhite** [comment]
Looks like there was an issue with publishing `0.10.1`. I uploaded it again and it should be available in ~1 hour.

**Comment by Amalip** [comment]
@colinrtwhite Thank you!
