### ISSUE TITLE
Image Icon From drawable

### ISSUE THREAD

**Issue by SyedAmmarSohail** [coil-kt/coil#377]
I have an imageView which has **wrapContent** of his **height** and **width**. But the image is shown as smaller.
The image should resize with its respective icon, instead to give the **width** and **height** size.

    imgItem.load(R.drawable.image) {
        placeholder(R.drawable.place_holder)
        error(R.drawable.broken_image)
        precision(Precision.EXACT)
        scale(Scale.FILL)
    }

**Version**
0.10.1

**Comment by colinrtwhite** [comment]
Do you have a sample I can use to reproduce this issue? The current bug report isn't very actionable.
