### ISSUE TITLE
java.lang.IllegalStateException: Unable to fetch data

### ISSUE THREAD

**Issue by androidseb25** [coil-kt/coil#379]
**Describe the bug**
When i load an image from Filepath i receive following issue

`java.lang.IllegalStateException: Unable to fetch data No fetcher supports: /storage/9016-4EF8/DCIM/100ANDRO/DSC_0686.JPG
`

Code looks like this

`iv.load(File(path)) {
                                crossfade(true)
                                error((resources?.getIdentifier("error_img", "drawable", packageName) as Int))
                                listener(
                                        onError = { request, throwable ->
                                            println(throwable.stackTrace)
                                        },
                                        onSuccess = { request, source -> println("success") }
                                )
                            }`

**Version**
Android 10 and latest version of coil

I hope someone can help me :(

**Comment by colinrtwhite** [comment]
Did you register any custom `Mappers` when creating your `ImageLoader`? Also, if you do `iv.load("file://$path")` does it work?

**Comment by androidseb25** [comment]
Hi thanks for the answer,

no no any other Mappers and `iv.load("file://$path")` brings me now a `java.io.FileNotFoundException: /storage/9016-4EF8/DCIM/100ANDRO/IMG-20150509-WA0002.jpeg: open failed: EACCES (Permission denied)`, but the file is existing :/

**Comment by androidseb25** [comment]
After research by stackoverflow i found a solution

for Android 10 add this in the Manifest file

`<application ...
    android:requestLegacyExternalStorage="true" ... >`

And now it works :D

**Comment by colinrtwhite** [comment]
Ah yep, that'll work for now, but long term you'll need to handle [scoped storage](https://developer.android.com/preview/privacy/storage).
