### ISSUE TITLE
Glitches sometimes in picture

### ISSUE THREAD

**Issue by billyjoker** [coil-kt/coil#381]
**Describe the bug**
Sometimes i get the image loaded with a glitch. I tried [this solution](https://github.com/coil-kt/coil/issues/285) talked in ahother issue but still occurring

`allowHardware(false)`

**Expected behavior**
No glitches

**To Reproduce**
Randomly

**Logs/Screenshots**
![Screenshot_20200430-190746](https://user-images.githubusercontent.com/4301306/80746706-a0bb4d80-8b22-11ea-9c35-08ae47050114.png)

**Version**
0.10.1

**Comment by colinrtwhite** [comment]
Do you have a sample I can use to reproduce this issue?

**Comment by billyjoker** [comment]
Sorry I'm late, but i was testing different ways to get this glitch. I put the picture as a local drawable and i've got again the glitch. I attach the picture.

`
        image_english.load(R.drawable.english_3) {
            placeholder(R.drawable.card_placeholder_dark)
            crossfade(true)
            crossfade(700)
            scale(Scale.FIT)
            allowHardware(false)
            transformations(
                    VignetteFilterTransformation(this@HomeActivity))
            target { drawable ->
                image_english.setImageDrawable(drawable)
                linear_title__english.visibility = VISIBLE
            }
        }
`

![english_3](https://user-images.githubusercontent.com/4301306/82985831-06510b80-9ff5-11ea-969e-470f9ce13566.jpg)
