### ISSUE TITLE
Allow access to internal Utils for debugging purposes and improve usage stats.

### ISSUE THREAD

**Issue by bmohan-bushel** [coil-kt/coil#382]
**Is your feature request related to a problem? Please describe.**
My team is considering migrating from Picasso to Coil. We have had an internal debugging tool with Picasso that allows us to view stats of the Picasso instance, using the Picasso StatsSnapshot object. We would like to keep that functionality, and it looks like some of the same logic is already in this library.

**Describe the solution you'd like**
Cache data appears to be already present in coil.util.Utils but it is marked as internal. Not all of the stats that we use are tracked however. It would useful to have similar snapshot functionality with Coil.

**Additional context**
Here are the stats accessible in StatsSnapshot
```
  public final int maxSize;
  public final int size;
  public final long cacheHits;
  public final long cacheMisses;
  public final long totalDownloadSize;
  public final long totalOriginalBitmapSize;
  public final long totalTransformedBitmapSize;
  public final long averageDownloadSize;
  public final long averageOriginalBitmapSize;
  public final long averageTransformedBitmapSize;
  public final int downloadCount;
  public final int originalBitmapCount;
  public final int transformedBitmapCount;
```

**Comment by colinrtwhite** [comment]
Hmm I don't think these stats are tracked in the library at the moment. `Utils` computes the max cache file size, but doesn't handle reads/writes. We could probably let users calculate these values (and more) themselves by exposing the decoded + transformed drawables in the `EventListener` API. Exposing the underlying data structures would allow users to compute their own stats (like distributions) without restricting them to averages and totals.

That said, I'm not 100% sure that's a good idea as users could misuse direct access to the underlying bitmap by modifying its pixels or keeping strong references.

`totalDownloadSize` and `averageDownloadSize` would be slightly tough to support as we only know the size if a `Fetcher`'s source is exhausted, which is typically only true after decoding however it's not guaranteed.

**Comment by colinrtwhite** [comment]
Also for cache hit stats - looks like OkHttp [has plans](https://github.com/square/okhttp/pull/6015/files) to add that to their `EventListener` API.

**Comment by bmohan-bushel** [comment]
Looks like it would be a bit of a headache to pull that data all together from the different sources then.

**Comment by colinrtwhite** [comment]
The approach would be similar to Picasso 3 - provide an `EventListener` [implementation](https://github.com/square/picasso/blob/master/picasso-stats/src/main/java/com/squareup/picasso3/stats/StatsEventListener.kt) that tracks the stats.

**Comment by colinrtwhite** [comment]
Closing this as [`EventListener`](https://coil-kt.github.io/coil/api/coil-base/coil/-event-listener/) can be used to build stats tracking functionality.
