### ISSUE TITLE
Loading images into "gone" Views cause downsampling to 1x1 BitmapDrawable

### ISSUE THREAD

**Issue by littledot** [coil-kt/coil#387]
**Describe the bug**

Consider the following layout:
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/img1"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:visibility="gone" />
</FrameLayout>
```
When Coil loads an image into a View whose visibility is "gone", it will downsample the image into a 1x1 BitmapDrawable.
```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main)

        val src =
            "https://pbs.twimg.com/profile_images/378800000666093975/cbe970ce9a19d2c6bec0d06c6004ccf0_400x400.png"

        Coil.loadAny(this, src) {
            target(img1)
            listener { request, source ->
                img1.visibility = View.VISIBLE
            }
        }
    }
}
```

**Expected behavior**

I think other libraries won't even start loading the image until the target View has valid dimensions.

I think it has something to do with this [size resolver.](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/size/ViewSizeResolver.kt#L62)

**To Reproduce**

Run the project: https://gitlab.com/littledot/android-bug-report

**Logs/Screenshots**

![](https://gitlab.com/littledot/android-bug-report/-/raw/master/screenshot/coil387.png)

**Version**
Coil 0.10.1

**Comment by colinrtwhite** [comment]
Thanks for the repro project! I think this is due to `ViewSizeResolver` waiting at most one layout pass for valid dimensions when instead we should wait as many as needed. Will have a fix up soon.
