### ISSUE TITLE
Crossfade and custom ImageTarget doesn't seems to work

### ISSUE THREAD

**Issue by damiancioo** [coil-kt/coil#388]
When requesting crossfade
```crossfade(true)```
with custom ImageTarget
```
imageView.load(url) {
  target(RoundedImageTarget(imageView, isCircle, radius))
}
```

RoundedImageTarget:

```
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory
import androidx.core.graphics.drawable.toBitmap

class RoundedImageTarget(
    view: ImageView,
    private val isCircle: Boolean,
    private val radius: Float? = null
) : ImageViewTarget(view) {
    override fun setDrawable(drawable: Drawable?) {
        val roundedDrawable = try {
            drawable?.let {
                val bitmap = it.toBitmap()
                val output = RoundedBitmapDrawableFactory.create(view.resources, bitmap)
                output.cornerRadius = if (isCircle) {
                    min(bitmap.width.toFloat(), bitmap.height.toFloat())
                } else radius ?: 0f
                output
            }
        } catch (e: IllegalArgumentException) {
            drawable
        }
        super.setDrawable(roundedDrawable)
    }
}
```

Combination of two makes crossfade effect NOT running.

Coil version: 0.10.1

**Comment by colinrtwhite** [comment]
You'll have to call `(drawable as? Animatable)?.start()` manually, as you're passing a wrapped `roundedDrawable` to `super.setDrawable`.

**Comment by colinrtwhite** [comment]
@damiancioo You could also use a `CircleCropTransformation` for this use case:

```kotlin
imageView.load(url) {
    if (isCircle) {
        transformations(CircleCropTransformation())
    }
}
```

**Comment by damiancioo** [comment]
Just to not be forgotten, I had CircleCropTransformation at first place, but after that there was some issues with view transitions, when changing from rounded image to square, so I moved to RoundedImageTarget.

`(drawable as? Animatable)?.start()` doesn't seem to make any difference in any method of `ImageViewTarget`

**Comment by colinrtwhite** [comment]
`val bitmap = it.toBitmap()` will convert the crossfade drawable into a bitmap, which means it can no longer animate. You could wrap it in another `CrossfadeDrawable` then call `start()` on it. I'm sorry, but as this isn't a Coil bug I don't have bandwidth to debug further.

**Comment by damiancioo** [comment]
Wrapping `RoundedBitmapDrawable` inside `CrossfadeDrawable` together with placeholder worked.
