### ISSUE TITLE
Can't load svg from Amazon S3

### ISSUE THREAD

**Issue by baillyjamy** [coil-kt/coil#389]
**Describe the bug**
I have a url pre-signed that represent a picture in an instance of S3. I would like to load this picture but i have this error :
```
Image Error : java.lang.IllegalStateException: Unable to fetch data. No fetcher supports : "S3URL"
```
I would point out that the object is of the type `java.net.URL`. The pre-signed work and i can get the file with this url on my browser.

**Expected behavior**
Load the picture with aws s3 pre-signed url.

**To Reproduce**
```kotlin
val request = LoadRequest.Builder(this.view.context)
            .data(card.imageUrl)
            .listener(
                onError = { _, error ->
                    Timber.d("Image Error : %s", error)
                })
            .target(view.imageView)
            .build()
Coil.imageLoader(view.context).execute(request)
```
```kotlin
override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(this)
            .componentRegistry {
                add(SvgDecoder(this@MainApplication))
            }
            .build()
    }
```

**Version**
Coil version : `0.10.0`

**Comment by baillyjamy** [comment]
With a Uri (`Uri.parse(card.imageUrl.toString())`) i have this error :
```
java.lang.IllegalStateException: BitmapFactory returned a null Bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network or disk) as it's not encoded as a valid image format.
        at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:153)
        at coil.RealImageLoader$loadData$2.invokeSuspend(RealImageLoader.kt:354)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by colinrtwhite** [comment]
Coil by default doesn't support `URL` (only `HttpUrl`). Passing it as a String (`.data(url.toString())`) is the recommended way to load it.

Re the `BitmapFactory` exception: Coil attempts to detect SVGs using their mime type. It's likely your URL doesn't end in `.svg` or the server returns an incorrect content type. To solve this you can set the decoder explicitly for the request:

```kotlin
val request = LoadRequest.Builder(context)
    .data(url.toString())
    .decoder(SvgDecoder())
    .target(imageView)
    .build()
```

**Comment by baillyjamy** [comment]
Thank you for your help. The content type was not correctly assign. Just to know. If i register `SvgDecoder` in my `ImageLoader`. I need also to set the decoder in the request ? Is it not implicit ?

**Comment by colinrtwhite** [comment]
It's recommended you register `SvgDecoder` when building your `ImageLoader` so it can automatically handle cases where the URL/file ends with `.svg`. However, in this case you need to set it explicitly for the request.

Other decoders like `GifDecoder` can check for an image's header signature, however SVGs don't have one.

**Comment by baillyjamy** [comment]
Ok, Thank you very much for these clarifications
