### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by gastsail** [coil-kt/coil#39]
At the documentation it says minSdkVersion = 14 , but When I run the app, it says that it requires Android N , minSdkVersion = 24 to run

I changed the minSdkVersion in my gradle to 24 and the app is running

**Comment by colinrtwhite** [comment]
Coil only uses Java 8 features that can be desugared by R8. To enable D8 desugaring check out the docs [here](https://coil-kt.github.io/coil/getting_started/#java-8).

**Comment by gastsail** [comment]
yes, I added those to work with the .load() method , and it works nice, but when I try to compile with sdk < 24 it says that it requires Android N to run

**Comment by gastsail** [comment]
Hi @colinrtwhite , can you check if that is ok ? , I'm running gradle 3.4.2

**Comment by colinrtwhite** [comment]
@gastsail You only did one part of the documentation; you also need to add `compileOptions`. See [here](https://coil-kt.github.io/coil/getting_started/#java-8). Also I would update your Gradle version. `5.6` is the latest.
