### ISSUE TITLE
CircleCropTransformation for placeholder or error

### ISSUE THREAD

**Issue by aleksei-kon** [coil-kt/coil#392]
CircleCropTransformation not work for placeholder or default error image. Does coil support such functionality?

![image](https://user-images.githubusercontent.com/47315479/81144712-4c2e2d00-8f7d-11ea-87c1-7babf2cd2584.png)

As placeholder I use this png image 
![default_placeholder](https://user-images.githubusercontent.com/47315479/81145216-7fbd8700-8f7e-11ea-9d49-bd5fb4a888f1.png)

**Comment by colinrtwhite** [comment]
Applying transformations to placeholder/error drawables is not supported. Tracked here: https://github.com/coil-kt/coil/issues/37
