### ISSUE TITLE
Need load local svg (from assert or raw) 

### ISSUE THREAD

**Issue by AlexNarbut** [coil-kt/coil#393]
Hello, i have my test app with several svg (i put them in raw directory (can to assets)). I found ImageLoder, but when i read doc, i thoutht that imageloder needs for network (remove) request (download), but not for local 

How can i load this svg to imageview with coil ?

**Comment by colinrtwhite** [comment]
You can reference Android assets using a uri in the following format: `file:///android_asset/image.jpg`. Once you have a uri you can call` imageView.load(uri)`. For SVG support check out: https://coil-kt.github.io/coil/svgs/
