### ISSUE TITLE
Image Sampling not working as shown in the README preview gif

### ISSUE THREAD

**Issue by lawloretienne** [coil-kt/coil#4]
**Describe the bug**
I tried to set up image sampling the way it is described in :

https://coil-kt.github.io/coil/getting_started/#image-sampling

but I don't see any low-res image loaded with a crossfade effect to the high-res image.

**To Reproduce**

```
imageView.load(image) {
    crossfade(true)
}
```

I am loading images in a `RecyclerView.Adapter`.

**Expected behavior**
A crossfade effect from low to the high res image.

**Logs/Screenshots**

**Library version**
e.g. 0.6.0

**Comment by lawloretienne** [comment]
I guess you have to specify the duration

```
imageView.load(image) {
    crossfade(true)
    crossfade(300)
}
```

but this doesn't have the cool pixelated effect that is in the gif.

**Comment by Gryzor** [comment]
@lawloretienne the gif is intentionally slowed down to _see_ the effect (or so it says there):

> List images have intentionally been loaded in low res and the crossfade has been slowed down to highlight the effect.

**Comment by colinrtwhite** [comment]
@lawloretienne It's expected behaviour to not see the image sampling effect on first load. The image sampling only comes into play when Coil has already loaded the image into memory at a smaller size than necessary. Next time that data is requested, it'll use that smaller image as a placeholder and fire off a new request to load the image at a greater size.

**Comment by lawloretienne** [comment]
i changed to 

```
imageView.load(image) {
    crossfade(900)
}
```

and still dont see the image sampling effect even on loads after the first load.

**Comment by colinrtwhite** [comment]
@lawloretienne Is `image` a Drawable? The effect currently only works for images that can be cached in the memory cache, which is URLs, Files, and Uris. However, I'm looking to improve that behaviour in a future release.

**Comment by lawloretienne** [comment]
image is a url.

**Comment by colinrtwhite** [comment]
@lawloretienne Hmm I'm not able to reproduce. I used your test image in the sample app and the smaller placeholder is set synchronously. The larger image crossfades in when the request completes.

If you're running the sample app locally, the image sampling effect isn't nearly as visible as in [the GIF](https://coil-kt.github.io/coil/getting_started/#image-sampling). Note: *Images in the list have intentionally been loaded with very low detail and the crossfade is slowed down to highlight the visual effect.*

**Comment by lawloretienne** [comment]
So if the gif doesnt represent whats happening at normal speeds then why even bother showing it.

**Comment by Gryzor** [comment]
@lawloretienne because it helps other people understand what is going on, how the effect performs, and perhaps observe more detail that would otherwise get lost at full speed. Geez.

**Comment by colinrtwhite** [comment]
@lawloretienne If you'd like to recreate the same effect, you can set the images in your list to low detail using:

```kotlin
imageView.load(url) {
    size(100, Int.MAX)
    scale(Scale.FILL)
}
```

and then set `crossfade(4000)` on your detail `ImageView`.

However, I believe it's better UX if the effect is as subtle to the user as possible (see Instagram). To the user, images seem to be set instantly vs. having to wait for us to reload the image from disk/other data sources.
