### ISSUE TITLE
Default MemoryCachePolicy fails in a RecyclerView (default imageLoader & default parameters)

### ISSUE THREAD

**Issue by kkcodings** [coil-kt/coil#410]
When I load an Image from an URL with the following code and reopen this screen, the ImageViews are mostly just blank. (probably due to caching issues)
```
fun ImageView.loadUrl(url: String) {
    load(url)
}
```

When I change the CachePolicy of the memoryCache to anything except CachePolicy.ENABLED (even to READ) the images are shown properly on every attempt, e.g.:
```
fun ImageView.loadUrl(url: String) {
    load(
        uri = url,
        builder = {
            memoryCachePolicy(CachePolicy.READ_ONLY)
        }
    )
}
```

I guess the expected behaviour would be showing the cached bitmap, and then replace with the image from the network call. 
When I tried to debug this with the callbacks in target, onStart and onSuccess were successfully called. Unfortunately I cannot view the bitmap on debug there because of bitmap configuration issues.

coil 0.11.0
Pixel 4

**Comment by colinrtwhite** [comment]
If you don't set the memory cache policy, can you post the error from `onError`?

**Comment by kkcodings** [comment]
That's the thing. It doesn't fail, it can successfully load the bitmap, which is blank.

**Comment by colinrtwhite** [comment]
Can you try [enabling logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging)? Also if you set `allowHardware(false)` does it work?

**Comment by kkcodings** [comment]
I got the following logs when I disabled allowHardware:

```
2020-05-22 11:04:06.582 7418-7418/<applicationID> I/RealImageLoader: 💾 Successful (DISK) - <imageUrl-1>
2020-05-22 11:04:06.586 7418-7418/<applicationID> I/RealImageLoader: 💾 Successful (DISK) - <imageUrl-2>
2020-05-22 11:04:08.998 7418-7418/<applicationID> I/RealImageLoader: 🧠 Cached - <imageUrl-1>
2020-05-22 11:04:08.999 7418-7418/<applicationID> I/RealImageLoader: 🧠 Cached - <imageUrl-2>

```

Note that the first two lines are from the first attempt after killing the app, which shows the images successfully. And the following lines with the Cached tag are right after reopening the same fragment, where the images are

**Comment by colinrtwhite** [comment]
Hmm those logs are the expected behaviour. Do you have a small sample that reproduces the bug? It's not clear what the root cause is based on the logs and I'm not able to reproduce locally.

**Comment by kkcodings** [comment]
When i tried to build a small sample, I found the source of this issue:  

The RecyclerView had `hasFixedSize = true` and the list got an empty list, and afterwards the real dataset, which was causing the issue obviously. 
I have still no idea, why it worked at the first attempt, and failed at the second one, and why the memory-caching of coil is affected by that. 

Nevertheless thanks for your support.
