### ISSUE TITLE
Image not Displayed Correctly when adjustViewBounds active

### ISSUE THREAD

**Issue by JosephSanjaya** [coil-kt/coil#420]
**Describe the bug**
Image not displayed corretly when **adjustViewbounds** in ImageView set to **true**, and add **Transformation set RoundedCornerTransformation**

**Expected behavior**
Image displayed to fit width and wrap content when adjustViewBounds true, and **Transformation set RoundedCornerTransformation**, instead it show picture so big or if we set maxheight then it just shown picture cropped portrait with rounded.

**To Reproduce**
**adjustViewbounds** in ImageView set to **true**, and add **Transformation set RoundedCornerTransformation**

**Version**
0.9.5

**Comment by colinrtwhite** [comment]
This sounds like the size resolver is falling back to the size of the display since the view doesn't have a valid size, which is expected behaviour. If you need the image in its original size you should set `size(OriginalSize)`.

**Comment by tmm1** [comment]
I'm running into this too. Would it be possible to automatically use OriginalSize when the ImageView has adjustViewBounds set?
