### ISSUE TITLE
Unexpected image cropping with RoundedCornersTransformation

### ISSUE THREAD

**Issue by Sottti** [coil-kt/coil#421]
The only difference between these two images is one applies the RoundedCornersTransformation and the other doesn't. xml is same for both.

ImageView is children of a ConstraintLayout. Constraint to parent with 0dp dimensions.

What I want to achieve is exactly this image with rounded corners.
<img width="326" alt="Screenshot 2020-06-04 at 01 10 28" src="https://user-images.githubusercontent.com/4732495/83701032-5e44cf00-a600-11ea-988f-3da44ec1e71c.png">

What I get instead is a cropped image (top and bottom)
<img width="463" alt="Screenshot 2020-06-04 at 01 10 23" src="https://user-images.githubusercontent.com/4732495/83701021-5ab14800-a600-11ea-847d-634aa4a11bee.png">

Is this expected behaviour? What is the reason?

I want to show the full image with original aspect ratio, and the images scales up until it reaches either width or height constraint.

**Comment by colinrtwhite** [comment]
Yep, this is expected behaviour ([docs](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/transform/RoundedCornersTransformation.kt#L26)). If you want to fit the image and crop you can use `scale(Scale.FIT)`.

**Comment by Sottti** [comment]
What I'm looking for is showing exactly same crop than without the transformation. What is weird is that if you look at the two pictures above, the only (only at all!) difference between them is the transformation, which I'd say is very unexpected! I'd expect cropping be the same.

Thanks!

**Comment by colinrtwhite** [comment]
@Sottti I've also gotten feedback that not cropping to the target's size is more unexpected. For reference, Glide also crops to the target's size.

Here's a version of `RoundedCornersTransformation` that does not crop:

```kotlin
/**
 * A [Transformation] that rounds the corners of the image.
 *
 * @param topLeft The radius for the top left corner.
 * @param topRight The radius for the top right corner.
 * @param bottomLeft The radius for the bottom left corner.
 * @param bottomRight The radius for the bottom right corner.
 */
class RoundedCornersTransformation(
    @Px private val topLeft: Float = 0f,
    @Px private val topRight: Float = 0f,
    @Px private val bottomLeft: Float = 0f,
    @Px private val bottomRight: Float = 0f
) : Transformation {

    constructor(@Px radius: Float) : this(radius, radius, radius, radius)

    init {
        require(topLeft >= 0 && topRight >= 0 && bottomLeft >= 0 && bottomRight >= 0) { "All radii must be >= 0." }
    }

    override fun key() = "${RoundedCornersTransformation::class.java.name}-$topLeft,$topRight,$bottomLeft,$bottomRight"

    override suspend fun transform(pool: BitmapPool, input: Bitmap, size: Size): Bitmap {
        val paint = Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG)

        val output = pool.get(input.width, input.height, input.safeConfig)
        output.applyCanvas {
            drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR)

            paint.shader = BitmapShader(input, Shader.TileMode.CLAMP, Shader.TileMode.CLAMP)

            val radii = floatArrayOf(topLeft, topLeft, topRight, topRight, bottomRight, bottomRight, bottomLeft, bottomLeft)
            val rect = RectF(0f, 0f, width.toFloat(), height.toFloat())
            val path = Path().apply { addRoundRect(rect, radii, Path.Direction.CW) }
            drawPath(path, paint)
        }
        pool.put(input)

        return output
    }
}
```

**Comment by Sottti** [comment]
I great, let me try that.

@colinrtwhite what is `safeConfig` doing? Is the only have I can't resolve.

**Comment by colinrtwhite** [comment]
Ah yep, `safeConfig` just guards against the bitmap config being null. Closing this out.

**Comment by Sottti** [comment]
Thanks a lot!
