### ISSUE TITLE
Are network exceptions propagated to callers?

### ISSUE THREAD

**Issue by jzbrooks** [coil-kt/coil#431]
We've been seeing some network errors (in the form of `IOException`) that seem to be related to image loading. I've briefly tried to understand how these types of errors are handled by coil or if they're propagated to callers, but don't have a ton of time to invest at the moment.

The new result type that's returned from `Coil.execute(request)` seems to imply, from an API surface level, that exceptions are caught result in a null drawable on the result since the drawable is nullable and that it's possible to specify an image to use in the case of error for loads. I want to understand better if I'm responsible for network exceptions or if coil handles those for me.

Am I missing the documentation, or is that an area in the docs that could be improved?

My project has been on 0.9.5 for a while but is in the middle of upgrading to 0.11.0.

**Comment by colinrtwhite** [comment]
Yep, the  `RequestResult` type returned by `ImageLoader.execute` contains all exceptions except `CancellationException`s (which are a special exception type for coroutines). This way callers are forced to handle success/error states and aren't caught off guard by uncaught exceptions thrown in their `CoroutineScope`.

**Comment by jzbrooks** [comment]
Got it. Somehow I missed the sealed class inheritors the first time through. Thanks!
