### ISSUE TITLE
Support for XML Drawables in placeholder

### ISSUE THREAD

**Issue by Queatz** [coil-kt/coil#433]
**Describe the bug**
Supplying an XML drawable resource results in a white placeholder.

**Expected behavior**
The placeholder is the drawable rendered correctly.

**To Reproduce**
Supply an XML drawable as a placeholder.  The one I'm using is:

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:width="64dp" android:height="64dp">
        <shape android:shape="rectangle">
            <gradient android:startColor="@color/colorPrimaryDark" android:endColor="@color/colorPrimary" android:angle="45" />
        </shape>
    </item>
</layer-list>
```

**Version**
0.11.0

**Comment by colinrtwhite** [comment]
Hmm I'm not able to reproduce this using `coil-sample`. Maybe your `width`/`height` are too large?

**Comment by Queatz** [comment]
It's the background of a screen in the app.  The device I'm testing with has a screen size of 1440x2560.  I'm using a crossfade as well.  It works when crossfading from a color resource, but the drawable above is crossfading from white.

**Comment by colinrtwhite** [comment]
Maybe it's being cropped by your scale? If you set `scale(Scale.FIT)` it will fit to the target's min dimensions.

**Comment by Queatz** [comment]
I did some more investigating and was able to get it working by removing the `android:width="64dp" android:height="64dp"` part from the drawable.

Interestingly, when I removed `android:scaleType="matrix"` from the ImageView, I did see the drawable at it's 64x64 size.

Up to you if you want to keep this open, from my POV it can be closed now.

**Comment by colinrtwhite** [comment]
👍 Sounds good.
