### ISSUE TITLE
How to pause request and resume request like Glide 

### ISSUE THREAD

**Issue by WuBingHui** [coil-kt/coil#435]
I have a list.
 when scroll was stoped  to do resume requests ,on the contrary scrolling to do pause requests
On Glide  like this. 
Glide.with(context).pauseRequests()
Glide.with(context).resumeRequests()

**Comment by colinrtwhite** [comment]
It's currently not possible to pause/resume requests globally with Coil.

**Comment by WuBingHui** [comment]
thank you !
