### ISSUE TITLE
Coil should automatically rotate images based on Exif information

### ISSUE THREAD

**Issue by ianhanniballake** [coil-kt/coil#44]
**Describe the bug**
When images have rotation information embedded within their Exif information, Coil should use that to automatically rotate the image correctly.

This is something that other image libraries (Glide, Picasso) do already. Using the [AndroidX ExifInterface library](https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface) allows you to extract the orientation information from any `Uri` / `InputStream`.

**To Reproduce**
You can use [this sample image](https://drive.google.com/file/d/1Ry_kfL37_cqXWeCwLDML9_spCFqiK6Fo/view?usp=sharing).

**Expected behavior**
The image should be rotated correctly.

**Logs/Screenshots**
n/a

**Library version**
0.6.1

**Comment by colinrtwhite** [comment]
Thanks for the report. Coil already uses the AndroidX Exif library as part of [BitmapFactoryDecoder](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/decode/BitmapFactoryDecoder.kt#L61) and should be automatically handling rotations, but I'll run the sample image to see what Coil's missing. I have a test [here](https://github.com/coil-kt/coil/blob/master/coil-base/src/androidTest/java/coil/decode/BitmapFactoryDecoderTest.kt#L97) as well to cover all the rotations.

**Comment by ianhanniballake** [comment]
FWIW, the case I was testing was loading the image via `Uri` - specifically, from a local `ContentProvider`. I suppose a `FileProvider` generated `Uri` would be similar enough for testing purposes.

**Comment by colinrtwhite** [comment]
Confirmed. Going to look into fixing this today.
