### ISSUE TITLE
Maybe add to documentation that Coil do not have its own disk cache like Glide or Picasso?

### ISSUE THREAD

**Issue by Viska97** [coil-kt/coil#442]
I think it is important for developers who want to migrate from Glide or Picasso know that Coil do not have own disk cache. I was shocked when discovered that. I think for applications that works with large images and uses them only in one place (only one variant of transformations used across app) it will be significant performance drop at cold start, becuase Coil at cold start will always load unoptimised copy of image (from source file for local image or file from OkHttp cache) instead of only load sampled image from disk cache.

**Comment by colinrtwhite** [comment]
Coil uses `OkHttp`'s disk cache, which is what Picasso does as well. It's also already mentioned in the docs [here](https://coil-kt.github.io/coil/image_loaders/#caching).
