### ISSUE TITLE
Add support for Jetpack Compose

### ISSUE THREAD

**Issue by Icyrockton** [coil-kt/coil#443]
Jetpack compose alpha is coming in summer.....
support jetpack compose, I think it will improve the competitiveness of coil
😎

**Comment by colinrtwhite** [comment]
Totally agree! Chris Banes actually has a [library](https://github.com/chrisbanes/accompanist) that integrates Coil with Compose. Compose is still under development, but the eventual plan is to upstream Accompanist (just the Coil parts) into Coil.

**Comment by andylamax** [comment]
I join the movement as well. Coil Compose is a necessity at the moment

**Comment by luca992** [comment]
I made a [basic library](https://github.com/luca992/coil-composable) wrapping coil for jetpack compose. It even works with gifs, and animated drawables now: https://github.com/luca992/coil-composable

**Comment by colinrtwhite** [comment]
Coil was mentioned [here](https://www.youtube.com/watch?v=PjQdFmiDgwk&t=1129s) and [here](https://www.youtube.com/watch?v=SMOhl9RK0BA&t=231) in the Jetpack Compose alpha videos!

**Comment by liuhuiAndroid** [comment]
I find a library which use coil for jetpack compose, address is here: https://github.com/skydoves/Landscapist

**Comment by liuhuiAndroid** [comment]
![image](https://user-images.githubusercontent.com/12246679/100335434-f51ea100-300f-11eb-8807-070f48085475.png)

**Comment by colinrtwhite** [comment]
@chrisbanes and I are now working on upstreaming https://github.com/google/accompanist/tree/main/coil into a new `coil-compose` artifact in this repo. It'll be part of the next minor release!
