### ISSUE TITLE
Why Compile SDK: 29+ ?

### ISSUE THREAD

**Issue by BimuratMukhtar** [coil-kt/coil#445]
I have compiled project with SDK version 28, everything works great, but in requirements says Compile SDK should be 29+, why we need this?

**Comment by colinrtwhite** [comment]
Coil compiles against SDK 29 so if you compile against a lower SDK it may cause build issues due to missing methods/types. That said, it isn't a hard requirement, but you should ideally always compile against the latest SDK anyways (note: compile is different from target/min api).

**Comment by BimuratMukhtar** [comment]
Ok thanks! But for sure: if you successfully compiled against to lower SDK, can it cause runtime issues? Or only possible build issues?

**Comment by colinrtwhite** [comment]
I believe if it compiles it shouldn't cause runtime issues, but I'm not 100% sure.
