### ISSUE TITLE
Load from InputStream

### ISSUE THREAD

**Issue by seanwu1105** [coil-kt/coil#448]
There are several ways to load the image. However, loading from `InputStream` is not one of them.

**Describe the solution you'd like**

Add an overloading method to accept `InputStream`.

``` kotlin
inline fun ImageView.load(
    inputStream: InputStream?,
    imageLoader: ImageLoader = Coil.imageLoader(context),
    builder: LoadRequestBuilder.() -> Unit = {}
): RequestDisposable = loadAny(inputStream, imageLoader, builder)
```

**Additional context**

In Android, we can simply use `BitmapFactory` to convert the input stream into a bitmap but I am not sure if this solution can be applied to other environment.

``` kotlin
val bitmap = BitmapFactory.decodeStream(inputStream)
imageView.load(bitmap)
```

**Comment by colinrtwhite** [comment]
Yep, this is because the data provided to `load` should be able to be used multiple times. Requests with a `ViewTarget` can be restarted if the associated view is detached then reattached. An `InputStream` can only be read once before it's exhausted and the request would fail if restarted.

**Comment by seanwu1105** [comment]
Thanks for the detailed explanation! I will close this issue.
