### ISSUE TITLE
RoundCornerTransition cause fragment share element transition jumping

### ISSUE THREAD

**Issue by MARGI3** [coil-kt/coil#450]
**Describe the bug**

[Description Image](https://gfycat.com/scarceripeafricanbushviper)

Fragment A:  ReclcyerView (with RoundCorner image items data, ViewHolder bind method to load URL and set RoundCornerTransformation) 
Fragment B:  detail screen will show the image

click Screen A image items  navigate to Screen B, apply fragment share element transition on the image view (which load URL with RoundCornerTranformation)

during the transition animation, the shared image view element will kind of like jumping, the animation not smooth.

```
// ViewHolder#bind()
itemView.newsImage.load(item.imageUrl) {
    scale(Scale.FILL)
    crossfade(true)
// once remove this transformations() method, issue diappeared.
    transformations(RoundedCornersTransformation(topLeft = cornerRadius, topRight = cornerRadius))
}
```

_**once remove this transformations() method, issue diappeared.**_

Fragment Navigation based on the jetpack navigation component.

**Expected behavior**

the image view shared element transition between two fragments should be smooth. but the first time starts the transition animation will look like jumping, and after that second try third try issue disappeared.

(kill the app and start the transition to reproduce the `first time`)

**Totally the same _code,_ just remove the RoundCornerTransformation on the image view then issue disappeared.**

**To Reproduce**

every first time starts the share element transition from an image view (which applied the RoundCornerTransformation) will cause a transition animation jumping.

(kill the app and start the transition to reproduce the `first time`)

**Logs/Screenshots**

If applicable, add logs or screenshots to help explain your problem.

**Version**

coil version: `0.10.1`

androidX fragment: `1.2.1`

androidX Navigation: `2.2.1`

**Comment by colinrtwhite** [comment]
Hmm this sounds related to the fact that requests with a `Transformation` won't always resolve synchronously due to needing the target view to be measured. The next release will include a `placeholderKey` method that will make this use case more intuitive.

For the moment I think your best bet is to postpone the shared element transition until `onStart` is called:

```kotlin
// Call this in your Fragment.onViewCreated
requireActivity().supportPostponeEnterTransition()

// Execute your request
val request = LoadRequest.Builder(context)
    .data("https://www.example.com/image.jpg")
    .target(imageView)
    .listener(onStart = { requireActivity().supportStartPostponedEnterTransition() })
    .build()
imageLoader.execute(request)
```

You may need to set [`setReorderingAllowed(true)`](https://chris.banes.dev/2018/02/18/fragmented-transitions/) as well.

**Comment by colinrtwhite** [comment]
As of `0.13.0` transformations will resolve synchronously if the view is already measured (same as other requests). I also added some guidance around shared element transitions [here](https://coil-kt.github.io/coil/recipes/#shared-element-transitions).
