### ISSUE TITLE
NullPointerException inside MovieDrawable

### ISSUE THREAD

**Issue by randrievskiy** [coil-kt/coil#456]
**I have an app in production and I see that users frequently get NullPointerException**
It happens only on Samsung devices such as Galaxy(A10, J4, J6, J7, J8, S8, M10) with Android 9.0 and only.

Fatal Exception: java.lang.NullPointerException      
       at android.graphics.Movie.nDraw(Movie.java)
       at android.graphics.Movie.draw(Movie.java:47)
       at coil.drawable.MovieDrawable.draw(MovieDrawable.kt:95)
      ...

**Library version is 0.9.5 and I've checked that there is nothing new here in 0.11.0**

**Comment by colinrtwhite** [comment]
Hmm the fact that it's Samsung + Android 9 only makes me think this is a manufacturer bug. Unfortunately, the exception occurs deep in the framework code as well.

I'd recommend using [`ImageDecoderDecoder`](https://coil-kt.github.io/coil/gifs/) on API 28+ to fix this - it'll be faster than `MovieDecoder` as well.

**Comment by randrievskiy** [comment]
Okay. I'll try) Thanks!
