### ISSUE TITLE
Decoding should look at file headers instead of filename

### ISSUE THREAD

**Issue by pedronveloso** [coil-kt/coil#458]
**Describe the bug**
I spotted a bug in which some APIs, namely Imgur, might have images named `.gif` but the actual image might be PNG or JPG. In this case, Coil will fail to decode the image. I've the GIF Decoding enabled as per the docs.

Here's the URL of image in question: https://i.imgur.com/7nLm7sih.gif

**Expected behavior**
Decode the image, by looking at the image headers instead of its filename. In a perfect world we would just be able to rely on the filename.

**Version**
0.11.0 (both core lib and Gif extension)

**Comment by colinrtwhite** [comment]
Hmm Coil already relies on file heads to check for GIFs [here](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/decode/DecodeUtils.kt#L35). I double checked and `DecodUtils.isGif` returns false for the image you linked. Can you describe the behaviour you're seeing?

**Comment by pedronveloso** [comment]
Turns out the error was on my side. Coincidentally, there was an actual issue which was that the image was being given by Imgur's API as an `HTTP` link instead of `HTTPS`, I pasted the link on the browser and it obviously properly redirected - thus I initially though by mistake that the issue was the extension. I'm closing this!
