### ISSUE TITLE
How to listen to downloads

### ISSUE THREAD

**Issue by liangjingkanji** [coil-kt/coil#459]
I already read document

**Comment by colinrtwhite** [comment]
I'm assuming you mean download progress for a network request? Coil relies on OkHttp for its networking so you should be able to add an OkHttp Interceptor when constructing your ImageLoader. Check out these two links for how to set it up: [one](https://coil-kt.github.io/coil/recipes/#using-a-custom-okhttpclient), [two](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java).

**Comment by liangjingkanji** [comment]
I think it's stupid to create a ImageLoader., is troublesome.... And an ImageLoader can only load  one image, You said an application should only create a ImageLoader

**Comment by colinrtwhite** [comment]
It's necessary to create an `ImageLoader` for any configuration. Check out [this link](https://coil-kt.github.io/coil/getting_started/#singleton).
