### ISSUE TITLE
Strict mode: Untagged network socket

### ISSUE THREAD

**Issue by saschpe** [coil-kt/coil#46]
**Describe the bug**
The underlying network socket managed by OkHttp isn't tagged according to policy. Strict mode complains about it. While it's a [longstanding OkHttp issue](https://github.com/square/okhttp/issues/3537) other libraries apply a fixed tag.

- https://source.android.com/devices/tech/datausage/tags-explained

**To Reproduce**
Enable strict mode in an app's Application class during *onCreate()*:

```kotlin
if (BuildConfig.DEBUG) {
    StrictMode.enableDefaults()
}
```

**Expected behavior**

**Logs/Screenshots**
```
2019-08-19 16:00:08.151 17277-17363/foo D/StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2023)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
...
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
...
```
**Library version**
0.6.1

**Comment by colinrtwhite** [comment]
Thanks for the report. Do you have an example of other libraries working around this issue? I'm a little hesitant to work around this issue in the base Coil package. You can set a custom OkHttpClient which packages the work around like so:

```kotlin
Coil.setDefaultImageLoader {
    ImageLoader(this) {
        val client = OkHttpClient.Builder()
            .apply { /** Apply the socket factory work-around. */ }
            .build()
         okHttpClient(client)
    }
}
```

**Comment by benjamin-bader** [comment]
If you decide not to add a tag in the base package, it might be nice to log a warning instead if the default, untagged, client is in use and strict-mode is on.  If nothing else, it will save library users from googling the error and blaming Coil.

**Comment by colinrtwhite** [comment]
@benjamin-bader Strict mode will already log a warning, which references OkHttp and not Coil.

**Comment by benjamin-bader** [comment]
This is true, but will lead people to think that coil is the problem.  A helpful message would perhaps avert a number of spurious github issues, but if you think the existing message form strict mode is fine, then that's all that matters.

**Comment by colinrtwhite** [comment]
Unfortunately, I don't think there's a way to show a message for this issue without requiring the user to install a custom socket factory. I'm going to close this issue for the moment + post the work-around as applied to Coil. If we get duplicate Github issues, we can point users back to this thread.

Here's the suggested work-around applied to Coil:

```kotlin
class TaggedSocketFactory(private val delegate: SocketFactory = getDefault()) : SocketFactory() {

    override fun createSocket(): Socket {
        val socket = delegate.createSocket()
        return configureSocket(socket)
    }

    override fun createSocket(host: String, port: Int): Socket {
        val socket = delegate.createSocket(host, port)
        return configureSocket(socket)
    }

    override fun createSocket(
        host: String,
        port: Int,
        localAddress: InetAddress,
        localPort: Int
    ): Socket {
        val socket = delegate.createSocket(host, port, localAddress, localPort)
        return configureSocket(socket)
    }

    override fun createSocket(host: InetAddress, port: Int): Socket {
        val socket = delegate.createSocket(host, port)
        return configureSocket(socket)
    }

    override fun createSocket(
        host: InetAddress,
        port: Int,
        localAddress: InetAddress,
        localPort: Int
    ): Socket {
        val socket = delegate.createSocket(host, port, localAddress, localPort)
        return configureSocket(socket)
    }

    private fun configureSocket(socket: Socket): Socket {
        TrafficStats.tagSocket(socket)
        return socket
    }
}

val imageLoader = ImageLoader(context) {
    val client = OkHttpClient.Builder().socketFactory(TaggedSocketFactory()).build()
    okHttpClient(client)
}

// If you use the Coil singleton...
Coil.setDefaultImageLoader(imageLoader)
```
