### ISSUE TITLE
Coil singleton never sets imageLoader property

### ISSUE THREAD

**Issue by RI42** [coil-kt/coil#464]
https://github.com/coil-kt/coil/blob/master/coil-singleton/src/main/java/coil/Coil.kt

Coil singleton never sets the default `imageLoader` property and always calls `@Synchronized
    private fun newImageLoader(context: Context): ImageLoader` in `fun imageLoader(context: Context)` because `imageLoader` is always `null`

**Comment by colinrtwhite** [comment]
Thanks - good catch! You're right it will keep entering `newImageLoader`, however the Application's `newImageLoader` will only be called once. That said it's still creating a new `ImageLoaderFactory` instance for each call, which isn't good. I've added the fix in #466 alongside some tests (though it's tough to cover this specific case).
