### ISSUE TITLE
Image Caching

### ISSUE THREAD

**Issue by rooparsh** [coil-kt/coil#471]
We are using Twilio Chat Sdk for implementing chat along with Coil for loading images, videos and gif. The url for media expires after some time so we have to request a new one in bindViewHolder of recycler view. With the custom caching mechanism we currently have with Coil, we are facing issues with it. 

Is there any way we can tweak caching in our favor for our use case? We are thinking to pass some unique strings on whose basis to cache the data. 

Any help in this regard would be appreciated.

**Comment by colinrtwhite** [comment]
If you need to invalidate the item in the memory cache, you can use `ImageLoader.invalidate` and set a custom `key` when creating your `LoadRequest`. This will also be improved on in the next release (likely released later this week) as [`MemoryCache`](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/memory/MemoryCache.kt) and cache keys will be public.

For invalidating items in the disk cache, I would use an OkHttp interceptor and set the `Cache-Control` header to the expiry time ([example](https://github.com/coil-kt/coil/blob/master/coil-sample/src/main/java/coil/sample/Application.kt#L46)). Coil will then miss that entry in the disk cache if it is expired.
