### ISSUE TITLE
Image Caching via HTTP

### ISSUE THREAD

**Issue by ulx** [coil-kt/coil#475]
Hello
A backside is going to update images via HTTP headers.
Does coil support the feature? Have I do it myself.
Specification
[https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8/Last-Modified](URL)

**Comment by colinrtwhite** [comment]
Yep, Coil relies on OkHttp which handles `Last-Modified`, `Cache-Control`, `If-Modified-Since`, and other similar cache control headers by default.
