### ISSUE TITLE
Parameter in MIME types

### ISSUE THREAD

**Issue by alcere** [coil-kt/coil#486]
Hi!
I noticed that in some occasions the mime type included in the fetch result contains a parameter, for instance, the mime type resulting of requesting to: `https://img.shields.io/badge/License-Boost%201.0-lightblue.svg` is` image/svg+xml;charset=utf-8`, and in consequence it is ignored by the SvgDecoder.

Do you have any advice on how to remove/ignore the parameter? Should it be done by a custom SVG decoder?

Thanks!

**Comment by colinrtwhite** [comment]
Thanks for reporting this. I think this behaviour can be considered a bug in `HttpUrlFetcher`'s parsing of the [content-type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) header. I've added a fix here #487.
