### ISSUE TITLE
Cannot load picture address without suffix

### ISSUE THREAD

**Issue by caiyoufei** [coil-kt/coil#492]
Like this:(May be caused by redirects)
http://gank.io/images/6b2efa591564475fb8bc32291fb0007c

**Comment by colinrtwhite** [comment]
This is not an issue with Coil. Your image url needs to be `https`.

**Comment by caiyoufei** [comment]
0.12.0之前：没有后缀名并且重定向之后无法加载图片
经测试0.12.0已修复了该问题
