### ISSUE TITLE
RecyclerView Reuse bug

### ISSUE THREAD

**Issue by caiyoufei** [coil-kt/coil#493]
Result like this:
![GIF (1)](https://user-images.githubusercontent.com/11989916/90146494-4da49800-ddab-11ea-85b0-36c895c2f55b.gif)
Code change like this:
![image](https://user-images.githubusercontent.com/11989916/90146641-7c227300-ddab-11ea-8803-2b8b9ddb25a2.png)

**Comment by caiyoufei** [comment]
I only used the picture in the first position, but this picture also appeared in other position

**Comment by colinrtwhite** [comment]
This occurs when you mix calls to `setImageResource`/`setImageDrawable` and `load`. If you need to call `setImageResource`/`setImageDrawable`, you should call `clear` first.

**Comment by caiyoufei** [comment]
OK,Thanks
