### ISSUE TITLE
Add a default implementation of the coil.util.Logger 

### ISSUE THREAD

**Issue by ahmdaeyz** [coil-kt/coil#496]
**Is your feature request related to a problem? Please describe.**
I think it's expected that the library logs by default at least at the Debug level. 
**Describe the solution you'd like**
Either Add a default implementation of the coil.util.Logger interface instead of it being null or at least specifying that there isn't a default logger in the README. I think both will be helpful.

**Comment by colinrtwhite** [comment]
Are you looking for [`DebugLogger`](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging)? That will log to `Log.println` + supports different log levels.

**Comment by ahmdaeyz** [comment]
Okay, nice! Can that be the initial value of the logger property instead of it being null? IMO, it's expected that logging is enabled by default. Would be happy to read your take on this!
**maybe here?**
`companion object {
        /** Create a new [ImageLoader] without configuration. */

        @JvmStatic

        @JvmName("create")
         // here
        operator fun invoke(context: Context) = Builder(context).build()
    }`
**Or in the builder itself?** 
` class Builder(context: Context) {

        private val applicationContext = context.applicationContext

        private var callFactory: Call.Factory? = null
        private var eventListenerFactory: EventListener.Factory? = null
        private var registry: ComponentRegistry? = null
        //here
        private var logger: Logger? = null
        private var defaults = DefaultRequestOptions.INSTANCE
.
}`

**Comment by colinrtwhite** [comment]
I don't think `DebugLogger` should be set by default. It's a debug tool and debug tools should be enabled explicitly or else they can accidentally be released into production. Also it slows down image loading, which we wouldn't want to do by default.
