### ISSUE TITLE
Caching Video thumbnail

### ISSUE THREAD

**Issue by rooparsh** [coil-kt/coil#497]
Hi , is there any way we can cache thumbnails generated from video url and load them in imageview. 

The approach that we are following is the thumbnail from url is only generated once via MediaMetadataRetriever's method `getFrameAtTime(2000)`. This generated thumbnail is then passed to imageview to load via Coil using the method
 

``` 
    view.load(thumbnail) {
      error(R.drawable.ic_attachment_camera)
      placeholder(R.drawable.ic_attachment_camera)
      crossfade(true)
      build()
    }
```
The imageview in question are part of recycler view, which has multiple views for images and videos(for videos we are just displaying thumbnail)

 But is the thumbnail generation logic is not being called every time we come to the activity. 

So is there any way to ease this.

**Comment by colinrtwhite** [comment]
Hmm the thumbnail should be cached automatically if you haven't disabled the memory cache. If you [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) do you see the image being served from the memory cache for subsequent requests?

Also you don't need to call `build` inside the DSL; it will be called automatically.

**Comment by rooparsh** [comment]
What's the recommended way to load videoFrame in image view from url which don't end in any video format but contains playable video. These links when opened in chrome or any other browser start playing immediately. How do they detect that its a video

**Comment by colinrtwhite** [comment]
`coil-video` only supports loading video frames [from `File` or non-network `Uris`](https://coil-kt.github.io/coil/videos/).

**Comment by soulgen** [comment]
@colinrtwhite could you please clarify why this issue is closed? Glide has video thumbnail caching, do you have any plans to implement this? This is the only think that stops me to switch to Coil.

**Comment by colinrtwhite** [comment]
@soulgen It's something I'm looking into, but I can't promise anything. It's difficult because `MediaMetadataRetreiver`'s frame decoding capabilities are strongly coupled with the data source it's being loaded from. Glide implements its own disk cache (which has several downsides) and passes the file to the `MediaMetadataRetreiver`. Coil relies on `OkHttp`'s disk cache which means it only has access to the `BufferedSource` and not the underlying cache file.
