### ISSUE TITLE
Documentation: dead link on Image Requests page

### ISSUE THREAD

**Issue by lfielke** [coil-kt/coil#501]
The documentation website contains a link to a nonexistent page.

The page at https://coil-kt.github.io/coil/image_requests/ contains a link in the last paragraph "See the API documentation for more information." that points to:
https://coil-kt.github.io/coil/api/coil-base/coil.request/-request/
This page doesn't exist.

I think the link should point to:  
https://coil-kt.github.io/coil/api/coil-base/coil.request/-image-request/

**Comment by colinrtwhite** [comment]
Thanks for the report - fixed here: https://github.com/coil-kt/coil/pull/502.
