### ISSUE TITLE
Fast download calls lead to mixed up images

### ISSUE THREAD

**Issue by pnehren** [coil-kt/coil#503]
Hello Together. 
I have a strange behaviour with coil downloading images to bitmapdrawables. Imagine i have 6 images showing numbers 1 to 6 which are mapped to fixed positions on a canvas. If i download these pictures with the below call the images got mixed up, so image 1 is not drawn at position belongs to image 1 on canvas for example.

`val downloadJobs = imageURLs.map { url -> scope.async { downloadImage(url) } }`
 
If i use such a call, it works. But why? 

```
imageURLs.forEach { url ->
                                    delay(15)
                                    downloadJobs.add(scope.async { downloadImage(url) })
                                    delay(15)
                                }

```

Any suggestions?

This is the download function:
```

 private suspend fun downloadImage(url: String): Bitmap? {
        return when (val result = coilImageLoader.execute(coilGetRequestBuilder.data(url).apply {
            allowHardware(enable = true)
        }.build())) {
            is SuccessResult -> (result.drawable as BitmapDrawable).bitmap
            is ErrorResult -> throw result.throwable
        }
    }
```

**Comment by pnehren** [comment]
Coil 0.12 seems to fix this issue! :)

**Comment by colinrtwhite** [comment]
Your Coil code looks ok - this is likely an issue with how you're using `downloadJobs` later in your code.
