### ISSUE TITLE
Add support for Animated PNG

### ISSUE THREAD

**Issue by tengyeekong** [coil-kt/coil#506]
Hope Coil able to support Animated PNG!

**Comment by 1359694358** [comment]
Could you  add support apng format image?  this format  image is popular

**Comment by colinrtwhite** [comment]
@1359694358 Open to contributions for this feature :).

**Comment by colinrtwhite** [comment]
Going to close this out since I don't think there's a lot of demand for separate APNG library. Also I'd rather not maintain a separate library for a small amount of code.

If you need APNG support import [this library](https://github.com/penfeizhou/APNG4Android), copy the above `Decoder` into your build, then [register it with your `ImageLoader`](https://coil-kt.github.io/coil/image_pipeline) and it should work.

**Comment by BasixKOR** [comment]
The answer above doesn't seem to work. The registered APNG decoder never get called `create` and it always show the first frame, indicating it was decoded by the built-in PNG decoder.

**Comment by kickym0802** [comment]
APNG

**Comment by ti4n1993** [comment]
> It's possible to support animated PNG using [this library](https://github.com/penfeizhou/APNG4Android) and a custom decoder:
> 
> Coil 3.0:
> 
> ```kotlin
> import coil3.ImageLoader
> import coil3.asImage
> import coil3.decode.DecodeResult
> import coil3.decode.Decoder
> import coil3.decode.ImageSource
> import coil3.fetch.SourceFetchResult
> import coil3.request.Options
> import com.github.penfeizhou.animation.apng.APNGDrawable
> import com.github.penfeizhou.animation.apng.decode.APNGParser
> import com.github.penfeizhou.animation.io.ByteBufferReader
> import com.github.penfeizhou.animation.io.StreamReader
> import com.github.penfeizhou.animation.loader.Loader
> import java.nio.ByteBuffer
> import okio.BufferedSource
> 
> class AnimatedPngDecoder(private val source: ImageSource) : Decoder {
> 
>     override suspend fun decode(): DecodeResult {
>         // We must buffer the source into memory as APNGDrawable decodes
>         // the image lazily at draw time which is prohibited by Coil.
>         val buffer = source.source().squashToDirectByteBuffer()
>         return DecodeResult(
>             image = APNGDrawable(Loader { ByteBufferReader(buffer) }).asImage(),
>             isSampled = false,
>         )
>     }
> 
>     private fun BufferedSource.squashToDirectByteBuffer(): ByteBuffer {
>         // Squash bytes to BufferedSource inner buffer then we know total byteCount.
>         request(Long.MAX_VALUE)
> 
>         val byteBuffer = ByteBuffer.allocateDirect(buffer.size.toInt())
>         while (!buffer.exhausted()) buffer.read(byteBuffer)
>         byteBuffer.flip()
>         return byteBuffer
>     }
> 
>     class Factory : Decoder.Factory {
> 
>         override fun create(
>             result: SourceFetchResult,
>             options: Options,
>             imageLoader: ImageLoader,
>         ): Decoder? {
>             val stream = result.source.source().peek().inputStream()
>             if (APNGParser.isAPNG(StreamReader(stream))) {
>                 return AnimatedPngDecoder(result.source)
>             } else {
>                 return null
>             }
>         }
>     }
> }
> ```
> 
> Coil 2.0:
> 
> ```kotlin
> import coil.ImageLoader
> import coil.decode.DecodeResult
> import coil.decode.Decoder
> import coil.decode.ImageSource
> import coil.fetch.SourceResult
> import coil.request.Options
> import com.github.penfeizhou.animation.apng.APNGDrawable
> import com.github.penfeizhou.animation.apng.decode.APNGParser
> import com.github.penfeizhou.animation.io.ByteBufferReader
> import com.github.penfeizhou.animation.io.StreamReader
> import com.github.penfeizhou.animation.loader.Loader
> import java.nio.ByteBuffer
> import okio.BufferedSource
> 
> class AnimatedPngDecoder(private val source: ImageSource) : Decoder {
> 
>     override suspend fun decode(): DecodeResult {
>         // We must buffer the source into memory as APNGDrawable decodes
>         // the image lazily at draw time which is prohibited by Coil.
>         val buffer = source.source().squashToDirectByteBuffer()
>         return DecodeResult(
>             drawable = APNGDrawable(Loader { ByteBufferReader(buffer) }),
>             isSampled = false,
>         )
>     }
> 
>     private fun BufferedSource.squashToDirectByteBuffer(): ByteBuffer {
>         // Squash bytes to BufferedSource inner buffer then we know total byteCount.
>         request(Long.MAX_VALUE)
> 
>         val byteBuffer = ByteBuffer.allocateDirect(buffer.size.toInt())
>         while (!buffer.exhausted()) buffer.read(byteBuffer)
>         byteBuffer.flip()
>         return byteBuffer
>     }
> 
>     class Factory : Decoder.Factory {
> 
>         override fun create(
>             result: SourceResult,
>             options: Options,
>             imageLoader: ImageLoader,
>         ): Decoder? {
>             val stream = result.source.source().peek().inputStream()
>             if (APNGParser.isAPNG(StreamReader(stream))) {
>                 return AnimatedPngDecoder(result.source)
>             } else {
>                 return null
>             }
>         }
>     }
> }
> ```

I display apng in LazyVerticalGrid,when scoll many times,it cause oom
