### ISSUE TITLE
Support for RemoteViews?

### ISSUE THREAD

**Issue by MaximilianKeppeler** [coil-kt/coil#514]
For example, Glide has NotificationTarget etc. to load the Image into the RemoteView. 
Does something like that also exist in Coil? I'm working with lots of RemoteViews for the Notification and App Widgets and don't exactly know how to handle Image loading with Coil in those areas. 

Thank you very much in advance!

**Comment by colinrtwhite** [comment]
There's no out of the box support, however it's possible to support `RemoteViews` with a custom `Target`. Here's how to do it:

```kotlin
class RemoteViewsTarget(private val remoteViews: RemoteViews) : Target {
    
    override fun onStart(placeholder: Drawable?) = setDrawable(placeholder)

    override fun onError(error: Drawable) = setDrawable(error)

    override fun onSuccess(result: Drawable) = setDrawable(result)

    private fun setDrawable(drawable: Drawable?) {
        remoteViews.setImageViewBitmap((drawable as? BitmapDrawable)?.bitmap)
    }
}

val request = ImageRequest.Builder(context)
    .data("https://www.example.com/image.jpg")
    .target(RemoteViewsTarget(remoteViews))
    .build()
imageLoader.enqueue(request)
```
