### ISSUE TITLE
When crossfade=true is set, the picture will not be displayed when it is loaded for the first time.

### ISSUE THREAD

**Issue by MRDHR** [coil-kt/coil#515]
**Describe the bug**
 when setting crossfade=true for imageloader, view will not be displayed when it is loaded for the first time. I have to call load again to display.

**Expected behavior**
The picture can also be displayed the first time it is loaded.

**To Reproduce**
How can we reproduce this?
example 1：
 val imageLoader = ImageLoader.Builder(this)
                .crossfade(true)
                .componentRegistry {
                    if (Build.VERSION.SDK_INT >= 28) {
                        add(ImageDecoderDecoder())
                    } else {
                        add(GifDecoder())
                    }
                }
                .okHttpClient {
                    OkHttpClient.Builder()
                            .cache(CoilUtils.createDefaultCache(this))
                            .build()
                }
                .build()
        Coil.setImageLoader(imageLoader)

imageView?.scaleType = ImageView.ScaleType.CENTER_CROP
imageView?.load(url)

example 2：
imageView?.scaleType = ImageView.ScaleType.CENTER_CROP
imageView?.load(url) {
            lifecycle(fragment)
            crossfade(true)
            allowRgb565(!((!TextUtils.isEmpty(url) && url!!.endsWith(".gif")) || !TextUtils.isEmpty(url) && url!!.endsWith(".png")))
        }

**Logs/Screenshots**
If applicable, add logs or screenshots to help explain your problem.
![QQ图片20200831140910](https://user-images.githubusercontent.com/5576916/91688012-96be5f80-eb93-11ea-8310-9a40e50b72b7.png)

**Version**
What library version are you using? Also does this occur on a specific API level or Android device.
0.12.0

**Comment by colinrtwhite** [comment]
Did this work properly on Coil 0.11.0? Also are there any logged errors if you [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging)?

**Comment by MRDHR** [comment]
The log after loading the picture is as follows (I have hidden the company information because it involves confidentiality)

2020-09-01 10:51:01.378 32057-843/myje D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2020-09-01 10:51:01.381 32057-843/myje I/chatty: uid=10088(.myje) yqcloud.com/... identical 1 line
2020-09-01 10:51:01.383 32057-843/myje D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2020-09-01 10:51:01.443 32057-32558/myje D/skia: SkJpegCodec::onGetPixels fEnTdshp 0 fISOSpeedRatings -1!
2020-09-01 10:51:01.476 32057-32057/myje I/RealImageLoader: 💾 Successful (DISK) - https://xxxxxx.com/books/BK-001/images/head2.jpg
2020-09-01 10:51:01.510 32057-32057/myje I/RealImageLoader: 💾 Successful (DISK) - http://www.dzkbw.com/books/rjb/yingyu/peps3x/coverbig.jpg

**Comment by MRDHR** [comment]
The log display was successful, but the picture did not display. Using version 0.11.0 is also not display.

**Comment by MRDHR** [comment]
The system I use is Android P

Androidmanifest has been set
NetworkSecurityConfig cleartextTrafficPermitted=“true”
RequestLegacyExternalStorage=“true”
UsesCleartextTraffic=“true”

**Comment by MRDHR** [comment]
When imageloader sets memoryCachePolicy (CachePolicy.DISABLED), the picture will not be displayed no matter how many times it is loaded.

**Comment by MRDHR** [comment]
I seem to know what the problem is because the view I use is RoundedImageView.

Https://github.com/vinc3m1/RoundedImageView

**Comment by colinrtwhite** [comment]
Ah yep, this is being tracked here (https://github.com/coil-kt/coil/issues/230) and (https://github.com/coil-kt/coil/issues/223). Unfortunately, there's not currently a great fix for this.
