### ISSUE TITLE
load (coil.load) Doesn't work

### ISSUE THREAD

**Issue by stevdza-san** [coil-kt/coil#521]
**Describe the bug**
When I updated coil to version: 0.13.0 the previous load function (coil.api.load) is now deprecated. I tried using new load (coil.load) function but the image doesn't show when I simply try using it like:

imageView.load("URL")

**Version**
0.13.0 . Device API 29

**Comment by colinrtwhite** [comment]
[`coil.api.load` calls `coil.load` directly](https://github.com/coil-kt/coil/blob/master/coil-singleton/src/main/java/coil/Deprecated.kt#L23) so there shouldn't be any difference. I'm not able to reproduce the issue as `coil.load` works correctly in the sample app. Do you have a reproduction sample I can use to reproduce the issue locally?

**Comment by stevdza-san** [comment]
> 
> 
> [`coil.api.load` calls `coil.load` directly](https://github.com/coil-kt/coil/blob/master/coil-singleton/src/main/java/coil/Deprecated.kt#L23) so there shouldn't be any difference. I'm not able to reproduce the issue as `coil.load` works correctly in the sample app. Do you have a reproduction sample I can use to reproduce the issue locally?

Here's the example
https://github.com/stevdza-san/CoilDemo

**Comment by colinrtwhite** [comment]
@stevdza-san The image in the sample app loads properly on my API 28 and 30 emulators. Maybe it's an issue with your local development environment? If you use [`DebugLogger`](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) you can see errors locally.

<img src="https://user-images.githubusercontent.com/5580160/92335680-2e75ef00-f067-11ea-94d0-3de6d64c1269.png" width=25%/>

**Comment by stevdza-san** [comment]
> 
> 
> @stevdza-san The image in the sample app loads properly on my API 28 and 30 emulators. Maybe it's an issue with your local development environment? If you use [`DebugLogger`](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) you can see errors locally.
> 
> <img alt="" width="25%/" src="https://user-images.githubusercontent.com/5580160/92335680-2e75ef00-f067-11ea-94d0-3de6d64c1269.png">

Android Emulator is giving me headaches again... I tried on genymotion and it works. Thank you!
