### ISSUE TITLE
How do I get the cache of the pictures that the coil has loaded?

### ISSUE THREAD

**Issue by oh-Rin** [coil-kt/coil#528]
Can I use the api to get the path of a picture that has been loaded and cached to disk?
```kotlin
fun getCoilCacheFile(url: String): File =
  appContext.cacheDir.resolve("image_cache/${url.encodeUtf8().md5().hex()}.1")
```
I currently use this method, but I don't know if it is correct?

**Comment by colinrtwhite** [comment]
That function should work, though this one is a little safer (`HttpUrl` standardizes the format internally):

```kotlin
fun cacheFile(url: String, cache: Cache = CoilUtils.defaultCache(context)): File {
    return File(cache.directory(), Cache.key(url.toHttpUrl()))
}
```

`cache` is the `Cache` used to create the `OkHttpClient`, which is `CoilUtils.defaultCache(context)` by default. Be aware that files can be evicted from the cache at any time if new requests need space on disk!

**Comment by caiyoufei** [comment]
lib version 1.1.1

fun String?.getCoilCacheFile(): File? {
  return this?.toFile() ?: this?.toHttpUrlOrNull()?.let { u ->
    CoilUtils.createDefaultCache(Utils.getApp()).directory.listFiles()?.lastOrNull { it.name.endsWith(".1") && it.name.contains(Cache.key(u)) }
  }
}

**Comment by caiyoufei** [comment]
![Uploading image.png…]()

**Comment by MajidArabi** [comment]
in coil3:

      import coil3.PlatformContext
      import coil3.SingletonImageLoader

      fun String?.getCoilCacheFile(
          context: PlatformContext
      ): File? = this?.let {
          val imageUrl = this
          val snapshot = SingletonImageLoader.get(context).diskCache?.openSnapshot(imageUrl)
      
          try {
              snapshot?.use { it.data.toFile() }
          } catch (_: Throwable) {
              null
          }
      }
