### ISSUE TITLE
Add option to continue using placeholder as an error resource

### ISSUE THREAD

**Issue by marin-marsic** [coil-kt/coil#538]
**Is your feature request related to a problem? Please describe.**
I use the same image as placeholder and error image and I have crossfade enabled: 
```Kotlin
placeholder(drawable)
error(drawable)
crossfade(true)
```
When the request is successful, placeholder image fades into result image. But when the error occurs, placeholder fades into itself which results in flickering.

**Describe the solution you'd like**
I would like to use placeholder resource as an error resource too, if the different error resource was not set.

**Comment by colinrtwhite** [comment]
I think this is probably better handled by using a custom crossfade transition. Something like this should work:

```kotlin
class NoErrorCrossfadeTransition(private val delegate = CrossfadeTransition()) : Transition {

    override suspend fun transition(target: TransitionTarget, result: ImageResult) {
        if (result is ErrorResult) {
            target.onError(result.drawable)
        } else {
            delegate.transition(target, result)
        }
    }
}
```

**Comment by marin-marsic** [comment]
Thanks for the insight. I have only one problem with this solution. This works great if the placeholder has no transparency, but if the placeholder resource is transparent, some additional transparency gets applied to it randomly (images using the same placeholder have different levels of opacity). I managed to fix that problem by setting full opacity to placeholder drawable which seems more like a hack to me. Don't know if I'm doing anything wrong.
