### ISSUE TITLE
Unable to play GIF when I load it second time

### ISSUE THREAD

**Issue by rupinderjeet** [coil-kt/coil#539]
### Description

I am loading gifs onto an ImageView. User is able to replace the loaded gif with another one.

Following is the code I use to initialize Coil singleton:

    val imageLoader = ImageLoader.Builder(context)
        .availableMemoryPercentage(0.25)
        .crossfade(true) // or not
        .componentRegistry {

            // video-support
            add(VideoFrameFileFetcher(context))
            add(VideoFrameUriFetcher(context))

            // gif-support
            if (SDK_INT >= 28) {
                add(ImageDecoderDecoder())
            } else {
                add(GifDecoder())
            }
        }
        .logger(DebugLogger(Log.VERBOSE))
        .build()

    Coil.setImageLoader(imageLoader)

Following is the code I use to load the gif. (result=plays successfully)

    // file = /storage/emulated/0/somelongpath/6421dc5e-c349-4f1b-b3ff-e5fad0e79e6e
    binding.imageView.load(file)

    // I/RealImageLoader: 💾 Successful (DISK) - /storage/emulated/0/somelongpath/6421dc5e-c349-4f1b-b3ff-e5fad0e79e6e
    // V/RealBitmapPool: Missing bitmap=[193600]
    // V/RealBitmapPool: Get bitmap=[193600]
    // Hits=0, misses=1, puts=0, evictions=0, currentSize=0, maxSize=0, strategy=SizeStrategy: entries=LinkedMultimap( {193600:0} ), sizes={}

User chose a new gif file to replace. (result=loads thumbnail, but doesn't play)

    // file = /storage/emulated/0/somelongpath/3f9377d2-5a3c-4965-a0d8-f12b7b8e0d2c
    binding.imageView.load(file)

    // I/RealImageLoader: 💾 Successful (DISK) - /storage/emulated/0/somelongpath/3f9377d2-5a3c-4965-a0d8-f12b7b8e0d2c
    // V/RealBitmapPool: Missing bitmap=[541440]
    // V/RealBitmapPool: Get bitmap=[541440]
    // Hits=0, misses=2, puts=0, evictions=0, currentSize=0, maxSize=0, strategy=SizeStrategy: entries=LinkedMultimap( {541440:0}, {193600:0} ), sizes={}

This is happening every time. Even if I use different gifs to test this, result is the same. First time works. Second time doesn't play. Third time works. Fourth and N times works.

Verified using `DecodeUtils.isGif(source)` that both and all files are gif.

### Expectation

Every call to `load` plays the gif.

Present in `0.13.0` & `1.0.0-rc3` with gif and video support on "Android Emulator Pixel 3 API 29"

**Comment by rupinderjeet** [comment]
It doesn't matter if the file names end with ".gif" or not, issue exists.

**Comment by colinrtwhite** [comment]
Do you have a sample project I could use to reproduce this? I'm not able to reproduce this behaviour in the `coil-sample` project in this repo.

**Comment by rupinderjeet** [comment]
[coil539.zip](https://github.com/coil-kt/coil/files/5280804/coil539.zip)

I hope this project runs without error for you. Also, a video record of the bug is present in `assets` folder.

**Comment by IljaKosynkin** [comment]
Ok @colinrtwhite I poked around this issue and maybe you could give me some additional insight.
So the problem essentially is that sometimes LifecycleRegistry can't clear up previous observer (in this case ImageViewTarget) in time, causing it to reuse no longer valid object. This causes onStart callback to be never invoked, therefore animation on drawable is never started. 
My question is: do we really need objects of ImageViewTarget to be identified by wrapped ImageView? If I change:
```
    override fun hashCode() = view.hashCode()
```
to:
```
    override fun hashCode() = view.hashCode() xor super.hashCode()
```
The problem seem to go away. Thoughts?

**Comment by colinrtwhite** [comment]
@IljaKosynkin I think that's probably the way to go. Can you double check if there are side effects + open a PR? Thanks!

**Comment by IljaKosynkin** [comment]
Hey @colinrtwhite added PR for that issue.
Sorry for delay, got caught up in stuff.
By the way, issue reproducible in the sample app, you just need to switch to GIF tab, then open GIF twice. Second time GIF will not play.
