### ISSUE TITLE
SIGABRT crash with scaleType and precision set (0.13.0)

### ISSUE THREAD

**Issue by Webwag-NPA** [coil-kt/coil#545]
**Describe the bug**
Hello, I do have the following crash when loading this image which is 2783 * 87 with Coil v0.13.0 : 
![image_causing_crash](https://user-images.githubusercontent.com/59887260/95083839-51a2c580-071d-11eb-99f5-5054cd395cf8.jpg) 

This is my code :
```kotlin
class NavigationActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val content = FrameLayout(this).apply {
            val imageView = ImageView(context).apply {
                layoutParams = FrameLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        246.dp
                ).apply { gravity = Gravity.CENTER_VERTICAL }

                scaleType = ImageView.ScaleType.CENTER

                load("https://user-images.githubusercontent.com/59887260/95083839-51a2c580-071d-11eb-99f5-5054cd395cf8.jpg") {
                    precision(Precision.EXACT)
                }
            }

            addView(imageView)
        }
        setContentView(content)
    }

}

private val Int.dp
    get() = (this * Resources.getSystem().displayMetrics.density).toInt()
```

Logcat :

```
2020-10-05 15:15:41.037 22871-22983/com.lanr.com.dev E/OpenGLRenderer: GL error:  GL_INVALID_VALUE
2020-10-05 15:15:41.038 22871-22983/com.lanr.com.dev A/OpenGLRenderer: glEGLImageTargetTexture2DOES error! GL_INVALID_VALUE (0x501)
2020-10-05 15:15:41.038 22871-22983/com.lanr.com.dev A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22983 (RenderThread), pid 22871 (om.lanr.com.dev)
```

I reproduce this issue on a Samsung S8, with Android 9. I tried to reproduce on other physical devices (Android 5, 6 and Android 10) and on emulator (Android 9 and Android 10) and I never crash, but the image didn't load neither. But on my Samsung S8, it's always crashing so I'm able to reproduce this crash every time.

If I remove `precision` from the `load` function or `scaleType` from the ImageView, then it works like a charm. 

And a last thing, if my ImageView doesn't have a fixed height (i.e. if I use `ViewGroup.LayoutParams.WRAP_CONTENT` instead of `246.dp`), then it doesn't crash, but it doesn't load the image neither and I have this in my logcat :

```
2020-10-05 15:35:44.622 27125-27202/com.lanr.com.dev W/GraphicBufferAllocator: over alloc limit : width(69575) x height(2175) = 151325625  Bitmap::allocateSkiaHardwareBitmap pid [27125]
2020-10-05 15:35:44.622 27125-27202/com.lanr.com.dev W/OpenGLRenderer: createGraphicBuffer() failed in GraphicBuffer.create()
2020-10-05 15:35:44.622 27125-27215/com.lanr.com.dev D/skia: --- Failed to allocate a hardware bitmap
```

Thanks a lot

**Comment by colinrtwhite** [comment]
`ImageView.ScaleType.CENTER` maps to `Scale.FILL` internally so Coil is attempting to fill the source image to the height of your image view. This can cause it to load a very long image in your case (69575 pixels according to your logs). I think it's more intuitive for Coil to default to `OriginalSize` in this case, however I'm avoiding adding any further behaviour changes to Coil 1.0 so this would need to ship in 1.1. In the meantime you can set `size(OriginalSize)` to fix the issue.

**Comment by colinrtwhite** [comment]
`ImageView.ScaleType.CENTER` maps to `Scale.FILL` internally so Coil is attempting to fill the source image to the height of your image view. This can cause it to load a very long image in your case (69575 pixels according to your logs).

I think it's more intuitive for Coil to default to `OriginalSize` in this case and will likely change this behaviour after 1.0 is released. In the meantime you can set `size(OriginalSize)` to fix the issue.

**Comment by Webwag-NPA** [comment]
Thanks for the explanation, I'm going to try this.
