### ISSUE TITLE
HTTP 404 responses not cached by OkHttp

### ISSUE THREAD

**Issue by clhols** [coil-kt/coil#549]
**Describe the bug**
The issue is described here:
https://github.com/square/okhttp/issues/6310

**Expected behavior**
HTTP responses that OkHttp can cache should be cached.

**To Reproduce**
Try any request that returns 404 with a Cache-Control header set to allow caching.

**Version**
1.0.0-rc3

**Comment by sakayori-daisuke** [comment]
有事対応を施した形跡がライブラリ側にあるとし、取り込みを判断
https://github.com/coil-kt/coil/issues/549
