### ISSUE TITLE
Using color resource as placeholder or error drawable

### ISSUE THREAD

**Issue by idrisadetunmbi** [coil-kt/coil#550]
I am getting some strange behaviors when I apply a color resource as the value of the placeholder for an image load instead of wrapping it in a `ColorDrawable`

```
// this
binding.imageView.load(imageUrl, builder = {
                placeholder(R.color.yellow)
                crossfade(true)
            })

// instead of this
binding.imageView.load(imageUrl, builder = {
                placeholder(ColorDrawable(R.color.yellow))
                crossfade(true)
            })
```

The color resource applied directly in the placeholder is manipulated across the app up to the theme level (with different opacity variations when used elsewhere). Is it wrong to apply the color resource directly that way?

**Comment by colinrtwhite** [comment]
I would use `placeholder(ColorDrawable(R.color.yellow))`. The `placeholder` function uses `AppCompatResources.getDrawable` internally to load the drawable, which may not work properly with colour resource IDs.
