### ISSUE TITLE
Load multiple images, combine them in transformations and display them

### ISSUE THREAD

**Issue by MFlisar** [coil-kt/coil#553]
I would like to load multiple images with coil and would have following requirements:

- I need to transform each image (scale it down) to minimize memory usage (you can't load e.g. 4 large images at once)
- I need to combine those images inside a transformation - e.g. display the 4 images in a grid like style
- the resulting image needs to run through another transformation - e.g. circle crop and tinting

The result could be something like following (taken from my app, made without coil though):
![example](https://user-images.githubusercontent.com/2437726/96549285-94cd6e80-12af-11eb-92a2-0a70925f232f.png)

**Question**

Is this possible? Not our of the box as far as I see, maybe someone can explain if this is somehow possible?

If this is not possible, then this is a feature request - would you mind adding this in the future? Is this planned or even definitely will not come?

**Comment by colinrtwhite** [comment]
There's no out of the box support for this, however it should be possible by launching multiple `execute` requests using `async` and then awaiting all the results. Once you have the 4 images separately you can combine the images manually and perform any transformations.

I don't think it makes sense to add this as a feature to Coil as it's possible to combine the images manually using separate `execute` requests.

**Comment by MFlisar** [comment]
I testet this and it works of course. What you suggest has a few drawbacks:

1. the thread for the final combination of images is not handled by coil
2. coil does not cache the final combination
3. I can't use already defined transformations on the combined bitmap (like e.g. the `CircleCropTransformations`)

ad 1) I can live with that, that's no big issue for me

ad 2.) can I somehow push back my combined image into the coil cache manually? Seems a little hard as I don't get the cache keys of the initial images and can't generate a final key. Any ideas or feedback here?

ad 3.) that's something I'd like to use as well, e.g. it would be nice to apply the already existing `CircleCropTransformations` on the combined image...

Any feedback or ideas are very appreciated, thanks

**Code example**

Here's what I have so far.

    fun loadMultipleImages(imageView: ImageView) {
        val images = listOf(
            "https://images.freeimages.com/images/large-previews/1f8/delicate-arch-1-1391746.jpg",
            "https://images.freeimages.com/images/large-previews/b10/can-t-look-over-1312680.jpg",
            "https://images.freeimages.com/images/large-previews/468/winter-wonderland-1383617.jpg",
            "https://images.freeimages.com/images/large-previews/241/night-fog-1521028.jpg"
        )
        (imageView.context as AppCompatActivity).lifecycleScope
            .launch(Dispatchers.IO) {

                val w = imageView.width
                val h = imageView.height

                // 1) load 4 images with coil (sequentially for this test)
                val images = images.map {
                    val request = ImageRequest.Builder(imageView.context)
                        .data(it)
                        .size(max(imageView.width / 2, h / 2))
                        .allowHardware(false)
                        .build()
                    imageView.context.imageLoader.execute(request).drawable!!
                }

                // 2) combine those 4 image in a grid

                val bitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
                val canvas = Canvas(bitmap)
                canvas.drawBitmap(images[0].toBitmap(w, h, Bitmap.Config.ARGB_8888), null, Rect(0, 0, w / 2, h / 2), null)
                canvas.drawBitmap(images[1].toBitmap(w, h, Bitmap.Config.ARGB_8888), null, Rect(w / 2, 0, w, h / 2), null)
                canvas.drawBitmap(images[2].toBitmap(w, h, Bitmap.Config.ARGB_8888), null, Rect(0, h / 2, w / 2, h), null)
                canvas.drawBitmap(images[3].toBitmap(w, h, Bitmap.Config.ARGB_8888), null, Rect(w / 2, h / 2, w, h), null)

                withContext(Dispatchers.Main) {
                    imageView.setImageBitmap(bitmap)
                }
            }

    }

**Comment by keygenqt** [comment]
Simple variant with compose. Size: 0, 1, 2, 3, 4 (max).

```
@Composable
fun CombineImage(
    placeholder: Painter,
    modifier: Modifier = Modifier,
    images: List<String>,
) {
    var doneCounter by remember { mutableStateOf(0) }

    Box(modifier = modifier) {
        if (images.isNotEmpty()) {
            when (images.size) {
                1 -> {
                    val painter = rememberAsyncImagePainter(images.first())
                    LaunchedEffect(painter.state) {
                        if (painter.state is AsyncImagePainter.State.Success) {
                            doneCounter += 1
                        }
                    }
                    Image(
                        modifier = Modifier.fillMaxSize(),
                        contentDescription = null,
                        contentScale = ContentScale.Crop,
                        painter = painter,
                    )
                }
                2 -> {
                    images.forEachIndexed { index, url ->
                        val painter = rememberAsyncImagePainter(url)
                        LaunchedEffect(painter.state) {
                            if (painter.state is AsyncImagePainter.State.Success) {
                                doneCounter += 1
                            }
                        }
                        Image(
                            modifier = Modifier
                                .fillMaxHeight()
                                .fillMaxWidth(0.47f)
                                .align(
                                    when (index) {
                                        0 -> Alignment.TopStart
                                        else -> Alignment.BottomEnd
                                    }
                                ),
                            contentDescription = null,
                            contentScale = ContentScale.Crop,
                            painter = painter,
                        )
                    }
                }
                3 -> {
                    images.forEachIndexed { index, url ->
                        val painter = rememberAsyncImagePainter(url)
                        LaunchedEffect(painter.state) {
                            if (painter.state is AsyncImagePainter.State.Success) {
                                doneCounter += 1
                            }
                        }
                        Image(
                            modifier = Modifier
                                .fillMaxHeight(if (index == 2) 1f else 0.47f)
                                .fillMaxWidth(0.47f)
                                .align(
                                    when (index) {
                                        0 -> Alignment.TopStart
                                        1 -> Alignment.BottomStart
                                        else -> Alignment.TopEnd
                                    }
                                ),
                            contentDescription = null,
                            contentScale = ContentScale.Crop,
                            painter = painter,
                        )
                    }
                }
                else -> {
                    images.take(4).forEachIndexed { index, url ->
                        val painter = rememberAsyncImagePainter(url)
                        LaunchedEffect(painter.state) {
                            if (painter.state is AsyncImagePainter.State.Success) {
                                doneCounter += 1
                            }
                        }
                        Image(
                            modifier = Modifier
                                .fillMaxSize(0.47f)
                                .align(
                                    when (index) {
                                        0 -> Alignment.TopStart
                                        1 -> Alignment.BottomStart
                                        2 -> Alignment.TopEnd
                                        else -> Alignment.BottomEnd
                                    }
                                ),
                            contentDescription = null,
                            contentScale = ContentScale.Crop,
                            painter = painter,
                        )
                    }
                }
            }
        }
        if (images.take(4).size != doneCounter) {
            Image(
                modifier = Modifier.fillMaxSize(),
                contentDescription = null,
                contentScale = ContentScale.Crop,
                painter = placeholder,
            )
        }
    }
}
```

![Screenshot 2022-12-14 at 00 15 16](https://user-images.githubusercontent.com/9665914/207445089-573f78c2-c0ec-49fc-b3d0-ab2f4b4e08be.png)
