### ISSUE TITLE
Does Coil compress the Image Loading? If yes, can I control how much an Image is Compressed?

### ISSUE THREAD

**Issue by KamathVishak96** [coil-kt/coil#555]
I'm using coil to display images in a recycler view and the scroll isn't very smooth. The scroll is comparatively smooth in Glide where I can set a factor for Compression with `public RequestBuilder<TranscodeType> thumbnail(float sizeMultiplier)`.

**Comment by colinrtwhite** [comment]
It's not currently possible to decode a thumbnail while decoding the full image. If you're seeing performance issues, I'd check out https://github.com/coil-kt/coil/issues/409.
