### ISSUE TITLE
Custom Fetcher - how to handled possible null result

### ISSUE THREAD

**Issue by MFlisar** [coil-kt/coil#558]
I've written following fetcher:

```
class AppIconFetcher(
    val context: Context
) : Fetcher<ComponentName> {

    override fun key(data: ComponentName): String? = "${data.packageName}|${data.className}"

    override suspend fun fetch(
        pool: BitmapPool,
        data: ComponentName,
        size: coil.size.Size,
        options: Options
    ): FetchResult {
        val ri = AppDataManager.loadResolveInfo(context, data)
        val drawable = ri?.loadIcon(context.packageManager) ?: ColorDrawable(Color.TRANSPARENT)
        return DrawableResult(
            drawable = drawable,
            isSampled = false,
            dataSource = DataSource.MEMORY
        )
    }
}
```

If an app is not installed anymore the `ResolveInfo` of the corresponding `ComponentName` will be null and so the `Drawable` will be null - is there a better way than what I do to handle this case? `DrawableResult::drawable` does not support `null` so I create a invisible drawable to solve this but this does not look clean to me, especially as I will create different drawables for each failing request so if this is the approach to use in this case, it looks like there should be an object like EmptyResult for this use case...

Loading the `ResolveInfo` for a `ComponentName` does need some time, so evaluating if it exists before loading the image is not the best solution and would need some extra work.

**Additional question**

I do load images with following code:

```
fun display(componentName: ComponentName, imageView: ImageView) {
        imageView.loadAny(componentName) {
            //crossfade(false)
            listener { request, metadata ->
                L.d { "Request: ${request.data} | metadata: ${metadata.dataSource} | key: ${metadata.memoryCacheKey}" }
            }
        }
    }
```

This results in logs like following;

> Request: ComponentInfo{com.google.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} | metadata: MEMORY | key: null (ImageRequest.kt:870)
> Request: ComponentInfo{com.sec.android.app.clockpackage/com.sec.android.app.clockpackage.ClockPackage} | metadata: MEMORY | key: Complex(base=com.sec.android.app.clockpackage|com.sec.android.app.clockpackage.ClockPackage, transformations=[], size=null, parameters={}) (ImageRequest.kt:870)

As you can see, the YouTube App has a key and the Clock App doesn't (and my logs show a lot of those 2 lines without any logic for me, some apps have a key and some not). Why? No key will mean that the YouTube icon is not cached and will always be reloaded or am I wrong?

**Comment by colinrtwhite** [comment]
I think either returning a "default" result like the default Android Studio app icon or `ColorDrawable(Color.TRANSPARENT)` is a good way to handle this. You could also throw an error if you want the caller's error drawable to be used. It's not possible to return a true `EmptyResult` because `Target.onSuccess` requires a non-null drawable.

You're right that if `metadata.memoryCacheKey` is null it means the result of the request was not written to the memory cache. In this case I'd guess that your `Fetcher` is returning a non-`BitmapDrawable` (probably a `VectorDrawable). To have it cached you can convert it to a `BitmapDrawable` using `.toBitmap().toDrawable()`.

**Comment by MFlisar** [comment]
I think caching is something most of the users expect by default - would it be possible to enable caching for non bitmap drawables globally somehow? Just by forcing the bitmap conversion for all non animated drawables e.g.?

In my custom fetcher I can force the conversion myself, but in others I can't...
