### ISSUE TITLE
Didn't show video thumbnail from media content uri (MediaStore) on Android 10

### ISSUE THREAD

**Issue by kimcy929** [coil-kt/coil#559]
I tried using **coil 1.0.0 and coil-video: 1.0.0** to show video thumbnail on Android 10 but it didn't work with media content Uri that was created by MediaStore. But it worked fine with Content Provider Uri (SAF).

Sure, I reconfigured VideoFrameXFetcher [https://github.com/coil-kt/coil/blob/ba9473f518e4484b80ef03e0bd9babcde81f35bc/coil-sample/src/main/java/coil/sample/Application.kt#L29-L30](url) 

Thanks!

**Comment by colinrtwhite** [comment]
Does the Uri work on API 28 or below? If so it might be due to [the storage changes in Android 11](https://developer.android.com/about/versions/11/privacy/storage). I'm not sure this is a bug in Coil, but if you believe it is please include a sample app that reproduces the issue.

**Comment by kimcy929** [comment]
Thank you!

I didn't test on API 28 because For Android 9.0 and lower I only use File API.

I think you can load thumbnail of a video or photo on Android 10 via **contentResolver.loadThumbnail** . I have used it on a my project.

https://developer.android.com/reference/android/content/ContentResolver#loadThumbnail(android.net.Uri,%20android.util.Size,%20android.os.CancellationSignal)

Reproduce the sample:

**minSdk: 21
targetSdk: 30**

```kotlin
class MyApplication : Application(), ImageLoaderFactory {

    override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(this)
            .availableMemoryPercentage(0.25) // Use 25% of the application's available memory.
            .crossfade(true) // Show a short crossfade when loading images from network or disk.
            .componentRegistry {
                // Fetchers
                add(VideoFrameFileFetcher(this@MyApplication))
                add(VideoFrameUriFetcher(this@MyApplication))
       }.build()
    }
}
```

```kotlin
imageView.load(mediaContentUri) { // content://media/external/video/media/6945
    videoFrameMillis(1000)
}
```

**Comment by colinrtwhite** [comment]
@kimcy929 Thanks for the code snippet. In this case it's not possible for Coil to detect that that `Uri` is a video file since it doesn't have an extension. If you do:

```kotlin
imageView.load(mediaContentUri) {
    videoFrameMillis(1000)
    fetcher(VideoFrameUriFetcher(context))
}
```

does it work correctly?

**Comment by kimcy929** [comment]
Yes. It's working fine.

Thank your for your solution.

**Comment by florianPOLARSTEPS** [comment]
> @kimcy929 Thanks for the code snippet. In this case it's not possible for Coil to detect that that `Uri` is a video file since it doesn't have an extension. 

Based on the `URI` from MediaStore we could try to resolve the MIME-type using [ContentResolver.getType](https://developer.android.com/reference/android/content/ContentResolver#getType(android.net.Uri)). That way we could make those decisions globally.

Drawback:
- This will come with a performance hit though and should not happen on the main thread since the call executes an SQLite statement behind the scenes.
