### ISSUE TITLE
Support frame-by-frame access of animated GIF/WEB and also of video files

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [coil-kt/coil#563]
**Is your feature request related to a problem? Please describe.**
I want to be able to go over all frames of such files, and if there is a known time between them (that it stays on the same frame) - to also know about it.

**Describe the solution you'd like**
Have 2 ways to go over frames:
1. Query of specific time, to get the frame of this time. The frame will include the bitmap, start time, and end time of the given frame.
2. A callback to act as if you play the animation/video, which will send us the Bitmaps of the frames as soon as it can.

**Additional context**
For Glide, I succeeded to have it for animated GIF/WEBP, but using weird workarounds.
I hope that for Coil it's possible to do it nicely, including for video files.

**Comment by colinrtwhite** [comment]
For video files, it's already possible to access individual frames: https://coil-kt.github.io/coil/videos/

**Comment by AndroidDeveloperLB** [comment]
Pretty sure Coil doesn't support individual frames, and instead it reaches key-frames.
Suppose I choose an MP4 file, and choose to get a bitmap of the frame of how it looks like on second 1, according to a tiny sample I've tried, it might return black instead.

**Comment by colinrtwhite** [comment]
It finds the nearest sync frame by default, however [you can use `videoFrameOption(OPTION_CLOSEST)`](https://github.com/coil-kt/coil/blob/master/coil-video/src/main/java/coil/request/Videos.kt#L48) to get the exact frame though this is much slower.

**Comment by AndroidDeveloperLB** [comment]
@colinrtwhite Seems to work now with this.
But is it efficient in getting the frames this way? 
Suppose I want to get the first 5 seconds of a video, in 30 fps , will it be smooth enough to get them, and show them in 30 fps ?

**Comment by AndroidDeveloperLB** [comment]
@colinrtwhite I've now tried something like that, and it seems to be extremely slow.


[CoilTest.zip](https://github.com/coil-kt/coil/files/5468941/CoilTest.zip)

**Comment by colinrtwhite** [comment]
@AndroidDeveloperLB Decoding video frames is a very expensive process that requires hardware support. Coil using Android's `MediaMetdataRetriever` class to accomplish this. It's not possible to decode exact frames quicker.

**Comment by AndroidDeveloperLB** [comment]
@colinrtwhite So how does video playback does it so well? Why can't I use it instead?
Converting video files, showing the images...
How can I batch show/handle the images?

**Comment by colinrtwhite** [comment]
I think this is out of scope for Coil. Broadly, Coil is a library that converts data (e.g. URLs, files, etc.) into images (i.e. `Drawable`s). For parsing video files and stepping through them frame by frame, you're better off using a parser like [`MediaMetadataRetriever`](https://developer.android.com/reference/android/media/MediaMetadataRetriever). In 2.x you can access the file directly in Coil's disk cache.

**Comment by AndroidDeveloperLB** [comment]
Too bad
