### ISSUE TITLE
Loading Vector Drawable from URL

### ISSUE THREAD

**Issue by mattinger** [coil-kt/coil#565]
I'm not seeing it mentioned anywhere whether coil can support loading a vector drawable via an http(s) url.  I do see support for SVGs via the svg library though, but i'm curious if vector drawables would be supported this way.

**Comment by colinrtwhite** [comment]
Coil does not support loading vector drawables from the network. I'd like to add this, however it's currently not possible as `VectorDrawableCompat` only has a `createFromXmlInner` method which requires a `Resources` instance.

**Comment by atonamy** [comment]
Any plans from Google to support such feature especially loading Animated Vector Drawables from external source like file or stream? Anyone anything knows about this?
