### ISSUE TITLE
RecyclerView sometimes shows empty images

### ISSUE THREAD

**Issue by MFlisar** [coil-kt/coil#567]
In a small launcher app I see following:

* the launcher is an app that is always running and it's running for days
* every now and then I open my launcher and see, that some items are not displayed
* I use a normal `RecyclerView` to display the items

Based on other issues I think following is some important extra information:

* I do not use prefetching in my `RecyclerView`
* I disabled crossfading as you can see in my code below

What can cause coil to not display images? Any hints in what direction I should look?

**Code**

I use the custom fetcher I've posted here: https://github.com/coil-kt/coil/issues/558

```
fun display(componentName: ComponentName, imageView: ImageView) {
        imageView.loadAny(componentName) {
            //crossfade(false)
            listener { request, metadata ->
                L.d { "Request: ${request.data} | metadata: ${metadata.dataSource} | key: ${metadata.memoryCacheKey}" }
            }
        }
    }

    fun init(context: Context) {
        val imageLoader = ImageLoader.Builder(context)
            .crossfade(false)
            .componentRegistry {
                // Fetchers
                add(AppIconFetcher(context))
                // Decoders
                // ...
            }
            .okHttpClient {
                OkHttpClient.Builder()
                    .cache(CoilUtils.createDefaultCache(context))
                    .build()
            }
            .apply {
                // Enable logging to the standard Android log if this is a debug build.
                if (BuildConfig.DEBUG) {
                    // logger(DebugLogger(Log.VERBOSE))
                }
            }
            .build()
        Coil.setImageLoader(imageLoader)
    }
```

**Comment by colinrtwhite** [comment]
You mentioned in the other ticket that sometimes your fetcher can return an empty result - maybe that's related? You could set up an `EventListener` that logs the output drawable in `onSuccess` and see if it ever returns blank. You can also log errors in `onError`.

**Comment by b95505017** [comment]
Same issue here, the difference is that I turn on crossfade.

**Comment by MFlisar** [comment]
> sometimes your fetcher can return an empty result - maybe that's related?

Definitely not, scrolling down and back up and images are shown again. And in my test environment I know, that none of the apps I show have been uninstalled so all of them do have an icon.

> You could set up an `EventListener` that logs the output drawable in `onSuccess` and see if it ever returns blank. You can also log errors in `onError`.

I will do what you suggest and let you know the result. Btw, do I really need to create my own the `ImageViewTarget` to log the output (`ImageViewTarget::onSuccess` is not open and `ImageViewTarget::setDrawable` does not know which image is set so I don't even can extend this class)  ? I don't see any bitmap inside the request listener `onSuccess` callback, so I do following:

```kotlin
object ImageManager {

    fun display(componentName: ComponentName, imageView: ImageView) {
        val context = imageView.context
        val imageLoader = context.imageLoader
        val target = ExtendedImageViewTarget(imageView)
        val request = ImageRequest.Builder(context)
            .data(componentName)
            .target(target)
            .listener(
                onError = { request, throwable ->
                    L.tag("COIL PROBLEM").e { "Request: ${request.data} | throwable: ${throwable.message}" }
                    L.e(throwable)
                    LogManager.showUnexpectedErrorNotification()
                },
                onSuccess = { request, metadata ->
	            // can't access bitmap here as far as I see
                    L.d { "Request: ${request.data} | metadata: ${metadata.dataSource} | key: ${metadata.memoryCacheKey}" }
					
                }
            )
            .build()
        imageLoader.enqueue(request)

//        imageView.loadAny(componentName) {
//            //crossfade(false)
//            listener { request, metadata ->
//                L.d { "Request: ${request.data} | metadata: ${metadata.dataSource} | key: ${metadata.memoryCacheKey}" }
//            }
//        }
    }
}
``` 

**Custom ImageViewTarget**

```kotlin
class ExtendedImageViewTarget(override val view: ImageView): PoolableViewTarget<ImageView>, TransitionTarget, DefaultLifecycleObserver {

	private var isStarted = false

	override val drawable: Drawable? get() = view.drawable

	override fun onStart(placeholder: Drawable?) = setDrawable(placeholder)

	override fun onError(error: Drawable?) = setDrawable(error)

	override fun onSuccess(result: Drawable) {
		setDrawable(result)
		if (drawable == null) {
			L.tag("COIL PROBLEM").e { "drawable == null - this should never happen!" }
			LogManager.showUnexpectedErrorNotification()
		}
	}

	override fun onClear() = setDrawable(null)

	override fun onStart(owner: LifecycleOwner) {
		isStarted = true
		updateAnimation()
	}

	override fun onStop(owner: LifecycleOwner) {
		isStarted = false
		updateAnimation()
	}

	/** Replace the [ImageView]'s current drawable with [drawable]. */
	protected open fun setDrawable(drawable: Drawable?) {
		(view.drawable as? Animatable)?.stop()
		view.setImageDrawable(drawable)
		updateAnimation()
	}

	/** Start/stop the current [Drawable]'s animation based on the current lifecycle state. */
	protected open fun updateAnimation() {
		val animatable = view.drawable as? Animatable ?: return
		if (isStarted) animatable.start() else animatable.stop()
	}

	override fun equals(other: Any?): Boolean {
		return (this === other) || (other is ImageViewTarget && view == other.view)
	}

	override fun hashCode() = view.hashCode()

	override fun toString() = "ExtendedImageViewTarget(view=$view)"
}
```

**Comment by MFlisar** [comment]
Finally, the error did occur again already - 2 images did not show up and I see following exception for both of them (exception is logger from the request onError listener):

	2020-10-28 19:42:04,307	[<COIL PROBLEM> ImageManager$display$$inlined$listener:870 onError]: Request: ComponentInfo{com.asus.aihome/com.asus.aihome.MainActivity} | throwable: Can't prepareToDraw on a recycled bitmap!
	2020-10-28 19:42:04,308	[Bitmap:400 checkRecycled]: java.lang.IllegalStateException: Can't prepareToDraw on a recycled bitmap!
		at android.graphics.Bitmap.checkRecycled(Bitmap.java:400)
		at android.graphics.Bitmap.prepareToDraw(Bitmap.java:2389)
		at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:487)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Any ideas why this does happen?

**Comment by colinrtwhite** [comment]
@MFlisar That error looks related to https://github.com/coil-kt/coil/issues/546. The easiest way to work-around this issue it to set `ImageLoader.bitmapPoolingEnabled(false)`.

**Comment by MFlisar** [comment]
Ok. Do you generally suggest to disabling bitmap pooling if coil is used with a `RecyclerView`?

**Comment by colinrtwhite** [comment]
@MFlisar I wouldn't worry about disabling it. It's a nice optimization to have, however it's most useful on API 23 and below. If it causes issues (like in this case), it's more worthwhile to disable it.

**Comment by colinrtwhite** [comment]
Closing this as I believe this is related to #546.

**Comment by rovkinmax** [comment]
I have the same issue with bitmapPoolingEnabled(false). In all recyclerviews in app when I scroll forward/back I often see placeholders even image already loaded

**Comment by rovkinmax** [comment]
I have the same issue with `bitmapPoolingEnabled(false)`. In all recyclerviews in app when I scroll forward/back I often see placeholders even image already loaded

https://user-images.githubusercontent.com/3259038/105153895-c9f59100-5b2a-11eb-8424-d1f027ed5794.mov

**Comment by Softtanck** [comment]
The same issue.
