### ISSUE TITLE
Palette integration

### ISSUE THREAD

**Issue by enricocid** [coil-kt/coil#573]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to easily access to the palette object, i.e. the main colour profiles in the image.

**Additional context**
It could be used to coordinate the colours of other visual elements on the image (music players for example).

**Comment by colinrtwhite** [comment]
Coil has a recipe for Palette integration: https://coil-kt.github.io/coil/recipes/#palette

**Comment by enricocid** [comment]
> Coil has a recipe for Palette integration: https://coil-kt.github.io/coil/recipes/#palette

Thanks, I'm closing then :)
