### ISSUE TITLE
Cache image with custom key

### ISSUE THREAD

**Issue by bakero98** [coil-kt/coil#578]
I am getting profile image using Facebook Graph API and each time for same image I get different uri ( it is intended to be this way ). Is there a way to cache that image with custom key ( user's uid?). Also I red documentation about caching it's not very descriptive in my opinion.

**Comment by colinrtwhite** [comment]
Yep, you can set a custom key using `memoryCacheKey(MemoryCache.Key(userId))`. It's not easily possible to set a custom disk cache key since that is controlled by OkHttp. Also, I'm open to a PR to improve the docs!
