### ISSUE TITLE
How can I pause or resume requests 

### ISSUE THREAD

**Issue by yxmFromTheMoon** [coil-kt/coil#580]
Like this in Glide
Glide.with(context).pauseAllRequests()
Glide.with(context).resumeRequests()

**Comment by RavioliWonton** [comment]
You can [execute](https://coil-kt.github.io/coil/api/coil-base/coil/-image-loader/execute/) a [ImageRequest](https://coil-kt.github.io/coil/image_requests/) by [singleton Coil or other IamgeLoader](https://coil-kt.github.io/coil/image_loaders/) in a [suspend launch scope](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/launch.html) and [able to simply cancel it](https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html).

**Comment by colinrtwhite** [comment]
This isn't supported out of the box, however you could accomplish this with a custom `Interceptor` and a `StateFlow`. Something like:

```kotlin
class PauseInterceptor : Interceptor {

    val isPaused = MutableStateFlow(false)

    override suspend fun intercept(chain: Interceptor.Chain): ImageResult {
        isPaused.first { !it }
        return chain.proceed(chain.request)
    }
}
```

You can add an interceptor when you create your `ImageLoader`.

**Comment by dlew** [comment]
It's worth noting that neither workaround here emulates how Glide or Picasso do pausing, since they will actually pause/cancel any loads in progress *then* resume/retry them later.

Simply cancelling does stop the loads, but then you have to manually restart them later; using the interceptor stops any new requests from starting, but does nothing to requests already in flight.

**Comment by ewgcat** [comment]
> This isn't supported out of the box, however you could accomplish this with a custom `Interceptor` and a `StateFlow`. Something like:
> 
> ```kotlin
> class PauseInterceptor : Interceptor {
> 
>     val isPaused = MutableStateFlow(false)
> 
>     override suspend fun intercept(chain: Interceptor.Chain): ImageResult {
>         isPaused.first { !it }
>         return chain.proceed(chain.request)
>     }
> }
> ```
> 
> You can add an interceptor when you create your `ImageLoader`.

so coil isn't supported the pause or resume requests like glide

**Comment by Softtanck** [comment]
So @colinrtwhite  it is a plan to added a API like Glide?
