### ISSUE TITLE
How to implement a size resolver that waits for the view to be laid out

### ISSUE THREAD

**Issue by MFlisar** [coil-kt/coil#582]
Is there something implemented to handle this problem? E.g. I need a custom `Viewtarget` to load images as background or for buttons - it makes sense to determine the image size based on the view itself.

What I do currently is following:

```kotlin
fun display(data: Any?, button: MaterialButton) {
    button.onGlobalLayout {
        val request = ImageRequest.Builder(button.context)
            .data(data)
            .size(button.iconSize)
            .target(object : ViewTarget<MaterialButton> {
                override val view = button
                override fun onSuccess(result: Drawable) {
                    view.icon = result
                }
            })
            .listener(listener)
            .build()
        button.context.imageLoader.enqueue(request)
    }
}
```

`onGlobalLayout` view extension is one of my own extensions and simply waits until the view is laid out and calls the lambda if it is...

Is this manual solution the way to go with custom view targets or is there something integrated into coil that I could use for this use case? If not, maybe it makes sense to be able resolve view sizes based on the provided view as soon as the view is laid out??

**Comment by colinrtwhite** [comment]
You can use `size(ViewSizeResolver(button))` to suspend until the view is measured. The size it returns will be used as the size for the request.

**Comment by MFlisar** [comment]
This will not work for a button or other non image views because the view size is not the image size. For such cases I need to write my own `ViewSizeResolver`, correct?

I added my first implementation below, but it is nearly a 1 to 1 copyof  the default `ViewSizeResolver` - sadly all it's helper functions are private...

**Suggestion / Idea**

Can't you make the helper functions inside `ViewSizeResolver` public? Or maybe you can change it in a way so that the user can provide an optional lambda to the `ViewSizeResolver` to adjust how the image size is deduced from the view?

```kotlin
class ButtonViewResolver(override val view: MaterialButton) : ViewSizeResolver<MaterialButton> {
	override suspend fun size(): Size {
		// Fast path: the view is already measured.
		getSize(view.isLayoutRequested)?.let { return it }

		// Slow path: wait for the view to be measured.
		return suspendCancellableCoroutine { continuation ->
			val viewTreeObserver = view.viewTreeObserver

			val preDrawListener = object : ViewTreeObserver.OnPreDrawListener {
				override fun onPreDraw(): Boolean {
					val size = getSize(false)
					if (size != null) {
						viewTreeObserver.removePreDrawListenerSafe(this)
						continuation.resume(size)
					}
					return true
				}
			}

			viewTreeObserver.addOnPreDrawListener(preDrawListener)

			continuation.invokeOnCancellation {
				viewTreeObserver.removePreDrawListenerSafe(preDrawListener)
			}
		}
	}

	private fun getSize(isLayoutRequested: Boolean): PixelSize? {
                // if a icon size is provided, we use this instead of the view size
		if (view.iconSize > 0)
			return PixelSize(view.iconSize, view.iconSize)
		val width = getWidth(isLayoutRequested).also { if (it <= 0) return null }
		val height = getHeight(isLayoutRequested).also { if (it <= 0) return null }
		return PixelSize(width, height)
	}

	private fun getWidth(isLayoutRequested: Boolean): Int {
		return getDimension(
			paramSize = view.layoutParams?.width ?: -1,
			viewSize = view.width,
			paddingSize = if (subtractPadding) view.paddingLeft + view.paddingRight else 0,
			isLayoutRequested = isLayoutRequested,
			isWidth = true
		)
	}

	private fun getHeight(isLayoutRequested: Boolean): Int {
		return getDimension(
			paramSize = view.layoutParams?.height ?: -1,
			viewSize = view.height,
			paddingSize = if (subtractPadding) view.paddingTop + view.paddingBottom else 0,
			isLayoutRequested = isLayoutRequested,
			isWidth = false
		)
	}

	/** Modified from Glide. */
	private fun getDimension(
		paramSize: Int,
		viewSize: Int,
		paddingSize: Int,
		isLayoutRequested: Boolean,
		isWidth: Boolean
	): Int {
		// Assume the dimension will match the value in the view's layout params.
		val insetParamSize = paramSize - paddingSize
		if (insetParamSize > 0) {
			return insetParamSize
		}

		// Fallback to the view's current size.
		val insetViewSize = viewSize - paddingSize
		if (insetViewSize > 0) {
			return insetViewSize
		}

		// If the dimension is set to WRAP_CONTENT and the view is fully laid out, fallback to the size of the display.
		if (!isLayoutRequested && paramSize == ViewGroup.LayoutParams.WRAP_CONTENT) {
			return view.context.resources.displayMetrics.run { if (isWidth) widthPixels else heightPixels }
		}

		// Unable to resolve the dimension's size.
		return -1
	}

	private fun ViewTreeObserver.removePreDrawListenerSafe(victim: ViewTreeObserver.OnPreDrawListener) {
		if (isAlive) {
			removeOnPreDrawListener(victim)
		} else {
			view.viewTreeObserver.removeOnPreDrawListener(victim)
		}
	}
}
``

**Comment by colinrtwhite** [comment]
@MFlisar Could you override `size`, add your check, and call `super.size()` if there's no icon size? I'm a little apprehensive to make `ViewSizeResolver`'s internal methods public since it's then something we'll have to support forever going forward.

**Comment by MFlisar** [comment]
Actually in this case I can even do following:

    ImageRequest.Builder(button.context)
         .size(button.iconSize)

It was an example only. I just wanted to point out that there are cases where the view size is different than the image size - `TextViews` and derivations like `Buttons` are just the first thing that come to my mind... Maybe even most custom view targets will use an image size different than the view size itself.

E.g. I do only define a icon size because I use coil, I would not set it otherwise. But it's easier to define it like this in combination with coil
