### ISSUE TITLE
Allow to add transformations

### ISSUE THREAD

**Issue by MFlisar** [coil-kt/coil#583]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I want to be able to add transformations from different places, currently you can only set all transformations at once.

**Additional context**
Consider following:

```kotlin
fun display(data: Any?, button: MaterialButton, builder: ImageRequest.Builder.() -> Unit = {}) {
	button.onGlobalLayout {
		val request = ImageRequest.Builder(button.context)
			.data(data)
			.size(button.iconSize)
			.listener(listener)
			.transformations(CropTransformation())
			.apply(builder)
			.target(object : ViewTarget<MaterialButton> {
				override val view = button
				override fun onSuccess(result: Drawable) {
					view.icon = result
				}
			})
			.build()
		button.context.imageLoader.enqueue(request)
	}
}
```

As you can see, I do already apply a `Transformation` in this function, if the calling place now wants to add additional transformations (e.g. circle crop, tinting, ...), it can't do that without removing the already added transformations (this means the caller must know about this internal transformation). It does not matter if the caller wants to circle crop, but if he wants to tint he must also provide the crop transformation again...

It would be nice to either be able to append transformations or to be able to retrieve all existing transformations from the builder - both allows me to append a transformation

**Comment by colinrtwhite** [comment]
You could use `build().transformations` inside `builder` to get the current list of transformations. I don't think it makes sense to expose transformations (and other builder properties) since they can often be incomplete/unresolved (e.g. lifecycle, sizeResolver, scale) until `ImageRequest.build()` is called. It's also convention to keep builder properties private.

**Comment by MFlisar** [comment]
With all the info you just gave me I think it's better to wrap the builder inside a small custom class and apply all added transformations inside this small wrapper... I don't like the build approach just to get the already set transformations...
