### ISSUE TITLE
Loading thumnail from memory cache.

### ISSUE THREAD

**Issue by JajaComp** [coil-kt/coil#593]
Hi! Why when i use this code for get thumbnail for VIDEO file:
```
imageView
                    .load(item.uri, imageLoader) {
                        this.memoryCacheKey(item.uri)
                        fallback(R.drawable.type_video)
                        error(R.drawable.type_video)
                    }
```

I got message "Cached image's request size (87, 154) is smaller than the requested size (154, 154, FILL)." in debug mode.

ImageView size is 154 x 154

```
<androidx.appcompat.widget.AppCompatImageView
        android:background="@drawable/border_image"
        android:src="@drawable/type_video"
        android:id="@+id/iv_preview"
        android:padding="8dp"
        android:scaleType="centerCrop"
        android:cropToPadding="true"
        android:layout_width="60dp"
        android:layout_height="60dp"/>
```

**Comment by colinrtwhite** [comment]
@JajaComp This is because your request is requesting a larger size than the image in the memory cache is. Adding `scale(Scale.FIT)` to your request or changing your `ImageView`'s scale type should result in a memory cache hit.

**Comment by JajaComp** [comment]
@colinrtwhite Not working for video thumbnails
Message for FIT:
Cached image's request size (86, 153) is smaller than the requested size (272, 272, FIT).
Message for FILL:
Cached image's request size (153, 272) is smaller than the requested size (272, 272, FILL).

If i use image loading - cache is fine.

**Comment by JajaComp** [comment]
Also i use coil insede RecyclerView and got next messages:
(First open)
LOG: Coil = ONLINE
LOG: Coil = 🏗  Cancelled - file:///data/user/0/....jpg
LOG: Coil = 💾 Successful (DISK) - file:///data/user/0/....jpg

(Scroll out and back) Double message
11-24 03:41:03.922  LOG: Coil = 🧠 Successful (MEMORY_CACHE) - file:///data/user/0/....jpg
11-24 03:41:03.926  LOG: Coil = 🧠 Successful (MEMORY_CACHE) - file:///data/user/0/....jpg

1) From onBindViewHolder -> load()
2) From ViewTargetRequestDelegate -> restart()

**Comment by JajaComp** [comment]
@colinrtwhite 
Can't get thumbnail from cache for this video (Size 1280x720). I think problem with algorithm of save thumbnail to cache
[test2.zip](https://github.com/coil-kt/coil/files/5586955/test2.zip)

Coil    : /data/user/0/com.example.myapplication/cache/test2.mp4: Cached image's request size (99, 176) is smaller than the requested size (176, 176, FILL).
Coil    : /data/user/0/com.example.myapplication/cache/test2.mp4: Cached image's request size (56, 99) is smaller than the requested size (176, 176, FIT).
