### ISSUE TITLE
Incorrect cache for video

### ISSUE THREAD

**Issue by JajaComp** [coil-kt/coil#595]
Can't get thumbnail from cache for this video (Size 1280x720). I think problem with algorithm of save thumbnail to cache, ignoring video rotation

Coil version 1.0.0
Target:
```
<androidx.appcompat.widget.AppCompatImageView
        android:background="@drawable/border_image"
        android:src="@drawable/type_video"
        android:id="@+id/iv_preview"
        android:padding="8dp"
        android:scaleType="centerCrop"
        android:cropToPadding="true"
        android:layout_width="60dp"
        android:layout_height="60dp"/>
```

Request:
```
imageView
                    .load(item.uri, imageLoader) {
                        this.memoryCacheKey(item.uri)
                        fallback(R.drawable.type_video)
                        error(R.drawable.type_video)
                    }
```

Sample video:
[test2.zip](https://github.com/coil-kt/coil/files/5586955/test2.zip)

Message if i use Scale.FILL
Coil : /data/user/0/com.example.myapplication/cache/test2.mp4: Cached image's request size (99, 176) is smaller than the requested size (176, 176, FILL).
Message if i use Scale.FIT
Coil : /data/user/0/com.example.myapplication/cache/test2.mp4: Cached image's request size (56, 99) is smaller than the requested size (176, 176, FIT).

Sample app
[Sample.zip](https://github.com/coil-kt/coil/files/5591857/Sample.zip)

**Comment by colinrtwhite** [comment]
Thanks for the report + sample project. I was able to figure out the issue here: #596.
