### ISSUE TITLE
sdk24以下，报错No static method hashCode(I)I in class Ljava/lang/Integer; or its super classes (declaration of 'java.lang.Integer' appears in /system/framework/core-libart.jar)

### ISSUE THREAD

**Issue by timizhuoym** [coil-kt/coil#597]
No static method hashCode(I)I in class Ljava/lang/Integer; or its super classes (declaration of 'java.lang.Integer' appears in /system/framework/core-libart.jar)

**Comment by colinrtwhite** [comment]
Please ensure you've enabled [Java 8 desugaring](https://coil-kt.github.io/coil/getting_started/#java-8) or provide sample code that reproduces the issue.
