### ISSUE TITLE
sdk21 加载图片失败

### ISSUE THREAD

**Issue by timizhuoym** [coil-kt/coil#598]
![image](https://user-images.githubusercontent.com/24522660/100173648-e3e96d80-2f05-11eb-8526-aeba66f9357b.png)
![image](https://user-images.githubusercontent.com/24522660/100173721-03809600-2f06-11eb-98ce-8d8c5ee58c72.png)
![image](https://user-images.githubusercontent.com/24522660/100173754-18f5c000-2f06-11eb-944a-826b7cd82b29.png)
![image](https://user-images.githubusercontent.com/24522660/100173789-26ab4580-2f06-11eb-802d-600f3f5f28a7.png)
![image](https://user-images.githubusercontent.com/24522660/100173814-31fe7100-2f06-11eb-9adf-9fd7cbf21d1e.png)
Please take a look

**Comment by timizhuoym** [comment]
Android5.1

**Comment by timizhuoym** [comment]
I found that Integer.hashCode is a method of sdk24

**Comment by colinrtwhite** [comment]
`Integer.hashCode` should be desugared by the Android Gradle plugin. How can I reproduce this issue?

**Comment by timizhuoym** [comment]
Use Coil to load the network picture in the style of the above picture, configure the placeholder image of the local resource id and the wrong picture. This problem will occur on the Android 5.1 mobile phone and cause the picture to fail to load.

**Comment by timizhuoym** [comment]
I just tried not to set the placeholder image and the wrong image, and use Android 5.1 to load only the network image without other settings. This problem must also occur. Please help.

**Comment by colinrtwhite** [comment]
@timizhuoym Please include a sample app that reproduces the issue. The test app in this repo works properly on Android 5.1.

**Comment by timizhuoym** [comment]
I just used the same method to load the image in another app and it did succeed. I'm sorry to bother you, let me see it myself
