### ISSUE TITLE
RoundedCornersTransformation doesn't work correctly with 'wrap_content'

### ISSUE THREAD

**Issue by clhols** [coil-kt/coil#599]
**Describe the bug**
After updating from 1.0.0 to 1.1.0 images started becoming very narrow and not keep the aspect ratio.
I narrowed it down to RoundedCornersTransformation. If I don't apply the transformation, then the image keeps its aspect ratio.

**Expected behavior**
RoundedCornersTransformation should work as before with Coil 1.0.0

**To Reproduce**
Build and run:
https://github.com/clhols/drchannels/tree/coil-issue

**Logs/Screenshots**
https://www.dropbox.com/s/1qziqi1i9ef7m96/Screenshot%202020-11-25%20at%2020.24.03.png?dl=1
https://www.dropbox.com/s/j989d15xydhpuvu/Screenshot%202020-11-25%20at%2020.23.46.png?dl=1

**Comment by colinrtwhite** [comment]
Does the `ImageView` in the screenshot use the `CENTER` or `MATRIX` scale types? This may be related to the first change in the [1.1.0 release](https://github.com/coil-kt/coil/blob/master/CHANGELOG.md#110---november-24-2020).

**Comment by clhols** [comment]
It uses "fit start"

**Comment by clhols** [comment]
https://www.dropbox.com/s/kii2cfcte4gyvvk/Screenshot%202020-11-26%20at%2023.59.34.png?dl=1

**Comment by clhols** [comment]
A workaround is to set both layout_width and layout_height of the image view to a fixed DP value.

**Comment by vbuberen** [comment]
@clhols Setting fixed size helped you? Without changing the scale type? 
I have issues with images, which already had fixed height and weight (24dp). Had to change the scale type from `center` to `centerCrop` to get proper size and transformation working.

Here is how user avatar looked after updating to Coil 1.1.0 without any changes (note, right image is a placeholder to show how avatar had to look):
<img width="76" alt="Screenshot 2020-11-27 at 14 48 54" src="https://user-images.githubusercontent.com/13467769/100451213-b2b49d00-30bf-11eb-86dd-9db54495dde9.png">
And here is fixed version after I changed the scale type changed. This is also how avatar looked before updating to 1.1.0.
<img width="73" alt="Screenshot 2020-11-27 at 14 49 52" src="https://user-images.githubusercontent.com/13467769/100451293-d2e45c00-30bf-11eb-87c8-2b5fc4e6a594.png">

**Comment by colinrtwhite** [comment]
@vbuberen That change is related to the first change in the [1.1.0 changelog](https://thoughtbot.com/blog/android-imageview-scaletype-a-visual-guide). It was made to ensure that the visual result of an image request is consistent with `ImageView.setImageResource`/`ImageView.setImageURI`. The center scale type typically loads the image without scaling it in the `ImageView`; Coil is now consistent with these other methods.

**Comment by vbuberen** [comment]
Thanks for explanations. My previous comment was mostly to the original issue reporter, since he mentioned that setting fixed size helped. It might confuse other people (like it confused me), so I shared how it worked for me.

**Comment by colinrtwhite** [comment]
Copying the comment from https://github.com/coil-kt/coil/issues/599:

Unfortunately there isn't a great way to solve this with the current way `Size` is modeled. I think we need the ability to only fit/fill on *either* width or height. Currently we can only fit/fill on both (`PixelSize`) or none `OriginalSize`.

The best way to work around this is to set `size(OriginalSize)` on your request.

**Comment by colinrtwhite** [comment]
This is fixed in `2.0.0`.
