### ISSUE TITLE
Does coil support cronet?

### ISSUE THREAD

**Issue by snepalnetflix** [coil-kt/coil#603]
Hi, I was curious if Coil can be customized to support networking libraries like Cronet.

Thanks

**Comment by colinrtwhite** [comment]
Coil doesn't have first-class support for it, but you could integrate with Cronet a couple of ways:

- Write an OkHttp [interceptor](https://square.github.io/okhttp/interceptors/) that delegates to Cronet. Then create an `OkHttpClient` with that interceptor when you [create your `ImageLoader`](https://coil-kt.github.io/coil/getting_started/#singleton).
- Write a custom [`Fetcher`](https://coil-kt.github.io/coil/image_pipeline/#fetchers) that handles any uri with an `https` scheme. Check out how Coil's [OkHttp-backed `Fetcher`](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/fetch/HttpFetcher.kt#L20) works for an example.
