### ISSUE TITLE
Bug photo size if scaleType="centerCrop"

### ISSUE THREAD

**Issue by umerov1999** [coil-kt/coil#604]
If photo is portrait variant, Coil 1.1.0 sometimes load this photo as landscape. Picasso load normal

    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/background_gray"

    <com.google.android.material.imageview.ShapeableImageView
        android:id="@+id/item_video_image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:scaleType="centerCrop"
        app:shapeAppearanceOverlay="@style/ShapeAppearance.MediumRoundedPictures" />

    </FrameLayout>
....

**Comment by colinrtwhite** [comment]
Please include a sample project that reproduces the bug. I tried using `ShapeableImageView` + `centerCrop` and the image was loaded with the correct size.

**Comment by umerov1999** [comment]
> Please include a minimal sample project that reproduces the bug. I tried using `ShapeableImageView` + `centerCrop` and the image was loaded with the correct size.

This bug is very rare.  Maybe because of the peculiarities in the recyclerview adapter.  A minimal project probably won't help.  I'll try to reproduce it.


Этот баг наблюдается очень редко. Может быть из-за особенностей в recyclerview адапторе. Минимальный проект скорее всего не поможет. Попробую воспроизвести его

**Comment by colinrtwhite** [comment]
Please re-open the issue if you're able to reproduce the issue with a sample project.
