### ISSUE TITLE
Provide callback when animated GIF is done playing

### ISSUE THREAD

**Issue by rundavidrun** [coil-kt/coil#606]
Provide a mechanism for the caller to be notified when an animated GIF has completed all loops. ( Similar to Glide V4's onAnimationEnd listener - see [https://github.com/bumptech/glide/pull/3438](https://github.com/bumptech/glide/pull/3438) )

For example,
```
binding.myImageView.load(R.drawable.some_gif_animation) {
   repeatCount(0)
   onAnimationComplete = { /* do something */ }
}
```

**Comment by colinrtwhite** [comment]
:+1: Makes sense. In the meantime as a work-around, `MovieDrawable` and `AnimatedImageDrawable` both implement `Animatable2`/`Animatable2Compat` which allows you to set a listener for start/end events.

**Comment by rundavidrun** [comment]
@colinrtwhite  - I'm not sure how to get access to the `MovieDrawable` when using `load`. Any pointers?

**Comment by sagar-viradiya** [comment]
@rundavidrun Head on to https://coil-kt.github.io/coil/targets/

The idea is to use target callbacks and in the success callback, you can typecast Drawable to MovieDrawable or AnimatedImageDrawable depending on which API level you are loading the image.

**Comment by rundavidrun** [comment]
Thanks. I still can't make this work. I have a gif stored in the drawable folder as animation.gif. It just loads the first frame of the animation and never calls the callback. I'm using:
```
val callback = object : Animatable2Compat.AnimationCallback() {
    override fun onAnimationEnd(drawable: Drawable) {
        Log.d("******", "animation end!!")
    }
}
val request = ImageRequest.Builder(this)
        .data(R.drawable.animation)
        .target(
                onSuccess = { result ->
                    Log.d("******", "got onSuccess")
                    val movieDrawable = result as MovieDrawable
                    movieDrawable.setRepeatCount(0)
                    movieDrawable.registerAnimationCallback(callback)
                    binding.fullScreenImage.load(movieDrawable)
                }
        ).build()
val imageLoader = ImageLoader.Builder(this)
        .componentRegistry {
            if (SDK_INT >= 28) {
                add(ImageDecoderDecoder())
            } else {
                add(GifDecoder())
            }
        }
        .build()
imageLoader.enqueue(request)
```

**Comment by sagar-viradiya** [comment]
@rundavidrun At the end of `onSuccess`, you are calling `load` which is nothing but an extension on ImageView and it internally creates a new request. Set the drawable like this `binding.fullScreenImage.setImageDrawable(result)`. This should fix your issue.

**Comment by rundavidrun** [comment]
@sagar-viradiya - using `binding.fullScreenImage.setImageDrawable(result)` still just shows the first frame of the animation. I'm looking forward to getting the update once your PR is integrated. Thanks for writing it!
