### ISSUE TITLE
Crossfade doesn't smoothly transition between images

### ISSUE THREAD

**Issue by ThomasArtProcessors** [coil-kt/coil#608]
Hi there.
Is it possible to achieve proper crossfade between two images ( not the placeholder ), by loading one and then the other?

I apply a crossfade between a series of images but it isn't a true smooth crossfade.
The original disappears, is replaced by just black, then the new image fades in.
So you always see this black, 'empty' image in between the transitions, instead of a smooth true crossfade. 
Is there a way to fix this?

Running version 1.1.0 ( was on 1.0.0 before with same problem )
Loading the image like this:
```
load(images[currentIndex].path) {
            crossfade(600)
}
```
I tried simply using `crossfade(true)`
I also tried `transition(CrossfadeTransition(600, true))`

But the result is always a 'false' crossfade. It's really just the first image disappearing, a short instant of black/empty image, then the new image fading in.

I'm assuming you simply can't crossfade two images without using two imageviews, but wanted to check.

**Comment by colinrtwhite** [comment]
If you're looking to crossfade without clearing the `ImageView` at the beginning of the request, you could use a custom `TransitionTarget` that ignores `onStart` which sets the placeholder. Something like:

```
val request = ImageRequest.Builder(context)
    .data(images[currentIndex].path)
    .crossfade(600)
    .target(object : TransitionTarget {
        override val drawable get() = imageView.drawable
        override val view get() = imageView
        override fun onSuccess(result: Drawable) {
            imageView.setImageDrawable(result)
            (result as? Animatable)?.start()
        }
    })
    .build()
imageLoader.enqueue(request)
```

**Comment by ThomasArtProcessors** [comment]
@colinrtwhite Thanks for this.
This works but only once for each image. In my case the imageview keeps "rotating" between the images infinitely.
They keep fading into each other in a loop.
With this it only fades each image once then never again.

**Comment by colinrtwhite** [comment]
Interesting it should continue to fade between `imageView.drawable` and `result` every time `imageLoader.enqueue(request)` is called.

**Comment by ThomasArtProcessors** [comment]
Not sure what happened last time but I tried this again and the code works fine and keeps working as I cycle through the same images continually...
Thanks!

**Comment by ThomasArtProcessors** [comment]
@colinrtwhite Actually there's an issue...
I got the Network call back crash from 
`android.net.ConnectivityManager$TooManyRequestsException`

That's because I was using a new `ImageLoader(context)` each time.
So I created a global one for the class and reused it. Which I'm assuming fixes the crash BUT the crossfade doesn't happen anymore by reusing the same loader...
Any ideas?

**Comment by ThomasArtProcessors** [comment]
@colinrtwhite Without re-creating the loader each time I get back to the situation where the crossfade only happens once for each image in the list, then never again.
If I recreate the loader each time it works fine ( though unfortunately it leads to the 'too many requests' crash ).

**Comment by 0n4li** [comment]
I modified the code as below:

```
val request = ImageRequest.Builder(context)
    .data(images[currentIndex].path)
    .crossfade(600)
    .target(object : TransitionTarget {
        override val drawable get() = imageView.drawable
        override val view get() = imageView
        override fun onSuccess(result: Drawable) {
            val drawable = if (result is Animatable) result else CrossfadeDrawable(imageView.drawable, result, durationMillis = 600)
            imageView.setImageDrawable(drawable)
            (drawable as? Animatable)?.start()
        }
    })
    .build()
imageLoader.enqueue(request)
```

**Comment by JJSarrasin** [comment]
For my case, I only need the following snippet to avoid the black blink effect (I need to disable cache policy, that's maybe not your need)

val request = ImageRequest.Builder(context)
                    .data(url)
                    .crossfade(0)
                    .memoryCachePolicy(CachePolicy.DISABLED)
                    .target(object : TransitionTarget {
                        override val drawable get() = cardView.showImageView.drawable
                        override val view get() = cardView.showImageView
                        override fun onSuccess(result: Drawable) {
                            myImageVie.setImageDrawable(result)
                        }
                    })
                    .build()

**Comment by oxyroid** [comment]
@colinrtwhite How can we use it in Jetpack Compose?

**Comment by Sculas** [comment]
@oxyroid I encountered the same issue. I've tried all sorts of hacks to fix it, but in the end, resorted to just forking it and fixing it myself. I don't think this is intended behavior necessarily though by the developers, so I probably won't PR it upstream.

[These](https://github.com/coil-kt/coil/compare/main...Sculas:coil:main) are the changes I've made. See the [GitHub Docs](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry) on how to use the GitHub Package Registry if you're not familiar with it.
```kt
// settings.gradle.kts
repositories {
    // ...
    maven {
        url = uri("https://maven.pkg.github.com/sculas/coil")
        credentials {
            username = settings.ext["gpr.user"] as String? ?: System.getenv("GITHUB_ACTOR")
            password = settings.ext["gpr.key"] as String? ?: System.getenv("GITHUB_TOKEN")
        }
        content {
            includeGroup("io.coil-kt.coil3")
        }
    }
}
```
```toml
# libs.versions.toml
[versions]
coil = "3.0.0-SNAPSHOT"
```

**Comment by revs87** [comment]
Problem still persists on "3.0.0-rc01" and for some reason I don't have access to the SNAPSHOT version: "Failed to resolve: io.coil-kt.coil3:coil-compose:3.0.0-SNAPSHOT'

**Comment by Sculas** [comment]
> Problem still persists on "3.0.0-rc01" and for some reason I don't have access to the SNAPSHOT version: "Failed to resolve: io.coil-kt.coil3:coil-compose:3.0.0-SNAPSHOT'

This is to use the official snapshots from Coil (not my fork mentioned above, if that's what you meant):

https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots
> Add the snapshots repository to your list of repositories:
> ```kt
> allprojects {
>     repositories {
>         maven("https://oss.sonatype.org/content/repositories/snapshots")
>     }
> }
> ```

**Comment by Samuel-Unknown** [comment]
@colinrtwhite could you show an example for Compose please? 🙏🙏🙏

**Comment by suomi35** [comment]
> > How can we use it in Jetpack Compose?
> 
> I encountered the same issue and had the same question. I've tried all sorts of hacks to fix it, but in the end, resorted to just forking it and fixing it myself. I don't think this is intended behavior necessarily though by the developers, so I probably won't PR it upstream since it doesn't make sense, but I'm always willing to if I'm wrong.
> 
> [These](https://github.com/coil-kt/coil/compare/main...Sculas:coil:main) are the changes I've made. See the [GitHub Docs](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry) on how to use the GitHub Package Registry if you're not familiar with it.
> 
> // settings.gradle.kts
> repositories {
>     // ...
>     maven {
>         url = uri("https://maven.pkg.github.com/sculas/coil")
>         credentials {
>             username = settings.ext["gpr.user"] as String? ?: System.getenv("GITHUB_ACTOR")
>             password = settings.ext["gpr.key"] as String? ?: System.getenv("GITHUB_TOKEN")
>         }
>         content {
>             includeGroup("io.coil-kt.coil3")
>         }
>     }
> }
> # libs.versions.toml
> [versions]
> coil = "3.0.0-SNAPSHOT"

I have setup the package registry, but AS still uses the official repo, not your fork.
