### ISSUE TITLE
How to load image from byte stream?

### ISSUE THREAD

**Issue by brookmg** [coil-kt/coil#609]
The title says it all. The type safe implementation of the `load` function doesn't show any way to load byte stream into an image view. How can that be done.

**Comment by brookmg** [comment]
Ya, I actually found a way to give it a `ByteArray` instead. Thanks for your answer.

**Comment by kihaki** [comment]
@brookmg You found an answer and then decided not to post it here? Are you literally [this xkcd](https://xkcd.com/979/)?!

**Comment by brookmg** [comment]
Indeed this is trash behavior, I don't remember what I was working on or how I solved this issue but let me look around.
