### ISSUE TITLE
Strange placeholder behaviour?

### ISSUE THREAD

**Issue by gajicm93** [coil-kt/coil#610]
**Describe the bug**
Placeholder is properly shown WHILE the image request is in progress, but if it fails for any reason, the placeholder also disappears.

**Expected behavior**
In case image load fails, placeholder should stay shown in the ImageView..

**To Reproduce**
Just set a placeholder parameter, and for the image url pass null.

**Version**
1.1.0

**Comment by colinrtwhite** [comment]
Yep, this is expected behaviour. If you'd like the placeholder to remain after an error you can set the `error` and/or `fallback` for the request.
