### ISSUE TITLE
Is it possible to specify a fallback URL?

### ISSUE THREAD

**Issue by digitalheir** [coil-kt/coil#613]
I have a separate web service to handle request in case the primary service is down or unresponsive. What is the best way to handle an IO error for the primary URL?

**Comment by colinrtwhite** [comment]
There isn't out of the box support for this, but you could create a custom [`Interceptor`](https://coil-kt.github.io/coil/image_pipeline/#interceptors) that catches any IO exceptions and retries the request with the fallback URL. You can pass in the fallback URL using a custom [parameter](https://coil-kt.github.io/coil/api/coil-base/coil.request/-parameters/).

**Comment by digitalheir** [comment]
Thank you!
