### ISSUE TITLE
Calling execute() on the main thread freezes the app

### ISSUE THREAD

**Issue by dlew** [coil-kt/coil#615]
**Describe the bug**

Attempts to run execute() on the main thread cause freezes the app.

**Expected behavior**

I expect to be able to run execute() on the main thread (even though yes, I know this is not good practice).

**To Reproduce**

Try to call `execute()` inside of `runBlocking {}` while on the main thread.

Here's a small sample:

```
class MainActivity : AppCompatActivity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val imageLoader = ImageLoader.Builder(this)
      .build()

    Log.i("test", "start")

    runBlocking {
      imageLoader.execute(
        ImageRequest.Builder(this@MainActivity)
          .data(R.drawable.image)
          .build()
      )
    }

    Log.i("test", "end") // Never prints
  }
}
```

**Version**

Coil 1.1.0.

**Comment by dlew** [comment]
I've been digging further into this, and while the easy answer would be "just call `execute()` instead of `enqueue()`", I am kind of curious why this is freezing in the first place.

It looks like it might be related to the same state I managed to get into for https://github.com/Kotlin/kotlinx.coroutines/issues/2448. I can see in the debugger that a successful HTTP request is made, and results are going to be delivered, then they just... aren't. We ended up being parked forever.

Might want to wait until we figure out that issue before proceeding here, as it might be something more core to coroutines and not something we should try to fix in this lib itself.

**Comment by colinrtwhite** [comment]
It's possible to run the request on the main thread by setting `ImageRequest.Builder.dispatcher(Dispatcher.Main.immediate)`. However, this won't work for network requests. That said, I'd highly recommend not blocking the main thread to decode a network image since it will block the main thread for multiple seconds!
