### ISSUE TITLE
Image cache in custom image loader 

### ISSUE THREAD

**Issue by saqibmirza2007** [coil-kt/coil#616]
We are making customImage loader using the code below but the Image always loads from the Network and cache is skipped ( eg on device orientation change it loads image from Network) . What can be missing from the configurations as I can't find it from installation and usage guide. 

`val imageLoader = ImageLoader.Builder(requireContext())
    .okHttpClient {​​​​​​​​
OkHttpClient.Builder()
            .addInterceptor(customInterceptor)
            .cache(CoilUtils.createDefaultCache(requireContext()))
            .build()
    }​​​​​​​​
.build()`

While it works fine with default loading of image. Thanks 

`val imageLoader = requireContext().imageLoader`

**Comment by colinrtwhite** [comment]
@saqibmirza2007 Are both the disk and memory caches skipped? If the disk cache is being skipped then your `cache-control` header might not allow disk caching. For the memory cache, I would [enable logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and check the logs.

**Comment by saqibmirza2007** [comment]
@colinrtwhite  I have enabled logs and by inspecting it shows that Image loads from **Disk cache and not from memory cache**. What could be the possible issue? Also the library is not loading images on Android 10 phones. I have tested on A30 Samsung

**Comment by colinrtwhite** [comment]
It's tough to say what the issue is without a test project that reproduces the issue.
