### ISSUE TITLE
ImageLoader vs ImageRequest cache policy

### ISSUE THREAD

**Issue by ardyfeb** [coil-kt/coil#618]
What's the difference setting cache policy on `ImageLoader` and `ImageRequest` ?

If we set `diskCachePolicy` to `DISABLED` on `ImageLoader` and set its `ENABLED` on `ImageRequest` does its get overriden ?

And where should we set the cache policy?

**Comment by colinrtwhite** [comment]
Yep! Setting the cache policy on the `ImageLoader` only sets the default for an `ImageRequest`. If you set the cache policy on the request, it will override what was set on the `ImageLoader`.

**Comment by ardyfeb** [comment]
Thanks @colinrtwhite
