### ISSUE TITLE
Remote Heif/heic images fail with E/HeifDecoderImpl: getSize: not supported!

### ISSUE THREAD

**Issue by sjmueller** [coil-kt/coil#619]
When trying to display a heif/heic image using (via accompanist CoilImage on Jetpack Compose) using a remote url (example https://blink-content.s3.amazonaws.com/116ecc2a-4069-4365-afbf-ebb94ddb8d6b.heic), the image is not displayed and an error appears in the console:

E/HeifDecoderImpl: getSize: not supported!
The code that throws is likely here https://android.googlesource.com/platform/frameworks/av/+/android-8.1.0_r1/media/libheif/HeifDecoderImpl.cpp#258

Is this a known limitation or is there a way to get remote heif image decoding to work without crashing?

**Comment by colinrtwhite** [comment]
@sjmueller Thanks for the report. Does the app crash for you when you load the image? I'm able to see the errors in the logs, however it doesn't crash for me.

**Comment by sjmueller** [comment]
@colinrtwhite the app does not crash, but in my Jetpack Compose app the heif images don't load either.

**Comment by colinrtwhite** [comment]
Looks like the error occurs while reading the image using `ExifInterface` so it may be an Android framework or AndroidX issue. Hopefully we can work around it.
