### ISSUE TITLE
How to get the latest image from the same url, and don't refresh the ImageView if data is not updated

### ISSUE THREAD

**Issue by taichushouwang** [coil-kt/coil#624]
Hi,

Issue :
For our project, we use a static url to request user's avatar, so I can't get any kind of metadata before I do the request. And in Coil if use cache, then it will not update the avatar in the app after avatar was changed in app or by other client.

Things I've read and tried:
I can use `memoryCachePolicy(CachePolicy.DISABLED)`  `diskCachePolicy(CachePolicy.WRITE_ONLY)` to disable the cache, but it will update the ImageView every time, I do the request. And also it will have a flashing of the change between the placeholder to the real image.

How I need to solve it:
For the better performance and user experience, I also want to use the cache of image.

So is there any way to get the image first, and then check its metadata like image last modified time or md5 to decide update ImageView or not.

Code used :
ImageView.load("http://xxx.api/user-profile/myOwnAvatar")

Coil Version: 1.1.0

Thanks a lot

**Comment by colinrtwhite** [comment]
You could create a custom `Target` that only sets the value of `onSuccess` on the `ImageView`. That way the `ImageView` won't be cleared at the start of the request.

**Comment by taichushouwang** [comment]
@colinrtwhite Thanks for your reply. As you said I create a custom `Target`, but it can't use the cache. Whenever I enter the page, it will set the ImageView, and has a flashing. And If I use your `ImageViewTarget`, it will use the cache. Even if I don't use `memoryCachePolicy(CachePolicy.DISABLED)` and `diskCachePolicy(CachePolicy.WRITE_ONLY)`, it will not update the image after I change the image in the server.

Why Why do these two Target have such inconsistent behavior, even if my `CustomTarget` inherit the `ImageViewTarget`

**Comment by taichushouwang** [comment]
I saw this document(https://coil-kt.github.io/coil/recipes/#using-a-memory-cache-key-as-a-placeholder), and I want to use the old image as the placeholder, but when I set the static url as `placeholderMemoryCacheKey`, the `cached` in `PoolableTargetDelegate.start` is still null, why? And can you tell me how to use? Thanks a lot

**Comment by colinrtwhite** [comment]
@taichushouwang For the snippet where you use `CustomViewTarget` are you creating your `ImageLoader` every time? You should [share the `ImageLoader`](https://coil-kt.github.io/coil/getting_started/#singleton) between requests since they each have their own memory caches. For `placeholderMemoryCacheKey` you'll need to pass it the memory cache key from the previous request (e.g. `imageView.metadata.memoryCacheKey`) - not the String URL.

**Comment by taichushouwang** [comment]
@colinrtwhite  Thanks for your reply.
> For the snippet where you use CustomViewTarget are you creating your ImageLoader every time? You should share the ImageLoader between requests since they each have their own memory caches.

Yes, you are right. I create ImageLoader every time. So it don't use the memory caches.

> For placeholderMemoryCacheKey you'll need to pass it the memory cache key from the previous request (e.g. imageView.metadata.memoryCacheKey) - not the String URL.

For this, if I open an activity every time, is the `placeholderMemoryCacheKey` useless for me?
