### ISSUE TITLE
How is image size determined when request is not tied to a View?

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [coil-kt/coil#625]
Hi, this looks like a great library and I'm integrating it into one of my projects.

For my use case, I need to load an image without showing it into a `View`, therefore in `ImageRequest` I am using `Target`, instead of `ViewTargert`. Like in the snippet below:

```kotlin
val request = ImageRequest.Builder(context)
    .data("https://www.example.com/image.jpg")
    .target(
        onStart = { },
        onSuccess = { drawable ->  },
        onError = { }
    )
    .build()

imageLoader.enqueue(request)
```
It is not clear to me how does Coil determine the size of the drawable in this case.

I have noticed that huge images are resized to fit in memory. But I also noticed that the size of the image changes based on the orientation of the phone, which makes me think that the size is somewhat related to UI components.

I don't think the drawable comes from the cache, since for this request I am using a new loader:

```kotlin
val disposable = ImageLoader.Builder(context)
        .availableMemoryPercentage(1.0)
        .bitmapPoolingEnabled(false)
        .precision(Precision.EXACT)
        .build()
```

Some clarity on the topic would be much appreciated!

Keep up the good work,
Pier

**Comment by colinrtwhite** [comment]
Thanks! If you don't specify a size for a request Coil will choose a `SizeResolver` using the logic [here](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/request/ImageRequest.kt#L870). In the case you specified, it would fall back to the `DisplaySizeResolver`, which will load the image using the dimensions of the display.
