### ISSUE TITLE
Picture cannot be loaded on Window

### ISSUE THREAD

**Issue by Nextweekends** [coil-kt/coil#630]
I can load the picture and display it in Activity, but it cannot be displayed on the Window

**Comment by colinrtwhite** [comment]
Do you have a stack trace?

**Comment by Nextweekends** [comment]
> Do you have a stack trace?

I didn’t find any wrong logs. I tried to set a default picture in the wrong callback, but it didn’t work.

**Comment by colinrtwhite** [comment]
I'm not able to help without at least a stack trace. You can enable logging [here](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging).

**Comment by Nextweekends** [comment]
> I'm not able to help without at least a stack trace. You can enable logging [here](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging).

I try to log  tag:RealImageLoader,priority:4,message:🏗  Cancelled

**Comment by colinrtwhite** [comment]
There's not enough information to help here. Please include a code sample that reproduces the issue.
