### ISSUE TITLE
SVG not respecting ScaleType?

### ISSUE THREAD

**Issue by taschmidt** [coil-kt/coil#634]
Sorry if this is a dumb question, I'm new to Coil (loving it so far!). I'm loading SVGs but it doesn't seem to be respecting the ScaleType for my ImageView. I'm setting it to FIT_START to left align it but it still seems to be centering horizontally.

![image](https://user-images.githubusercontent.com/228736/104343114-2caeb300-54c1-11eb-8af0-7bf5efa6e303.png)

How can I left align it?

**Comment by colinrtwhite** [comment]
Hmm does the SVG fill the view bounds of your `ImageView` (i.e. does its width equal the width of the view)? Coil uses the `ImageView.scaleType` to figure out how big it should load the SVG, but positioning inside the `ImageView` is up to the `ImageView`.

**Comment by taschmidt** [comment]
It doesn't appear to fill it since the aspect ratio appears to be maintained. When I was using Glide I had to add this to the SVG (which I believe was the underlying AndroidSVG object):

```
svg.documentPreserveAspectRatio = PreserveAspectRatio.START
```

Do I have access to that with Coil (without duplicating a bunch of code)?

**Comment by colinrtwhite** [comment]
It's not possible to access the `SVG` object directly in Coil. Can you post the SVG so I can test locally?

**Comment by taschmidt** [comment]
Sure...

[my-ride.svg.zip](https://github.com/coil-kt/coil/files/5810759/my-ride.svg.zip)

**Comment by taschmidt** [comment]
@colinrtwhite Any update?

**Comment by colinrtwhite** [comment]
@taschmidt Your SVG has a width and height of `100%`. It's not possible for Coil determine the SVG's aspect ratio with a dynamic value so it loads the image at the `ImageView`'s size. Changing the svg to have a fixed width/height (you can copy the view box's values) should fix the issue.
