### ISSUE TITLE
`ImageRequest.data()` accepts nullable values, but the subsequent load request fails with `cannot set the request's data to null.`

### ISSUE THREAD

**Issue by alexanderbezverhni** [coil-kt/coil#635]
**Describe the bug**
`ImageRequest.data()` accepts nullable values. Method description doesn't state what the expected behavior should be in this case, so it may be likely interpreted by a developer as a deliberate fail request which should eventually show `error` placeholder. Instead, image load request internals fail with `Interceptor com.example.Interceptor cannot set the request's data to null` and none image is set to the `ImageView`.

**Expected behavior**
Fall back to `error` placeholder when `null` value is passed to `ImageRequest.data()`.

**To Reproduce**
Pass `null` value to `ImageRequest.data()`

**Version**
`1.1.0`

**Comment by colinrtwhite** [comment]
Debugged privately - ended up being an error unrelated to Coil.
