### ISSUE TITLE
Allow fetcher to failover to next available fetcher, or make default fetchers accessible

### ISSUE THREAD

**Issue by timusus** [coil-kt/coil#637]
**Is your feature request related to a problem? Please describe.**
For my usecase, I have multiple custom fetchers registered against a given type. If the first fetcher fails to yield a result, I'd like Coil to then try the next fetcher. If that fetcher fails, then I'd like to invoke the mapper, to make a http request.

Unfortunately, fetchers and mappers aren't invoked according to the order in which they were registered, and a failing fetcher does not then cause the next fetcher or mapper to be invoked.

**Describe the solution you'd like**
1. I'd like to have Coil attempt successive fetchers, in the order they're registered in. The same goes for the mapper - if a fetcher for a type is registered before a mapper for the same type, then I'd like the fetcher to be attempted before the mapper is invoked.

2. In the meantime, I can write my own 'aggregate' fetcher and implement this behaviour myself.  However, I can't easily delegate to the existing `HttpFetcher`, as it is internal, as are its concrete implementations. I could map my data to a url with a mapper, but then the custom fetchers won't be invoked. It would be helpful to be able to retrieve fetchers from the registry, by type, so they can be used as delegates in custom fetchers.

**Additional context**
The problem I have is with attempting to load artwork for audio files. The first fetcher searches for images in directories. The second searches the metadata of the file itself. Then, if that fails, I make a http request to retrieve the artwork from an online source.

**Comment by colinrtwhite** [comment]
Totally agree that there should be a better way to fail over to the next fetcher/decoder. I have some ideas about how to handle this better, but they'll require an API change and a major version bump. This is definitely a top priority to improve on in the next major version, though!

**Comment by colinrtwhite** [comment]
This is supported in the 2.x alphas (by returning `null`) and will soon be supported in a stable release.
