### ISSUE TITLE
scaleType="centerInside" working inproperly. Width and Height are set to fixed value.

### ISSUE THREAD

**Issue by ttojiyev** [coil-kt/coil#641]
I am using coil in the adapter. ImageView properties:

```
<ImageView
                    android:id="@+id/imageIcon"
                    android:layout_width="90dp"
                    android:layout_height="36dp"
                    android:scaleType="centerInside"
                    tools:src="@drawable/ic_communal_gas" />
```
I also added `android:adjustViewBounds="true(false)"`

`centerInside` works with all server images. Except one.
I've even tried scaling image programmatically in the adapter before loading image. But without success.
I am uploading the result screenshot and the "foreign matter image"

**Original image:**
![PayNet_1155](https://user-images.githubusercontent.com/23132933/105028694-2bf2bf80-5a73-11eb-80f3-82a83c5a9fff.png)

**Screenshot from result:**
![photo_2021-01-19_16-26-47](https://user-images.githubusercontent.com/23132933/105028720-33b26400-5a73-11eb-99a1-990fccf035b6.jpg)

**Comment by colinrtwhite** [comment]
Hmm it's tough for me to say what's going wrong, but I suspect it's related to `adjustViewBounds`. Can you attach a small code sample that reproduces the issue?

**Comment by ttojiyev** [comment]
I tried to set `adjustViewBounds`, first to `true` then to `false`. It didn't help.
I can share the part of my code. If you need some other parts say, I will also share.

```
import coil.load
...
class MyUtilityAdapter(val data: ArrayList<MyUtilityData?>) :
    RecyclerView.Adapter<MyUtilityAdapter.BottomSheetViewHolder>() {
...
fun onBind(d: MyUtilityData) {
            itemView.apply {
                ...
                imageIcon.scaleType = ImageView.ScaleType.CENTER_INSIDE  //added here too because thought it not updating
                imageIcon.load(d.logoUrl)
                ...
        }
}
```

**Comment by colinrtwhite** [comment]
@ttojiyev I'd need a small sample project to debug this issue.

**Comment by ttojiyev** [comment]
@colinrtwhite I fixed it after long day. Images of Bell and Gas were included to the `LinearLayout `with `orientation ``vertical`. I changed it to `horizontal `and cropping was immediately fixed. Thank you for your feedback )
