### ISSUE TITLE
Coil doesn't load URLs with query parameters

### ISSUE THREAD

**Issue by alirezanazari** [coil-kt/coil#649]
**Describe the bug**
I try to load images which protected by signatures and token to show them by coil , it seems  query parameters removed from URL and this library doesn't load them. We used headers and setParameter() methods but doesn't work. 

Sample URL:
http://test.com/images/svg/xxxx.svg?SignedHeaders=host&Signature=bd1628825bb8e67a56edb9b

**Version**
Android 9, 10
Coil 1.1.1

**Comment by imherrera** [comment]
Try logging out the url with okHttp interceptor

**Comment by alirezanazari** [comment]
@imherrera actually downloaded and URL is correct but Coil doesn't load the image : 
Note : I checked and Glide loaded this URL.

```

 <-- 200 OK http://1.1.1.1/images/svg/image.svg?mz-Signature=68e87d4a08414aa0307abc1a38b1c84bae63bb9564e13 (109ms)
 Accept-Ranges: bytes
 Content-Length: 2806
 Content-Security-Policy: block-all-
 Content-Type: application/octet-stream
 ETag: "c6d8cb78952c7682b32ff0c"
 Last-Modified: Sat, 30 Jan 2021 16:24:25 GMT
 Server: MinIO/RELEASE.2020-50Z
 Vary: Origin
 X-Amz-Request-Id: 165FA684AEE1
 X-Xss-Protection: 1; mode=block
 Date: Mon, 01 Feb 2021 14:38:00 GMT
 <?xml version="1.0" encoding="UTF-8"?>
 <svg width="44px" height="44px" viewBox="0 0 44 44" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
     <title>ACB3B96C-FB03-4F91-95A6-022E76CD7108</title>
     <defs>
         <linearGradient x1="0%" y1="50%" x2="100%" y2="50%" id="linearGradient-1">
             <stop stop-color="#9E2373" offset="0%"></stop>
             <stop stop-color="#E8CAE1" offset="100%"></stop>
         </linearGradient>
     </defs>
     <g id="Payment" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
         <g id="Sim-List" transform="translate(-315.000000, -574.000000)" fill-rule="nonzero">
             <g id="Sim-Operator" transform="translate(0.000000, 306.000000)">
                 <g id="Rightell" transform="translate(0.000000, 258.000000)">
                     <g id="Icon" transform="translate(315.000000, 10.000000)">
                         <g id="rightel-logo-1" transform="translate(2.000000, 2.000000)">
                             <path d="M17.2273288,5.04288195 C8.64950978,5.15024792 2.16052802,12.2490505 2.57734309,20.5210662 C2.97458973,28.4024574 9.57063984,34.7223173 17.7147539,34.4855615 C25.9554453,34.2461272 32.3543973,27.2886192 31.9779096,19.0854278 C31.6267195,11.4319382 25.3326036,5.07234621 17.22718,5.04288195 L17.2273288,5.04288195 Z M39.9999256,21.2492649 C39.9026043,21.9067792 39.8142859,22.5658559 39.7064735,23.2216588 C38.4400313,30.9240323 32.2768677,37.4224634 24.6052978,39.0322833 C17.8893073,40.4415825 11.9123786,38.8600364 6.82808299,34.2389844 C3.37771434,31.1029755 1.36112404,27.1523842 0.70227052,22.5281327 C-0.470719406,14.2957003 3.62280338,6.26572302 10.991695,2.32264651 C18.5809733,-1.73821262 28.0782855,-0.33099673 34.1650355,5.75195864 C37.3227705,8.90761032 39.1991079,12.7003894 39.8374258,17.1125874 C39.8933781,17.4991942 39.9459078,17.8862474 39.9999256,18.2730774 L39.9999256,21.2492649 Z" id="Shape" fill="#9B2776"></path>
                             <path d="M19.2293358,30.6262647 C25.1057437,30.6063987 30.0884769,25.9651085 30.0837185,19.768686 C30.0788043,13.5686921 25.0985265,8.9549317 19.2879667,8.92967935 C13.3859635,8.90426211 8.40747133,13.598454 8.39457447,19.7475551 C8.38180171,25.8979955 13.3134933,30.5930802 19.2293358,30.6262647 M17.2811978,5.45969702 C25.1678716,5.40560481 31.6721808,11.9408663 31.6052909,19.9286561 C31.5397404,27.7590056 25.1245681,34.1266333 17.1608854,34.0932088 C9.28961332,34.0597435 2.85063152,27.6089313 2.95159868,19.5817814 C3.05070573,11.6900481 9.5240625,5.41155719 17.2811978,5.45977142" id="Shape" fill="url(#linearGradient-1)"></path>
                         </g>
                     </g>
                 </g>
             </g>
         </g>
     </g>
 </svg>
 <-- END HTTP (2806-byte body)
```

**Comment by imherrera** [comment]
Have you added the  `SvgDecoder` component? 
To load svgs with coil you need add this dependency `io.coil-kt:coil-svg:1.1.1`  and register the component like so:
`val imageLoader = ImageLoader.Builder(context)
    .componentRegistry {
        add(SvgDecoder(context))
    }
    .build()`

or if you are using the singleton component to load your images you can do it like this:

`class MyApp : Application(), ImageLoaderFactory {

    override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(context)
            .componentRegistry {
                add(SvgDecoder(context))
            }
            .build()

    }
    
}`

**Comment by alirezanazari** [comment]
@imherrera i did it and it works before migrate  to Minio (add those parameters to URL)
it seems can't decode the svg file and return this error:

> E/RealImageLoader: java.lang.IllegalStateException: BitmapFactory returned a null Bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network or disk) as it's not encoded as a valid image format.

**Comment by imherrera** [comment]
The problem is your http response body has this `Content-Type: application/octet-stream` which basically tells coil that the response is a binary, instead the `Content-Type` should be `Content-Type: image/svg+xml` as per docs: 

> The ImageLoader will automatically detect and decode any SVGs if the request's MIME type is image/svg+xml. The MIME type is inferred using the HTTP content-type header, a URI's suffix, or a file's extension. If you need to force a specific request to use the SvgDecoder, you can set the Fetcher explicitly for the request.

**Comment by colinrtwhite** [comment]
@imherrera is right. Your SVG needs to needs to have the content type `image/svg+xml` or it won't be detected automatically. You can force the image request to use the SVG decoder by setting `decoder(SvgDecoder(context))` on your request.

**Comment by alirezanazari** [comment]
@colinrtwhite @imherrera  yes you're right and Backend side fixed it and it's working now.
Thank you.
