### ISSUE TITLE
listener with error and drawable

### ISSUE THREAD

**Issue by BugsBunnyBR** [coil-kt/coil#652]
Today, if I want to have access to what error happened during loading the image or the success drawable I need to do something like this
``` kotlin
val target = object : ImageViewTarget(imageViewTarget.view) {
                override fun onSuccess(result: Drawable) {
                    super.onSuccess(result)
                    listener.onSuccess(result)
                }
            }
coilBuilder.target(target)
    .listener(
        onError = { _, error -> listener.onError(error) }
    )
```

Can't we have just set the listener and have the drawable and the exception in the listener?

**Comment by colinrtwhite** [comment]
Can you add some more info on your use case. Why does the listener need access to the error drawable instead of create a custom `Target`? The current design is intended to keep things simple and keep view/drawable access isolated to the `Target`.

**Comment by BugsBunnyBR** [comment]
Sorry, I think I didn't express myself well.
Look at my sample above.

If I want access to the drawable, I need to override the target.
If I want access to the cause of the error (exception), I need to pass a listener.

To me, it seems like if we had to callbacks that run in different moments. The target callbacks and the listener callbacks. This is confusing.

To have access to the drawable that was set in the target in the success loading of an image, we need to override the target.onSuccess. Why is it not available in the listener.onSuccess ? (I am not sure, but also, it seems that listener.onSuccess runs before coil sets the image in the ImageView, so I can't get the Drawable/bitmap from the ImageView)

Why I need access to the drawable in the onSuccess? Because of ken burns effect for instance. I am migrating a codebase to coil there are a lot of code that does not fit perfectly in coil so I need wrap it.

Also, What if I want to download the image without setting a target? We need to set a target to have access to the image! When, in my mind, all I wanted is a callback to when the image is downloaded.

 
 Well, these are the the pain points I found while migrating our code base to coil. I kinda understand that you wanted to keep the "target setting logic" and the "caching/error handling logic" in different places.

**Comment by colinrtwhite** [comment]
Hmm I don't think it's a good idea to combine target + listener. Changing it at would require a breaking API change, which is not possible. You can always create a custom adapter + extension method that combines the two for your use case.

**Comment by BugsBunnyBR** [comment]
Yeah, that can be a breaking change, but you could also just add a new type of listener and it wouldn't be.
In the synchronous call the ImageResult we have access to all data. It would be great to be possible to attach a `resultListener` to the request builder that is called after all other work is done (setting the image in the imageview target, so example).
