### ISSUE TITLE
ScaleType delay takes effect

### ISSUE THREAD

**Issue by Moredistant** [coil-kt/coil#658]
When I set imageView.scaleType=ImageView.ScaleType.FIT_XY, the size of the picture is not immediately resized

And size (100x100) doesn't work in ImageRequest.Builder.

![QQ20210206-211930](https://user-images.githubusercontent.com/18004892/107119986-db2df400-68c5-11eb-8c44-4b5a9aa00ea3.png)
![QQ20210206-211957](https://user-images.githubusercontent.com/18004892/107119987-de28e480-68c5-11eb-9e3f-e9c762253eef.png)

I need to stretch the image to the size of imageview and take effect immediately. What should I do?
There is no such problem with using Glide.

**Comment by colinrtwhite** [comment]
Do you want the image to be stretched? Is the second image the desired result? Setting `ScaleType.FIT_XY` should change the scaling on your image instantly. This process is handled by `ImageView` - not Coil.

**Comment by Moredistant** [comment]
Yes, I need to stretch the image. So how do I get coil to resize before display?

**Comment by colinrtwhite** [comment]
@Moredistant Coil does not stretch the image, but as you mentioned `ImageView.ScaleType.FIT_XY` should stretch the image properly. I don't believe Glide stretches the image while decoding either so it should be the same process.

**Comment by Moredistant** [comment]
![QQ20210208-105854](https://user-images.githubusercontent.com/18004892/107171065-d455cd00-69fc-11eb-991b-0edc7459b11b.png)
![QQ20210208-105900](https://user-images.githubusercontent.com/18004892/107171067-d586fa00-69fc-11eb-9cd0-434ca803d601.png)
![QQ20210208-105908](https://user-images.githubusercontent.com/18004892/107171072-d750bd80-69fc-11eb-8b09-ae65766776aa.png)

**Comment by Moredistant** [comment]
As shown above, it takes a while for coil to stretch
Sorry, my English is not good. This is machine translation. I hope you can understand what it means.

**Comment by Moredistant** [comment]
![QQ20210208-110351](https://user-images.githubusercontent.com/18004892/107171274-59d97d00-69fd-11eb-8b90-12fe27feea54.png)

**Comment by Moredistant** [comment]
This is the source code: https://drive.google.com/file/d/1MW8NXMOpx5tLEFJKCxsttPUyEg6wY5u5/view?usp=sharing

**Comment by Moredistant** [comment]
I found out why, Just turn off crossfade.

Thank you for your reply.
