### ISSUE TITLE
Consider updating Transformation docs to explicitly say that they are cached and reused based on the key

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [coil-kt/coil#660]
Maybe it's me, or I just missed it, but when using my own `Transformation` it wasn't obvious that once set, older instances get reused if the key is the same.

I now noticed that the doc of [key](https://coil-kt.github.io/coil/api/coil-base/coil.transform/-transformation/key/) do hint at that, but maybe consider making it more explicit in `Trasnformation` [kdoc](https://coil-kt.github.io/coil/api/coil-base/coil.transform/-transformation/)?

**Comment by colinrtwhite** [comment]
:+1: Good point. Just updated the docs.
