### ISSUE TITLE
How to prefetch images in reyclerview on scroll?

### ISSUE THREAD

**Issue by raghunandankavi2010** [coil-kt/coil#665]
Glide provides something like recyclerview integration https://bumptech.github.io/glide/int/recyclerview.html where we can preload images on scroll.

Is there something similar to this in Coil?. I have read that you can preload images.  Can we use the same to prefetch items on recyclerview scroll?.

**Comment by colinrtwhite** [comment]
There isn't any out of the box RecyclerView preloading integration for Coil, however you could use the same [listener scroll method as Glide](https://github.com/bumptech/glide/blob/master/integration/recyclerview/src/main/java/com/bumptech/glide/integration/recyclerview/RecyclerToListViewScrollListener.java) and sub in Glide -> Coil.

**Comment by raghunandankavi2010** [comment]
Hmmm. we should use https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/ListPreloader.java. If you look at the code preloadItem is called for increasing and decreasing. I have used Coil in place of glide. Is there a way to check if image in already in diskcache before making a network request. I feel images are getting downloaded to disk again.

Right now i am using
   
       ImageRequest imageRequest = preloadModelProvider.getPreloadRequestBuilder(item);
        if (imageRequest == null) {
            return;
        }
        Disposable disposable = Coil.enqueue(imageRequest);
        preloadTargetQueue.add(disposable); 

in place of glide. 

In case of glide for loading
 
          preloadRequestBuilder.into(preloadTargetQueue.next(dimensions[0], dimensions[1])); 

and then cancelling

      private void cancelAll() {
        for (int i = 0; i < preloadTargetQueue.queue.size(); i++) {
          requestManager.clear(preloadTargetQueue.next(0, 0));
       }
     }

Am i missing anything or is my approach wrong?
