### ISSUE TITLE
Inconsistent loading of drawables when switching between screens

### ISSUE THREAD

**Issue by itsandreramon** [coil-kt/coil#672]
When navigating between fragments (Jetpack Navigation), Coil reloads the images in an inconsistent way, which causes flakiness as you can see in the screenshots. (taken after navigating back and forth)

**Expected behavior**
The same images should load in the same way every time.

**To Reproduce**
This is the way I am currently loading my images:

```kotlin
fun ImageView.setImageFromContact(contactId: Long, contentResolver: ContentResolver) {
  val inputStream = ...
  val placeholder = ContextCompat.getDrawable(context, R.drawable.ic_account)

  if (inputStream != null) {
    val contactImage = BitmapFactory.decodeStream(inputStream)

    load(contactImage) {
      placeholder(placeholder)
      crossfade(true)
      transformations(CircleCropTransformation())
    }
  } else {
    load(placeholder) {
      crossfade(true)
      transformations(CircleCropTransformation())
    }
  }
}
```

**Logs/Screenshots**
<img src="https://i.imgur.com/HGyB6wi.png"/>
<img src="https://i.imgur.com/XY2SDbO.png"/>

**Version**
Coil 1.1.1 Android R Google Pixel 4 latest updates

**Comment by imherrera** [comment]
You should be getting the placeholder drawable with `val placeholder = ContextCompat.getDrawable(context, R.drawable.ic_account)`, and then pass it to `load(placeholder)`, also i recommend you declare `placeholder`  inside the else clausule you dont want the overhead of getting the `placeholder` regardless of if your `inputstream` is null or not

**Comment by itsandreramon** [comment]
yea I am actually loading the drawable this way, just forget to correct because I did not want to include the tinting in the sample. But thanks for the advice with the overhead!

**Comment by imherrera** [comment]
have you tried with `crossfade(false)` ?

**Comment by itsandreramon** [comment]
Still happening but far less often

**Comment by colinrtwhite** [comment]
@itsandreramon Were you seeing this on an emulator or a real device? The emulator can sometimes cause graphical glitches.

I tried reproducing the scenario in the sample app, but wasn't able to. Do you have a small sample project I could take a look at?
