### ISSUE TITLE
ImageDecoderDecoder createTempFile exception

### ISSUE THREAD

**Issue by randrievskiy** [coil-kt/coil#675]
I have an issue ьostly on Samsung devices: `FileNotFoundException` while creating tempFile here:
`ImageDecoderDecoder.decode().. File.createTempFile("tmp", null, null)`

When it happens GIF is freezed at 1st frame

Possible(works for me) fix is to pass as a 3rd parameter specific directory(e.g. `cacheDir.path/temp`) instead of passing null and check it before
```
if (!tempDirectory.exists()) {
     tempDirectory.mkdir()
}
```

Coil version is 1.1.1

**Comment by colinrtwhite** [comment]
Thanks for the report. Which devices exactly were you seeing this exception on?

**Comment by randrievskiy** [comment]
Sorry for the late response. 
Samsung Galaxy A10s Android 10
Samsung Galaxy M31 Android 10
Samsung Galaxy A30s Android 10
