### ISSUE TITLE
Didn't Load Image With Coil - Kotlin

### ISSUE THREAD

**Issue by halilozel1903** [coil-kt/coil#681]
Hello everyone,

I'm using Coil in Android App but Coil didn't load.

`implementation "io.coil-kt:coil:0.11.0"
`

Then add internet permission in Manifest like this:

`<uses-permission android:name="android.permission.INTERNET" />`

BUT if I'm trying load it from url. This didn't work

`image.load("https://images.bjk.com.tr/media/taraftar_media/taraftar-44572235d1010e0.jpg")`

I don't understand. What is the problem?  Can you help me please?

**Comment by jacobceles** [comment]
@halilozel1903 
1. Is there a reason you are using the 0.11.0 version? The latest is 1.1.1 so I recommend upgrading to that using:
`implementation("io.coil-kt:coil:1.1.1")`
2. As long as `image` is a reference to the ImageView, `image.load("https://images.bjk.com.tr/media/taraftar_media/taraftar-44572235d1010e0.jpg")` will work just fine.

**Comment by halilozel1903** [comment]
Okay. I upgraded new version. It's worked. Thanks 👍🏻 

![Screenshot_1614667420](https://user-images.githubusercontent.com/22895813/109609614-9f8cef80-7b3c-11eb-91a4-aa119ce1b33e.png)
