### ISSUE TITLE
How can I view different photo?

### ISSUE THREAD

**Issue by halilozel1903** [coil-kt/coil#684]
Hi,

I want to show photo from this url.

https://ebanking.alrayan.com/WebApplication.UI/CampaignBannerDisplay.aspx?ImageID=288

The extension for this is not .png or .jpg. 

This way didn't work

`image.load("https://ebanking.alrayan.com/WebApplication.UI/CampaignBannerDisplay.aspx?ImageID=288")`

How can I do that?

**Comment by colinrtwhite** [comment]
Your URL does not link to a valid image format. If you run into issues in the future, you can [enable debugging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) to print out any errors.
