### ISSUE TITLE
gif extension does not load gif images that stored in various folders correctly 

### ISSUE THREAD

**Issue by sobhan-jabbari** [coil-kt/coil#691]
when any gif stored in "drawable" folder and another stored in "drawable-ldrtl" and locale is any right to left language, then gif extension load from "drawable" folder. but it was expected to be loaded from the "drawable-ldrtl" folder

**Comment by cemore2048** [comment]
@sobhan-jabbari any chance you might be able to post how you're loading the gifs? I couldn't reproduce by forcing rtl in the debug settings. Have two different gifs under the same name, one in 'drawable' and the other in 'drawable-ldltr'. Looks like it's loading correctly.

<img src="https://user-images.githubusercontent.com/4750618/126049369-7de7b120-a3ed-4601-b520-0c0bc5116de4.png" width="270">

This was left to right
<img src="https://user-images.githubusercontent.com/4750618/126049369-7de7b120-a3ed-4601-b520-0c0bc5116de4.png" width="270">

This was right to left
<img src=https://user-images.githubusercontent.com/4750618/126049373-cba30882-da50-4b04-ab07-a9dc17feddf4.png" width="270">

**Comment by colinrtwhite** [comment]
Going to close this out since it seems like this is fixed.
