### ISSUE TITLE
Fetcher is called more often than expected

### ISSUE THREAD

**Issue by MFlisar** [coil-kt/coil#692]
I use coil in a launcher application to show all installed apps icons. What I see is that every now and then coil refetches images (although imo it should only load them from memory cache).

What I checked is following:

- make sure memory cache did not reach its limits (it's never higher than ~30%)
- make sure all images are converted to cacheable bitmaps
- make sure my app was not restarted

**Logs**

Mostly when scrolling my apps lists I do see following:

```
// One line like following for each app (the line comes from the custom fetcher):
ImageManager - fetch ComponentInfo{...}
// Many lines like following during scrolling up/down (the line comes from my listener)
Request: ComponentInfo{...} | metadata: MEMORY_CACHE | key: Complex(...)
```

**Question**

Every now and then I come back to my launcher and I see the log line from the fetcher again although I've never hit the memory limits nor did my app restart (it's set as default launcher and so it will always run and I'm sure it did not crash in the meantime).

Is my understanding wrong that as long as I do not exceed the memory limit (`imageLoader.memoryCache.maxSize`) my loaded images should stay in the memory cache and the fetcher should not be executed again?

My observations show that the memory cache is cleared (I check the `imageLoader.memoryCache.size` regularly) but how can this be if it never reaches it maximum? My device is not running at it's limit neither...

**Code**

Here's my custom fetchers code:

```kotlin
override suspend fun fetch(
        pool: BitmapPool,
        data: ComponentName,
        size: coil.size.Size,
        options: Options
    ): FetchResult {

        val ai = AppsManager.loadActivityInfo(context, data)
//        val ri = AppsManager.loadResolveInfo(context, data)

        val drawable = ai?.loadIcon(context.packageManager)
            ?: throw ImageException.AppNotFoundException(data.packageName)

        L.d { "ImageManager - fetch $data" }

        // force bitmap drawable to force caching!
        val bitmapDrawable = if (drawable is BitmapDrawable) drawable else drawable.toBitmap().toDrawable(context.resources)
        return DrawableResult(
            drawable = bitmapDrawable,
            isSampled = false,
            dataSource = DataSource.MEMORY
        )
    }
```

And here's my listener code:

```kotlin
private val listener = object : ImageRequest.Listener {
        override fun onError(request: ImageRequest, throwable: Throwable) {
            L.tag("COIL PROBLEM")
                .e { "Request: ${request.data} | throwable: ${throwable.message}" }
            L.e(throwable)
            if (throwable !is ImageException) {
                LogManager.showUnexpectedErrorNotification()
            }
        }

        override fun onSuccess(request: ImageRequest, metadata: ImageResult.Metadata) {
            L.d { "Request: ${request.data} | metadata: ${metadata.dataSource} | key: ${metadata.memoryCacheKey}" }
        }
    }
```

**Comment by colinrtwhite** [comment]
It sounds like it's being cleared due to system calls to `ComponentCallbacks2.onTrimMemory` or `ComponentCallbacks2.onLowMemory`. You can verify this is the case by using [`DebugLogger(Log.VERBOSE)`](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging).

**Comment by MFlisar** [comment]
What should I look out for especially? My first tests show following (I already have a question regarding this) but this did not have the cache reset effect yet.

**Log 1**

> I/RealImageLoader: 🧠 Successful (MEMORY_CACHE) - ComponentInfo{...}
> D/[ImageManager$listener:33 onSuccess]: Request: ComponentInfo{...} | metadata: MEMORY_CACHE | key: Complex(base=..., transformations=[], size=null, parameters={}) (ImageManager.kt:33)
> I/RealImageLoader: 🧠 Successful (MEMORY_CACHE) - ComponentInfo{...}
> D/[ImageManager$listener:33 onSuccess]: Request: ComponentInfo{...} | metadata: MEMORY_CACHE | key: Complex(base=..., transformations=[], size=null, parameters={}) (ImageManager.kt:33)
> I/RealImageLoader: 🧠 Successful (MEMORY_CACHE) - ComponentInfo{...}
> D/[ImageManager$listener:33 onSuccess]: Request: ComponentInfo{...} | metadata: MEMORY_CACHE | key: Complex(base=..., transformations=[], size=null, parameters={}) (ImageManager.kt:33)
> I/RealImageLoader: 🧠 Successful (MEMORY_CACHE) - ComponentInfo{...}
> D/[ImageManager$listener:33 onSuccess]: Request: ComponentInfo{...} | metadata: MEMORY_CACHE | key: Complex(base=..., transformations=[], size=null, parameters={}) (ImageManager.kt:33)
> I/RealImageLoader: 🏗  Cancelled - ComponentInfo{...}
> D/[AppIconFetcher:39 fetch]: ImageManager - fetch ComponentInfo{...} (AppIconFetcher.kt:39)
> I/RealImageLoader: 🧠 Successful (MEMORY) - ComponentInfo{...}
> D/[ImageManager$listener:33 onSuccess]: Request: ComponentInfo{...} | metadata: MEMORY | key: Complex(base=..., transformations=[], size=null, parameters={}) (ImageManager.kt:33)

This log comes from a recycler view - I do call "view.clear()" in the `RecyclerView.ViewHolder::onViewRecycled` callback => you can see a Cancelled log line above followed by a fetch (although this image has been loaded already and cached) => is the clear call wrong? This should not clear the cached image but only cancel a running request, shouldn't it?

**Log 2**

> V/RealWeakMemoryCache: trimMemory, level=20
> V/RealBitmapPool: trimMemory, level=20

I see a lot of above log lines - I assume coil does not react to those flags, does it? Level 20 is the `TRIM_MEMORY_UI_HIDDEN` flag which makes sense but for a launcher (that is set as default launcher) this does not mean that any memory resources should be released.

**Comment by MFlisar** [comment]
Finally you showed me the right direction - the cache is cleared if the system calls trimMemory with the flag 80 (which is `TRIM_MEMORY_COMPLETE`).

In this case I would say that all other apps in memory should free up memory and not the launcher - can I somehow integrate this logic in coil?

It also seems weird that the system calls this callback on my device so early - "only" 2.5GiB of 3.5GiB are used (I do check this with `ActivityManager.MemoryInfo()`)...

**Comment by colinrtwhite** [comment]
@MFlisar It's not possible to not trim the memory cache when `onTrimMemory` is called. This is partly because failing to free extra memory when it's called will result in your app being killed faster. I believe launchers are higher priority to stay in memory vs. other apps, however they can still be killed. That said, if you can find an official reference that says launchers should not respond to these events please let me know.

Any images that are still visible won't be freed as they'll still be present in the `WeakMemoryCache`. Only images that you don't have a strong reference are eligible to be freed.

**Comment by MFlisar** [comment]
Do you have experience with `onTrimMemory`? Is it normal that this is called so early? E.g. my phone uses 2GB of RAM after reboot immediately and 2.5GB when I use it normally and in this state it already calls the `onTrimMemory` - it has 3.5GB in total. I must check if this is something with the integrated optimisation in my samsung phone... Still, I would prefer if I could tune the cache trimming because if the device has that less memory there are bigger problems anyways - for me it would be nice to only trim and free up memory manually or if the `onTrimMemory` is called with the low or critical memory flag. But I understand that this may be too special for the library. I can only use a custom disc cache as far as I can see - I can't plug in a custom memory cache, can I?

But there is still the second part of my problem - the log line with `RealImageLoader: 🏗 Cancelled - ComponentInfo{...}` which comes regularly when scrolling up and down in a `RecyclerView` which has the effect that the corresponding image is refetched - any thoughts on that? I see this without `onTrimMemory` calls in between...

**Comment by colinrtwhite** [comment]
@MFlisar This is likely due to the request being cancelled due to scrolling the item off screen while it's loading or [this RecyclerView behaviour](https://github.com/coil-kt/coil/issues/542).

**Comment by MFlisar** [comment]
That's clear so far, I know that cancelling the request does make sense in this case - but why is the already cached image removed from the in memory cache after the request is cancelled?

**Comment by colinrtwhite** [comment]
@MFlisar Cancelling a request shouldn't remove the image from the memory cache.

**Comment by colinrtwhite** [comment]
Going to close this out as the initial question has been resolved.
