### ISSUE TITLE
希望提供coil 类似 Glide pauseRequests resumeRequests的方法

### ISSUE THREAD

**Issue by ewgcat** [coil-kt/coil#701]
RecyclerView+coil加载很多大图，快速滑动卡顿解决方案,需要滑动是禁止加载，未滑动的时候加载的api

**Comment by ewgcat** [comment]
> Sorry, but I can only help in English.

issue  RecyclerView+coil loads many large images to solve the problem of fast sliding,please add two method like glide
pauseRequests() and resumeRequests()
`
class AutoLoadRecyclerView @JvmOverloads constructor(
    context: Context?,
    attrs: AttributeSet? = null,
    defStyle: Int = 0
) : RecyclerView(context!!, attrs, defStyle) {
    private fun init() {
        addOnScrollListener(ImageAutoLoadScrollListener())
    }

    inner class ImageAutoLoadScrollListener :
        OnScrollListener() {
        override fun onScrolled(
            recyclerView: RecyclerView,
            dx: Int,
            dy: Int
        ) {
            super.onScrolled(recyclerView, dx, dy)
        }

        override fun onScrollStateChanged(
            recyclerView: RecyclerView,
            newState: Int
        ) {
            super.onScrollStateChanged(recyclerView, newState)
            when (newState) {
                SCROLL_STATE_IDLE ->
                    try {
                        if (context != null) Glide.with(context).resumeRequests()
                    } catch (e: Exception) {
                        e.printStackTrace()
                    }
                SCROLL_STATE_DRAGGING ->
                    try {
                        if (context != null) Glide.with(context).pauseRequests()
                    } catch (e: Exception) {
                        e.printStackTrace()
                    }
                SCROLL_STATE_SETTLING ->
                    try {
                        if (context != null) Glide.with(context).pauseRequests()
                    } catch (e: Exception) {
                        e.printStackTrace()
                    }
            }
        }
    }

    init {
        init()
    }
}`

**Comment by colinrtwhite** [comment]
Check out [this thread](https://github.com/coil-kt/coil/issues/580) for how to pause/resume requests with Coil.
