### ISSUE TITLE
How to get the disk cache file absolute path?

### ISSUE THREAD

**Issue by rockyoung** [coil-kt/coil#702]
As the [doc](https://coil-kt.github.io/coil/getting_started/#preloading) say we can preload a network image only into the disk cache, but how can we get the disk cache file absolute path?

Think about the case I'm facing: in my app, we have a webview to show some html content, and the img element inside does not using the 'src' attribute to fetch network image directly, we want use coil to preload all network images and setup the src from local disk cache files.

**Comment by colinrtwhite** [comment]
Coil uses the OkHttp `Cache` object as its disk cache. You can get the default `Cache` that Coil creates using `CoilUtils.createDefaultCache` then get its path using `cache.directory.path`.

**Comment by rockyoung** [comment]
thanks for the reply, it looks like the only way is to manually initialize the `ImageLoader` (though it has no difference compared to the default implementation) and save the reference to the `Cache` returned by `CoilUtils.createDefaultCache` at that time.
