### ISSUE TITLE
Hope to provide support for "wepb" dynamic map

### ISSUE THREAD

**Issue by lhm0603** [coil-kt/coil#704]
Hope to provide support for "wepb" dynamic map

Just like “Glide”, it has “GlideWebpDecoder” support

https://github.com/zjupure/GlideWebpDecoder

**Comment by colinrtwhite** [comment]
Coil currently only supports animated WebP on API 28+ (that's when the system support arrives). You'll need to import the `coil-gif` module to use it. Non-animated WebP support is completely supported on API 19+.
