### ISSUE TITLE
Reset single memory/disc cache entry

### ISSUE THREAD

**Issue by MFlisar** [coil-kt/coil#706]
Is there a way to remove all cache entries (memory + disc) for a given reqeust?

E.g. I have following:

```kotlin
val data = ... // data is a valid coil model that can be loaded via `ImageRequest.Builder.data`

// remove all related cache entries from memory and disc cache
// could look like following
context.imageLoader.memoryCache.removeAll(data)
val cache = CoilUtils.createDefaultCache(context)
cache.removeAll(data)
```

Is that somehow possible?

**Comment by colinrtwhite** [comment]
You can clear values from the memory cache using [`MemoryCache.remove`](https://coil-kt.github.io/coil/getting_started/#memory-cache) with the `MemoryCache.Key` of the request. You can't clear memory cache entries using only the request's data.

It's not officially supported, but you can clear disk cache entries by manually clearing the file in `Cache`. Something like:

```kotlin
val cache = CoilUtils.createDefaultCache(context)
val file = File(cache.directory, "${Cache.key(data.toHttpUrl())}.1")
file.delete()
```

Keep an eye on [this ticket](https://github.com/coil-kt/coil/issues/100) for better support for this in the future.
