### ISSUE TITLE
One drawable to rule them all

### ISSUE THREAD

**Issue by xanscale** [coil-kt/coil#709]
actually to cover placeholder, fallback and error with the same drawable we need to do this
```
imageView.load("url") {
    placeholder(R.drawable.icon)
    fallback(R.drawable.icon)
    error(R.drawable.icon)
}
```

Comparison with **Picasso**: using `placeholder` method cover all this cases. I think picasso apply placeholder before everything and if something go wrong it just keep placeholder

I don't know if it is better to "fix" placeholder method or create a new one

**Comment by colinrtwhite** [comment]
Hmm this seems like a good candidate for a custom extension function. What would you call this function that sets all the drawables? We can't modify `placeholder`'s existing behaviour as it would be a major behaviour change for existing users.

**Comment by xanscale** [comment]
agree with you, but i don't know if it is a `placeholder`'s bugfix or a new feature.

in picasso and glide (not sure for glide) if something go wrong placeholder remain visible

**Comment by colinrtwhite** [comment]
I'd recommend adding an extension function to `ImageRequest` that sets all 3. We can't modify the existing behaviour of `placeholder`/`fallback`/`error` as it would be a breaking change for existing users of the library.
