### ISSUE TITLE
Setup a benchmark with Glide, Fresco, Picasso

### ISSUE THREAD

**Issue by kaushalyap** [coil-kt/coil#71]
Setup a benchmark (memory, time, library size) with Glide, Fresco, Picasso for common set of scenarios

**Why?**

- for comparison
- to identify bottlenecks
- to keep track of performance changes as library evolves

**Comment by kaushalyap** [comment]
Fresco have https://github.com/facebook/fresco/tree/master/samples for comparisons

**Comment by colinrtwhite** [comment]
:+1: This is on my roadmap after shipping `0.7.0`.

**Comment by kaushalyap** [comment]
@colinrtwhite  you may find this useful: https://proandroiddev.com/coil-vs-picasso-vs-glide-get-ready-go-774add8cfd40

**Comment by colinrtwhite** [comment]
Thanks, reposting my response from the article:

> I’ve been focused on bug fixes and high priority features for the past month over performance optimization. Performance is very important to me and I plan to do a full profile of Coil soon. That said, there are likely bottlenecks that haven’t been found yet. However, I think this gives Coil a lot of room to get faster since there hasn’t been a lot of time spent on profiling Coil yet.
> 
> Coil being last in the “first load” metric is likely because Coil is paying the cost of initializing Coroutine’s Dispatchers.Main, which can take [upwards of 125 ms](https://github.com/Kotlin/kotlinx.coroutines/issues/878) in debug mode. R8 rewrites the loading mechanism to be much faster.
> 
> Glide and Picasso are libraries that have had years to mature whereas Coil has been out for a month. I’m confident performance will only get better in subsequent versions.

**Comment by colinrtwhite** [comment]
Adam Hurwitz re-ran the benchmark in the article with the most up to date Coil version: https://medium.com/@AdamHurwitz/colin-white-and-miguel-%C3%A1ngel-ruiz-l%C3%B3pez-1ecb7b58e5d7

Also I'll have a more scientific benchmark alongside the Coil 1.0.0 release using the androidx benchmarking library.

**Comment by kaushalyap** [comment]
> Also I'll have a more scientific benchmark alongside the Coil 1.0.0 release using the androidx benchmarking library.
where is it? results please

**Comment by colinrtwhite** [comment]
@kaushalyap I'm planning to upload it alongside 1.0.0 stable (the latest version is `1.0.0-rc3`).

**Comment by colinrtwhite** [comment]
I finally wrote up [an article](https://colinwhite.medium.com/benchmarking-image-loading-libraries-on-android-3ddf365a1927) benchmarking each of the libraries. Hope it's useful!

**Comment by ezequielmessore-bycoders** [comment]
Hi @colinrtwhite let me ask you something: Have you updated any benchmarks with the new version of Coil 3.x?
