### ISSUE TITLE
Memorycache return null bitmap

### ISSUE THREAD

**Issue by dumihi** [coil-kt/coil#712]
1. Question 1:
My imageLoader is singleton. This is my excute request

  val bitmap: Bitmap? = imageLoader.memoryCache[coil.memory.MemoryCache.Key("my_image_link")]
                            if (bitmap != null) {
                                msg.profile.vipChatIconDrawable =
                                    BitmapDrawable(appContext.resources, bitmap)
                                handleAddingMessage(chatMsg)
                            } else {
                                val request = ImageRequest.Builder(appContext)
                                    .data("my_image_link")
                                    .allowHardware(false)
                                    .memoryCacheKey("my_image_link")
                                    .build()
                                imageLoader.execute(request).drawable?.let {
                                    msg.profile.vipChatIconDrawable = it
                                    handleAddingMessage(chatMsg)
                                }
                            }
After successful fetching in else condition, I back to my previous fragment and go this logic again. But never jump to condition if.
I wonder whether mageLoader.memoryCache[MemoryCache.Key] is working ?

2. Question 2:
Additionally,  imageLoader.execute can not get the latest image if backend update new image with same link

**Comment by colinrtwhite** [comment]
I'd use the [DebugLogger](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) to see why your image may not be in the memory cache.

For the use case in your question however, it looks like you can just use `imageLoader.execute` in delete the `if (bitmap != null)` branch. If the image is already in the memory cache, imageLoader.execute(request)` will set the drawable synchronously.

For your second question, your backend should set the `cache-control` header on their requests to handle this appropriately.
