### ISSUE TITLE
E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor

### ISSUE THREAD

**Issue by rockyoung** [coil-kt/coil#713]
**Describe the bug**
Load local images into recyclerview with gridlayoutmanager(span count 4), first time display or scroll fast.

**Expected behavior**
no error log output.

**To Reproduce**
first time display or scroll really fast.

**Logs/Screenshots**
1617093259.523 4319-4804 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.523 4319-4818 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.524 4319-4805 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.525 4319-4816 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.528 4319-4822 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.528 4319-4618 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.530 4319-4618 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.530 4319-4824 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.531 4319-4821 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.531 4319-4820 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.532 4319-4818 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.534 4319-4828 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.535 4319-4827 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.535 4319-4825 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.537 4319-4819 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.537 4319-4823 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.538 4319-4617 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.538 4319-4616 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.539 4319-4830 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.540 4319-4833 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.541 4319-4832 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.542 4319-4836 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.542 4319-4829 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.542 4319-4834 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.544 4319-4830 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.547 4319-4833 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.547 4319-4832 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.548 4319-4613 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.548 4319-4619 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.549 4319-4824 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.549 4319-4836 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.549 4319-4829 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.550 4319-4816 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.550 4319-4834 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.551 4319-4612 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.553 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.554 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.555 4319-4319 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.558 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.558 4319-4613 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.560 4319-4824 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.560 4319-4619 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.560 4319-4821 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.561 4319-4822 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.561 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.562 4319-4816 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.562 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.562 4319-4805 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.562 4319-4612 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.562 4319-4804 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.562 4319-4821 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.563 4319-4806 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.563 4319-4319 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.565 4319-4822 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.565 4319-4828 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.565 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.566 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.568 4319-4805 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.568 4319-4820 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.569 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.571 4319-4641 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.571 4319-4804 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.571 4319-4807 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.572 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.574 4319-4806 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.575 4319-4828 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.577 4319-4817 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.577 4319-4807 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.578 4319-4825 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.578 4319-4823 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.579 4319-4820 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.579 4319-4832 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.579 4319-4825 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.580 4319-4817 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.580 4319-4319 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.581 4319-4823 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.582 4319-4833 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.582 4319-4641 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.583 4319-4832 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.584 4319-4827 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.588 4319-4827 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.588 4319-4836 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.590 4319-4836 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.590 4319-4833 E/IPCThreadState: More than IPC_LIMIT_LEVEL, pid 4319 wait~
1617093259.599 4319-4829 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.600 4319-4617 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.605 4319-4319 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.606 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.607 4319-4543 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.619 4319-4819 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.624 4319-4834 E/IPCThreadState: More than IPC_START_MONITOR_LEVEL, start Monitor
1617093259.826 4319-4319 W/DEBUG: begin to generate trace
1617093259.921 4319-4841 W/DEBUG: begin to generate anr
1617093259.921 4319-4841 E/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
1617093259.921 4319-4841 E/DEBUG: Basic Information: 'pid: 4319/tid: 4841/time: 20210330163419'
1617093259.921 4319-4841 E/DEBUG: Cpu Information: 'abi: arm64-v8a,armeabi-v7a,armeabi/processor: AArch64 Processor rev 1 (aarch64)/hardware: '
1617093259.921 4319-4841 E/DEBUG: Mobile Information: 'model: ***/version: 9/sdk: 28'
1617093259.921 4319-4841 E/DEBUG: Build fingerprint: '***/***/***:9/***/9.1.0.228C00:user/release-keys'
1617093259.921 4319-4841 E/DEBUG: Runtime Information: 'start: 20210330163408/maxheap: 402653184/primaryabi: arm64-v8a/ground: fg'
1617093259.921 4319-4841 E/DEBUG: Application Information: 'version: 1.5.00-dev/subversion: release/buildseq: 3008d5ab/versioncode: 1500'
1617093259.921 4319-4841 E/DEBUG: CrashSDK Information: 'version: 3.2.0.4/nativeseq: 200403192109/javaseq: 200403192109/arch: arm64-v8a/target: crashsdk'
1617093259.921 4319-4841 E/DEBUG: UUID: ce3ef310-6da8-47e8-993d-6e5e42f2b1af
1617093259.921 4319-4841 E/DEBUG: Report Name: 5f714801f472fc6b58a36ff8_1.5.00-dev_3008d5ab_MHA-AL00_9_161709324801233480_20210330163419_fg_anr.log
1617093259.921 4319-4841 E/DEBUG: Log Type: anr
1617093259.921 4319-4841 E/DEBUG: kernel version: Linux version 4.9.148 #1 SMP PREEMPT Fri May 22 19:13:52 CST 2020

**Version**
What library version are you using? 
1.1.1
Does this occur on a specific API level or Android device?
tested on API level 27, 28 and 29.

**Comment by colinrtwhite** [comment]
@rockyoung What's the behaviour you're seeing exactly? Is it only the log statement?

**Comment by rockyoung** [comment]
no, something seems to block the main thread and the scrolling animation is not as smooth as expected.
and my crash sdk reported it as an ANR type issue at the bottom of output logs.

**Comment by rockyoung** [comment]
[Using Glide](https://vimeo.com/534114783)
[Using Coil](https://vimeo.com/534116342)
Same codebase, only difference is:
```kotlin
override fun setThumbnail(option: ImageOption) {
    itemBinding.thumbnail.load(option.data.uri)
//    Glide.with(itemView.context).load(option.data.uri)
//      .into(itemBinding.thumbnail)
}
```
```kotlin
override fun setThumbnail(option: ImageOption) {
//    itemBinding.thumbnail.load(option.data.uri)
    Glide.with(itemView.context).load(option.data.uri)
      .into(itemBinding.thumbnail)
}
```

**Comment by colinrtwhite** [comment]
Thanks this does seem like the same issue as https://github.com/coil-kt/coil/issues/409. I've spent some time looking into it, but haven't been able to pin down the exact cause for the performance difference. I have plans to address this long term by performing fetching on `Dispatchers.IO` and decoding on `Dispatchers.Default`, however to work around this for the moment set `ImageLoader.Builder.dispatcher(Dispatchers.Default)`.

Going to close this issue out to centralize discussion in https://github.com/coil-kt/coil/issues/409.
