### ISSUE TITLE
Image are downloaded every time in recyclerview when there is internet connection, not loaded from cache.

### ISSUE THREAD

**Issue by ashishmahla** [coil-kt/coil#717]
**Describe the bug**
I am loading images inside my view holder in my recyclerview adapter as follows (onBindViewHolder):
```
 itemView.ivWallpaperModelThumbnail.load(wallpaper.thumbnailUrl) {
            this.crossfade(200)
            this.placeholder(ShimmerDrawable(primaryColor, itemView.context.dpToPx(24)))
}
```
When I open the screen and scroll down, all the images are loaded for the first time from the internet. But when I scroll back up, already downloaded images are also making a network call. I checked in the profiler and the data transfer is negligible, and the response code is 304. So it's returning 'Not Modified', but while that request is being processed, the placeholder is shown even though images are already cached and ready to be used. When I turn off the internet it loads from the cache as it should.

**Expected behavior**
When I am trying to load a URL for which the image is already present in the cache, it should use that cached image while it checks if the resource has changed on the server. If the resource is modified on that URL then it should reload it.

Also, if I can control the cache such that if I have an image available in the cache and I do want it to check if the image is modified on the server then that would be even better.

**Version**
Coil Version: 0.11.0

**PS**
I am not attaching any logs right now because I am new to Coil and I am not sure if this is a bug or if I am missing something in the setup on my end. If it's something from my end then please enlighten me on how to achieve the above-mentioned behavior with Coil. If it's an issue in the library and you need more details then I would be happy to add more info like logs and screenshots as per your demand.

**Comment by ashishmahla** [comment]
Sorry about that, just migrated to v1.1.1, and it's not happening in that one. Although another issue is happening now. When I go to the detailed view of the loaded wallpaper, there it's loading again for the same image.

**Comment by colinrtwhite** [comment]
This sounds like your server is sending a `cache-control` header that requires you to revalidate the image every time it's loaded. You can rewrite the header using OkHttp to disable this. [Here's how it's done in the sample app.](https://github.com/coil-kt/coil/blob/master/coil-sample/src/main/java/coil/sample/Application.kt#L51)

**Comment by ashishmahla** [comment]
Thanks for your help. I am using firebase storage and downloading images from there. Incase you know about it, can you assert that firebase storage does that.

Also, if I rewrite the header using OkHttp, will it load without revalidating? Can I achieve the functionality of showing the cached image while its revalidating it and if its changed the reload the image using coil.?
