### ISSUE TITLE
A problem about RoundedCornersTransformation

### ISSUE THREAD

**Issue by ShowMeThe** [coil-kt/coil#728]
In my case ,  I want to show a rounded corner Image by Coil RoundedCornersTransformation,
Example:
```
btn.setOnClickListener ​{
           ​iv1.load(url){
               ​transformations(RoundedCornersTransformation(15f))
           ​}
           ​iv2.load(url){
               ​transformations(RoundedCornersTransformation(15f))
           ​}
       ​}
```
but if I set the ImageView's layout_height wrap_content it will show  like the following gif :
[Gif](https://github.com/ShowMeThe/CoilExample/blob/master/gif/animation.gif)
My Layout xml :
```
<LinearLayout ...>
    <Button
        android:id="@+id/btn"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>
    <ImageView
        android:id="@+id/iv1"
        android:layout_width="match_parent"
        android:layout_height="200dp"/>
    <ImageView
        android:id="@+id/iv2"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</LinearLayout>
```
Here is my Example : [Example](https://github.com/ShowMeThe/CoilExample)

So I remove the transformations and got the reusult like the following gif:
[Remove the transformations](https://github.com/ShowMeThe/CoilExample/blob/master/gif/animation2.gif)

Here is my thiking :
Beacause I set the  ImageView's layout_height wrap_content , Coil will try to calculate a suitable height of the imageview, when the drawable attach to the ImageView , ImageView has  exactly height . I press the buton to load the photo again. Coil will calculate the ImageView in the  exactly height and  exactly width , So I got a two different result.

Version:  "io.coil-kt:coil:1.1.1"

**Comment by colinrtwhite** [comment]
Thanks for the report - this is the same issue as https://github.com/coil-kt/coil/issues/728. Going to close this one to track there.

Unfortunately there isn't a great way to solve this with the current way `Size` is modeled. The best way to work around this is to set `size(OriginalSize)` on your request.
