### ISSUE TITLE
Error 504 when loading "served" images

### ISSUE THREAD

**Issue by fiote** [coil-kt/coil#730]
**Describe the bug**

Served urls (like https://www.pontofrio-imagens.com.br/Control/ArquivoExibir.aspx?IdArquivo=1264532317) will fail with error 504.

**Expected behavior**

Normal image urls (ending with .png, .jpeg, etc) will load up just fine.

android:usesCleartextTraffic="true" is set on the manifest, so that's not the problem.

It's also not about the image's size, because I tried a "normal" image (4x the "served" one's size/weight) and it worked as well.

Is there any type of configuration that I can use to make this work?

**To Reproduce**
Just try to load that image with coil.

**Version**
koil: 1.2.0
device: galaxy s20
android: 11

**Comment by colinrtwhite** [comment]
I get a 403 when trying to access that image using Coil. It's possible that website is blocking mobile clients or another cause, though I don't think it's an issue with Coil.

**Comment by fiote** [comment]
Is there a way to set coil's agent like we do in curl to 'fake' who's requesting the image?

**Comment by colinrtwhite** [comment]
Yep, you can set the user agent using an [OkHttp interceptor](https://stackoverflow.com/questions/26509107/how-to-specify-a-default-user-agent-for-okhttp-2-x-requests). Here's how to set a [custom OkHttpClient](https://coil-kt.github.io/coil/recipes/#using-a-custom-okhttpclient) for Coil.

**Comment by fiote** [comment]
@colinrtwhite thanks a lot, that worked!
