### ISSUE TITLE
Transformation for error behavior

### ISSUE THREAD

**Issue by Papashkin** [coil-kt/coil#735]
Hello, dear Coiil devs!

I have a question related to behaviour when I'm trying to load the image.

This is my `load` code:

```
fun ImageView.loadImage(
        path: String?,
        placeholder: Drawable?,
        isCacheDisabled: Boolean = false,
        transformation: Transformation?
): Disposable = this.load(path) {
    placeholder(placeholder)
    error(placeholder)
    fallback(placeholder)
    size(OriginalSize)
    transformations()
    if (isCacheDisabled) {
        memoryCachePolicy(CachePolicy.DISABLED)
    }
    transformation?.let {
        transformations(it)
    }
}
```

I'm using `RoundedCornersTransformation` for images, and, frankly, it works pretty fine.
However, in case an error or URL I have brings null instead of the image, I'm trying to use a placeholder also for fallback and error, but transformation doesn't work in these cases (i.e. in both cases: error and null result).

Could you please explain to me, is it possible to keep transformation also for cases error and null result occurred?

Thanks in advance,
Papashkin

**Comment by colinrtwhite** [comment]
Yep, this isn't currently supported, however there's a ticket to track its support [here](https://github.com/coil-kt/coil/issues/37).
