### ISSUE TITLE
Gradle build fails on Coil 1.2.0

### ISSUE THREAD

**Issue by yasandev** [coil-kt/coil#739]
After updating to 1.2.0 from 1.1.1, I can no longer build my project successfully, 

> Execution failed for task ':app:dataBindingMergeDependencyArtifactsSellerDebug'.
> Could not resolve all files for configuration ':app:sellerDebugCompileClasspath'.
   > Could not find androidx.lifecycle:lifecycle-common-java8:2.3.1.
     Required by:
         project :app > io.coil-kt:coil-base:1.2.0

> Could not find androidx.lifecycle:lifecycle-common-java8:2.3.1.
Required by:
    project :app > io.coil-kt:coil-base:1.2.0
Search in build.gradle files

My project build.gradle file has the repositories below: 

```
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
    }
}
```

```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

I use coil in a few projects and I could not update to 1.2.0 since it came out on any of them but I have not seen anyone else here reporting this issue. I am not sure if this is only happening to me or not but I have tried everything I could to fix it but had no success. It simply cannot find `androidx.lifecycle:lifecycle-common-java8:2.3.1` when trying to build.

**Comment by colinrtwhite** [comment]
Hmm it's available on [Google's Maven repo](https://maven.google.com/web/index.html?q=lifecycle#androidx.lifecycle:lifecycle-common-java8:2.3.1). Maybe something's misconfigured in your Gradle scripts?

**Comment by yasandev** [comment]
I just tried adding 1.2.0 on a Compose project and there were no issues. So I guess something is wrong on my side & I will close the issue but I am not sure what is exactly the problem.

I cannot still add the project on ANY of my non-compose projects. And as you can see on my build gradle file, I have added all the repositories I need. The only difference I noticed on the Compose project was that the allproject.repositories was placed on settings.gradle instead:

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
        maven { url 'https://jitpack.io' }
    }
}
```

But I get an error when I try adding it like this to my older projects.

Other than Coil, it looks like I have similar issues with some random other packages as well that only happen on their new releases (similar to Coil, I only have problems with getting their new versions and the older ones work fine). It does not make much sense since I have not modified most of these build.gradle files recently.
