### ISSUE TITLE
SVG doesn't Scale

### ISSUE THREAD

**Issue by Bradleycorn** [coil-kt/coil#746]
Hi, I'm trying to load some svg images, and the images load but they don't seem to get scaled to fit inside the imageview when I use `Scale.FIT` in the Request Builder and `android:scaleType="fitCenter"`  on my ImageView. An example svg that I'm loading is attached. What am I doing wrong?

[jockey_silk.svg.zip](https://github.com/coil-kt/coil/files/6434209/jockey_silk.svg.zip)

**Comment by colinrtwhite** [comment]
Hmm SVGs are converted to bitmaps so the `ImageView` should scale it. It's tough to say what the issue is without a project that reproduces the issue.
