### ISSUE TITLE
Still used memory after the whole cache clear

### ISSUE THREAD

**Issue by patrykkubiakespeo** [coil-kt/coil#747]
I've loaded images with Coil which in my sample app uses the 70 MB in the graphics section in the Android Profiler. As you can see on the photo, after clearing the whole cache (memory, disk, and network) and clearing the bitmap pool there is still the 50 MB occupied memory. Also, the shutdown method didn't help to free the whole memory. 
![image](https://user-images.githubusercontent.com/74542228/117303364-e79dfa80-ae7c-11eb-969f-884a15877dba.png)

I am curious how can I free that memory. In comparison, Glide can free all the used memory (the memory usage is the same before and after the image loading) so I know that this should be possible.
![image](https://user-images.githubusercontent.com/74542228/117305291-e5d53680-ae7e-11eb-8170-a135ff487b0e.png)

**Comment by colinrtwhite** [comment]
Hmm this looks related to the fact that we don't proactively call `Bitmap.recycle` if the [`WeakMemoryCache`](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/memory/WeakMemoryCache.kt#L137) is cleared. Those bitmaps will be cleared naturally by GC (assuming your code isn't holding a reference to those bitmaps), however we may be able Glide's behaviour here - will have to check.

**Comment by colinrtwhite** [comment]
Going to close this out as expected behaviour and continue discussion in #749.
