### ISSUE TITLE
Cached Images not loaded on app launch with no network

### ISSUE THREAD

**Issue by BrettyWhite** [coil-kt/coil#750]
**Describe the bug**
During a normal session, I can see in the logs that an image is downloaded, then accessed via cache from the logs:
```txt
RealImageLoader: ☁️  Successful (NETWORK)
...
RealImageLoader: 🧠 Successful (MEMORY_CACHE)
```

However, If I exit the app, and come back in with no network I am seeing:

```txt
RealImageLoader: 🏗  Cancelled
...
RealImageLoader: 🚨 Failed
```
For each image in the recyclerview. 

After those logs, this log happens:

```txt
2021-05-07 16:22:10.708 21396-21396/com.app.android E/RealImageLoader: coil.network.HttpException: HTTP 504: Unsatisfiable Request (only-if-cached)
        at coil.fetch.HttpFetcher.fetch$suspendImpl(HttpFetcher.kt:90)
        at coil.fetch.HttpFetcher$fetch$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Expected behavior**

I have tried to override the `ImageLoader` with all cache policies enabled:

```kotlin
    override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(applicationContext)
            .crossfade(true)
            .availableMemoryPercentage(0.25) // Use 25% of the application's available memory.
            .componentRegistry {
                add(SvgDecoder(this@Application))
            }
            .diskCachePolicy(CachePolicy.ENABLED)
            .memoryCachePolicy(CachePolicy.ENABLED)
            .networkCachePolicy(CachePolicy.ENABLED)
            .okHttpClient {
                // Don't limit concurrent network requests by host.
                val dispatcher = Dispatcher().apply { maxRequestsPerHost = maxRequests }
                OkHttpClient.Builder()
                    .cache(CoilUtils.createDefaultCache(applicationContext))
                    .dispatcher(dispatcher)
                    .build()
            }.apply {
                // Enable logging to the standard Android log if this is a debug build.
                if (BuildConfig.DEBUG) { logger(DebugLogger(Log.VERBOSE))}
            }
            .build()
 ```

I am loading the images with the `load()` method:

```kotlin
itemBinding.soundIV.load(currentSound.iconUrl)
```

Is there a way to have the images load straight from the cache when the network is unavailable?

**To Reproduce**
1. load images with internet
2. exit the app and disconnect from cellular/wifi
3. reenter app and see logs posted above

**Version**
I have only tested on Android 11, versions 1.2.0 and 1.2.1 of Coil

Thank you for any help!!

**Comment by colinrtwhite** [comment]
Is your server returning a cache control header that prevents caching the images locally? The 504 error response is thrown when you're offline and the image is not present in the cache.

**Comment by BrettyWhite** [comment]
I dont believe so, these are the headers on all of the images:

```txt
content-type: image/png
etag: "2479fa8e0fe9c6ebc4c0bfcf848d8d9e"
last-modified: Fri, 15 Jan 2021 06:01:47 GMT
via: 1.1 varnish, 1.1 varnish
cache-control: public, max-age=2592000
accept-ranges: bytes
date: Sat, 08 May 2021 00:37:27 GMT
age: 714713
x-served-by: cache-bwi5128-BWI, cache-chi21171-CHI
x-cache: MISS, HIT
x-cache-hits: 0, 1
x-timer: S1620434248.810055,VS0,VE1
access-control-allow-origin: *
content-length: 1903
```

**Comment by colinrtwhite** [comment]
Hmm that cache header should be cacheable. I tried disabling internet connectivity in the `coil-sample` app, but cached images were loaded as expected. It's tough to say what the issue is without a sample that reproduces the issue.

**Comment by BrettyWhite** [comment]
Understood. I'll try and make one today. If i can't I will close the issue. Thank you for your help

**Comment by BrettyWhite** [comment]
Ok I figured it out. I was also using an instance of Exoplayer that was using the same cache dir as OkHTTP. Once i moved that, everything works as expected. Thanks again!

**Comment by cjcj125125** [comment]
Hello, I have the same problem as you, how to solve it? The error message is:

coil.network.HttpException: HTTP 504: Unsatisfiable Request (only-if-cached)
