### ISSUE TITLE
Default singleton ImageLoader picking wrong dark/light theme for placeholder if theme is not the device default

### ISSUE THREAD

**Issue by DAA-Android** [coil-kt/coil#752]
I am having an issue with the placeholder resource while loading images into an ImageView when the app dark/light theme is the opposite to the device default.

To give an example: in a device which has dark mode as device default, but my app changes it to light mode (via settings the user can apply, set with AppCompatDelegate.setDefaultNightMode()) I want to load a server image into my ImageView.
The placeholder is taken from resources (res/drawable or res/drawable-night). In this scenario, I would expect the res/drawable one is used (as the theme has been changed to light). But when the placeholder is shown, the dark one is used for an instant, and later replaced with the light one (the right one). Sometimes this change is so fast that it is imperceptible, but if scrolled fast (it is done in every item of a RecyclerView), it can be easily seen. I attach a screen recording showing it.

https://user-images.githubusercontent.com/39724150/117702053-4d192080-b1c8-11eb-8a98-e5edd2786793.mp4

The same scenario occurs for a device with default light mode changed to dark mode.
I don't know if it comes from ImageLoader using Application Context (I am using the default singleton that is initialized lazily), any help is appreciated.

**Comment by DAA-Android** [comment]
After more deep debugging I have found the bug was not the placeholder.
When binding my ViewHolder, I don't have the URL of the image to load (I have to take it asynchronously), so before doing the
`load(myUrl){
placeholder(R.drawable.placeholder)
}`
Y use
`load(R.drawable.placeholder)`

This way, the placeholder image is properly shown while the URL is being fetched, and then it is loaded.
I don't know why, but when loading my placeholder image, the theme used is the device default and not the one set by the app. When the URL is fetched and the other load() request is done, the right theme placeholder is used (as shown in the video, first the wrong one is loaded, then it is replaced by the right one as the placeholder of the second request).

So it looks like a bug when loading a resource.

**Comment by colinrtwhite** [comment]
Interesting, thanks for taking a look. Can you create a small project that reproduces the issue?

**Comment by DAA-Android** [comment]
I will create it along the week to make it easier to find the bug.

**Comment by colinrtwhite** [comment]
Awesome, thanks for digging into this + creating the project. I'll take a look into this likely this weekend.

**Comment by colinrtwhite** [comment]
I think you're correct that this is related to `ResourceUriFetcher` using the application context to check if we're in night mode. As a work-around you can manually clear the memory cache (or individual entries) when night mode is enabled/disabled.
