### ISSUE TITLE
Add documentation on supported file formats

### ISSUE THREAD

**Issue by carstenhag** [coil-kt/coil#754]
**Is your feature request related to a problem? Please describe.**
Currently it is unclear as to what file formats are supported. Is it JPG, PNG only, or are webp,  apng, etc also supported?

**Describe the solution you'd like**
Document on the website and in the readme what's supported

**Additional context**
There are svg and gif extending libs for coil, so these are clear.

**Comment by colinrtwhite** [comment]
Added documentation for supported image formats [here](https://coil-kt.github.io/coil/getting_started/#supported-image-formats).

**Comment by carstenhag** [comment]
Thanks a lot! 😲
