### ISSUE TITLE
Loading all images(URIs) from device using MediaStore API

### ISSUE THREAD

**Issue by Shaw007** [coil-kt/coil#756]
Hello, I am using coil to show local device images media with URIs to display them in a recycler view. I am using the default imageView.load(content://media/external/images/media/74152) function to display a list of images. When I scroll to the bottom of the recyclerview and then scroll back to the top quickly using fast scrolling, the images load again with placeholders. How can I cache these local URI images so that they don't show placeholders again once loaded in the first place?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6193968/118114757-74a6fd80-b401-11eb-9241-666466238834.gif)

**Comment by Shaw007** [comment]
anyone?

**Comment by colinrtwhite** [comment]
This looks like expected behaviour as Coil can only keep so many images in memory before it evicts the least recently used. To increase the amount of memory allocated to your `ImageLoader`'s memory cache, set `ImageLoader.availableMemoryPercentage` to a higher value.
