### ISSUE TITLE
Cache images with URL path

### ISSUE THREAD

**Issue by alirezanazari** [coil-kt/coil#761]
Hi
I have Url like this: http://test.com/images/svg/xxxx.svg?SignedHeaders=host&Signature=bd1628825bb8e67a56edb9b
query parameters are changeable but the path (/images/svg/xxxx.svg) is always same.
could you please give us some examples to cache images in memory in this way?

**Comment by colinrtwhite** [comment]
You can set a custom memory cache key using `ImageRequest.key(url)`. Coil relies on OkHttp for disk caching so there isn't an easy way to set the disk cache key, however you could probably  load `http://test.com/images/svg/xxxx.svg` without the extra params and add a [network interceptor](https://square.github.io/okhttp/interceptors/#network-interceptors) that adds the query params after the disk cache. [Here's how to configure your `ImageLoader`'s `OkHttpClient`](https://coil-kt.github.io/coil/recipes/#using-a-custom-okhttpclient).
