### ISSUE TITLE
Loading the same image into different views at the same time leads to unpredictable results

### ISSUE THREAD

**Issue by simon-st** [coil-kt/coil#769]
**Describe the bug**
When loading the same image into multiple views at the same time, the result is not as expected. I get images cut off, in wrong size or not showing at all.

**Expected behavior**
Image shows in right size in all views.

**To Reproduce**
Simple layout with 3 ImageViews:
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="vertical"
    android:background="#888888"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="20dp"
    tools:context=".MainActivity">

    <ImageView
        android:id="@+id/iv1"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:scaleType="fitCenter"
        android:background="#FF0000"/>
    <ImageView
        android:id="@+id/iv2"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:scaleType="fitCenter"
        android:background="#00FF00"/>
    <ImageView
        android:id="@+id/iv3"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:scaleType="fitCenter"
        android:background="#0000FF"/>
</LinearLayout>
```

Loading the same image 3 times:
```
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)

    val iv1 = findViewById<ImageView>(R.id.iv1)
    val iv2 = findViewById<ImageView>(R.id.iv2)
    val iv3 = findViewById<ImageView>(R.id.iv3)

    Coil.setImageLoader(ImageLoader.Builder(this).logger(DebugLogger(Log.ERROR)).build())

    iv1.load(R.drawable.ic_pause_black_24dp)
    iv2.load(R.drawable.ic_pause_black_24dp)
    iv3.load(R.drawable.ic_pause_black_24dp)
}
```

**Logs/Screenshots**
No logs were observed.

Observed outcomes:
<img width="115" alt="Screen Shot 2021-06-03 at 11 42 06 AM" src="https://user-images.githubusercontent.com/1965839/120697764-f9b28f00-c462-11eb-9292-01e0b1e05855.png">

<img width="107" alt="Screen Shot 2021-06-03 at 11 42 36 AM" src="https://user-images.githubusercontent.com/1965839/120697779-ff0fd980-c462-11eb-813a-f627aacca3e4.png">

<img width="110" alt="Screen Shot 2021-06-03 at 11 43 06 AM" src="https://user-images.githubusercontent.com/1965839/120697791-033bf700-c463-11eb-8f98-f1dcee9b235a.png">

<img width="103" alt="Screen Shot 2021-06-03 at 11 43 45 AM" src="https://user-images.githubusercontent.com/1965839/120697805-06cf7e00-c463-11eb-8655-43d67446db07.png">

**Version**
io.coil-kt:coil:1.2.1

**Comment by simon-st** [comment]
FYI using a custom ImageView that changes the bitmap background color reveals that the received bitmap does have the correct size, but the loaded image is scaled down inside of it.

```
class SimonImageView @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        defStyle: Int = 0
) : AppCompatImageView(context, attrs, defStyle) {

    override fun setImageDrawable(drawable: Drawable?) {
        (drawable as? BitmapDrawable)?.let {
            val newBitmap: Bitmap = Bitmap.createBitmap(
                it.bitmap.width,
                it.bitmap.height,
                it.bitmap.config
            )
            newBitmap.setHasAlpha(true)
            val canvas = Canvas(newBitmap)
            canvas.drawColor(Color.BLACK)
            canvas.drawBitmap(it.bitmap, 0f, 0f, null)

            super.setImageDrawable(BitmapDrawable(resources, newBitmap))
        }
    }
}
```

Result:
<img width="111" alt="Screen Shot 2021-06-03 at 12 19 51 PM" src="https://user-images.githubusercontent.com/1965839/120700189-3469f680-c466-11eb-8241-6fb9b51e3426.png">

**Comment by colinrtwhite** [comment]
Are you using a custom `ImageView` in your code? It looks like scaling isn't working for your `ImageView`. Also could you include a small sample project that includes the test resources?

**Comment by simon-st** [comment]
it happens with my custom view as well as with the default ImageView.

Here is a simple sample app for testing:
[MyApplication.zip](https://github.com/coil-kt/coil/files/6594033/MyApplication.zip)

**Comment by colinrtwhite** [comment]
Awesome, thanks for the project - I was able to reproduce + fix [here](https://github.com/coil-kt/coil/pull/771).

**Comment by simon-st** [comment]
@colinrtwhite awesome, thanks for the quick fix. What version will that be in?
