### ISSUE TITLE
Disk cache for custom Fetcher without the use of OkHttp

### ISSUE THREAD

**Issue by jpmcosta** [coil-kt/coil#79]
**Is your feature request related to a problem? Please describe.**
Implementing a custom fetcher seems to also require the implementation of disk cache.

**Describe the solution you'd like**
An interface to provide a bitmap and have it cached on disk, preventing unnecessary fetches.

**Note**
I apologize if I'm missing a simple solution.

**Comment by colinrtwhite** [comment]
Thanks for the enhancement request. Unfortunately, I'm not sure this is a good fit for Coil.

One of the main design decisions behind Coil was to rely on OkHttp's disk cache as:
1. This significantly reduces the complexity + size of Coil's codebase.
2. Coil automatically handles `Cache-Control` headers for free (something that Glide does not).

If you want to add disk caching to your custom `Fetcher`, I would use OkHttp's [DiskLruCache](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt) and write any responses from your `Fetcher` to it. This is similar to how OkHttp handles disk caching internally. The main downside to this is `DiskLruCache` is technically not part of OkHttp's public API.

**Comment by jpmcosta** [comment]
Thank you for your reply.

> I would use OkHttp's DiskLruCache and write any responses from your Fetcher to it.

That's how you would handle, for instance, if you wanted to fetch and cache the device's app icons?
That would be my use-case.

**Comment by jpmcosta** [comment]
@colinrtwhite thank you for your reply.

> I would use OkHttp's DiskLruCache and write any responses from your Fetcher to it.

That's how you would handle, for instance, if you wanted to fetch and cache the device's app icons?
That would be my use-case.

**Comment by colinrtwhite** [comment]
@jpmcosta Other app's icons are already stored on disk as part of their apk. You can load them without creating a custom Fetcher like so:

```kotlin
val packageName = "com.android.settings" // Replace with the correct app's package name.
val appInfo = packageManager.getApplicationInfo(packageName, 0)
imageView.load("android.resource://$packageName/${appInfo.icon}")
```

NOTE: I recently fixed a bug with loading other app's resources so you'll have to use the `0.8.0` [snapshot](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots) until it's released.

**Comment by jpmcosta** [comment]
@colinrtwhite you can load them, but are they cached? Because if the app is uninstalled and the icon is not cached, then you stop being able to load it.

**Comment by colinrtwhite** [comment]
@jpmcosta Ah that's a good point. They would not be cached after they're uninstalled. In that case I would recommend writing a custom Fetcher with `DiskLruCache`. Check out `ResourceUriFetcher` for how to open an `InputStream` to that resource then you just need to check if it's already in your disk cache and serve it. If it's not, write it to the disk cache using `BufferedSource` and return the same source from your `Fetcher`.

You could also preemptively cache all the app's images outside of Coil then pass the `File` to `imageView.load`.

**Comment by jpmcosta** [comment]
@colinrtwhite I see. Well, my initial goal with when opening this issue was to have the library to that work for me. 😅

Still, thank you for answering and keep the great work.
