### ISSUE TITLE
Target ignores previous sizing

### ISSUE THREAD

**Issue by ElMaestro89** [coil-kt/coil#791]
I defined an ImageView with a custom width/height I calculated previously. In my load(), I define target with onStart/onSuccess/onError and I load the drawable in param, but this one appears resized, and not the one expected.
But if I don't use target(), I get the expected size. 
I'm using trget() to define some actions depending on the result

**Expected behavior**
Using target(), the drawable I get should be sized as defined previously

**Code**            
```
val params = RelativeLayout.LayoutParams(customWidth, customHeight)
val ivAttachment = ImageView(context)
ivAttachment.apply {
  layoutParams = params

  load(url) {
       transformations(RoundedCornersTransformation(10f))
       error(R.drawable.ic_refresh)
       target(
           onStart = { placeholder ->
               
           },
           onSuccess = { result ->
               load(result)
                // Commented lines below don't change anything
                // size(customWidth, customHeight)
               // precision(Precision.EXACT)
               // scale(Scale.FILL)
           },
           onError = { error ->
               load(error)
               setOnClickListener {
                   Toast.makeText(context, "Hey", Toast.LENGTH_SHORT).show()
               }
           }
       )
   }
}
```
**Using target()**
<img width="384" alt="Capture d’écran 2021-07-05 à 18 08 58" src="https://user-images.githubusercontent.com/25926333/124498158-3227ee80-ddbc-11eb-9421-869f76e43967.png">

**Without target()** (expected)
<img width="384" alt="Capture d’écran 2021-07-05 à 18 09 41" src="https://user-images.githubusercontent.com/25926333/124498164-33f1b200-ddbc-11eb-9715-83bd0415ea46.png">

**Version**
implementation "io.coil-kt:coil:1.2.2"

**Comment by colinrtwhite** [comment]
@ElMaestro89 This is because setting `target` inside `load` overwrites the `target` set by the `load` function and your `ImageView` won't be updated. I'd recommend using the [regular `ImageRequest` syntax](https://coil-kt.github.io/coil/migrating/#non-view-targets) if you need a custom target. You can extend `ImageViewTarget` and add your custom behaviour.

**Comment by ElMaestro89** [comment]
Thanks a lot Colin
