### ISSUE TITLE
How to make  imageView not support GIF

### ISSUE THREAD

**Issue by hyx0804xiaokeai** [coil-kt/coil#796]
all images support GIF when I add GIF Decoder to ImageLoader, How to make  a part of imageView not support GIF。

**Comment by hyx0804xiaokeai** [comment]
in my Application:

**Comment by colinrtwhite** [comment]
You can set the decoder for individual requests using `ImageRequest.Builder.decoder(GifDecoder())`. Setting the decoder in your `ImageLoader` will support GIFs for all `ImageView`s and it's not possible to disable it for individual `ImageView`s.
