### ISSUE TITLE
Support for a regular suspending ImageView.load

### ISSUE THREAD

**Issue by kevincianfarini** [coil-kt/coil#80]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I'm not quite understanding why the implementation chose to go with a custom `RequestDisposable` over job or a pure suspending alternative. Normally, I delegate some network tasks in my RecyclerViews to my ViewHolders like so

```kotlin
abstract class CoroutineViewHolder(
    itemView: View,
    scope: CoroutineScope
) : RecyclerView.ViewHolder(itemView), CoroutineScope by scope {

    /**
     * This establishes a lifecycle for recycling of views for
     * coroutine aware ViewHolders. Cancel the work that's being
     * done if this view is recycled and no longer needed.
     */
    @CallSuper
    fun onRecycled() {
        this.cancel("${this}.onRecycled called")
    }
}
```
where `onRecycled` is a method I call from a similar coroutine adapter I've made. 

```kotlin
abstract class CoroutineAdapter<T : CoroutineViewHolder>(scope: CoroutineScope) : RecyclerView.Adapter<T>(), CoroutineScope by scope  {

    @CallSuper
    override fun onViewRecycled(holder: T) {
        super.onViewRecycled(holder)
        holder.onRecycled()
    }
}
```

needing to be bound to use a `RequestDisposable` seems like reinventing the wheel to me. There's got to be something I'm missing for this design choice. 

**Describe the solution you'd like**
If possible, a pure susending `ImageView.load` function would be great. 

**Additional context**

**Comment by colinrtwhite** [comment]
Yep, this was a conscious decision to not use `Job` as it represents a one-shot piece of work. `load` can seem like it's a one-shot operation, but actually for any `ViewTargets`, the request can be restarted multiple times if the `View` is detached and re-attached.

This is done so resources can be freed more proactively in `RecyclerViews` and `Fragments`; Glide has the same optimization. This behaviour is also essentially required to support `Fragments` as it's impossible to find a `Fragment`'s `Lifecycle` given its `Context` from `Fragment.getContext`.

If you want a pure suspending function, you could use `get` and manually set the result `Drawable` on your `ImageView`.

**Comment by colinrtwhite** [comment]
Closing this out, but feel free to reopen if you have more questions.
