### ISSUE TITLE
Unable to load heif/heic picture

### ISSUE THREAD

**Issue by drakeet** [coil-kt/coil#801]
**Describe the bug**

Just call the test:
```kotlin
imageView.load("https://raw.githubusercontent.com/nokiatech/heif/gh-pages/content/images/autumn_1440x960.heic")
```

LogCat:

```
2021-07-11 15:25:45.944 29066-29128/* I/HeifDecoderImpl: HeifDecoder* createHeifDecoder()
2021-07-11 15:25:45.944 29066-29128/* I/HeifDecoderImpl: HeifDecoderImpl::HeifDecoderImpl()
```

And the image is not displayed at all.

**Version**

Device: Android 11
App targetSdkVerison: 30
Coil: both 1.2.2 & 1.3.0 will fail

**Comment by colinrtwhite** [comment]
It loads as expected in the sample app. You can enable logging to see the exception: https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging

<img src="https://user-images.githubusercontent.com/5580160/125206052-beb62f00-e24a-11eb-8a1f-0d5fc250b0a5.png" width=50%/>
