### ISSUE TITLE
A png with CircleCropTransformation not play well in 1.3.0 but is ok in 1.2.2

### ISSUE THREAD

**Issue by ppqoppqh** [coil-kt/coil#803]
The Code is

         ImageLoadHelper.Companion.displayImage(userHeaderImageView,
                    account.getAvatar(), ImageLoadHelper.Companion.getERROR_REQUEST_OPTIONS(),
                    new CircleCropTransformation(), -1, -1,
                    null,
                    null);

        fun displayImage(imageView: ImageView?, url: Any?,
                         defaultRequestOptions: DefaultRequestOptions? = null,
                         transformations: Transformation? = null,
                         width: Int = -1, height: Int = -1,
                         target: Target? = null,
                         listener: ImageRequest.Listener? = null) {
            imageView?.loadAny(url?:R.drawable.ic_image_default, DEFAULT_IMAGE_LOADER) {
                defaults(
                    defaultRequestOptions?:ERROR_REQUEST_OPTIONS
                )
                transformations?.let {
                    transformations(it)
                }
                if (width != -1 && height != -1) {
                    size(width, height)
                }
                if (target != null) {
                    target(target)
                }
                if (listener != null) {
                    listener(listener)
                }
            }
        }

        val DEFAULT_REQUEST_OPTIONS: DefaultRequestOptions = DefaultRequestOptions(
            allowRgb565 = true,
            memoryCachePolicy = CachePolicy.DISABLED,
            diskCachePolicy = CachePolicy.ENABLED,
            bitmapConfig = Bitmap.Config.RGB_565,
            networkCachePolicy = CachePolicy.READ_ONLY
        )
        val ERROR_REQUEST_OPTIONS: DefaultRequestOptions = DEFAULT_REQUEST_OPTIONS
            .copy(placeholder = Aimee.getContext().resources.getDrawable(R.drawable.ic_image_default),
                error = Aimee.getContext().resources.getDrawable(R.drawable.ic_image_default)
            )

account.getAvatar() is https:\/\/pic1.huanxi.com\/1f482fdd475dffa7a7ee.png

1.2.2
![4f4k8dcxnhuuauo30fp4gxfh2_0](https://user-images.githubusercontent.com/8034587/125463878-404dfe5d-68fd-476e-baa3-e10b5342aef0.jpg)

1.3.0
![p7h0pbkqmrxbog1yzbxjgga0_0](https://user-images.githubusercontent.com/8034587/125463932-a8dba46f-efb9-4092-a639-662465070bd0.jpg)

is there some options for 1.3.0?

**Comment by ppqoppqh** [comment]
ImageLoadHelper.Companion.displayImage(userHeaderImageView,
                account.getAvatar(), ImageLoadHelper.Companion.getERROR_REQUEST_OPTIONS(),
                null, -1, -1,
                null,
                null);
that is ok in 1.3.0

**Comment by colinrtwhite** [comment]
Hmm this looks related to [this change](https://github.com/coil-kt/coil/commit/85155d4a6a23c93f634fa94ea35550a8e5fa6c46). Can you please upload a sample project that reproduces the issue? Also I'd recommend not setting `ImageLoader.Builder.defaults` as they'll be overwritten when the request is executed.

**Comment by ppqoppqh** [comment]
transform(pool: BitmapPool, input: Bitmap, size: Size)
I think it is beacause
The input is a scaledBitmap
drawBitmap(input, radius - input.width / 2f, radius - input.height / 2f, paint) also do the scaled again
so I added
