### ISSUE TITLE
CircleCropTransformation,gif not play

### ISSUE THREAD

**Issue by XjxBoom** [coil-kt/coil#805]
I don't know if it's a bug,
 
val imageLoader by lazy {
        ImageLoader.Builder(this)
            .componentRegistry {
                if (SDK_INT >= 28) {
                    add(ImageDecoderDecoder(this@MainActivity))
                } else {
                    add(GifDecoder())
                }
            }
            .build()
    }

  mBinding.ivImg.load("xxxxxx.gif",imageLoader) {
            transformations(CircleCropTransformation())
        }
not CircleCropTransformation(),gif play
when i set CircleCropTransformation(). this gif not play

**Comment by colinrtwhite** [comment]
[This is intended behaviour](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/transform/Transformation.kt#L14). You can create a custom `AnimatedTransformation` that circle crops the GIF to have it continue animating.

**Comment by XjxBoom** [comment]
https://coil-kt.github.io/coil/api/coil-gif/coil-gif/coil.transform/-animated-transformation/index.html
 404 not found

**Comment by XjxBoom** [comment]
> [This is intended behaviour](https://github.com/coil-kt/coil/blob/6adb699382411988dbfed6fdd0a36beceebfe1ba/coil-base/src/main/java/coil/transform/Transformation.kt#L14). You can create a custom `AnimatedTransformation` that circle crops the GIF to have it continue animating.

https://coil-kt.github.io/coil/api/coil-gif/coil-gif/coil.transform/-animated-transformation/index.html
404 NOT FOUND..

**Comment by elviswong-cn** [comment]
if i don't know the url is gif or static image,how?Because I found that transformations also conflict with animatedTransformation
