### ISSUE TITLE
Image not loading using remember rememberImagePainter

### ISSUE THREAD

**Issue by aasierra** [coil-kt/coil#807]
**Describe the bug**
When just using the basic example described, in a basic project. No images load. This is due to the fact that State.Empty is set on the ImagePainter by default as well as a null painter is returned for that state.
https://github.com/coil-kt/coil/blob/main/coil-compose-base/src/main/java/coil/compose/ImagePainter.kt#L278 <- The null painter being set.
https://github.com/coil-kt/coil/blob/main/coil-compose-base/src/main/java/coil/compose/ImagePainter.kt#L139 <- The draw call being made, but it is null since the state is set to empty.

**Expected behavior**
An image loads from a url.

**To Reproduce**
Here is link to project https://github.com/aasierra/BrokenCoil1.3.0Issue Please just clone and run on an emulator. This was ran on Pixel 3a API 30 x86 emulator.

**Logs/Screenshots**
No logs for this available.

**Version**
1.3.0 Android API 30 x86 emulator Pixel 3a

**Comment by colinrtwhite** [comment]
@aasierra I ran the project locally and it loaded the image as expected. Can you [post the exception you're encountering](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging)? The `ImagePainter` is only initialized to `State.Empty`, but calling `rememberImagePainter` sets its `request`, which will cause the request to be executed which updates the state.

<img src="https://user-images.githubusercontent.com/5580160/125978569-baa477af-b87c-4ac9-8ebf-62c04a367b3c.png" width=50%/>

**Comment by aasierra** [comment]
Hey there Colin, thank you for taking a look at this so quickly, I am a little confused however in regards to enable logging. https://github.com/coil-kt/coil/search?q=%22fun+logger%22 When searching through the code I only find that method logger is defined on ImageLoader's Builder. However I don't see how I can override / alter / call that from rememberImagePainter which is defined as below.
`inline fun rememberImagePainter(
    data: Any?,
    onExecute: ExecuteCallback = ExecuteCallback.Default,
    builder: ImageRequest.Builder.() -> Unit = {},
): ImagePainter = rememberImagePainter(data, LocalImageLoader.current, onExecute, builder)`

Seeing that you are able to make the image load really makes me wonder if this is my computer however. So I will keep looking into this.

**Comment by colinrtwhite** [comment]
@aasierra You can set configure the `ImageLoader` on your application class: https://coil-kt.github.io/coil/getting_started/#singleton

**Comment by corneloaie** [comment]
@aasierra I'm also having this issue but only when loading the image inside LazyColumn/LazyVerticalGrid:
```
LazyVerticalGrid(
                cells = GridCells.Fixed(3),
                contentPadding = PaddingValues(top = 72.dp)
            ) {
                photos?.let { photosList ->
                    items(photosList) { photo ->
                            val painter = rememberImagePainter(data = photo.url)
                            Image(
                                modifier = Modifier.padding(2.dp).clickable {
                                    photosViewModel.onPhotoClicked(photo)
                                },
                                painter = painter,
                                contentDescription = stringResource(R.string.cd_details_photo),
                                contentScale = ContentScale.Fit,
                                alignment = Alignment.Center
                            )
                    }
                }
            }
```
In a DetailsScreen the photo is loaded also if I modify this code and transform this into a Column { } and forEach the photos it will also work.

**Comment by aasierra** [comment]
Colin, thank you for your time. After turning on debug logging, I was able to determine it was an issue with my device having a proxy on.

**Comment by colinrtwhite** [comment]
@corneloaie This is expected behaviour (it's mentioned [here](https://coil-kt.github.io/coil/compose/#migrating-from-accompanist)). You need to constrain the dimensions for the `Image` composable by setting a size or set `size(OriginalSize)` when building your `ImageRequest` if you want to load the image with its original dimensions.

**Comment by corneloaie** [comment]
Thanks you for pointing that out, missed that part in the migration reading. Great help!

**Comment by thisistherealme** [comment]
![Image](https://github.com/user-attachments/assets/4e1d6ddb-dd4d-4cdc-aae2-d7b7e5c2c0d5)

I have no idea what I'm doing but thinking they using ads to post on u tube with a id that I guess to gain gross and with our knowledge of
