### ISSUE TITLE
coil-compose intermittently will not load an image

### ISSUE THREAD

**Issue by ColtonIdle** [coil-kt/coil#812]
**Describe the bug**
Every now and then, if you load the same image a bunch of times... one of them just goes missing.

**Expected behavior**
Always show the expected image.

**To Reproduce**
This is my composable which is a thin wrapper around coil
```
@Composable
fun ImageWithUrl(string: String) {
    Image(
        painter = rememberImagePainter(string),
        contentDescription = null,
        modifier = Modifier.size(48.dp))
}
```

Then we have

```
            Row {
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
                ImageWithUrl(string = "https://avatars.githubusercontent.com/u/31751141?s=400&u=30aca0f5193f402d07e2aab8e4a413f8905cd459&v=4")
}
```

**Logs/Screenshots**
If I open the screen sometimes it works, but if I back out and reload then every now and then a random one disappears.

First open:
<img width="565" alt="Screen Shot 2021-07-18 at 9 33 22 PM" src="https://user-images.githubusercontent.com/31751141/126090342-48715520-a2bd-42f5-ad30-4a80b8853242.png">

Second:
<img width="567" alt="Screen Shot 2021-07-18 at 9 33 57 PM" src="https://user-images.githubusercontent.com/31751141/126090358-49b3d962-9722-4ee8-bb6a-ea812e85fa55.png">

Third:
<img width="505" alt="Screen Shot 2021-07-18 at 9 35 03 PM" src="https://user-images.githubusercontent.com/31751141/126090436-52d36ea3-d1fc-4635-8fc8-ab401736676a.png">

**Version**
What library version are you using? Does this occur on a specific API level or Android device?
1.3.0 of lib

Other tips:
It seems like the images always load the first time? But then the subsequent times, the loading gets iffy. I can repro every time with multiple devices. I don't think I'm doing anything wrong with coil-compose?

**Comment by colinrtwhite** [comment]
Hmm I'm not able to reproduce this in my test project. Can you attach a sample project that reproduces the issue?

**Comment by colinrtwhite** [comment]
Hmm I'm not able to reproduce this in my test project. Can you attach a sample project that reproduces the issue?

**Comment by ColtonIdle** [comment]
Okay. So I can't repro... but I think I "repro'd" it yesterday because of this bug ()

aka. I opened the bug with the wrong code samples.

The code that creates the issue is actually this which I copied from compose samples. https://github.com/android/compose-samples/blob/72d4b5905fa40fa6622b62d81b3b03625b8a14ce/Crane/app/src/main/java/androidx/compose/samples/crane/util/NetworkUtil.kt

```
@Composable
fun ImageWithUrl(
    imageUrl: String,
    modifier: Modifier = Modifier,
) {
    ProvideImageLoader {
        Box(modifier) {
            Image(
                painter = rememberImagePainter(data = imageUrl, builder = { crossfade(true) }),
                contentDescription = null)
        }
    }
}

@Composable
fun ProvideImageLoader(content: @Composable () -> Unit) {
    val context = LocalContext.current
    val loader =
        remember(context) {
            ImageLoader.Builder(context).componentRegistry { add(ImageSizingInterceptor) }.build()
        }
    CompositionLocalProvider(LocalImageLoader provides loader, content = content)
}

@OptIn(ExperimentalCoilApi::class)
object MyServerSizingInterceptor : Interceptor {
    override suspend fun intercept(chain: Interceptor.Chain): ImageResult {
        val data = chain.request.data
        val size = chain.size

        if (data is String && size is PixelSize && size.width > 0 && size.height > 0) {
            val url = HttpUrl.parse(data)!!
                    .newBuilder()
                    .addQueryParameter("w", size.width.toString())
                    .addQueryParameter("h", size.height.toString())
                    .build()
            val request = chain.request.newBuilder().data(url).build()
            return chain.proceed(request)
        } else {
            return chain.proceed(chain.request)
        }
    }
}
```

But basically if you use this sizing interceptor then things break. I have it working with my server which does resizing, but the compose sample uses the resize capability of unsplash.

Maybe something above looks blatantly wrong to you?

**Comment by colinrtwhite** [comment]
That code should be fine, though it looks like they're creating an `ImageLoader` for each call which isn't optimal. Maybe they're running into some resource limits by creating too many `ImageLoader`s? I'll create a PR to update their sample.

I'd try to use `rememberImagePainter` without the `imageLoader` param which will use the shared `ImageLoader`. Without a reproduction sample I can't offer too much more help unfortunately.

**Comment by ColtonIdle** [comment]
Thanks for confirming. I'll check your PR later today (or whenever you make it) and actually try to create a minimal repro in the next 48 hours. Thanks @colinrtwhite

**Comment by ColtonIdle** [comment]
>We only create one ImageLoader which is shared for every rememberImagePainter call. Each ImageLoader has its own memory cache, OkHttpClient, network observer, so it's cheaper to only create one.

Creates a new OkHttpClient every time? Yeah... that's probably the issue. Hahaha. Thanks

**Comment by ColtonIdle** [comment]
Confirmed that this issue was due to an "error" in the original coil usage in compose-sample. @colinrtwhite saved the day by creating a PR that improves image loading.

https://github.com/android/compose-samples/pull/609
