### ISSUE TITLE
coil-compose not loading file as image

### ISSUE THREAD

**Issue by wakaztahir** [coil-kt/coil#813]
**Describe the bug**
I have a Java File , which is an image , which was working fine with accompanist version of the library but as soon as I upgraded , Those image files are not being displayed even though they present inside the storage
I created these files using `context.openFileOutput(id, Context.MODE_PRIVATE)`
Now I am loading them as File objects since they were saved by the user previously
The images are not showing , not even an empty box , Even though `rememberImagePainter` is being used , The state does not have any error as well

I am also supplying a loader since some images might be an svg
```
    val loader = remember {
        ImageLoader.Builder(context).componentRegistry {
            add(SvgDecoder(context))
        }.build()
    }

    val painter = rememberImagePainter(data = request, imageLoader = loader)

     Image(
          modifier = modifier,
          painter = painter,
          contentDescription = stringResource(R.string.random_image),
          contentScale = contentScale
      )

```

Checking for an error like this

```
 if (painter.state is ImagePainter.State.Error) {
        LaunchedEffect(key1 = painter.state, block = {
            Log.e(
                "TL_AttachmentPhotoImage",
                "Error Loading Image With Request : " + request.toString() + " , isSvg : " + isSvg.toString()
            )
        })
    }
```

**Expected behavior**
The Images should load and show properly

**To Reproduce**
Use context.openFileOutput to create and save an image
load The Image using a file object as a data in the Image Painter

**Logs/Screenshots**
no logs

**Version**
"io.coil-kt:coil-compose:1.3.0"

**Comment by colinrtwhite** [comment]
Is the `Image` inside a `LazyColumn`? The `Image` needs to have a specified size or else the image won't be loaded. Also please include a sample project that reproduces the issue.

**Comment by wakaztahir** [comment]
Image is not inside lazy column , Will provide sample project soon !

**Comment by wakaztahir** [comment]
switching to deprecated rememberCoilPainter instantly solves the problem , feels like rememberImagePainter doesn't work with file objects which is the data in rememberImagePainter and request in rememberCoilPainter in my case

**Comment by wakaztahir** [comment]
Its just happening in my project , apparently , there must be something that is causing image painter to not load image , however still coil painter can load the image , I have disabled the cache policy but that didn't solve the problem , Its really hard to know where this problem is coming from since the project has dependencies and the codebase is very large but I'm trying !

**Comment by wakaztahir** [comment]
I don't get it I'm supplying same parameters to both painters and yet one draws and one does not and only happens in my project !

**Comment by colinrtwhite** [comment]
Try [enabling logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) and see if there are exceptions.

**Comment by wakaztahir** [comment]
![Capture](https://user-images.githubusercontent.com/42442700/126582917-6f0f5cb6-38b5-4c5c-a1d6-03547137827c.PNG)

It Says Success but Images don't appear

**Comment by wakaztahir** [comment]
if change the painter to accompanist painter , images appear !
Maybe its a ui error and not a loading error

**Comment by wakaztahir** [comment]
Actually there are no logs from image loader , I was using accompanist painter and got success logs but in coil painter there is not a single log

**Comment by colinrtwhite** [comment]
This sounds related to the way `rememberImagePainter` handles undefined constraint vs. how Accompanist handled it. Try setting `Modifier.size(128.dp)` (or another size) on the `Image` composable.

Going to close this out, but feel free to create a new ticket if you're able to create a sample that reproduces the issue.

**Comment by wakaztahir** [comment]
Giving a size works !
I want it to fill the width and I've given the contentScale to fill width

**Comment by wakaztahir** [comment]
The image does not draw itself unless I specify a fixed size , if the image height is greater than the size I specify , it always cuts the image , please fix this

**Comment by wakaztahir** [comment]
should I open another issue ?
