### ISSUE TITLE
[coil-compose] When the placeholder image is a GIF image, the image will be cropped

### ISSUE THREAD

**Issue by wthee** [coil-kt/coil#815]
**Describe the bug**
![screenshot](https://wthee.xyz/wp-content/uploads/2021/07/S10721-15270282-e1626852745871.png)

**Expected behavior**
fit size
![expected](http://wthee.xyz/wp-content/uploads/2021/07/S10721-15364419-e1626853122150.png)

**To Reproduce**
[see this demo](https://github.com/wthee/coil-placeholder)

**Logs/Screenshots**

**Version**
1.3.0

**Comment by colinrtwhite** [comment]
Thanks for the repro project. Unfortunately, this is an issue (or maybe intended behaviour?) with how Android's `AnimatedImageDrawable` draws its contents without scaling to fit the canvas it's drawing on. You can reproduce this issue without Coil by calling `ImageView.setImageResource(R.drawable.load)`.

You can report the issue to the graphics team [here](https://issuetracker.google.com/issues/new?component=192644&template=1438858).

Fortunately, you can work around this issue by using Coil's `ScaleDrawable` (make sure you don't accidentally use Android's `ScaleDrawable`):

```kotlin
placeholder(ScaleDrawable(AppCompatResources.getDrawable(context, R.drawable.load)!!))
```

**Comment by wthee** [comment]
> `placeholder(ScaleDrawable(AppCompatResources.getDrawable(context, R.drawable.load)!!))`

Thanks! It worked
