### ISSUE TITLE
[coil-compose] Display Image Without Specifying Size

### ISSUE THREAD

**Issue by wakaztahir** [coil-kt/coil#820]
**Describe the bug**
The image does not draw itself unless I specify a fixed size , if the image height is greater than the size I specify , it always cuts the image , please fix this

I've given content scale as fill width , coil should adjust the height of the image according to it

**Expected behavior**
Image should draw properly when the size isn't specified

**To Reproduce**
Created an image without size In a grid which is not lazy

**Version**
Latest

**Comment by colinrtwhite** [comment]
It's not possible to display an image without specifying the size due to [a compose design decision](https://issuetracker.google.com/186012457). Also it sounds like you should use content scale `Fit` instead of `Fill` to have it not crop your image.

**Comment by wakaztahir** [comment]
I did not need to specify size when I was using accompanist !
