### ISSUE TITLE
how to get file from remote uri like glide  Target<File>

### ISSUE THREAD

**Issue by mikaelzero** [coil-kt/coil#821]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Additional context**

**Comment by colinrtwhite** [comment]
This is not possible at the moment. See https://github.com/coil-kt/coil/issues/100 for more info.

**Comment by mikaelzero** [comment]
I try to use other ways to solve this problem, can you help me see if there is any problem
https://github.com/mikaelzero/mojito/blob/master/coilimageloader/src/main/java/net/mikaelzero/coilimageloader/CoilImageLoader.kt
