### ISSUE TITLE
[Idea] Add Support for Firebase Storage Reference

### ISSUE THREAD

**Issue by madhurgupta10** [coil-kt/coil#822]
**Is your feature request related to a problem? Please describe.**
We use Firebase Storage (https://firebase.google.com/docs/storage/android/start) for our images, we used Glide which has built-in support for Firebase Storage Reference.

**Describe the solution you'd like**
It would be great if coil-compose can load Images from a Firebase Storage Reference automatically.

**Describe alternatives you've considered**
We currently use https://github.com/skydoves/Landscapist as alternative.

**Comment by colinrtwhite** [comment]
Thanks, but I think this is probably a good fit for a 3rd party library. Glide doesn't have built in support for Firebase Storage, but the Firebase team maintains a [separate artifact](https://firebaseopensource.com/projects/firebase/firebaseui-android/storage/readme/) for it (maybe they'll consider creating one for Coil :)). Fortunately, someone already wrote a `Fetcher` that supports Firebase Storage [here](https://github.com/coil-kt/coil/pull/213) that you can copy it into your codebase.
