### ISSUE TITLE
load function does not work for the first time

### ISSUE THREAD

**Issue by mahramane** [coil-kt/coil#823]
**Describe the bug**
Hi
After updating to version 1.3.0. The load function does not work for the first time, and it works when I call it again.

**Expected behavior**

**To Reproduce**

**Specifications of Android Studio.**

Android Studio Bumblebee | 2021.1.1 Canary 4
Build # AI-211.7628.21.2111.7545178, built on July 13, 2021
Runtime version: 11.0.10 + 0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 6
Registry: external.system.auto.import.disabled = true
-----------------

Create a new project and add the coil library then load a simple photo

findViewById <ImageView> (R.id.imageView) .load (R.drawable.image)

**Logs/Screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Version**
coil version : 1.3.0
compileSdk 30
targetSdk 30

implementation 'androidx.core:core-ktx:1.6.0'
implementation 'androidx.appcompat:appcompat:1.3.1'
implementation 'com.google.android.material:material:1.4.0'

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    plugins {
        id 'com.android.application' version '7.1.0-alpha04'
        id 'com.android.library' version '7.1.0-alpha04'
        id 'org.jetbrains.kotlin.android' version '1.5.20'
    }
}

**Comment by colinrtwhite** [comment]
Please include a sample project. This is not reproducible in the `coil-sample` project in this repo.

**Comment by mahramane** [comment]
> Please include a sample project. This is not reproducible in the `coil-sample` project in this repo.

https://github.com/mahramane/test_coil

**Comment by colinrtwhite** [comment]
Thanks for the project, however it works correctly for me. Closing this out as it seems like a local configuration issue.

https://user-images.githubusercontent.com/5580160/127241102-4b25d57b-b38c-4f6b-8d2b-fcdc251fa205.mp4

**Comment by mahramane** [comment]
I checked on Android 11. What version did you run on?
