### ISSUE TITLE
Pixelated RoundedCornersTransformation

### ISSUE THREAD

**Issue by s4cha** [coil-kt/coil#837]
Hello there
We recently migrated from `fresco` to `Coil` and we are facing an issue using `RoundedCornersTransformation` which yields a pixelated image.

Any idea where this would come from?

code
```kotlin
imageView.load(item.uri.toString()) {
    crossfade(true)
    transformations(RoundedCornersTransformation(8.dp.px.toFloat()))
}
```

library used is `io.coil-kt:coil-compose:1.3.0`
![Screenshot_20210802_113803_com octopepper yummypets](https://user-images.githubusercontent.com/1812953/127841116-6e003b02-733b-4128-9f62-d53182fa5060.jpg)
<img width="671" alt="Screenshot 2021-08-02 at 11 41 31" src="https://user-images.githubusercontent.com/1812953/127841152-8a9c8287-790a-4a21-9bfd-a95c618961ac.png">

**Comment by colinrtwhite** [comment]
If they're small images it's possible they're getting scaled up. Try adding `precision(Precision.EXACT)` to your request.

**Comment by s4cha** [comment]
Worked like a charm, thank you 👍
