### ISSUE TITLE
[Compose] Image is not displaying when using LazyList without specifying height

### ISSUE THREAD

**Issue by wiryadev** [coil-kt/coil#838]
**Describe the bug**
Image is not visible when used inside LazyList (both Column and Row) but working correctly if its not inside list. I tried to use Accompanist Coil and it is working as expected.
Here is the composable that contains Coil:
```
@Composable
fun BasicCoilCompose(imgUrl: String) {
    Column {
        Text(text = "Coil", style = MaterialTheme.typography.h4)
        Image(
            painter = rememberImagePainter(imgUrl),
            contentDescription = "Basic",
            modifier = Modifier
                .fillMaxWidth()
        )
    }
}
```
And the lazy lis:
```
@Composable
fun ImageList() {
    val imgUrl = "https://www.pdvg.it/wp-content/uploads/2021/07/fifa_22.jpg"
    LazyColumn(
        contentPadding = PaddingValues(vertical = 12.dp, horizontal = 16.dp)
    ) {
        item { AccompanistCoil(imgUrl) }
        item { BasicCoilCompose(imgUrl) }
    }
}
```
**Expected behavior**
Coil showing image when the Composable containing it used as list's item.

**To Reproduce**
I uploaded small project to github. Click **[here](https://github.com/wiryadev/coil-compose-blog)**

**Logs/Screenshots**
Use composable directly (works) |  Use it inside lazy list (accompanist works, coil doesnt)
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/26060382/127884220-b303c150-eea8-42e0-b05d-6f684a4d7737.png) | ![image](https://user-images.githubusercontent.com/26060382/127884323-f830d47f-583d-4e42-bf4f-fbf76ed081b1.png)

**Version**
Library Version: 1.3.1
API Level: tested in both API 29 and 30

**Additional Context**
I should specify height when using Coil whereas its unnecessary when using Accompanist. Here is the screenshot when i explicitly set the image height to 128.dp

![image](https://user-images.githubusercontent.com/26060382/127885908-fcac9259-370f-4e50-acb7-39be40a4978f.png)

**Comment by colinrtwhite** [comment]
Thanks for the report + sample project, however this is intended behaviour ([mentioned here](https://coil-kt.github.io/coil/compose/#migrating-from-accompanist)). You can set `ImageRequest.size(OriginalSize)` to have the image display without an `Image` size.

It's not possible to display an image without specifying the size due to [a compose design decision](https://issuetracker.google.com/186012457). Accompanist uses a timer internally to work-around this however, timers can be flaky which is why it was removed in `coil-compose`.

**Comment by dazza5000** [comment]
We hit this issue too and I noticed that Glide doesn't have this issue when using `GlideImage` - is there anything we can borrow from that implementation?
