### ISSUE TITLE
StrongMemoryCache determining available space

### ISSUE THREAD

**Issue by ThinkJarvis** [coil-kt/coil#854]
**Describe the bug**
    override fun set(key: Key, bitmap: Bitmap, isSampled: Boolean) {
        // If the bitmap is too big for the cache, don't even attempt to store it. Doing so will cause
        // the cache to be cleared. Instead just evict an existing element with the same key if it exists.
        val size = bitmap.allocationByteCountCompat
        if (size > maxSize) {
       }
 }

if (size > maxSize) this condition use current bitmap size compare with maxSize

I think it is incorrect

**Expected behavior**

val size = bitmap.allocationByteCountCompat + cache.size()
        if (size > maxSize)

I think it should use total cache size compare with maxSize

**To Reproduce**
None

**Logs/Screenshots**
None

**Version**
None

**Comment by colinrtwhite** [comment]
The check is checking for if only the input bitmap is larger than the entire cache so it wouldn't make sense to add `cache.size()`. If the bitmap is smaller than the max cache size then we add it to the cache as normal. The `LruCache` automatically removes items from the cache if `bitmap.allocationByteCountCompat + cache.size() > cache.maxSize()`.

**Comment by ThinkJarvis** [comment]
oh, I see , thanks
