### ISSUE TITLE
Get the Drawable from a success request on Compose

### ISSUE THREAD

**Issue by metehus** [coil-kt/coil#858]
**Is your feature request related to a problem? Please describe.**

There's a discussion on #851 about getting the drawable from the `rememberImagePainter` in order to use on other methods (like getting the color palette) without making another request externally.

The best way of doing that would be using the `target` from the `ImageRequest`. But, as seen on the discussion, it is set internally so it's not possible to use that on the image request builder inside the `rememberImagePainter`
```kotlin
    val painter = rememberImagePainter(
        imageURL,
        builder = {
            target( // target must be null
                onSuccess = {
                    doStuffWithDrawable(it)
                }
            )
        },
    )
```

**Describe the solution you'd like**

A solution i see to that would be a callback like the ImageRequest's target on the compose function, like so:
```kotlin
    val painter = rememberImagePainter(
        imageURL,
        callbacks = {
            onSuccess { drawable ->
                doStuffWithDrawable(drawable)
            }
        }
    )
```
The internal target would pipe the the `onStart`, `onError` and `onSuccess` from the internal target to the callbacks on the remember function.

**Comment by brettmcginnis** [comment]
I was able to leverage the transform to grab the bitmap https://stackoverflow.com/q/68094647

**Comment by colinrtwhite** [comment]
This should be easier in 2.0 since `listener` has the image result. The best way to grab the bitmap currently is to use `((rememberImagePainter(data).state.painter) as? BitmapPainter).bitmap`

**Comment by metehus** [comment]
> This should be easier in 2.0 since `listener` has the image result. The best way to grab the bitmap currently is to use `((rememberImagePainter(data).state.painter) as? BitmapPainter).bitmap`

Oh, thats cool and much easier. Is there a way to do check when the request is done? maybe checking for changes on the painter and check if it has a successful result?

**Comment by colinrtwhite** [comment]
@metehus You can use `listener(onSuccess = {})` to listen for when the request completes successfully. `ImagePainter.state` is also a compose state property so your composition will recompose automatically when it changes.

**Comment by tipialican** [comment]
@colinrtwhite is it possible to access the drawable in onSuccess?

**Comment by colinrtwhite** [comment]
@univeous Ah! Sorry I totally got this wrong and it's not possible to access the bitmap in `BitmapPainter`. Given the other solutions are hacky, I'm going to push `1.3.3` today which will relax setting the target when using `rememberImagePainter`. That way you'll be able to get the drawable using:

```kotlin
val painter = rememberImagePainter(
    data = "https://www.example.com/image.jpg",
    builder = {
        target { drawable -> TODO() }
    }
)
```

That said, I'll probably prevent setting the target again in Coil 2.0 since the drawable accessible via `listener.onSuccess`.

**Comment by colinrtwhite** [comment]
@univeous Ah! Sorry I totally got this wrong and it's not possible to access the bitmap in `BitmapPainter`. Given the other solutions are hacky, I'm going to push 1.3.3 today which expose the `Drawable` in `ImagePainter.state`. That way you'll be able to get the drawable using:

```kotlin
val painter = rememberImagePainter("https://www.example.com/image.jpg")
val drawable = (painter.state.result as? SuccessResult)?.drawable
Image(painter = painter, contentDescription = null)
```
