### ISSUE TITLE
fail to load https://t.mmzztt.com/thumbs/2021/07/32360_960.jpg

### ISSUE THREAD

**Issue by gkj17** [coil-kt/coil#860]
fail to load "https://t.mmzztt.com/thumbs/2021/07/32360_960.jpg", it will show a empty view.....

**Comment by colinrtwhite** [comment]
Your url returns a 403 response. I don't think this is a bug with Coil.

**Comment by gkj17** [comment]
![6a7a13892fd3c80a74dde67d39b55fc](https://user-images.githubusercontent.com/31543062/129405817-c972004e-a37c-4431-8391-73202587e1e5.png)
I can access this url correctly.(probably because I am in China)
But this Url can be loaded using Glide.
I migrated my project from Glide to Coil, and this bug happened

**Comment by colinrtwhite** [comment]
Hmm I would try [enabling logging](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) to see the exception.

**Comment by gkj17** [comment]
Thanks for your concern! 
I think this should be a problem that needs to be fixed

**Comment by gkj17** [comment]
I solved it by adding Headers... Maybe Glide will auto add some headers?

**Comment by RobertTadevosyan** [comment]
@gkj17 what headers did you add ?
