### ISSUE TITLE
some image will lead to java.lang.IllegalArgumentException: width and height must be > 0.

### ISSUE THREAD

**Issue by gkj17** [coil-kt/coil#861]
II don't know the specific reason. I only know that sometimes this error occurs when sliding the list

```
val request = ImageRequest.Builder(imageView.context)
            .data(imageUrl)
            .size(imageView.width, imageView.height)
            ...
            .build()
```

**Comment by colinrtwhite** [comment]
It's likely your image view's width/height is 0 when you start the request. You probably want to set size(ViewSizeResolver(imageView)) instead.
