### ISSUE TITLE
RoundedCornersTransformation wrong beviour while upscale

### ISSUE THREAD

**Issue by StanislavChumarin** [coil-kt/coil#865]
If a loaded image is smaller than target ImageView, then rounded corners are applied to smaller image and upscale makes those radii bigger

**Expected behavior**
Image should be first scaled before cutting corners

**Version**
version 1.3.2

**Comment by colinrtwhite** [comment]
Setting `ImageRequest.precision(Precision.EXACT)` should work-around this. Unfortunately, I don't think there's a great way to have Coil do this automatically without disabling the precision optimization for all targets.
