### ISSUE TITLE
a best way get bitmap in recyclerview

### ISSUE THREAD

**Issue by mikaelzero** [coil-kt/coil#877]
val request = ImageRequest.Builder(context)
            .data(maskImageUrl)
            .target(
                onSuccess = {
                    if (maskLayout.tag == maskImageUrl) {
                        maskLayout.changeBitmap(it.toBitmap())
                    }
                }
            )
            .build()
        context.imageLoader.enqueue(request)

If I use this way, the picture of the list will be messed up

**Comment by mikaelzero** [comment]
i tried this way


        CoilUtils.clear(materialMaskLayout)
        val materialRequest = ImageRequest.Builder(context)
            .data(maskImageUrl)
            .target(object : PoolableViewTarget<View> {
                override val view: View
                    get() = materialMaskLayout

                override fun onSuccess(result: Drawable) {
                    materialMaskLayout.changeBitmap(result.toBitmap())
                }

                override fun onClear() {
                    materialMaskLayout.changeBitmap(null)
                }

            })
            .build()
        context.imageLoader.enqueue(materialRequest)

**Comment by colinrtwhite** [comment]
Please ask usage questions in Github Discussions.
