### ISSUE TITLE
Unable to Load Local / Regular Image

### ISSUE THREAD

**Issue by hassan31** [coil-kt/coil#88]
Hi, I', trying to load local image from drawable, but it's not displaying the image in my recycler view. But if I try `view.ivAccount.setImageResource(account.image)` the native code to display, then it works.
![image](https://user-images.githubusercontent.com/3063382/64479862-3e749d80-d18b-11e9-8952-6b4d208f0d22.png)

Please have a look into attached screenshots that are not working using your code.
![no_image](https://user-images.githubusercontent.com/3063382/64479851-171dd080-d18b-11e9-86f1-767cdf76cf95.png)

Your Code Screenshot:
<img width="668" alt="code" src="https://user-images.githubusercontent.com/3063382/64479867-52b89a80-d18b-11e9-9850-9375d9b3f621.png">

**Comment by colinrtwhite** [comment]
Is `ic__settings` a vector drawable? If so, I believe this should be fixed by https://github.com/coil-kt/coil/pull/89.

**Comment by hassan31** [comment]
No, it's not a vector, its simple png image.
