### ISSUE TITLE
Support for stable keys for disk cache content

### ISSUE THREAD

**Issue by dant3** [coil-kt/coil#880]
**Is your feature request related to a problem? Please describe.**
In my application I'm displaying various images. I only have identifiers of those images and to actualy download them I need to query API server to get a temporary url where I can download an image from. My issue is that coil relies directly on OkHttp for disk cache -- at OkHttp level only an url of an image is known -- which is temporary and will change the next time I need to download an image, but the image itself is actually the same.
In order to correctly hit the disk cache in this situation, a stable key for this cache is required, just like with the memory cache, where it's already possible.

**Describe the solution you'd like**
Similarly to how you can provide custom memoryCache key I would like to be able to provide diskCache key, so that then it matches I instantly get disc cache hit without using the network. It can be the same key FWIW

**Comment by colinrtwhite** [comment]
Unfortunately, I don't think this is possible to implement. Coil relies on OkHttp's disk cache which does not support custom cache keys.

That said, you could implement this manually using two OkHttp interceptors. Register one interceptor using `addInterceptor` which sets the request's URL; this URL will be used as the disk cache key. Register the second interceptor using `addNetworkInterceptor`; this interceptor will map the disk cache URL to the real network URL.

**Comment by dant3** [comment]
You mean that I should supply some frugal URL which I will turn into a real thing into networkIntercentor? This is such an ugly hack that its amusing to hear such suggestion.
For now I ended up working this around like this: the API server also provides and URL which I can do a GET request to, which will redirect to the real url. The downside is that I have to be authenticated to query this API. So I provide authentication details using addHeader functionality.
This is still quite a hack. Back in the days we had this functionality in fresco and glide and it's quite fun that new libraries just don't have this.

**Comment by colinrtwhite** [comment]
@dant3 I'm fairly sure Glide and Picasso do not support this feature either. Picasso also uses OkHttp's disk cache so any solution that works for it will work for Coil.

If you have a better idea of how to implement this functionality in Coil, submit a PR. Closing this since this isn't likely to be implemented.

**Comment by dant3** [comment]
You're right about picasso, sorry. Glide uses same memory cache keys. Thanks for your response anyway, I'll consider making a PR if my workaround will not work out one way or another.

**Comment by Tolriq** [comment]
That's the big missing feature of Coil :( 
Disk cache with stable keys, to support changing urls, identical content on different servers, proper cache handling for bad servers and a few other use cases currently hard to manage.
Ohttp as cache is a layer too deep in the chain for proper caching. (content:// urls should be cached when from remote sources too, ...)

But it seems Coil 2 have nice API changes to simplify things, is there some rough ETA for it?
