### ISSUE TITLE
Disable crossfade transition if target view is not shown

### ISSUE THREAD

**Issue by sav007** [coil-kt/coil#889]
**Describe the bug**
If target view is not shown ([view.isShown](https://developer.android.com/reference/android/view/View#isShown())==false), executing image request with crossfade transition enabled, never completes if image fetched from disk / network. As a result passed `ImageRequest.Listener` is never called. If image is in the mem cache, everything works as expected because of `transition === Transition.NONE`.

Here is a possible use case, the main content (that includes image view) of the screen is invisible and placeholders are shown until the content and image are loaded. After content is loaded it shown to the user.

As workaround on client side, check if view is not shown then override image request with crossfade config disabled.

**Expected behavior**
My assumption if target view is not shown, then skip crossfade transition.

**Version**
1.3.2

**Comment by colinrtwhite** [comment]
Thanks for the report - I agree it would be better to skip the transition in this case. `CrossfadeTransition` already skips suspending if [`View.isVisible`](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/transition/CrossfadeTransition.kt#L45) returns false, though I'm guessing a parent view is invisible in your case? We could replace `isVisible` with `isShown` - my only concern is if there is a potential performance impact.

**Comment by sav007** [comment]
yes in our case the target image view is visible but the parent container view is not.

> with isShown - my only concern is if there is a potential performance impact.

You mean because it traverse the parent view hierarchy?

**Comment by colinrtwhite** [comment]
@sav007 Yep, though I did some quick tests and the performance impact looks pretty negligible.
