### ISSUE TITLE
Cache-Control is not working as expected.

### ISSUE THREAD

**Issue by kavinmk6** [coil-kt/coil#896]
**Describe the bug**
I am facing issue in setting validity for Cache in android jetpack using coil. What I Need: In Android Jetpack compose, I need to download an SVG image from the Url and store it to the cache. But the cache should store the image only for 20 seconds. so within the 20 seconds, there should not be any further image request. For this 20 seconds, the image should display from the cache. After 20 seconds, I want the image, should get cleared from the cache (I tried with both MemoryCache and diskCache)

What's the problem I am facing: The image is not getting cleared from the cache even after 20 seconds. I am using Coil for the jetpack compose jetpack coil and Jetpack header for Cachecontrol Thanks in Advance....

**Expected behavior**
The cached Image should be cleared after a particular time.

**To Reproduce**
https://stackoverflow.com/questions/69122657/androidcache-validity-for-an-image-using-coil-in-jetpack?noredirect=1#comment122313961_69122657. Please go through the link where I have posted details with the codebase.

**Logs/Screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Version**
"io.coil-kt:coil-compose:1.3.2"
 "io.coil-kt:coil-svg:1.3.2"

**Comment by colinrtwhite** [comment]
This isn't a bug. Looking at your code, you're setting the cache-control header for the request. You need to set it for the response using a network interceptor like this: https://github.com/coil-kt/coil/blob/main/coil-sample/src/main/java/coil/sample/Application.kt#L51.
