### ISSUE TITLE
Disable placeholder (equivalent to Picasso's .noPlaceholder())

### ISSUE THREAD

**Issue by kawaiiDango** [coil-kt/coil#897]
**Is your feature request related to a problem? Please describe.**
As of now, I am using the workaround `placeholderMemoryCacheKey(imageView.metadata?.memoryCacheKey)`. This does not work with GIFs probably because they are too large to fit in the memory. So, The imageView flashes before the second load as in the code below.

 It would be nice if we have a clean way to disable placeholders.

        lifecycleScope.launch {
            imageView.load("https://bestanimations.com/media/easter/908905210funny-cute-easter-bunny-and-cat-animated-gif-2.gif") {
                placeholderMemoryCacheKey(imageView.metadata?.memoryCacheKey)
                error(R.drawable.ic_launcher_background)
            }
            delay(5000)
            imageView.load("https://bestanimations.com/media/easter/908905210funny-cute-easter-bunny-and-cat-animated-gif-2.gif") {
                placeholderMemoryCacheKey(imageView.metadata?.memoryCacheKey)
                error(R.drawable.ic_launcher_background)
            }
        }

**Describe the solution you'd like**
No flashes on subsequent loads

**Additional context**

**Comment by colinrtwhite** [comment]
`placeholderMemoryCacheKey(imageView.metadata?.memoryCacheKey)` won't work with animated images as they can't be stored in the memory cache since non-bitmap drawables aren't shareable. For `noPlaceholder` support, this is actually already possible in Coil by creating a custom `ImageViewTarget` and skipping `onStart` and `onClear`.

**Comment by sam-murphy55** [comment]
@colinrtwhite Can you please provide an example of how to implement the noPlaceholder for Coil's `AsyncImage` in Jetpack Compose?
