### ISSUE TITLE
ComponentRegistry injection in a multi-module project

### ISSUE THREAD

**Issue by LudoFarkas** [coil-kt/coil#903]
**Is your feature request related to a problem? Please describe.**
Hi,

we would like to migrate from Glide to Coil in our project. It is a multi-module project with tens of modules and we use Dagger to inject dependencies. 
The Coil initializer is in a separate module and we would like to inject custom Fetchers and Mappers to it, to create a ComponentRegistry that is eventually registered in the ImageLoader. The particular Fetchers and Mappers are declared in different modules, according to their use cases.

Currently we use Dagger multibind to inject wrapper objects representing Fetchers and Mappers to the initialization module. In order to keep the type, the wrapper looks like this:

```
sealed class CoilComponent<T: Any> {
    abstract val type: KClass<T>

    data class FetcherEntry<T: Any>(val fetcher: Fetcher<T>, override val type: KClass<T>) : CoilComponent<T>()

    data class MapperEntry<T: Any>(val mapper: Mapper<T, *>, override val type: KClass<T>) : CoilComponent<T>()
}
```

Then in the initializer module, we have a function to construct the ComponentRegistry:

```
    @JvmStatic
    @Provides
    fun coilComponentRegistry(
        componentsProvider: Provider<@JvmSuppressWildcards Set<CoilComponent<*>>>
    ): ComponentRegistry {
        val componentEntries = componentsProvider.get()

        return ComponentRegistry.Builder()
            .apply {
                componentEntries.forEach { entry ->
                    when (entry) {
                        is CoilComponent.FetcherEntry -> add(entry.fetcher, entry.type.java)
                        is CoilComponent.MapperEntry -> add(entry.mapper, entry.type.java)
                    }
                }
            }
            .build()
    }
```
However, the non-inline add() function is marked as internal in the ComponentRegistry.Builder and the inline add() function is not suitable with this setup because of the missing type. Neither there is a possibility to inject multiple ready-made ComponentRegistries to the ImageLoader.

**Describe the solution you'd like**
I would like to get an advice on how to deal with this type of problem. Or a change in the Coil API to enable injecting either multiple ComponentRegistries, or make the non-inline add() function public in ComponentRegistry.Builder

**Comment by colinrtwhite** [comment]
Thanks for the explanation - I think this is a good use case to make the non-inlined `ComponentRegistry.add` method public. Until that's made public you can call that method using Java as a work-around.

**Comment by LudoFarkas** [comment]
OK, thanks for the answer.
