### ISSUE TITLE
Coil load image wider than actual size

### ISSUE THREAD

**Issue by alirezanazari** [coil-kt/coil#906]
**Describe the bug**
when i load a simple svg image on ImageView it shows correctly but when i try to load it by Coil it shows widely in wrap-content ImageView. there is no different between loading with server or local .

**Expected behavior**
show in actual size

**To Reproduce**
load an image by setImageResource() and by coil

**Logs/Screenshots**
[Incorrect](https://ibb.co/prnBZRD)
[Correct](https://ibb.co/gthTLGf)

**Version**
Coil v1.3.1

**Comment by colinrtwhite** [comment]
Please ask usage questions in Github Discussions.
