### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by Mrliu00070** [coil-kt/coil#908]
**Describe the bug**
Canvas: trying to draw too large(107102208bytes) bitmap.
android.graphics.RecordingCanvas.throwIfCannotDraw (RecordingCanvas.java:280)
android.graphics.drawable.BitmapDrawable.draw (BitmapDrawable.java:548)
coil.drawable.CrossfadeDrawable.draw (CrossfadeDrawable.java:100)
android.widget.ImageView.onDraw (ImageView.java:1418)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)

**To Reproduce**
I don'e know, firebase bug.

**Logs/Screenshots**
Canvas: trying to draw too large(107102208bytes) bitmap.
android.graphics.RecordingCanvas.throwIfCannotDraw (RecordingCanvas.java:280)
android.graphics.drawable.BitmapDrawable.draw (BitmapDrawable.java:548)
coil.drawable.CrossfadeDrawable.draw (CrossfadeDrawable.java:100)
android.widget.ImageView.onDraw (ImageView.java:1418)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)

**Version**
 implementation 'io.coil-kt:coil:1.3.2'
    implementation("io.coil-kt:coil-gif:1.3.2")
    implementation("io.coil-kt:coil-svg:1.3.2")
    implementation("io.coil-kt:coil-video:1.3.2")

**Comment by colinrtwhite** [comment]
You're likely loading a very large image with `size(OriginalSize)`  somewhere in your code, which causes this crash when the image is drawn. I don't think this is an issue with the library itself.

**Comment by xoif** [comment]
I'm a bit late to the party, but just had a similar issue. After understanding that coil should (normally) perform downsampling automatically, I noticed that the local image url was first loaded into a drawable and then passed to coil:
`holder.binding.thumbnail.load(Drawable.createFromPath(localFilePath).absolutePath))`

That somehow seems to bypass coils downsampling and thus led to the crash. 
When passing the url directly, no such issue occurs: 
`holder.binding.thumbnail.load(localFilePath)`
