### ISSUE TITLE
Memory cache for app icons using resource uri

### ISSUE THREAD

**Issue by kawaiiDango** [coil-kt/coil#910]
**Describe the bug**
I am using https://github.com/coil-kt/coil/issues/79#issuecomment-533903394 to load app icons in a recyclerview.
Memory cache doesn't seem to work as I see the placeholder image and the crossfade every time I scroll back.

**Expected behavior**
Memory cache should work

**To Reproduce**
How can we reproduce this? Please attach a small project that reproduces the bug.

**Logs/Screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Version**
1.3.2

**Comment by colinrtwhite** [comment]
Please ask usage questions in Github Discussions.
