### ISSUE TITLE
Image not loading if parent view height is "wrap_content" & ImageView height is "match_parent"

### ISSUE THREAD

**Issue by vitaliecroitor** [coil-kt/coil#926]
### Image not loading if parent view height is `wrap_content` but the ImageView height is `match_parent`

**Setup to reproduce:**

**activity_layout.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <ImageView
        android:id="@+id/my_image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true" />
</FrameLayout>
```

**MainActivity**
```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        findViewById<ImageView>(R.id.my_image).load("https://example.com/example.png") 
    }
}
```
**Coil version: `1.3.2`**

It looks like this is not supposed to happen `¯\_(ツ)_/¯`. Also, please note if you change the `ImageView` height to `wrap_content` it fixes the issue. 
P.S. Awesome library 👍

**Comment by colinrtwhite** [comment]
This is expected behavior. Your image view is being laid out at 0 height with match parent so Coil waits until it is laid out with a non-zero size.
