### ISSUE TITLE
Coil 2.0: Support disk cache factory

### ISSUE THREAD

**Issue by Tolriq** [coil-kt/coil#932]
First nice work on 2.0 many great additions.

**Is your feature request related to a problem? Please describe.**
Disk cache configuration should support a factory configuration to allow delayed configuration in background thread. (As in Glide)
1) Current builder for example stat the folder if you set any size percent it will occurs on main thread for most users and disk access on main thread is well not good.
2) The cache folder could be tied to some settings that needs to be loaded and it should not be mandatory to block until those settings are read to create / inject imageloader.

**Describe the solution you'd like**
Add an imageloader diskCache builder option that support a DiskCacheFactory that returns a diskCache that would be called when first needed in a background thread.

**Additional context**
Allow settings / disk access to occurs in background thread and when they are actually needed for smoother application start.

**Comment by colinrtwhite** [comment]
Good point - implemented here: https://github.com/coil-kt/coil/pull/935

**Comment by Tolriq** [comment]
Thanks, just a small nitpick but since 2.0 support 4 different dispatchers and the new lazy way is not suspend to give back control maybe it's worth to add a small note about the dispatcher it will be ran by default? (I guess being the fetcher one is kinda implicit, but one could think it's done as an interceptor as per the custom cache interceptor sample)
