### ISSUE TITLE
Coil 2.0: Possible cancellation issue (at least with compose)

### ISSUE THREAD

**Issue by Tolriq** [coil-kt/coil#933]
**Describe the bug**
When using coil 2.0 with compose in lazy column, during fast fling, the requests are no more cancelled and all previous requests needs to ends before loading the one currently on screen.

**Expected behavior**
Offscreen not yet loaded image requests should be cancelled.

**To Reproduce**
Fast scroll a lazycolumn and wait for image to appear (and see logs, no cancellation all success from network requests). Not yet sure 100% about repro code as I'm not yet 100% confident on my compose and coil 2.0 understanding.

So opening this early to get some pointers on where to look in existing coil tests for compose cancellation stuff to try build a repro test.

**Comment by JatinVashisht1** [comment]
I am using coil inside lazyColumn but it is not showing images when used within lazy column. How can I resolve this issue?
