### ISSUE TITLE
In dark mode Coil rememberImagePainter rendering image in negative colours on Redmi device

### ISSUE THREAD

**Issue by AbhilashRaipally** [coil-kt/coil#955]
**Describe the bug**
 When I set my device to the dark theme via the android system setting, certain images loaded with Coil rememberImagePainter gets rendered in negative colours.

All images and UI elements that are loaded without using coil get displayed properly in the dark theme. 
Some images that are loaded with coil show this issue. 

In light mode images loaded with coil get rendered properly

**To Reproduce**
Use rememberImagePainter to load the image from URL
Once the app is opened in Android Redmi device, switch to dark mode 

Following is a snapshot of the compose code we use to load the image.
```
Row(modifier = Modifier
            .padding(top = 8.dp, start = 8.dp)
            .fillMaxWidth()) {
            Image(
                painter = rememberImagePainter(video.authorImage),
                contentDescription = null,
                modifier = Modifier.size(32.dp).clip(CircleShape)
            )
}
```

**Logs/Screenshots**
The image marked with a red circle is the one that's getting rendered in negative colors.

<img width="376" alt="Screenshot 2021-10-16 at 1 27 58 PM" src="https://user-images.githubusercontent.com/88826131/137579461-ab1fca2a-e856-4e5d-8d28-0b5a12ba5efc.png">

The original image to be rendered is
![ap](https://user-images.githubusercontent.com/88826131/137579605-015c673a-3d3d-430d-9c14-3ba3840de838.jpeg)

**Version**
Library version - io.coil-kt:coil-compose:1.4.0
It occurs only in certain Android devices, we were able to reproduce it consistently on Redmi 9 power device

**Comment by colinrtwhite** [comment]
Thanks for the report. It looks like Redmi injects some custom dark mode logic into apps that can sometimes invert images: https://www.reddit.com/r/Xiaomi/comments/mrzwdn/image_colour_inversion/. Unfortunately, I don't think Coil can work-around this issue. The linked Reddit post has instructions for how to disable the Redmi feature.
