### ISSUE TITLE
RoundedCorners not work

### ISSUE THREAD

**Issue by mt131** [coil-kt/coil#96]
holder.imageViewCover.scaleType = ImageView.ScaleType.CENTER_CROP
        holder.imageViewCover.load(producList[position].cover_image) {
            transformations(RoundedCornersTransformation(32f))
        }

but the image is not rounded conner

**Comment by mt131** [comment]
<ImageView
        app:riv_corner_radius="16dp"
        android:id="@+id/imageViewCover"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="8dp"
        android:layout_marginBottom="4dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.5" />
it is an imageView in a recycleview

**Comment by mt131** [comment]
it is not work in 1 project but  working in other project now

**Comment by JcMinarro** [comment]
It is not working fine for me either.
Some pictures are rounded but other ones not.
It is the same case, I am trying to load pictures into a recyclerView that has a `GridLayoutManager` with three columns. The holder will take the size depending on the screen size, and it is always squared thanks to the constraint condition I add to the picture (`app:layout_constraintDimensionRatio="H,1:1"`)

It is my ImageView xml:
```
<ImageView
        android:id="@+id/file_image"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_margin="1dp"
        android:scaleType="centerCrop"
        android:adjustViewBounds="true"
        app:layout_constraintDimensionRatio="H,1:1"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        />
```

**Comment by FrostRocket** [comment]
The RoundedCornersTransformation does work, but what I found in my testing is that it rounds the actual image, not the ImageView itself (which is probably what you're expecting). So the image ends up rounded, then scaled into the Imageview via the ScaleType you specified. If it resizes the image to crop, you'll lose those corners.

I was also expecting "RoundedCornersTransformation" to round the image post-scaling so you see those transformations in the view itself.

**Comment by colinrtwhite** [comment]
@FrostRocket Yep, it's "technically" working, though definitely not the desired behaviour. Tracking the fix [here](https://github.com/coil-kt/coil/issues/126).
