### ISSUE TITLE
The "replaceWith" for clear()->dispose() isn't working

### ISSUE THREAD

**Issue by edenman** [coil-kt/coil#969]
Coil 2.0.0-alpha02
Android Studio Bumblebee | 2021.1.1 Beta 2

I'm guessing it needs to be `expression = "dispose()"` instead of `expression = "dispose"` but I've not used this API before.

https://user-images.githubusercontent.com/1063557/139968605-7bdb222e-9b3e-4ac7-9862-9d12b9aee416.mov

**Comment by colinrtwhite** [comment]
Thanks for the heads up - fixed here: https://github.com/coil-kt/coil/pull/970
