### ISSUE TITLE
Pass `DataSource` to `Target.onSuccess()`

### ISSUE THREAD

**Issue by chrisbanes** [coil-kt/coil#99]
The source is useful to know when to run certain types of animation/transition when loading images.

For instance, I apply a fade + saturation animation for images when they're 'first loaded'. The easiest way to implement this (approximately) is to look at where the image is loaded from. This was pretty easy with Glide's `TransitionFactory`, but not so with Coil.

I've added this to my app [here](https://github.com/chrisbanes/tivi/commit/a4d65bbbc9e83c2c0f1d9418d11325032523c7cb), by making the target implement both `Target` and `Request.Listener`.

**Comment by colinrtwhite** [comment]
Added a comment on #98, which also discusses this ticket.

**Comment by colinrtwhite** [comment]
This is now supported! 🎉 The transitions API is part of the `0.9.0-SNAPSHOT`.

Definitely looking for feedback on the API (it'll be marked as experimental for one release) so if you have suggestions let me know!

Both `ImageLoader` and `Request` builders accept a Transition.Factory, which enables you to return a new transition (or null for no transition) for each `Transition.Event`.

[Check out the `Transition` interface for more info.](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/transition/Transition.kt)

**Comment by chrisbanes** [comment]
Thanks Colin! I'll take a look at this later today.

**Comment by colinrtwhite** [comment]
Thanks! No rush - probably still a couple weeks away from releasing `0.9.0`.
