### ISSUE TITLE
Attempting to draw too large Bitmaps on Xiaomi devices

### ISSUE THREAD

**Issue by Danyaga** [coil-kt/coil#991]
**Describe the bug**
We are have this weird crashes when we load Bitmap object in ImageView objects right after having those taken with CameraX on some phones. The crash is reporting that we tried to display a 190mb image or more in some cases.

It could be that the measures were taken wrongly and the result is have the Bitmap scaled to a really high size.

**To Reproduce**
This bug seems happening so frequently on Xiaomi devices. E. G. Xiaomi MI 9

Replicate it should be pretty straightforward: 

- Implement CameraX to take photo in an Activity;
- Collect in the callback the photo taken with `BitmapFactory.decodeFile(outputFileResults.savedUri?.path)`
- Display right after the in a ImageView the photo just taken as Bitmap loaded at the step before.

I'll see if I have time to create a minimal project where this crash happens, later.

**Version**
We are using `io.coil-kt:coil:1.1.1`

**Comment by colinrtwhite** [comment]
Do you show the image in a view that uses `wrap_content`? That resolves to display size which could potentially be large. We use CameraX with Coil at Instacart and haven't encountered this issue so I'm not sure this is a bug in Coil. Without a way to reproduce this locally, I don't think it's possible to diagnose.

**Comment by colinrtwhite** [comment]
In your reproduction steps you mention using `BitmapFactory.decodeFile(outputFileResults.savedUri?.path)`, which decodes the image and doesn't invoke Coil. `BitmapFactory.decodeFile` also decodes the image at full size which may be why you're seeing issues. You should use `imageView.load(outputFileResults.savedUri?.path)` instead.

**Comment by Danyaga** [comment]
Thanks for the help! We tried to solve the way you suggested.

I'll let you know if we still find issues and for that time I'll provide a project to verify the issue on your side.
